window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Trc={LNd:0,KNd:9,Nbd:6,MNd:5,NNd:10};a.xCc={Wtc:0};c.ZVb=function(){p.w.call(this);this.xsb=a.Trc.Nbd;this.PG=a.xCc.Wtc;this.fH=new c.ja;this.Oc=this.Oc|a.Wb.oaa|a.Wb.owa|a.Wb.jab|a.Wb.DD|a.Wb.zT|a.Wb.CD;this.mh=this.mh|a.ei.uP|a.ei.XX;this.tf(!1)};var p=c.u(c.ZVb,c.IT);p.Mg=function(){return c.sZb};p.kId=function(b){this.xsb!=b&&(this.xsb=b,this.m(a.f.i),this.$u())};p.ypd=function(){return this.xsb};p.Ip=function(a){p.j.Ip.call(this,a);this.XNc()};p.Wob=
function(){if(this.Ob()){var a=this.Xd(),a=Math.abs(a.Ra()),c=this.Ce();this.xd();this.xd();c.Ua(c.Q()+a);""==this.nb()?(c.Qa(c.Q()),c.Fa(a)):(this.nb(),c.Qa(c.Q()+this.TW()),c.Fa(this.fia()),c.Qa(c.va+a));b.Gp(this.fH,c)||(this.fH=c,this.rb());this.Ip(!0)}};p.He=function(a){a.Va(a.M()+this.fH.ba());a.Ua(a.Q()+4);a.Qa(a.va-4);a.Fa(a.ua-4);p.j.He.call(this,a)};p.PQc=function(a,b,c){a.Va(a.M()+this.fH.ba());a.Ua(a.Q()+4);a.Qa(a.va-4);a.Fa(a.ua-4);p.j.PQc.call(this,a,b,c)};p.gj=function(){p.j.gj.call(this);
this.Dd(a.$.Uz)};p.Wc=function(){var b=this.XK()||this.yk()&&(this.VX()||this.tP());this.iH(a.Wb.bL,b);p.j.Wc.call(this)};p.MD=function(a){var b=!1,b=a.Wd().lOa(this,this.ea.ii,this.VX(),this.tP(),a);!1==b&&p.j.MD.call(this,a)};p.VT=function(a){var b=!1;null!=a.Wd()&&a.fa().yk()&&(b=a.Wd().mOa(this,this.ea.ii,a,this.VX(),this.tP()));!1==b&&p.j.VT.call(this,a)};p.ue=function(b){""==b[1]&&(b[1]=a.TPb);p.j.ue.call(this,b)};p.XNc=function(){var a=this.Ce(),a=this.YA(a,null),c=this.Ce();c.Va(c.M()+this.fH.ba()/
2+1);c.Ua(c.Q()+2);c.Qa(c.va-2);c.Fa(c.ua-2);var e=this.Oa().gb(),f=this.nb();b.Id[e].Ag(f,c,this.fH);b.la(a)};p.jr=p[a.$.RF]=function(a){this.Wob();p.j.jr.call(this,a)};p.Tt=p[a.$.QF]=function(){p.j.Tt.call(this);this.Wob()};p.lK=p[a.$.Uz]=function(){this.Wob();this.$u()};p.Dpc=p[a.$.Oab]=function(){this.Qg()};e.$c(c.ZVb,"PRIM_GPBX",{Pa:{Caption:{a:p.nb,g:function(a){this.Eb(e.ma(a))}},ThemeStyle:{a:function(){return e.ta(this.LK(),a.su.v)},g:function(b){this.Pza(e.qa(b,a.su.v))}}}});c.sZb=function(a){u.w.call(this,
a);this.mb=this.MTa=this.KBa=this.Sd=this.Ec=null};var u=c.u(c.sZb,c.b4);u.bf=function(a,b){var c=null;u.j.bf.call(this,a,b);this.MTa=4;this.Ec=document.createElement("div");this.Sd=document.createElement("div");this.KBa=document.createElement("div");this.mb=document.createElement("span");this.G.appendChild(this.Ec);this.G.appendChild(this.Sd);this.G.appendChild(this.KBa);this.G.appendChild(this.mb);this.j9a(this.Ec,this.MTa);this.j9a(this.Sd,0);this.j9a(this.KBa,0);c=this.Ec.style;c.borderTopWidth=
"0px";c=this.Sd.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.KBa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.mb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};u.j9a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};u.Ag=function(a,b,c){var e=this.Ec.style;e.left=b.Q()+"px";e.top=b.M()+"px";e.width=b.aa()+"px";e.height=b.ba()+"px";e.borderColor=this.Rk();e=this.Sd.style;e.left=b.Q()+this.MTa-1+"px";e.top=b.M()+"px";e.width=c.Q()-b.Q()+"px";e.height="1px";e.borderColor=this.Rk();e=this.KBa.style;e.left=c.va+2+"px";e.top=b.M()+"px";e.width=b.va-this.MTa-c.va+"px";e.height="1px";e.borderColor=this.Rk();e=this.mb.style;e.left=c.Q()+7+"px";e.top=c.M()+2+"px";e.height=
c.ba()+"px";e.width=c.aa()+"px";this.mb.textContent=a}});
