window.LANSA.addSrc("web",function(e,c,a,b,p){e.Fb("PRIM_LABL");var u=null,h=null;a.CI={iib:0,J3b:1,K3b:2,I3b:3};a.CI.v={INLINE:a.CI.iib,LEFT:a.CI.J3b,RIGHT:a.CI.K3b,CENTER:a.CI.I3b};a.ED={rHa:0,gFb:1,kFb:2,lFb:3,nFb:4,X2a:5};a.ED.v={NONE:a.ED.rHa,NOTLOADED:a.ED.gFb,PERMISSIONDENIED:a.ED.kFb,POSITIONUNAVAILABLE:a.ED.lFb,TIMEOUT:a.ED.nFb,UNKNOWNERROR:a.ED.X2a};a.kS={$xb:0,Yxb:1,ayb:2,Zxb:4};a.kS.v={NONE:a.kS.$xb,ERROR:a.kS.Yxb,WARNING:a.kS.ayb,INFORMATION:a.kS.Zxb};c.ceb=function(){s.w.call(this);
this.Za=[]};var s=c.u(c.ceb,c.jd);s.R=function(){s.j.R.call(this)};s.pc=function(){return this.Za.length};s.be=function(a){return this.Za[a-1]};s.FH=function(a){for(var c=null,d=0;d<this.Za.length;d++){var e=this.Za[d];if(b.GD(e.Pl,a)){c=e;break}}return c};e.jb(c.ceb,"PRIM_WEB","URLParameters",{Pa:{Item:{a:function(a){return this.FH(e.ma(a))},Vv:"na"},ItemCount:{a:s.pc}},Sf:{Of:"Item"},fp:{ro:function(a){return this.be(e.L(a))},av:s.pc}});c.beb=function(){g.w.call(this);this.ab=this.Pl=""};var g=
c.u(c.beb,c.jd);g.ph=function(){return this.Pl.toUpperCase()};g.Ja=function(){return this.ab};e.jb(c.beb,"PRIM_WEB","URLParameter",{Pa:{Name:{a:g.ph},Value:{a:g.Ja}}});c.$db=function(){f.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(u=localStorage)}catch(c){}this.Yp=null};var f=c.u(c.$db,c.jd);f.R=function(){f.j.R.call(this)};f.s4a=function(){return null!=u};f.pc=function(){return this.RO().length};f.be=function(a){return this.RO()[a-
1]};f.FH=function(a){for(var b=null,c=this.RO(),d=0;d<c.length;d++){var e=c[d];if(e.Pl==a){b=e;break}}return b};f.RO=function(){if(null==this.Yp&&(this.Yp=[],u))for(var a=0;a<u.length;a++){var b=u.key(a);""!=b&&u[b]!=p&&this.Yp.push(new c.FMa(b))}return this.Yp};f.Oya=function(){this.Yp=null};f.Ig=function(a,b){var d=this.RO(),e=this.FH(a);null==e&&(e=new c.FMa(a),d.push(e));e.Xa(b)||d.splice(d.indexOf(e),1)};f.os=function(c){var d=this.RO(),e=this.FH(c);null!=e&&(u.removeItem(c),d.splice(d.indexOf(e),
1),b.to().s9(a.dE.ana))};f.pn=function(){u&&(u.clear(),this.Oya(),b.to().s9(a.dE.ana))};e.jb(c.$db,"PRIM_WEB","LocalStorage",{Pa:{Available:{a:f.s4a},Item:{a:function(a){return this.FH(e.ma(a))},Vv:"na"},ItemCount:{a:f.pc}},jc:{Add:f.Ig,Remove:f.os,Clear:f.pn},Sf:{Of:"Item"},fp:{ro:function(a){return this.be(e.L(a))},av:f.pc}});c.FMa=function(a){q.w.call(this);this.Pl=a};var q=c.u(c.FMa,c.jd);q.ph=function(){return this.Pl};q.Ja=function(){var a="";u&&(a=u[this.Pl],a===p&&(a=""));return a};q.Xa=function(c){var d=
!0;try{u[this.Pl]=c,b.to().s9(a.dE.ana)}catch(e){b.to().SGb(a.dE.ana),d=!1}return d};e.jb(c.FMa,"PRIM_WEB","LocalStorageItem",{Pa:{Name:{a:q.ph},Value:{a:q.Ja,g:function(a){this.Xa(e.ma(a))}}},Sf:{Of:"Value"}});c.aeb=function(){n.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(h=sessionStorage)}catch(c){}this.Yp=null};var n=c.u(c.aeb,c.jd);n.R=function(){n.j.R.call(this)};n.s4a=function(){return null!=h};n.pc=
function(){return this.RO().length};n.be=function(a){return this.RO()[a-1]};n.FH=function(a){for(var b=null,c=this.RO(),d=0;d<c.length;d++){var e=c[d];if(e.Pl==a){b=e;break}}return b};n.RO=function(){if(null==this.Yp&&(this.Yp=[],h))for(var a=0;a<h.length;a++){var b=h.key(a);""!=b&&h[b]!=p&&this.Yp.push(new c.GMa(b))}return this.Yp};n.Oya=function(){this.Yp=null};n.Ig=function(a,b){var d=this.RO(),e=this.FH(a);null==e&&(e=new c.GMa(a),d.push(e));e.Xa(b)||d.splice(d.indexOf(e),1)};n.os=function(c){var d=
this.RO(),e=this.FH(c);null!=e&&(h.removeItem(c),d.splice(d.indexOf(e),1),b.to().s9(a.dE.bna))};n.pn=function(){h&&(h.clear(),this.Oya(),b.to().s9(a.dE.bna))};e.jb(c.aeb,"PRIM_WEB","SessionStorage",{Pa:{Available:{a:n.s4a},Item:{a:function(a){return this.FH(e.ma(a))},Vv:"na"},ItemCount:{a:n.pc}},jc:{Add:n.Ig,Remove:n.os,Clear:n.pn},Sf:{Of:"Item"},fp:{ro:function(a){return this.be(e.L(a))},av:n.pc}});c.GMa=function(a){d.w.call(this);this.Pl=a};var d=c.u(c.GMa,c.jd);d.ph=function(){return this.Pl};
d.Ja=function(){var a="";h&&(a=h[this.Pl],a===p&&(a=""));return a};d.Xa=function(c){var d=!0;try{h[this.Pl]=c,b.to().s9(a.dE.bna)}catch(e){b.to().SGb(a.dE.bna),d=!1}return d};e.jb(c.GMa,"PRIM_WEB","SessionStorageItem",{Pa:{Name:{a:d.ph},Value:{a:d.Ja,g:function(a){this.Xa(e.ma(a))}}},Sf:{Of:"Value"}});c.Zdb=function(){v.w.call(this)};var v=c.u(c.Zdb,c.jd);v.R=function(){v.j.R.call(this)};v.vCc=function(a){0<a&&window.history.go(0-a)};v.wCc=function(a){0<a&&window.history.go(a)};v.Ig=function(a,c){var d=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.to().Thb();c&&b.to().LHa()};v.RRc=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.to().Thb();c&&b.to().LHa()};e.jb(c.Zdb,"PRIM_WEB","History",{jc:{Add:function(a,b){this.Ig(e.ma(a),b===p?!0:e.ya(b))},Replace:function(a,b){this.RRc(e.ma(a),b===p?!0:e.ya(b))},
GoBack:function(a){this.vCc(a===p?1:e.L(a))},GoForward:function(a){this.wCc(a===p?1:e.L(a))}}});c.BYb=function(){m.w.call(this);this.od=b.Cd(0,0,400,400);this.xCa=this.We="";this.mh&=~a.ei.uP;this.mh&=~a.ei.XX};var m=c.u(c.BYb,c.dm);m.Mg=function(){return c.SYb};m.KH=function(){return this.We};m.km=function(b){this.We!=b&&(this.We=b,this.ga(a.f.i))};m.QS=function(){return this.xCa};m.Yib=function(a){this.xCa=a};m.Hd=function(a,c,d){m.j.Hd.call(this,a,c,d);a=this.Oa().gb();b.Id[a].km(this.We)};m.ltc=
function(){this.Ga(a.K.MQb)};e.jb(c.BYb,"PRIM_WEB","Page",{Pa:{Source:{a:m.KH,g:function(a){this.km(e.ma(a))}},Description:{a:m.QS,g:function(a){this.Yib(e.ma(a))}}}});c.bla=function(){z.w.call(this)};var z=c.u(c.bla,c.dm);z.q6a=function(){for(var a=null,b=this;b;){if(b instanceof c.deb){a=b;break}b=b.Nb}return a};z.sba=function(){z.j.sba.call(this);var a=this.q6a();a&&a.NW(this)};z.IY=function(){z.j.IY.call(this);var a=this.q6a();a&&a.OW(this)};z.rf=function(a){z.j.rf.call(this,a);var b=this.q6a();
b==this&&b.Lz(a,!1)};e.jb(c.bla,"PRIM_WEB","RichTextItem",{});c.heb=function(){k.w.call(this)};var k=c.u(c.heb,c.bla);k.Mg=function(){return c.HZb};e.jb(c.heb,"PRIM_WEB","RichTextLine",{});c.eeb=function(){y.w.call(this)};var y=c.u(c.eeb,c.bla);y.Mg=function(){return c.FZb};e.jb(c.eeb,"PRIM_WEB","RichTextBreak",{});c.feb=function(){L.w.call(this);this.IV=null;this.bEa=a.CI.iib;this.qXa=this.rXa=0};var L=c.u(c.feb,c.bla);L.R=function(){L.j.R.call(this);this.hQa(null)};L.Mg=function(){return c.GZb};
L.yAc=function(){return this.IV};L.hQa=function(b){this.IV!=b&&(null!=this.IV&&(this.IV.Ca(this,this.BCb),this.IV.wb()),this.IV=b,null!=this.IV&&(this.IV.Aa(),this.IV.Ea(this,this.BCb)),this.ga(a.f.i))};L.ftd=function(){return this.bEa};L.Z5b=function(b){this.bEa!=b&&(this.bEa=b,this.ga(a.f.i))};L.zAc=function(){return this.rXa};L.a6b=function(b){this.rXa!=b&&(this.rXa=b,this.ga(a.f.i))};L.xAc=function(){return this.qXa};L.$5b=function(b){this.qXa!=b&&(this.qXa=b,this.ga(a.f.i))};L.Hd=function(a,
c,d){L.j.Hd.call(this,a,c,d);a=this.Oa().gb();b.Id[a].Ag(this.bEa,this.rXa,this.qXa)};L.Ehb=function(){var a=this.IV,c=this.Oa().gb(),a=a?a.dh():"";b.Id[c].Xc(a)};L.BCb=function(b,c){switch(c.Ya){case a.f.ub:case a.f.Rb:this.hQa(null);break;case a.f.i:this.ga(a.f.i)}};e.jb(c.feb,"PRIM_WEB","RichTextImage",{Pa:{Image:{a:L.yAc,g:function(a){this.hQa(a)}},Width:{a:L.zAc,g:function(a){this.a6b(e.L(a))}},Height:{a:L.xAc,g:function(a){this.$5b(e.L(a))}},Alignment:{a:function(){return e.ta(this.bEa,a.CI.v)},
g:function(b){this.Z5b(e.qa(b,a.CI.v))}}}});c.HMa=function(){C.w.call(this);this.ey=null};var C=c.u(c.HMa,c.bla);C.Mg=function(){return c.IZb};C.Ky=function(){null==this.ey&&(this.ey=new c.geb(this));return this.ey};e.jb(c.HMa,"PRIM_WEB","RichTextParagraph",{Pa:{Items:{a:C.Ky}}});c.deb=function(){T.w.call(this);this.od=b.Cd(0,0,100,100)};var T=c.u(c.deb,c.HMa);T.Mg=function(){return c.EZb};T.NW=function(b){if(!this.Zc()){var c=e.Qb();c.Vb("ITEM",b);this.Ga(a.K.fI,c);c.mc()}};T.OW=function(b){if(!this.Zc()){var c=
e.Qb();c.Vb("ITEM",b);this.Ga(a.K.hI,c);c.mc()}};T.q2=function(b){if(!this.Zc()){var c=e.Qb();c.Vb("ITEM",b);this.Ga(a.K.gI,c);c.mc()}};T.Lz=function(b,c){if(!c&&!this.Zc()){var d=e.Qb();d.Vb("ITEM",b);d.ef("CONTINUE",!0);this.Ga(a.K.eI,d);c=!d.Qf("CONTINUE");d.mc()}return c};e.jb(c.deb,"PRIM_WEB","RichText",{});c.geb=function(a){t.w.call(this);this.Za=[];this.xz=a};var t=c.u(c.geb,c.jd);t.R=function(){t.j.R.call(this)};t.pc=function(){return this.Za.length};t.be=function(a){return this.Za[a-1]};
t.Ig=function(b,d,e,f){var g=new c.heb;g.Aa();g.Eb(b);d!=p&&g.sb(d);e!=p&&g.jm(e);f!=p&&g.Nn(f);g.Na(this.xz);this.Za[this.Za.length]=g;this.xz.ga(a.f.i);this.xz.Ob()&&this.xz.Pg();return g};t.Xfc=function(){var b=new c.eeb;b.Aa();b.Na(this.xz);this.Za[this.Za.length]=b;this.xz.ga(a.f.i);this.xz.Ob()&&this.xz.Pg();return b};t.fgc=function(b,d,e,f,g,k,m){var n=new c.feb;n.Aa();n.hQa(b);d!=p&&n.Z5b(d);e!=p&&n.a6b(e);f!=p&&n.$5b(f);g!=p&&n.sb(g);k!=p&&n.jm(k);m!=p&&n.Nn(m);n.Na(this.xz);this.Za[this.Za.length]=
n;this.xz.ga(a.f.i);this.xz.Ob()&&this.xz.Pg();return n};t.kgc=function(b,d,e,f){var g=new c.HMa;g.Aa();b!=p&&g.Eb(b);d!=p&&g.sb(d);e!=p&&g.jm(e);f!=p&&g.Nn(f);g.Na(this.xz);this.Za[this.Za.length]=g;this.xz.ga(a.f.i);this.xz.Ob()&&this.xz.Pg();return g};t.os=function(b){this.Za.splice(this.Za.indexOf(b),1);b.Na(null);b.wb();this.xz.ga(a.f.i)};t.xj=function(){for(;0<this.Za.length;)this.os(this.Za[0]);this.xz.ga(a.f.i)};e.jb(c.geb,"PRIM_WEB","RichTextItems",{Pa:{Item:{a:function(a){return this.be(e.L(a))},
Vv:"na"},ItemCount:{a:t.pc}},jc:{Add:t.Ig,AddBreak:t.Xfc,AddImage:function(b,c,d,f,g,k,m){return this.fgc(b,e.qa(c,a.CI.v),d,f,g,k,m)},AddParagraph:t.kgc,Remove:t.os,RemoveAll:t.xj},Sf:{Of:"Item"},fp:{ro:function(a){return this.be(e.L(a))},av:t.pc}});c.DYb=function(){B.w.call(this);this.od=b.Cd(0,0,100,100)};var B=c.u(c.DYb,c.dm);B.Mg=function(){return c.jZb};B.Hd=function(a,b,c){B.j.Hd.call(this,a,b,c)};B.Og=function(a){this.yI();a&&this.nya();b.cb().XA(this)};B.KB=function(){this.ea.cW()};e.jb(c.DYb,
"PRIM_WEB","Camera",{});c.NYb=function(){G.w.call(this);this.od=b.Cd(0,0,100,100);this.oE=null;this.RFa("")};var G=c.u(c.NYb,c.dm);G.R=function(){this.oE=null;G.j.R.call(this)};G.Mg=function(){return c.JZb};G.Rta=function(){this.Oa()&&this.RFa(this.Oa().Cuc());return this.oE};G.RFa=function(a){this.oE=new c.TF({data:a,mimetype:"image/png",filename:"signature.png"})};G.pn=function(){if(this.Oa()){var a=this.Oa().gb();b.Id[a].pn();this.xc()}};G.Hd=function(a,b,c){G.j.Hd.call(this,a,b,c)};G.Og=function(a){this.yI();
a&&this.nya();b.cb().XA(this)};G.KB=function(){this.ea.cW()};G.xc=function(){this.Ga(a.K.wh)};e.jb(c.NYb,"PRIM_WEB","Signature",{Pa:{Blob:{a:G.Rta}},jc:{Clear:G.pn}});c.IYb=function(){P.w.call(this);this.Rub=this.btb=this.vqb=this.uqb=this.qqb=this.wWa=this.Qtb=0;this.S6=a.ED.gFb};var P=c.u(c.IYb,c.jd);P.czc=function(){return this.Qtb};P.oyc=function(){return this.wWa};P.Xtc=function(){return this.qqb};P.iuc=function(){return this.uqb};P.juc=function(){return this.vqb};P.Lxc=function(){return this.btb};
P.$Ac=function(){return this.Rub};P.Hpd=function(){return this.S6};P.XQc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.Qtb=d.coords.longitude;b.wWa=d.coords.latitude;b.qqb=d.coords.accuracy;b.uqb=d.coords.altitude?d.coords.altitude:0;b.vqb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.btb=d.coords.heading?d.coords.heading:0;b.Rub=d.coords.speed?d.coords.speed:0;b.S6=a.ED.rHa;d=new c.Eka;b.Ga(a.K.D2b,d)},function(d){b.Qtb=0;b.wWa=0;b.qqb=
0;b.uqb=0;b.vqb=0;b.btb=0;b.Rub=0;b.S6=a.ED.X2a;switch(d.code){case d.PERMISSION_DENIED:b.S6=a.ED.kFb;break;case d.POSITION_UNAVAILABLE:b.S6=a.ED.lFb;break;case d.TIMEOUT:b.S6=a.ED.nFb;break;case d.UNKNOWN_ERROR:b.S6=a.ED.X2a}d=new c.Eka;b.Ga(a.K.D2b,d)});return this.wWa};e.jb(c.IYb,"PRIM_WEB","Geolocation",{Pa:{Longitude:{a:P.czc},Latitude:{a:P.oyc},Accuracy:{a:P.Xtc},Altitude:{a:P.iuc},AltitudeAccuracy:{a:P.juc},Heading:{a:P.Lxc},Speed:{a:P.$Ac},ErrorCode:{a:function(){return e.ta(this.S6,a.ED.v)}}},
jc:{Refresh:P.XQc}});c.FYb=function(){A.w.call(this)};var A=c.u(c.FYb,c.jd);A.eLc=function(b,c){if("undefined"!==typeof console)switch(c){case a.kS.Yxb:console.error(b);break;case a.kS.ayb:console.warn(b);break;case a.kS.Zxb:console.info(b);break;default:console.log(b)}};e.jb(c.FYb,"PRIM_WEB","Console",{Pa:{},jc:{Log:function(b,c){return this.eLc(e.ma(b),c?e.qa(c,a.kS.v):a.kS.$xb)}}});c.HYb=function(){Q.w.call(this);this.Xb=this.fb=null;this.oz=this.Qr="";this.Wtb=!1};var Q=c.u(c.HYb,c.ls);Q.R=function(){Q.j.R.call(this);
this.dn(null)};Q.Mg=function(){return c.rZb};Q.dh=function(){return this.Qr};Q.q5a=function(){return this.oz};Q.wg=function(b){this.fb!=b&&(this.dn(b),this.m(a.f.i))};Q.hb=function(){var a=null;return a=this.fb};Q.hc=function(){return this.Xb};Q.U5a=function(){return this.Wtb};Q.K5b=function(b){this.Wtb!=b&&(this.Wtb=b,this.ga(a.f.i))};Q.xc=function(){this.Ga(a.K.wh)};Q.N3a=function(b,c){var d=e.Qb();d.Vb("FILE",b);d.Vb("FILES",c);this.Ga(a.K.vGb,d);d.mc()};Q.XN=function(){this.KQ=b.Wka(this.Xb.xk());
this.fb.CS(this.hc())};Q.dn=function(a){var c=null;a&&(c=a.ax(),this.fb==a?c.eo(this.Xb):a.Ay(c));this.fb&&(this.fb.Ca(this),this.Xb.Ca(this),b.la(this.Xb),this.Xb=null);if(this.fb=a)this.fb.Ea(this,this.xl),this.Xb=c,this.Xb.Ea(this,this.Ru);this.Qg()};Q.dMd=function(){};Q.xl=function(b,c){c.Ya==a.f.i?c.cr==a.je.ow?this.fb.Ay(this.hc()):this.dn(this.fb):c.Ya==a.f.ub&&this.wg(null)};Q.Ru=function(b,c){c.Ya==a.f.i&&c.cr==a.je.ow&&this.XN()};e.jb(c.HYb,"PRIM_WEB","FilePicker",{Pa:{MultiSelect:{a:Q.U5a,
g:function(a){this.K5b(e.ya(a))}}}});c.Xdb=function(a){H.w.call(this);this.rWa=a;this.BV=this.oE=null};var H=c.u(c.Xdb,c.jd);H.R=function(){null!=this.oE&&(this.oE=null);null!=this.BV&&(b.Izb(this.BV),this.BV=null);H.j.R.call(this)};H.ph=function(){return this.rWa.name};H.Rta=function(){null==this.oE&&(this.oE=new c.qUb(this.rWa));return this.oE};H.A6a=function(){return this.rWa.size};H.szc=function(){return this.rWa.type};e.jb(c.Xdb,"PRIM_WEB","File",{Pa:{Name:{a:H.ph},Blob:{a:H.Rta},FileSize:{a:H.A6a},
MimeType:{a:H.szc}}});c.Ydb=function(){ba.w.call(this);this.Za=[]};var ba=c.u(c.Ydb,c.jd);ba.R=function(){for(var a=0;a<this.Za.length;a++)this.Za[a].wb();this.Za=[];ba.j.R.call(this)};ba.pc=function(){return this.Za.length};ba.be=function(a){return this.Za[a-1]};ba.tr=function(a){this.Za.push(a);a.Aa()};e.jb(c.Ydb,"PRIM_WEB","Files",{Pa:{Item:{a:function(a){return this.be(e.L(a))},Vv:"na"},ItemCount:{a:ba.pc}},Sf:{Of:"Item"},fp:{ro:function(a){return this.be(e.L(a))},av:ba.pc}});c.EYb=function(){sa.w.call(this)};
var sa=c.u(c.EYb,c.jd);sa.shb=function(a){var d=this;if(window.FileReader&&a instanceof c.TF){if(a=a.Fia()){var e=b.eQ(),f=new FileReader;f.onload=function(a){d.MW(a.target.result);b.Px(e)};f.readAsText(a)}}else d.MW("")};sa.MW=function(b){var c=e.Qb();c.lF("DATA",b);this.Ga(a.K.O1,c)};e.jb(c.EYb,"PRIM_WEB","ClobReader",{jc:{Read:sa.shb}});c.CYb=function(){ia.w.call(this)};var ia=c.u(c.CYb,c.jd);ia.shb=function(a){var d=this;if(window.FileReader&&a instanceof c.TF){if(a=a.Fia()){var e=b.eQ(),f=new FileReader;
f.onload=function(a){d.MW(b.eGb(a.target.result));b.Px(e)};f.readAsDataURL(a)}}else d.MW("","")};ia.MW=function(b){var c=e.Qb();c.lF("DATA",b);this.Ga(a.K.O1,c)};e.jb(c.CYb,"PRIM_WEB","BlobReader",{jc:{Read:ia.shb}});c.EZb=function(a){Y.w.call(this,a)};var Y=c.u(c.EZb,c.em);Y.Eb=function(a){this.G.textContent=a};Y.wy=function(){Y.j.wy.call(this);this.G.style.whiteSpace="normal";this.G.style.overflowX="auto";this.G.style.overflowY="auto"};Y.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",
a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);return Y.j.bf.call(this,a,b)};c.IZb=function(a){D.w.call(this,a)};var D=c.u(c.IZb,c.em);D.Eb=function(a){this.G.textContent=a};D.Ava=function(){return!1};D.Dda=function(){};D.wy=function(){};D.bf=function(a,b){this.G=document.createElement("p");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);return D.j.bf.call(this,a,b)};c.FZb=function(a){K.w.call(this,a)};var K=c.u(c.FZb,c.em);K.Ava=function(){return!1};K.Dda=function(){};
K.wy=function(){};K.bf=function(a,b){this.G=document.createElement("br");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);return K.j.bf.call(this,a,b)};c.GZb=function(a){E.w.call(this,a)};var E=c.u(c.GZb,c.em);E.Xc=function(a){this.G.src=a};E.Ava=function(){return!1};E.Ag=function(b,c,d){this.G.style.width=0==c?"auto":c+"px";this.G.style.height=0==d?"auto":d+"px";switch(b){case a.CI.iib:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display=
"inline";this.G.style.cssFloat="none";break;case a.CI.J3b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="left";break;case a.CI.K3b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="right";break;case a.CI.I3b:this.G.style.marginLeft="auto",this.G.style.marginRight="auto",this.G.style.display="block",this.G.style.cssFloat="none"}};E.Dda=function(){};E.wy=
function(){this.G.style.borderStyle="solid"};E.bf=function(a,b){this.G=document.createElement("img");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);return E.j.bf.call(this,a,b)};c.HZb=function(a){da.w.call(this,a)};var da=c.u(c.HZb,c.em);da.Eb=function(a){this.G.textContent=a};da.Ava=function(){return!1};da.Dda=function(){};da.wy=function(){};da.bf=function(a,b){this.G=document.createElement("span");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",
this.bc);return da.j.bf.call(this,a,b)};c.jZb=function(a){ca.w.call(this,a)};var ca=c.u(c.jZb,c.em);ca.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);return ca.j.bf.call(this,a,b)};c.JZb=function(a){ea.w.call(this,a);this.JG=this.qm=null;this.ddc=this.awb=!1;this.ltb=null};var ea=c.u(c.JZb,c.em);ea.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",
this.bc);this.G.style.msTouchAction="none";this.JG=document.createElement("canvas");this.JG.style.touchAction="none";this.G.appendChild(this.JG);this.qm=this.JG.getContext("2d");this.Fzb();return ea.j.bf.call(this,a,b)};ea.Xm=function(a,b,c,d){ea.j.Xm.call(this,a,b,c,d);a=this.qm.getImageData(0,0,this.JG.width-1,this.JG.height-1);this.JG.width=this.Uc;this.JG.height=this.bd;this.qm.putImageData(a,0,0)};ea.wL=function(a){this.$6b(a);return!0};ea.nfb=function(a){this.Z6b(a);return!0};ea.VMa=function(a){this.Y6b(a);
return!0};ea.yoa=function(a){this.$6b(a);return!0};ea.xv=function(a){this.Z6b(a);return!0};ea.yda=function(a){this.Y6b(a);return!0};ea.PMb=function(a){this.G.onpointerdown===p&&a.touches!==p?(a.iqb=a.touches[0].pageX-this.pa.ds(),a.jqb=a.touches[0].pageY-this.pa.es()):(a.iqb=a.clientX-this.pa.ds(),a.jqb=a.clientY-this.pa.es());this.pa.xc()};ea.Fzb=function(){this.i_a(!0);this.ltb=new Image;this.ltb.onload=function(){throw 0;};this.ltb.src=null};ea.i_a=function(a){(this.ddc||a)&&this.qm.clearRect(0,
0,this.qm.canvas.width,this.qm.canvas.height);this.ddc=!1};ea.Cuc=function(){var a=this.JG.toDataURL("image/png");return b.eGb(a)};ea.pn=function(){this.Fzb()};ea.$6b=function(a){a.preventDefault();this.i_a(!1);this.qm.beginPath();this.PMb(a);this.qm.moveTo(a.iqb,a.jqb);this.awb=!0};ea.Y6b=function(a){a.preventDefault();this.awb=!1};ea.ZJd=function(a){this.xv(a)};ea.Z6b=function(a){this.awb&&(a.preventDefault(),this.i_a(!1),this.qm.strokeStyle="rgb(0,0,0)",this.qm.lineWidth=1,this.PMb(a),this.qm.lineTo(a.iqb,
a.jqb),this.qm.stroke())};c.SYb=function(a){ma.w.call(this,a);this.Mra=this.$a=null};var ma=c.u(c.SYb,c.em);ma.km=function(a){this.Mra.src=a};ma.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.bc);this.G.setAttribute("LANSAHandle",this.bc);this.Mra=document.createElement("iframe");this.hFa(this.Mra);this.Mra.style.width="100%";this.Mra.style.height="100%";this.G.appendChild(this.Mra);return ma.j.bf.call(this,a,b)};ma.jW=function(){var a=this;ma.j.jW.call(this);
a.G.addEventListener("load",function(){a.pa.ltc()},!1)};ma.hFa=function(a){ma.j.hFa.call(this,a);this.G.style.overflowX="auto";this.G.style.overflowY="auto"};c.rZb=function(a){$.w.call(this,a);this.QQ=null};var $=c.u(c.rZb,c.reb);$.bf=function(a,b){var c=$.j.bf.call(this,a,b);this.QQ=document.createElement("input");this.QQ.type="File";var d=this.QQ.style;this.mb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.QQ);return c};$.Hd=function(){$.j.Hd.call(this);
this.D$c()};$.Xm=function(a,b,c,d){$.j.Xm.call(this,a,b,c,d);this.QQ.style.left="0px";this.QQ.style.top="0px";this.QQ.style.width=c+"px";this.QQ.style.height=d+"px"};$.jW=function(){var a=this;this.E1();a.QQ.addEventListener("change",function(b){a.Hjc(b);a.QQ.value=""},!1)};$.D$c=function(){this.QQ.multiple=this.pa.U5a()};$.Hjc=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.Ydb,e=0,f;f=a[e];e++)f=new c.Xdb(f),null==b&&(b=f),d.tr(f);b&&this.pa.N3a(b,d)}},{rp:["PRIM_LABL"]});
