window.LANSA.addSrc("labl",function(e,c,a,b){a.Vpb={ENd:0,Zpb:16};a.bY={SKc:1,mbb:1,lbb:2,HQb:240};a.ibb={OMa:0,d_b:1};c.ls=function(){p.w.call(this);this.Jv=a.sn.d9;this.hR=a.bY.SKc;this.jfa=a.ibb.OMa;this.sA=this.HA=this.BA=this.OA=0;this.Uj=null;this.LM=a.Nj.XT;this.Ha=null;this.Iu=0;this.lV=a.$e.fQ;this.G0=new c.ja;this.fH=new c.ja;this.Oc=this.Oc|a.Wb.oaa|a.Wb.owa|a.Wb.jab|a.Wb.DD|a.Wb.zT|a.Wb.kab|a.Wb.CD;this.mh=this.mh|a.ei.hka|a.ei.uP|a.ei.XX;this.tf(!1);this.Oma(!1)};var p=c.u(c.ls,c.bu);
p.R=function(){this.Uj&&(this.Uj.Ca(this,this.K1a),this.Uj=null);p.j.R.call(this);this.Xc(null)};p.Mg=function(){return c.reb};p.eA=function(c){this.Uj!=c&&(this.Uj&&this.Uj.Ca(this,this.K1a),this.Uj=c,null==this.Uj?this.Oma(!1):(this.Oma(!0),this.Uj.Ea(this,this.K1a)),this.m(a.f.i),b.cb().wd(this,!1))};p.hD=function(){return this.Uj};p.Fe=function(){return 0!=(this.hR&a.bY.mbb)?!0:!1};p.kw=function(){return!this.qo()&&this.Fe()};p.of=function(c){c=this.hR&~a.bY.mbb|(c?a.bY.mbb:0);this.hR!=c&&(this.hR=
c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.tJa=function(){return 0!=(this.hR&a.bY.lbb)?!0:!1};p.h6b=function(b){b=this.hR&~a.bY.lbb|(b?a.bY.lbb:0);this.hR!=b&&(this.hR=b,this.Qg(),this.ga(a.f.i))};p.UJd=function(c){this.TJa()!=c&&(this.hR=this.hR&~a.bY.HQb|c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.TJa=function(){return this.hR&a.bY.HQb};p.xg=function(c){this.Jv!=c&&(this.Jv=c,b.cb().wd(this,!1),this.ga(a.f.i))};p.Hf=function(){return this.Jv};p.Ye=function(){return this.OA};p.Me=function(c){this.OA!=
c&&(this.OA=c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.af=function(){return this.BA};p.Qe=function(c){this.BA!=c&&(this.BA=c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.Vf=function(){return this.HA};p.we=function(c){this.HA!=c&&(this.HA=c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.og=function(){return this.sA};p.Af=function(c){this.sA!=c&&(this.sA=c,this.Gd(),b.cb().wd(this,!1),this.ga(a.f.i))};p.ss=function(c){this.LM!=c&&(this.LM=c,b.cb().wd(this),this.m(a.f.i))};p.Ac=function(){return this.Ha};
p.Xc=function(c){this.Ha!=c&&(null!=this.Ha&&(this.Ha.Ca(this,this.Xl),this.Ha.wb()),this.Ha=c,null!=this.Ha&&(this.Ha.Aa(),this.Ha.Ea(this,this.Xl)),this.Gd(),b.cb().wd(this),this.m(a.f.i))};p.Xt=function(){return this.LM};p.fw=function(){return this.Iu};p.hu=function(c){c!=this.Iu&&(this.Iu=c,this.Gd(),this.ga(a.f.i),b.cb().wd(this))};p.DK=function(){return this.lV};p.OI=function(b){this.lV!=b&&(this.lV=b,this.Gd(),this.m(a.f.i))};p.Cl=function(){var b=a.ee.KD;switch(this.Cg()){case a.Jg.TA:switch(this.DX()){case a.lh.Sq:b=
a.ee.KD;break;case a.lh.pQ:b=a.ee.ANa;break;default:b=a.ee.CNa}break;case a.Jg.ZJ:switch(this.DX()){case a.lh.Sq:b=a.ee.BNa;break;case a.lh.pQ:b=a.ee.R0b;break;default:b=a.ee.T0b}break;default:switch(this.DX()){case a.lh.Sq:b=a.ee.CY;break;case a.lh.pQ:b=a.ee.Q0b;break;default:b=a.ee.DY}}return b};p.AB=function(){return 0!=(this.jfa&a.ibb.d_b)};p.hyd=function(a){this.jfa|=a};p.VHc=function(a){this.jfa&=~a};p.iyd=function(a,b){this.jfa=this.jfa&~a|(b?a:0)};p.Hd=function(a,b,c){p.j.Hd.call(this,a,b,
c);this.Ip(!1)};p.B4=function(a){p.j.B4.call(this,a);this.Ip(a)};p.Ip=function(a){p.j.Ip.call(this,a);a=this.Ce();this.zDb(a,!1)};p.gj=function(){p.j.gj.call(this);this.Dd(a.$.Uz);this.Dd(a.$.xwa)};p.Wc=function(){this.iH(a.Wb.bL,this.XK());p.j.Wc.call(this)};p.zq=function(a){null!=this.Uj?this.Uj.Le():p.j.zq.call(this,a)};p.Og=function(){this.GY();b.cb().XA(this)};p.KB=function(){this.ZR()};p.MD=function(a){var b=!1,b=a.Wd().oOa(this,this.ea.ii,this.M$a(),this.O$a(),this.N$a(),a);!1==b&&p.j.MD.call(this,
a)};p.ue=function(b){""==b[1]&&(b[1]=a.VPb);p.j.ue.call(this,b)};p.zDb=function(a,e){var g=b.Bc(a),f=b.Bc(g),q=null,n=0<this.Iu?this.Iu:-1;this.Ha&&(q=this.Ha.Nyb(g.ba()-4,g.ba()-4));g.Va(g.M()+this.OA);g.Ua(g.Q()+this.BA);g.Qa(g.va-this.HA);g.Fa(g.ua-this.sA);var d=this.nb(),v=new c.ja,m=new c.ja,p=[],k="";p[0]=v;p[1]=f;p[2]=m;p[3]=n;p[4]=n;p[5]=0;this.Uya(null,q,d,this.Xd(),g,p);v=p[0];f=p[1];g=p[5];this.Ha&&this.Ha instanceof c.iL&&(k=this.Ha.dh());this.G0=v;this.fH=f;e||(q=this.Oa().gb(),n=this.kw(),
b.Id[q].Ag(q,f,k,v,n,this.tJa(),g))};p.Uya=function(e,p,g,f,q,n){e=n[0];var d=n[1],v=n[2],m=n[3],z=n[4],k=n[5],d=b.Bc(q);if(null!=p&&this.xd()){var y=a.Bf.iAa;this.hD()||(y|=a.Bf.rRa);k=y;if(this.kw())switch(this.TJa()){case a.Vpb.Zpb:y|=a.Bf.$B;break;default:y|=a.Bf.$B,k|=a.Bf.$B}else k|=this.Jv;switch(this.Cg()){case a.Jg.TA:k|=a.Bf.Aca;break;case a.Jg.ZJ:k|=a.Bf.kAa;break;default:k|=a.Bf.Rmb}b.Rwa(p,g,f,q,0,this.Cl(),this.Cl(),this.Xt(),e,d,v,0,this.xd()?0:2,m,z,y)}else if(k=this.Txb(d),0<g.length){d.aa()>
q.aa()&&(this.kw()?this.TJa()==a.Vpb.Zpb&&(d=new c.ja(0,0,q.aa(),d.ba())):d=new c.ja(0,0,q.aa(),d.ba()));switch(this.Cg()){case a.Jg.TA:d=new c.ja(q.Q()+(q.aa()-d.aa())/2,1,d.aa(),d.ba());k|=a.Bf.Aca;break;case a.Jg.ZJ:d=new c.ja(q.va-d.aa(),1,d.aa(),d.ba());k|=a.Bf.kAa;break;default:d=new c.ja(q.Q(),1,d.aa()+1,d.ba()),k|=a.Bf.Rmb}switch(this.DX()){case a.lh.Sq:d=new c.ja(d.Q(),q.M()+(q.ba()-d.ba())/2,d.aa(),d.ba());break;case a.lh.pQ:d=new c.ja(d.Q(),q.ua-1-d.ba(),d.aa(),d.ba())}}n[0]=e;n[1]=d;n[2]=
v;n[3]=m;n[4]=z;n[5]=k};p.Txb=function(c){var e=this.Xd(),g=a.Bf.iAa,f=this.nb();if(0<f.length)if(this.hD()||(g|=a.Bf.rRa),this.gz=b.vL(f,e,this.kw(),c.aa(),c.ba()),this.kw())switch(this.TJa()){case a.Vpb.Zpb:b.DB(f,c,g|a.Bf.$B,e);break;default:b.DB(f,c,g|a.Bf.$B,e),g|=a.Bf.$B}else b.DB(f,c,g,e),g|=this.Jv;return g};p.Ljc=function(){var a=b.yP();this.Ak(!1,!0);this.Txb(a);this.Zb(a.aa())};p.LB=function(c){if(this.tJa())switch(b.yq(c)){case a.Z.UOa:case a.Z.S3b:case a.Z.Z3b:case a.Z.Eba:case a.Z.$3b:case a.Z.QTc:case a.Z.uVc:case a.Z.V3b:case a.Z.BVc:case a.Z.WOa:c.Bk(!0);
return}p.j.LB.call(this)};p.MB=function(a){var b=this.qo(),c=this.vq();(b||c)&&this.R1b(a,b,c)};p.R1b=function(a,e,g){var f=new c.ja,q=new c.ja(0,0,1E4,1E4);this.kw()&&q.Qa(q.Q()+a.aa()-(this.ea.Ri()+this.ea.$j()));this.zDb(q,!0);""==this.nb()&&this.G0.Yf()||(""==this.nb()?f=this.G0:(f=b.Bc(this.fH),f.Fa(f.ua+(0<this.fH.ba()?1:0)),f=f.w_(this.G0)));e&&a.Qa(a.Q()+this.ea.Ri()+this.BA+f.aa()+this.HA+this.ea.$j());g&&a.Fa(a.M()+this.ea.ak()+this.OA+f.ba()+this.sA+this.ea.zl())};p.mya=function(a,b){p.j.mya(a,
b);b[0]&&this.tJa()&&(b[0]=!1)};p.rf=function(a){b.cdb();return p.j.rf.call(this,a)};p.Xl=function(c,e){switch(e.Ya){case a.f.ub:case a.f.Rb:e.pi==this.Ha&&this.Xc(null);break;case a.f.i:e.pi==this.Ha&&(b.cb().wd(this),this.Gd())}};p.K1a=function(b,c){c.Ya==a.f.Rb&&this.eA(null)};p.Tt=p[a.$.QF]=function(a){p.j.Tt.call(this,a);b.cb().wd(this,!1)};p.Uhd=p[a.$.xwa]=function(){b.cb().wd(this,!1)};p.lK=p[a.$.Uz]=function(){b.cb().wd(this,!1)};p.Gha=p[a.$.Hwa]=function(a){this.Qy()?this.tf(!1):p.j.Gha.call(this,
a)};p.rO=p[a.$.eL]=function(){this.Uj&&this.Uj.Le()};p.Dy=p[a.$.Tz]=function(b){this.AB()&&(this.wo(),this.VHc(a.ibb.d_b));p.j.Dy.call(this,b)};e.$c(c.ls,"PRIM_LABL",{Pa:{Ellipses:{a:function(){return e.ta(this.Hf(),a.sn.v)},g:function(b){this.xg(e.qa(b,a.sn.v))}},Caption:{a:p.nb,g:function(a){this.Eb(e.ma(a))}},Alignment:{a:function(){return e.ta(this.Cg(),a.Jg.v)},g:function(b){this.Kb(e.qa(b,a.Jg.v))}},VerticalAlignment:{a:function(){return e.ta(this.DX(),a.lh.v)},g:function(b){this.On(e.qa(b,
a.lh.v))}},FocusControl:{a:p.hD,g:p.eA},WordWrap:{a:p.Fe,g:function(a){this.of(e.ya(a))}},Selectable:{a:p.tJa,g:function(a){this.h6b(e.ya(a))}},MarginLeft:{a:p.af,g:function(a){this.Qe(e.L(a))}},MarginTop:{a:p.Ye,g:function(a){this.Me(e.L(a))}},MarginBottom:{a:p.og,g:function(a){this.Af(e.L(a))}},MarginRight:{a:p.Vf,g:function(a){this.we(e.L(a))}},Image:{a:p.Ac,g:p.Xc},ImagePosition:{a:function(){return e.ta(this.Xt(),a.Nj.v)},g:function(b){this.ss(e.qa(b,a.Nj.v))}},ImageHeight:{a:p.fw,g:function(a){this.hu(e.L(a))}},
ImageSizing:{a:function(){return e.ta(this.DK(),a.$e.v)},g:function(b){this.OI(e.qa(b,a.$e.v))}}},Sf:{Of:"Caption"}});c.reb=function(a){u.w.call(this,a);this.kUa=this.Iu=this.dDa=this.ktb=this.jtb=this.Ha=this.bF=this.fga=this.EC=this.Hvb=this.Gvb=this.Fvb=this.mb=null};var u=c.u(c.reb,c.em);u.nb=function(){return this.mb.textContent};u.Eb=function(a){this.mb.textContent=a};u.N2=function(){return this.mb};u.BK=function(){return this.mb};u.Ag=function(b,c,g,f,q,n,d){null==this.Ha.parentElement&&this.G.appendChild(this.Ha);
if(null==this.kUa||this.kUa!=n)this.kUa=n,this.mb.spellcheck=!1,this.mb.setAttribute("contenteditable",n);this.Ha.style.backgroundImage=e.Uv(g);switch(this.pa.DK()){case a.$e.fQ:this.Ha.style.backgroundSize="contain";break;case a.$e.VQa:this.Ha.style.backgroundSize="cover";break;case a.$e.uf:this.Ha.style.backgroundSize="100% 100%";break;case a.$e.Od:this.Ha.style.backgroundSize="auto"}if(null==this.bF||this.bF!=q)this.bF=q,this.mb.style.whiteSpace=q?"pre-wrap":"pre";if(null==this.fga||this.fga!=
d)this.fga=d,this.mb.style.textAlign=0!=(d&a.Bf.kAa)?"right":0!=(d&a.Bf.Aca)?"center":"",0!=(d&a.Bf.hAa)||0!=(d&a.Bf.jAa)||0!=(d&a.Bf.lAa)?(this.mb.style.textOverflow="ellipsis",this.mb.style.overflow="hidden"):(this.mb.style.textOverflow="clip",this.mb.style.overflow="visible");if(null==this.Fvb||this.Fvb!=c.Q())this.Fvb=c.Q(),this.mb.style.left=c.Q()+"px";if(null==this.Gvb||this.Gvb!=c.M())this.Gvb=c.M(),this.mb.style.top=c.M()+"px";if(null==this.EC||this.EC!=c.ba())this.EC=c.ba(),this.mb.style.height=
c.ba()+"px";if(null==this.Hvb||this.Hvb!=c.aa())this.Hvb=c.aa(),this.mb.style.width=c.aa()+"px";if(null==this.jtb||this.jtb!=f.Q())this.jtb=f.Q(),this.Ha.style.left=f.Q()+"px";if(null==this.ktb||this.ktb!=f.M())this.ktb=f.M(),this.Ha.style.top=f.M()+"px";if(null==this.Iu||this.Iu!=f.ba())this.Iu=f.ba(),this.Ha.style.height=f.ba()+"px";if(null==this.dDa||this.dDa!=f.aa())this.dDa=f.aa(),this.Ha.style.width=f.aa()+"px"};u.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("LANSAHandle",
this.bc);this.mb=document.createElement("div");var c=this.mb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ha=document.createElement("div");c=this.Ha.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.mb);this.G.appendChild(this.Ha);return u.j.bf.call(this,a,b)};u.jW=function(){var a=this;this.E1();a.mb.addEventListener("paste",function(b){a.kba(b);b.preventDefault()},!1)};u.jpb=function(){var a="";u.j.jpb.call(this);"rgba(0,0,0,0)"==this.JTa&&""!=this.G.style.boxShadow&&(a=this.G.style.boxShadow);this.mb.style.textShadow=a};u.wL=function(a){u.j.wL.call(this,a);return!this.kUa};u.kba=function(){}});
