window.LANSA.addSrc("ver",function(e,c,a,b,p){c.TQb=function(){u.w.call(this);this.pf=new c.kd;this.qqa=this.$a=null};var u=c.u(c.TQb,c.jd);u.Kxc=function(){return document.hasFocus()};u.X1c=function(a,s,g){var f=e.td("PRIM_VS","Style"),q=null,n=null;s===p&&(s=0);g===p&&(g=0);if(a){if(0==s&&0==g)a.Ak(!0),q=a.ea;else if(0!=s){var d=a.YA(new c.ja,null);s=a.h7.Lb[s-1];a.yf().Oa().bgb(d,s,a.lfa,null,null,s.gb());q=s.Yu();if(0!=g&&(g=a.u1a(g-1)))for(var u in s.gb().Rt)if(n=s.gb().Rt[u],n.hn.zb==g){a.yf().Oa().$fb(d,
n.hn,n.hn.I$(),n.hn.qd.pJa(),n.hn.zb.Rua(),null);q=n.hn.I$();break}b.la(d)}q&&(f.Qj(q.ii),f.Jp(q.QW()),f.$h(q.dy),f.xw(q.Ly()),f.Ph(q.ox()),f.yd(q.$v()),f.fg(q.eD()),f.Nn(q.Vt()),f.nv(q.jx()),f.ov(q.kx()),f.lv(q.hx()),f.mv(q.ix()),f.Zm(q.Ri()),f.Kn(q.ak()),f.hm(q.zl()),f.Il(q.$j()),f.SL(q.Xd().lx()),f.rt(q.Xd().Ra()),f.fA(q.Xd().ui()),f.SD(q.Xd().fx()),f.YL(q.Xd().qx()),f.ZP(q.Xd().GF()),f.cQ(q.Xd().JF()));n&&(a.yf().Oa().Bj.sp&&f.Ph(a.yf().Oa().Bj.sp),a.yf().Oa().Bj.kj&&f.yd(a.yf().Oa().Bj.kj))}return f};
u.r9c=function(a,b){return a.F3a(b,[[]])};u.Okc=function(){null.xid()};u.Tjc=function(a,e,g){var f;g===p&&(g=1);f===p&&(f=!0);a=new c.kd(a,e);if((e=b.JT(a))&&e.ae()){var q=e.Nh(a),n=new c.it(e,q,a,1),d=new c.it(e,q,a,1),u=new c.it(e,q,a,2);b.fC(a.Bb(),a.Cb(),q.Bb(),q.Cb());f?(f=b.W(),e.Mj(n),null==f.Tj?e.In(d):(f=f.Tj.gb(),b.gqb(null,f,q.Bb(),q.Cb(),a.Bb(),a.Cb())),2==g&&(u=new c.it(e,q,a,2),e.Mj(u))):(e.UT(n),e.Vla(d));b.la(n);b.la(u);b.la(d)}};u.O9c=function(a,e){var g=new c.kd(a,e),f=b.JT(g);if(f&&
f.ae()){var p=f.Nh(g),n=new c.it(f,p,g,1),d=new c.it(f,p,g,1),u=new c.it(f,p,g,1),m=!1;b.fC(g.Bb(),g.Cb(),p.Bb(),p.Cb());f.yya(p,f,!1);f.xya(u);m=u.Tg;m||(f.Mj(n),f.In(d));b.la(n);b.la(d);b.la(u)}};u.jEc=function(a,e){var g=new c.kd(a,e),f=b.JT(g);if(f&&f.ae()){var p=f.Nh(g);for(b.fC(g.Bb(),g.Cb(),p.Bb(),p.Cb());f;)p=f.Nh(g),b.Tbc(null,f.gb(),p.Bb(),p.Cb(),g.Bb(),g.Cb()),f=f.U()}};u.iYc=function(a,e){var g=new c.kd(a,e),f=b.JT(g);f&&f.ae()&&(f=f.Nh(g),b.fC(g.Bb(),g.Cb(),f.Bb(),f.Cb()))};u.PYc=function(a,
e){(this.qqa=b.JT(new c.kd(a,e)))&&document.hasFocus()&&(b.dqb(this.qqa.gb()),this.qqa=null)};u.KHc=function(a,c){if(""!=a||0!=c){var e=0==c?a.charCodeAt(0):c,f;if(document.hasFocus())f=b.eqb();else if(this.qqa)f=this.qqa.gb();else return;b.Qbc(null,f,e);""!=a&&b.Rbc(null,f,a,a.charCodeAt(0));b.Sbc(null,f,e)}};u.AMc=function(a,e){this.pf=new c.kd(this.pf.Bb()+(0<a?1:0==a?0:-1),this.pf.Cb()+(0<e?1:0==e?0:-1));if(this.$a){var g=this.$a.Nh(this.pf);b.fC(this.pf.Bb(),this.pf.Cb(),g.Bb(),g.Cb());b.nXb(this.$a,
g,this.pf)}};u.UKc=function(a,e,g){g===p&&(g=1);this.pf=new c.kd(a,e);if(this.$a=b.JT(this.pf))a=!1,e=this.$a.Nh(this.pf),this.$a.Mf.Hk&&(new c.ja(this.$a.Mf.Hk.ff,this.$a.Mf.Hk.vf,this.$a.Mf.Hk.Uc,this.$a.Mf.Hk.bd)).$d(e)&&(this.$a.Mf.Hk.tya(null),a=this.$a.Mf.Hk.TE),a||(b.fC(this.pf.Bb(),this.pf.Cb(),e.Bb(),e.Cb()),b.lXb(this.$a,e,this.pf,g))};u.VKc=function(){if(this.$a){var a=!1,e=this.$a.Nh(this.pf);this.$a.Mf.Hk&&(new c.ja(this.$a.Mf.Hk.ff,this.$a.Mf.Hk.vf,this.$a.Mf.Hk.Uc,this.$a.Mf.Hk.bd)).$d(e)&&
(this.$a.Mf.Hk.uya(null),a=this.$a.Mf.Hk.TE);a||(b.fC(this.pf.Bb(),this.pf.Cb(),e.Bb(),e.Cb()),b.mXb(this.$a,e,this.pf,1));this.$a=null}};u.zTc=function(a,e){this.pf=new c.kd(a,e);if(this.$a=b.JT(this.pf)){var g=this.$a.Nh(this.pf);b.fC(this.pf.Bb(),this.pf.Cb(),g.Bb(),g.Cb());b.oXb(this.$a,g,this.pf,1)}};u.ATc=function(){if(this.$a){var a=this.$a.Nh(this.pf);b.fC(this.pf.Bb(),this.pf.Cb(),a.Bb(),a.Cb());b.pXb(this.$a,a,this.pf,1);this.$a=null}};e.jb(c.TQb,"PRIM_VER","Debugger",{Pa:{HasFocus:{a:u.Kxc}},
jc:{Crash:function(){this.Okc()},Click:function(a,b,c){this.Tjc(e.L(a),e.L(b),c===p?1:e.L(c))},Touch:function(a,b){this.O9c(e.L(a),e.L(b))},Hover:function(a,b){this.jEc(e.L(a),e.L(b))},SetCursorPos:function(a,b){this.iYc(e.L(a),e.L(b))},SetFocus:function(a,b){this.PYc(a,b)},KeyPress:function(a,b){this.KHc(e.ma(a),b===p?0:e.L(b))},MouseMove:function(a,b){this.AMc(a,b)},LeftMouseDown:function(a,b,c){this.UKc(e.L(a),e.L(b),c===p?1:e.L(c))},LeftMouseUp:function(){this.VKc()},RightMouseDown:function(a,
b){this.zTc(a,b)},RightMouseUp:function(){this.ATc()},StyleSnapshot:function(a,b,c){return this.X1c(a,b===p?0:e.L(b),c===p?0:e.L(c))},ThemeDrawStyle:function(a,b){return this.r9c(a,e.ma(b))}}})});
