window.LANSA.addSrc("msg",function(e,c,a,b,n){e.Fb("PRIM_PPNL");a.Hma={U4:0,GOc:1,IOc:2,DOc:4,EOc:8};a.Hma.v={NONE:a.Hma.U4,TEXT:a.Hma.GOc,WARNING:a.Hma.IOc,ERROR:a.Hma.DOc,FATAL:a.Hma.EOc};a.zZ={s1b:1,u1b:2,t1b:4};a.zZ.v={ERROR:a.zZ.s1b,QUESTION:a.zZ.u1b,INFORMATION:a.zZ.t1b};a.mp={Hgd:16,a0a:1,RGa:16,OGa:32,TGa:64,QGa:128,SGa:256,PGa:512};a.mp.v={NONE:a.mp.a0a,OK:a.mp.RGa,CANCEL:a.mp.OGa,YES:a.mp.TGa,NO:a.mp.QGa,RETRY:a.mp.SGa,IGNORE:a.mp.PGa};a.EG={xgb:16,w1b:48,x1b:192,y1b:224,v1b:768};a.EG.v=
{OK:a.EG.xgb,OKCANCEL:a.EG.w1b,YESNO:a.EG.x1b,YESNOCANCEL:a.EG.y1b,IGNORERETRY:a.EG.v1b};c.FWb=function(){q.w.call(this)};var q=c.u(c.FWb,c.wd);e.kd(c.FWb,"PRIM_MSG",{});c.pdb=function(){m.w.call(this);this.kD=[]};var m=c.u(c.pdb,c.wd);m.fBc=function(){e.Fb("PRIM_PCOL");var a=new c.JUb(this);return new c.pZ(a)};m.mh=function(a,b){var e=new c.qdb(this,a);this.kD.push(e);e.dj(b);this.$uc(e);return e};m.op=function(a){if(a)for(var b=0;b<this.kD.length;b++){var c=this.kD[b];c.ga()==a&&(this.sIb(c),this.kD.splice(b--,
1),c.WBb())}};m.Glc=function(){for(;0<this.kD.length;){var a=this.kD.shift();this.sIb(a);a.WBb()}};m.$uc=function(b){var c=e.Qb();c.Wb("MESSAGE",b);this.Ga(a.K.nOc,c);c.nc()};m.sIb=function(b){var c=e.Qb();c.Wb("MESSAGE",b);this.Ga(a.K.oOc,c);c.nc()};e.kd(c.pdb,"PRIM_MSGQ",{Oa:{Messages:{a:m.fBc}},ic:{Add:function(a,b){return this.mh(e.ma(a),b===n?null:b)},Clear:function(a){return this.op(a===n?null:a)},ClearAll:function(){return this.Glc()}}});c.JUb=function(a){s.w.call(this);this.ZEa=a};var s=c.u(c.JUb,
c.Iba);s.lc=function(){return this.ZEa.kD.length};s.Gw=function(a){return this.ZEa.kD[a]};c.qdb=function(a,b){g.w.call(this);this.ZEa=a;this.Ig=b;this.eb=null};var g=c.u(c.qdb,c.wd);g.Aq=function(){return this.Ig};g.ga=function(){return this.eb};g.dj=function(a){this.pg()&&this.eb!=a&&(null!=this.eb&&(this.eb.wM(this),this.eb.Ca(this,this.Ms)),this.eb=a)&&(a.KK(this),a.Da(this,this.Ms))};g.pg=function(){return null!==this.ZEa};g.WBb=function(){this.dj(null);this.Ig="";this.ZEa=null};g.Ms=function(b,
c){switch(c.Ya){case a.f.sb:this.dj(null)}};e.jb(c.qdb,"PRIM_MSGQ","Message",{Oa:{Text:{a:g.Aq},Control:{a:g.ga,g:g.dj}}});c.J_b=function(){k.w.call(this);this.Kqa=[]};var k=c.u(c.J_b,c.wd);k.U=function(){this.Yj();k.j.U.call(this)};k.Sd=function(a){return this.Kqa[a]};k.lc=function(){return this.Kqa.length};k.mh=function(b){this.Kqa.push(b);this.l(a.f.h)};k.Yj=function(){this.Kqa=[];this.l(a.f.h)};k.PAc=function(){for(var a="",b=0;b<this.Kqa.length;b++){var c=this.Kqa[b];c.length>a.length&&(a=c)}return a};
e.jb(c.J_b,"PRIM_WEB","MessageBoxCaptions",{ic:{Add:k.mh,RemoveAll:k.Yj}});c.I_b=function(){f.w.call(this);e.Fb("PRIM_PHBN");e.Fb("PRIM_LABL");this.JFa=this.L8=this.Sha=null;this.YEa=a.zZ.t1b;this.hB=a.EG.xgb;this.Re=a.mp.a0a;this.mVa=[];this.NR=null;this.GZa=new c.Us;this.FZa=new c.yQ;this.sD=new c.bn;this.uH=e.bd("PRIM_WEB","MessageBoxCaptions");this.uH.Ba();this.uH.Da(this,this.GCb);this.Mf=new c.Qeb;this.lN=new c.yQ;this.GH=new c.yQ;this.IK=new c.yQ;this.TN=new c.yQ;this.cO=new c.yQ;this.lK=new c.yQ;
this.GH.Aa(this,a.K.bc,this.Cqc);this.lN.Aa(this,a.K.bc,this.Poc);this.IK.Aa(this,a.K.bc,this.tsc);this.TN.Aa(this,a.K.bc,this.Aqc);this.cO.Aa(this,a.K.bc,this.grc);this.lK.Aa(this,a.K.bc,this.bqc);this.sD.Na(this);this.Mf.Na(this);this.lN.Na(this);this.GH.Na(this);this.IK.Na(this);this.TN.Na(this);this.cO.Na(this);this.lK.Na(this);this.L8=new c.pb;this.JFa=new c.wg;this.L8.xd(this.JFa);this.JFa.Ed(a.m.iR);this.JFa.qg(9);this.e8b(this.L8);this.L8.Ba();this.JFa.Ba();this.sD.Ta(90);this.sD.Gf(!1);this.sD.Ua(57);
this.sD.Ib(!0);this.sD.fR(!0);this.sD.h_(!0);this.Mf.$e(6);this.Mf.JE(a.Sg.pq);this.Mf.Ta(20);this.Mf.Ua(57);this.Mf.Vu(64);this.Mf.KM(64);this.Mf.xc(64);this.Mf.ac(64);this.Mf.Gf(!1);this.GH.Bb(b.Ao().ok||"OK");this.TN.Bb(b.Ao().no||"No");this.IK.Bb(b.Ao().yes||"Yes");this.cO.Bb(b.Ao().retry||"Retry");this.lN.Bb(b.Ao().cancel||"Cancel");this.lK.Bb(b.Ao().ignore||"Ignore");this.z6b(this.hB);this.BQa(!1);this.Zlb(!0)};var f=c.u(c.I_b,c.Tw);f.U=function(){this.uH.Ca(this,this.GCb);this.uH.xb();this.uH=
null;this.pBb();f.j.U.call(this)};f.VYc=function(a){this.GZa.tb(a)};f.Cwc=function(){return this.GZa.og()};f.Dwc=function(){return this.GZa.Tj()};f.wja=function(){return this.FZa.og()};f.RG=function(a){this.FZa.tb(a)};f.wwc=function(){return this.FZa.Tj()};f.kBa=function(b){b!=this.lU()&&(this.Bb(b),this.tUa(),this.l(a.f.h))};f.lU=function(){return this.nb()};f.v0c=function(b){this.uH.Yj();b!=this.PKb()&&(this.uH.mh(b),this.l(a.f.h))};f.Fwc=function(){return this.uH};f.PKb=function(){return 0<this.uH.lc()?
this.uH.Sd(0):""};f.P6b=function(b){this.NR!==b&&(null!=this.NR&&(this.NR.Ca(this,this.VCb),this.NR.xb()),this.NR=b,null!==this.NR&&(this.NR.Ba(),this.NR.Da(this,this.VCb)),this.tUa(),this.l(a.f.h))};f.Bxc=function(){return this.NR};f.w0c=function(b){this.YEa!=b&&(this.YEa=b,this.tUa(),this.l(a.f.h))};f.utd=function(){return this.YEa};f.z6b=function(b){this.hB=b;this.GH.Ib(0!=(this.hB&a.mp.RGa));this.lN.Ib(0!=(this.hB&a.mp.OGa));this.IK.Ib(0!=(this.hB&a.mp.TGa));this.TN.Ib(0!=(this.hB&a.mp.QGa));
this.lK.Ib(0!=(this.hB&a.mp.PGa));this.cO.Ib(0!=(this.hB&a.mp.SGa))};f.god=function(){return this.hB};f.UKd=function(a){this.Re=a};f.fvd=function(){return this.Re};f.dnc=function(b,e,f){var g=new c.Us;g.Na(this.sD);g.Ta(0);g.Gf(!1);g.Ua(e);g.Jn(a.Sg.pq);g.ac(f.Xa());g.xc(f.Qa());g.Pe(!1);g.Bb(b);return g};f.X8b=function(a,e){var f=b.Sw(0,0),g=new c.ha(0,0,0,0);b.sC(a,g,0,e);f.ac(g.aa()+2);f.xc(g.ba()+2);return f};f.cCc=function(){if(null!=this.NR)return this.NR;var d="";switch(this.YEa){case a.zZ.s1b:d=
"lansa_error.png";break;case a.zZ.u1b:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.ZL;e.$v(b.sc(d));return e};f.Aic=function(){var a=this.FZa.Tj().$a.ZD(),b=null;this.GH.Tj().Yj();this.lN.Tj().Yj();this.IK.Tj().Yj();this.TN.Tj().Yj();this.cO.Tj().Yj();this.lK.Tj().Yj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.GH.Tj().mh(b),this.lN.Tj().mh(b),this.IK.Tj().mh(b),this.TN.Tj().mh(b),this.cO.Tj().mh(b),this.lK.Tj().mh(b);this.GH.Wj(!1,!0);this.lN.Wj(!1,!0);
this.IK.Wj(!1,!0);this.TN.Wj(!1,!0);this.cO.Wj(!1,!0);this.lK.Wj(!1,!0)};f.Gic=function(){var a=this.GZa.Tj().$a.ZD(),b=null;this.sD.Tj().Yj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.sD.Tj().mh(b);this.sD.Wj(!1,!0)};f.poa=function(){this.Sha=b.gR();this.Re=a.mp.a0a;this.vAb();var c=b.um();this.Gz(a.Ri.h5,null,c,null);this.TZc()};f.tUa=function(){this.PL()&&(this.vAb(),this.eh())};f.vAb=function(){var a;this.pBb();this.Mf.Zc(this.cCc());this.Aic();this.Gic();a=this.qyb();this.lQc(a)};
f.gAa=function(){this.qyb();f.j.gAa.call(this)};f.qyb=function(){var a=this.pA(),b=this.blc(),c=this.hlc(),c=this.glc(c),e=this.dlc(a),f=this.clc(b),g=this.jlc(c,e,f);this.BUc(g,b,e);this.hic(b,c,f,g);return a};f.BUc=function(a,b,c){this.ac(a.Xa());this.xc(a.Qa());a=b.Xa();b=b.Qa();this.lN.ac(a);this.GH.ac(a);this.IK.ac(a);this.TN.ac(a);this.cO.ac(a);this.lK.ac(a);this.lN.xc(b);this.GH.xc(b);this.IK.xc(b);this.TN.xc(b);this.cO.xc(b);this.lK.xc(b);this.sD.ac(c.Xa());this.sD.xc(c.Qa())};f.hic=function(a,
b,c,e){this.TYc(a);a=e.Qa()-c.Qa();this.lN.Ua(a);this.GH.Ua(a);this.IK.Ua(a);this.TN.Ua(a);this.cO.Ua(a);this.lK.Ua(a);this.Mf.Ta(20);this.Mf.Ua(this.Zq.Qa()+20);this.sD.Ta(40+b.Xa());this.sD.Ua(this.Zq.Qa()+20)};f.jlc=function(a,c,e){var f=b.qE(),g=b.Sw(0,0);a=this.flc(a,c);c=this.iA.hLa(this.iA.nb(),this.iA.wn().length)+10;g.ac(Math.max(a.Xa(),c,e.Xa())+60);g.xc(this.Zq.Qa()+a.Qa()+e.Qa()+40);g.ac(Math.min(f.aa()-40,g.Xa()));g.xc(Math.min(f.ba()-40,g.Qa()));return g};f.$ja=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};f.OAc=function(){var a="",a=this.$ja(this.GH.nb(),a),a=this.$ja(this.lN.nb(),a),a=this.$ja(this.IK.nb(),a),a=this.$ja(this.TN.nb(),a),a=this.$ja(this.cO.nb(),a),a=this.$ja(this.lK.nb(),a);return" "+a+" "};f.blc=function(){var a=this.OAc(),c=b.Sw(0,0),c=this.GH.je();return c=this.X8b(a,c)};f.pA=function(){var a=this.uH.PAc(),c=b.Sw(0,0),c=this.sD.je();return c=this.X8b(a,c)};f.hlc=function(){var a=b.Sw(0,0);a.ac(this.Mf.Xa());a.xc(this.Mf.Qa());return a};f.dlc=function(a){var c=
b.Sw(0,0),e=a.Xa()+4;a=this.uH.lc()*(a.Qa()+4);e+=20;a+=20;e=170>e?170:e;a=70>a?70:a;a=630<a?630:a;c.ac(630<e?630:e);c.xc(a);return c};f.glc=function(a){var c=b.Sw(0,0);c.xc(a.Qa()+16);c.ac(a.Xa()+8);return c};f.flc=function(a,c){var e=b.Sw(0,0);e.xc(Math.max(a.Qa(),c.Qa()));e.ac(2+a.Xa()+2+c.Xa()+2);return e};f.clc=function(a){var c=b.Sw(0,0),e=66>a.Xa()?66:a.Xa(),f=25>a.Qa()?25:a.Qa();a.ac(e);a.xc(f);c.xc(a.Qa()+24);c.ac(3*a.Xa()+8);return c};f.TYc=function(b){b=b.Xa()+20;var c=1;this.hB&a.mp.SGa&&
(this.cO.Ta(this.Xa()-c*b),++c);this.hB&a.mp.PGa&&(this.lK.Ta(this.Xa()-c*b),++c);this.hB&a.mp.OGa&&(this.lN.Ta(this.Xa()-c*b),++c);this.hB&a.mp.RGa&&(this.GH.Ta(this.Xa()-c*b),++c);this.hB&a.mp.QGa&&(this.TN.Ta(this.Xa()-c*b),++c);this.hB&a.mp.TGa&&this.IK.Ta(this.Xa()-c*b)};f.lQc=function(a){for(var b=0,c=a.Qa(),e=0;e<this.uH.lc();e++)this.mVa.push(this.dnc(this.uH.Sd(e),b,a)),b+=c};f.TZc=function(){switch(this.hB){case a.EG.xgb:case a.EG.w1b:this.GH.Ve(!0,!0);break;case a.EG.x1b:case a.EG.y1b:this.IK.Ve(!0,
!0);break;case a.EG.v1b:this.lK.Ve(!0,!0)}};f.Fka=function(a){this.Re=a;this.Mm();b.ty(this.Sha);this.Sha=null};f.pBb=function(){for(var a=0;a<this.mVa.length;++a)this.mVa[a].Na(null);this.mVa=[]};f.GCb=function(){this.tUa()};f.Cqc=function(){this.Fka(a.mp.RGa)};f.Poc=function(){this.Fka(a.mp.OGa)};f.tsc=function(){this.Fka(a.mp.TGa)};f.Aqc=function(){this.Fka(a.mp.QGa)};f.grc=function(){this.Fka(a.mp.SGa)};f.bqc=function(){this.Fka(a.mp.PGa)};f.VCb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.P6b(null);
break;case a.f.h:this.l(a.f.h)}};e.jb(c.I_b,"PRIM_WEB","MessageBox",{Oa:{Title:{a:f.lU,g:function(a){this.kBa(e.ma(a))}},Caption:{a:f.PKb,g:function(a){this.v0c(e.ma(a))}},Text:{a:f.Aq,g:function(a){this.SM(e.ma(a))}},Captions:{a:f.Fwc},Image:{a:function(){return e.ta(this.YEa,a.zZ.v)},g:function(b){this.w0c(e.qa(b,a.zZ.v))}},CustomImage:{a:f.Bxc,g:function(a){this.P6b(a)}},Result:{a:function(){return e.ta(this.Re,a.mp.v)}},Buttons:{a:function(){return e.ta(this.hB,a.EG.v)},g:function(b){this.z6b(e.qa(b,
a.EG.v))}},CaptionStyle:{a:f.Cwc,g:function(a){this.VYc(a)}},CaptionStyles:{a:f.Dwc},ButtonStyle:{a:f.wja,g:function(a){this.RG(a)}},ButtonStyles:{a:f.wwc}},ic:{Show:f.poa}});c.Deb=function(b){l.w.call(this);this.QXa=[];this.kD=[];this.eb=b;this.Oc=new c.Tw;this.Oc.Aa(this,a.K.Uv,this.T9);this.Oc.Aa(this,a.K.ZO,this.e3a);this.aha=new c.bn;this.aha.kb(new c.ha(0,0,100,25));this.aha.Na(this.Oc);this.aha.Gf(!1);this.aha.$b(a.nSb)};var l=c.u(c.Deb,c.rk);l.ds=function(){return this.Oc};l.Yf=function(){return 0==
this.kD.length};l.KK=function(a){this.kD.push(a)};l.wM=function(a){this.kD.splice(this.kD.indexOf(a),1);this.Yf()&&this.Oc.Mm()};l.T9=function(){e.Fb("PRIM_LABL");for(var b=0,f=6,g=100;b<this.kD.length;b++){var l=this.QXa[b],k=this.kD[b];l||(l=new c.Us,l.Ta(5),l.Gf(!1),l.Ua(f),l.Jn(a.Sg.pq),l.ac(320),l.xc(20),l.Pe(!1),this.QXa.push(l));l.Na(this.aha);l.Bb(k.Aq());l.zlc();g<l.Xa()+15&&(g=l.Xa()+15);f+=25}for(;b<this.QXa.length;b++)l=this.QXa[b],l.Na(null);this.aha.xc(f+6);this.aha.ac(g);this.Oc.xc(f+
6);this.Oc.ac(g)};l.e3a=function(){this.eb.Wj(!0)}},{rp:["PRIM_PPNL"]});
