window.LANSA.addSrc("web",function(e,c,a,b,n){e.Fb("PRIM_LABL");var q=null,m=null;a.lJ={Hjb:0,D5b:1,E5b:2,C5b:3};a.lJ.v={INLINE:a.lJ.Hjb,LEFT:a.lJ.D5b,RIGHT:a.lJ.E5b,CENTER:a.lJ.C5b};a.oE={SIa:0,NGb:1,RGb:2,SGb:3,UGb:4,p4a:5};a.oE.v={NONE:a.oE.SIa,NOTLOADED:a.oE.NGb,PERMISSIONDENIED:a.oE.RGb,POSITIONUNAVAILABLE:a.oE.SGb,TIMEOUT:a.oE.UGb,UNKNOWNERROR:a.oE.p4a};a.lT={Fzb:0,Dzb:1,Gzb:2,Ezb:4};a.lT.v={NONE:a.lT.Fzb,ERROR:a.lT.Dzb,WARNING:a.lT.Gzb,INFORMATION:a.lT.Ezb};c.Gfb=function(){s.w.call(this);
this.ab=[]};var s=c.u(c.Gfb,c.wd);s.U=function(){s.j.U.call(this)};s.lc=function(){return this.ab.length};s.Sd=function(a){return this.ab[a-1]};s.hG=function(a){for(var c=null,d=0;d<this.ab.length;d++){var e=this.ab[d];if(b.uC(e.Im,a)){c=e;break}}return c};e.jb(c.Gfb,"PRIM_WEB","URLParameters",{Oa:{Item:{a:function(a){return this.hG(e.ma(a))},zw:"na"},ItemCount:{a:s.lc}},ig:{dg:"Item"},gq:{Ap:function(a){return this.Sd(e.G(a))},Lv:s.lc}});c.Ffb=function(){g.w.call(this);this.bb=this.Im=""};var g=
c.u(c.Ffb,c.wd);g.oh=function(){return this.Im.toUpperCase()};g.Ia=function(){return this.bb};e.jb(c.Ffb,"PRIM_WEB","URLParameter",{Oa:{Name:{a:g.oh},Value:{a:g.Ia}}});c.Dfb=function(){k.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(q=localStorage)}catch(c){}this.Tq=null};var k=c.u(c.Dfb,c.wd);k.U=function(){k.j.U.call(this)};k.J5a=function(){return null!=q};k.lc=function(){return this.OP().length};k.Sd=function(a){return this.OP()[a-
1]};k.hG=function(a){for(var b=null,c=this.OP(),d=0;d<c.length;d++){var e=c[d];if(e.Im==a){b=e;break}}return b};k.OP=function(){if(null==this.Tq&&(this.Tq=[],q))for(var a=0;a<q.length;a++){var b=q.key(a);""!=b&&q[b]!=n&&this.Tq.push(new c.eOa(b))}return this.Tq};k.eAa=function(){this.Tq=null};k.mh=function(a,b){var d=this.OP(),e=this.hG(a);null==e&&(e=new c.eOa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};k.Xs=function(c){var d=this.OP(),e=this.hG(c);null!=e&&(q.removeItem(c),d.splice(d.indexOf(e),
1),b.Cp().u$(a.OE.roa))};k.op=function(){q&&(q.clear(),this.eAa(),b.Cp().u$(a.OE.roa))};e.jb(c.Dfb,"PRIM_WEB","LocalStorage",{Oa:{Available:{a:k.J5a},Item:{a:function(a){return this.hG(e.ma(a))},zw:"na"},ItemCount:{a:k.lc}},ic:{Add:k.mh,Remove:k.Xs,Clear:k.op},ig:{dg:"Item"},gq:{Ap:function(a){return this.Sd(e.G(a))},Lv:k.lc}});c.eOa=function(a){f.w.call(this);this.Im=a};var f=c.u(c.eOa,c.wd);f.oh=function(){return this.Im};f.Ia=function(){var a="";q&&(a=q[this.Im],a===n&&(a=""));return a};f.Wa=function(c){var d=
!0;try{q[this.Im]=c,b.Cp().u$(a.OE.roa)}catch(e){b.Cp().xIb(a.OE.roa),d=!1}return d};e.jb(c.eOa,"PRIM_WEB","LocalStorageItem",{Oa:{Name:{a:f.oh},Value:{a:f.Ia,g:function(a){this.Wa(e.ma(a))}}},ig:{dg:"Value"}});c.Efb=function(){l.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(m=sessionStorage)}catch(c){}this.Tq=null};var l=c.u(c.Efb,c.wd);l.U=function(){l.j.U.call(this)};l.J5a=function(){return null!=m};l.lc=
function(){return this.OP().length};l.Sd=function(a){return this.OP()[a-1]};l.hG=function(a){for(var b=null,c=this.OP(),d=0;d<c.length;d++){var e=c[d];if(e.Im==a){b=e;break}}return b};l.OP=function(){if(null==this.Tq&&(this.Tq=[],m))for(var a=0;a<m.length;a++){var b=m.key(a);""!=b&&m[b]!=n&&this.Tq.push(new c.fOa(b))}return this.Tq};l.eAa=function(){this.Tq=null};l.mh=function(a,b){var d=this.OP(),e=this.hG(a);null==e&&(e=new c.fOa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};l.Xs=function(c){var d=
this.OP(),e=this.hG(c);null!=e&&(m.removeItem(c),d.splice(d.indexOf(e),1),b.Cp().u$(a.OE.soa))};l.op=function(){m&&(m.clear(),this.eAa(),b.Cp().u$(a.OE.soa))};e.jb(c.Efb,"PRIM_WEB","SessionStorage",{Oa:{Available:{a:l.J5a},Item:{a:function(a){return this.hG(e.ma(a))},zw:"na"},ItemCount:{a:l.lc}},ic:{Add:l.mh,Remove:l.Xs,Clear:l.op},ig:{dg:"Item"},gq:{Ap:function(a){return this.Sd(e.G(a))},Lv:l.lc}});c.fOa=function(a){d.w.call(this);this.Im=a};var d=c.u(c.fOa,c.wd);d.oh=function(){return this.Im};
d.Ia=function(){var a="";m&&(a=m[this.Im],a===n&&(a=""));return a};d.Wa=function(c){var d=!0;try{m[this.Im]=c,b.Cp().u$(a.OE.soa)}catch(e){b.Cp().xIb(a.OE.soa),d=!1}return d};e.jb(c.fOa,"PRIM_WEB","SessionStorageItem",{Oa:{Name:{a:d.oh},Value:{a:d.Ia,g:function(a){this.Wa(e.ma(a))}}},ig:{dg:"Value"}});c.Cfb=function(){h.w.call(this)};var h=c.u(c.Cfb,c.wd);h.U=function(){h.j.U.call(this)};h.nEc=function(a){0<a&&window.history.go(0-a)};h.oEc=function(a){0<a&&window.history.go(a)};h.mh=function(a,c){var d=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.Cp().rjb();c&&b.Cp().kJa()};h.DTc=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.Cp().rjb();c&&b.Cp().kJa()};e.jb(c.Cfb,"PRIM_WEB","History",{ic:{Add:function(a,b){this.mh(e.ma(a),b===n?!0:e.ya(b))},Replace:function(a,b){this.DTc(e.ma(a),b===n?!0:e.ya(b))},
GoBack:function(a){this.nEc(a===n?1:e.G(a))},GoForward:function(a){this.oEc(a===n?1:e.G(a))}}});c.x_b=function(){z.w.call(this);this.qd=b.Cd(0,0,400,400);this.TDa=this.We="";this.rg&=~a.Ug.pQ;this.rg&=~a.Ug.cZ};var z=c.u(c.x_b,c.bn);z.dh=function(){return c.P_b};z.lG=function(){return this.We};z.Kl=function(b){this.We!=b&&(this.We=b,this.ea(a.f.h))};z.UT=function(){return this.TDa};z.ukb=function(a){this.TDa=a};z.Kd=function(a,c,d){z.j.Kd.call(this,a,c,d);a=this.Pa().hb();b.Qd[a].Kl(this.We)};z.Zuc=
function(){this.Ga(a.K.QSb)};e.jb(c.x_b,"PRIM_WEB","Page",{Oa:{Source:{a:z.lG,g:function(a){this.Kl(e.ma(a))}},Description:{a:z.UT,g:function(a){this.ukb(e.ma(a))}}}});c.uma=function(){C.w.call(this)};var C=c.u(c.uma,c.bn);C.G7a=function(){for(var a=null,b=this;b;){if(b instanceof c.Hfb){a=b;break}b=b.Tb}return a};C.Fca=function(){C.j.Fca.call(this);var a=this.G7a();a&&a.WX(this)};C.KZ=function(){C.j.KZ.call(this);var a=this.G7a();a&&a.XX(this)};C.yf=function(a){C.j.yf.call(this,a);var b=this.G7a();
b==this&&b.zA(a,!1)};e.jb(c.uma,"PRIM_WEB","RichTextItem",{});c.Lfb=function(){t.w.call(this)};var t=c.u(c.Lfb,c.uma);t.dh=function(){return c.E0b};e.jb(c.Lfb,"PRIM_WEB","RichTextLine",{});c.Ifb=function(){v.w.call(this)};var v=c.u(c.Ifb,c.uma);v.dh=function(){return c.C0b};e.jb(c.Ifb,"PRIM_WEB","RichTextBreak",{});c.Jfb=function(){K.w.call(this);this.ZW=null;this.zFa=a.lJ.Hjb;this.LYa=this.MYa=0};var K=c.u(c.Jfb,c.uma);K.U=function(){K.j.U.call(this);this.FRa(null)};K.dh=function(){return c.D0b};
K.oCc=function(){return this.ZW};K.FRa=function(b){this.ZW!=b&&(null!=this.ZW&&(this.ZW.Ca(this,this.gEb),this.ZW.xb()),this.ZW=b,null!=this.ZW&&(this.ZW.Ba(),this.ZW.Da(this,this.gEb)),this.ea(a.f.h))};K.gvd=function(){return this.zFa};K.S7b=function(b){this.zFa!=b&&(this.zFa=b,this.ea(a.f.h))};K.pCc=function(){return this.MYa};K.U7b=function(b){this.MYa!=b&&(this.MYa=b,this.ea(a.f.h))};K.nCc=function(){return this.LYa};K.T7b=function(b){this.LYa!=b&&(this.LYa=b,this.ea(a.f.h))};K.Kd=function(a,
c,d){K.j.Kd.call(this,a,c,d);a=this.Pa().hb();b.Qd[a].Rg(this.zFa,this.MYa,this.LYa)};K.cjb=function(){var a=this.ZW,c=this.Pa().hb(),a=a?a.wh():"";b.Qd[c].Zc(a)};K.gEb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.FRa(null);break;case a.f.h:this.ea(a.f.h)}};e.jb(c.Jfb,"PRIM_WEB","RichTextImage",{Oa:{Image:{a:K.oCc,g:function(a){this.FRa(a)}},Width:{a:K.pCc,g:function(a){this.U7b(e.G(a))}},Height:{a:K.nCc,g:function(a){this.T7b(e.G(a))}},Alignment:{a:function(){return e.ta(this.zFa,a.lJ.v)},
g:function(b){this.S7b(e.qa(b,a.lJ.v))}}}});c.gOa=function(){D.w.call(this);this.My=null};var D=c.u(c.gOa,c.uma);D.dh=function(){return c.F0b};D.pz=function(){null==this.My&&(this.My=new c.Kfb(this));return this.My};e.jb(c.gOa,"PRIM_WEB","RichTextParagraph",{Oa:{Items:{a:D.pz}}});c.Hfb=function(){O.w.call(this);this.qd=b.Cd(0,0,100,100)};var O=c.u(c.Hfb,c.gOa);O.dh=function(){return c.B0b};O.WX=function(b){if(!this.ed()){var c=e.Qb();c.Wb("ITEM",b);this.Ga(a.K.RI,c);c.nc()}};O.XX=function(b){if(!this.ed()){var c=
e.Qb();c.Wb("ITEM",b);this.Ga(a.K.TI,c);c.nc()}};O.k3=function(b){if(!this.ed()){var c=e.Qb();c.Wb("ITEM",b);this.Ga(a.K.SI,c);c.nc()}};O.zA=function(b,c){if(!c&&!this.ed()){var d=e.Qb();d.Wb("ITEM",b);d.nf("CONTINUE",!0);this.Ga(a.K.QI,d);c=!d.gg("CONTINUE");d.nc()}return c};e.jb(c.Hfb,"PRIM_WEB","RichText",{});c.Kfb=function(a){x.w.call(this);this.ab=[];this.kA=a};var x=c.u(c.Kfb,c.wd);x.U=function(){x.j.U.call(this)};x.lc=function(){return this.ab.length};x.Sd=function(a){return this.ab[a-1]};
x.mh=function(b,d,e,f){var h=new c.Lfb;h.Ba();h.Bb(b);d!=n&&h.tb(d);e!=n&&h.jn(e);f!=n&&h.Wo(f);h.Na(this.kA);this.ab[this.ab.length]=h;this.kA.ea(a.f.h);this.kA.Pb()&&this.kA.eh();return h};x.Khc=function(){var b=new c.Ifb;b.Ba();b.Na(this.kA);this.ab[this.ab.length]=b;this.kA.ea(a.f.h);this.kA.Pb()&&this.kA.eh();return b};x.Thc=function(b,d,e,f,h,g,l){var k=new c.Jfb;k.Ba();k.FRa(b);d!=n&&k.S7b(d);e!=n&&k.U7b(e);f!=n&&k.T7b(f);h!=n&&k.tb(h);g!=n&&k.jn(g);l!=n&&k.Wo(l);k.Na(this.kA);this.ab[this.ab.length]=
k;this.kA.ea(a.f.h);this.kA.Pb()&&this.kA.eh();return k};x.Yhc=function(b,d,e,f){var h=new c.gOa;h.Ba();b!=n&&h.Bb(b);d!=n&&h.tb(d);e!=n&&h.jn(e);f!=n&&h.Wo(f);h.Na(this.kA);this.ab[this.ab.length]=h;this.kA.ea(a.f.h);this.kA.Pb()&&this.kA.eh();return h};x.Xs=function(b){this.ab.splice(this.ab.indexOf(b),1);b.Na(null);b.xb();this.kA.ea(a.f.h)};x.Yj=function(){for(;0<this.ab.length;)this.Xs(this.ab[0]);this.kA.ea(a.f.h)};e.jb(c.Kfb,"PRIM_WEB","RichTextItems",{Oa:{Item:{a:function(a){return this.Sd(e.G(a))},
zw:"na"},ItemCount:{a:x.lc}},ic:{Add:x.mh,AddBreak:x.Khc,AddImage:function(b,c,d,f,h,g,l){return this.Thc(b,e.qa(c,a.lJ.v),d,f,h,g,l)},AddParagraph:x.Yhc,Remove:x.Xs,RemoveAll:x.Yj},ig:{dg:"Item"},gq:{Ap:function(a){return this.Sd(e.G(a))},Lv:x.lc}});c.z_b=function(){B.w.call(this);this.qd=b.Cd(0,0,100,100)};var B=c.u(c.z_b,c.bn);B.dh=function(){return c.g0b};B.Kd=function(a,b,c){B.j.Kd.call(this,a,b,c)};B.xg=function(a){this.hJ();a&&this.Gza();b.cb().HB(this)};B.zC=function(){this.ca.rX()};e.jb(c.z_b,
"PRIM_WEB","Camera",{});c.K_b=function(){H.w.call(this);this.qd=b.Cd(0,0,100,100);this.YE=null;this.nHa("")};var H=c.u(c.K_b,c.bn);H.U=function(){this.YE=null;H.j.U.call(this)};H.dh=function(){return c.G0b};H.gva=function(){this.Pa()&&this.nHa(this.Pa().nwc());return this.YE};H.nHa=function(a){this.YE=new c.zG({data:a,mimetype:"image/png",filename:"signature.png"})};H.op=function(){if(this.Pa()){var a=this.Pa().hb();b.Qd[a].op();this.qc()}};H.Kd=function(a,b,c){H.j.Kd.call(this,a,b,c)};H.xg=function(a){this.hJ();
a&&this.Gza();b.cb().HB(this)};H.zC=function(){this.ca.rX()};H.qc=function(){this.Ga(a.K.Zg)};e.jb(c.K_b,"PRIM_WEB","Signature",{Oa:{Blob:{a:H.gva}},ic:{Clear:H.op}});c.F_b=function(){J.w.call(this);this.wwb=this.Kub=this.dsb=this.csb=this.Zrb=this.RXa=this.wvb=0;this.Q7=a.oE.NGb};var J=c.u(c.F_b,c.wd);J.QAc=function(){return this.wvb};J.aAc=function(){return this.RXa};J.Jvc=function(){return this.Zrb};J.Uvc=function(){return this.csb};J.Vvc=function(){return this.dsb};J.uzc=function(){return this.Kub};
J.RCc=function(){return this.wwb};J.Krd=function(){return this.Q7};J.MSc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.wvb=d.coords.longitude;b.RXa=d.coords.latitude;b.Zrb=d.coords.accuracy;b.csb=d.coords.altitude?d.coords.altitude:0;b.dsb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.Kub=d.coords.heading?d.coords.heading:0;b.wwb=d.coords.speed?d.coords.speed:0;b.Q7=a.oE.SIa;d=new c.Ula;b.Ga(a.K.x4b,d)},function(d){b.wvb=0;b.RXa=0;b.Zrb=
0;b.csb=0;b.dsb=0;b.Kub=0;b.wwb=0;b.Q7=a.oE.p4a;switch(d.code){case d.PERMISSION_DENIED:b.Q7=a.oE.RGb;break;case d.POSITION_UNAVAILABLE:b.Q7=a.oE.SGb;break;case d.TIMEOUT:b.Q7=a.oE.UGb;break;case d.UNKNOWN_ERROR:b.Q7=a.oE.p4a}d=new c.Ula;b.Ga(a.K.x4b,d)});return this.RXa};e.jb(c.F_b,"PRIM_WEB","Geolocation",{Oa:{Longitude:{a:J.QAc},Latitude:{a:J.aAc},Accuracy:{a:J.Jvc},Altitude:{a:J.Uvc},AltitudeAccuracy:{a:J.Vvc},Heading:{a:J.uzc},Speed:{a:J.RCc},ErrorCode:{a:function(){return e.ta(this.Q7,a.oE.v)}}},
ic:{Refresh:J.MSc}});c.B_b=function(){y.w.call(this)};var y=c.u(c.B_b,c.wd);y.WMc=function(b,c){if("undefined"!==typeof console)switch(c){case a.lT.Dzb:console.error(b);break;case a.lT.Gzb:console.warn(b);break;case a.lT.Ezb:console.info(b);break;default:console.log(b)}};e.jb(c.B_b,"PRIM_WEB","Console",{Oa:{},ic:{Log:function(b,c){return this.WMc(e.ma(b),c?e.qa(c,a.lT.v):a.lT.Fzb)}}});c.E_b=function(){P.w.call(this);this.Yb=this.gb=null;this.BN=this.Cs="";this.Cvb=!1};var P=c.u(c.E_b,c.Us);P.U=function(){P.j.U.call(this);
this.jo(null)};P.dh=function(){return c.o0b};P.wh=function(){return this.Cs};P.UJb=function(){return this.BN};P.zg=function(b){this.gb!=b&&(this.jo(b),this.l(a.f.h))};P.ib=function(){var a=null;return a=this.gb};P.hc=function(){return this.Yb};P.j7a=function(){return this.Cvb};P.E7b=function(b){this.Cvb!=b&&(this.Cvb=b,this.ea(a.f.h))};P.qc=function(){this.Ga(a.K.Zg)};P.e5a=function(b,c){var d=e.Qb();d.Wb("FILE",b);d.Wb("FILES",c);this.Ga(a.K.bIb,d);d.nc()};P.LK=function(){this.OR=b.nma(this.Yb.Uj());
this.gb.AT(this.hc())};P.jo=function(a){var c=null;a&&(c=a.Ix(),this.gb==a?c.un(this.Yb):a.fz(c));this.gb&&(this.gb.Ca(this),this.Yb.Ca(this),b.la(this.Yb),this.Yb=null);if(this.gb=a)this.gb.Da(this,this.Un),this.Yb=c,this.Yb.Da(this,this.Ev);this.fh()};P.eOd=function(){};P.Un=function(b,c){c.Ya==a.f.h?c.Vr==a.te.Rw?this.gb.fz(this.hc()):this.jo(this.gb):c.Ya==a.f.sb&&this.zg(null)};P.Ev=function(b,c){c.Ya==a.f.h&&c.Vr==a.te.Rw&&this.LK()};e.jb(c.E_b,"PRIM_WEB","FilePicker",{Oa:{MultiSelect:{a:P.j7a,
g:function(a){this.E7b(e.ya(a))}}}});c.Afb=function(a){G.w.call(this);this.MXa=a;this.QW=this.YE=null};var G=c.u(c.Afb,c.wd);G.U=function(){null!=this.YE&&(this.YE=null);null!=this.QW&&(b.oBb(this.QW),this.QW=null);G.j.U.call(this)};G.oh=function(){return this.MXa.name};G.gva=function(){null==this.YE&&(this.YE=new c.wWb(this.MXa));return this.YE};G.R7a=function(){return this.MXa.size};G.hBc=function(){return this.MXa.type};e.jb(c.Afb,"PRIM_WEB","File",{Oa:{Name:{a:G.oh},Blob:{a:G.gva},FileSize:{a:G.R7a},
MimeType:{a:G.hBc}}});c.Bfb=function(){ha.w.call(this);this.ab=[]};var ha=c.u(c.Bfb,c.wd);ha.U=function(){for(var a=0;a<this.ab.length;a++)this.ab[a].xb();this.ab=[];ha.j.U.call(this)};ha.lc=function(){return this.ab.length};ha.Sd=function(a){return this.ab[a-1]};ha.hs=function(a){this.ab.push(a);a.Ba()};e.jb(c.Bfb,"PRIM_WEB","Files",{Oa:{Item:{a:function(a){return this.Sd(e.G(a))},zw:"na"},ItemCount:{a:ha.lc}},ig:{dg:"Item"},gq:{Ap:function(a){return this.Sd(e.G(a))},Lv:ha.lc}});c.A_b=function(){da.w.call(this)};
var da=c.u(c.A_b,c.wd);da.Rib=function(a){var d=this;if(window.FileReader&&a instanceof c.zG){if(a=a.Wja()){var e=b.gR(),f=new FileReader;f.onload=function(a){d.TX(a.target.result);b.ty(e)};f.readAsText(a)}}else d.TX("")};da.TX=function(b){var c=e.Qb();c.UH("DATA",b);this.Ga(a.K.G2,c)};e.jb(c.A_b,"PRIM_WEB","ClobReader",{ic:{Read:da.Rib}});c.y_b=function(){ia.w.call(this)};var ia=c.u(c.y_b,c.wd);ia.Rib=function(a){var d=this;if(window.FileReader&&a instanceof c.zG){if(a=a.Wja()){var e=b.gR(),f=new FileReader;
f.onload=function(a){d.TX(b.LHb(a.target.result));b.ty(e)};f.readAsDataURL(a)}}else d.TX("","")};ia.TX=function(b){var c=e.Qb();c.UH("DATA",b);this.Ga(a.K.G2,c)};e.jb(c.y_b,"PRIM_WEB","BlobReader",{ic:{Read:ia.Rib}});c.B0b=function(a){V.w.call(this,a)};var V=c.u(c.B0b,c.dn);V.Bb=function(a){this.H.textContent=a};V.bz=function(){V.j.bz.call(this);this.H.style.whiteSpace="normal";this.H.style.overflowX="auto";this.H.style.overflowY="auto"};V.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",
a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return V.j.kf.call(this,a,b)};c.F0b=function(a){Q.w.call(this,a)};var Q=c.u(c.F0b,c.dn);Q.Bb=function(a){this.H.textContent=a};Q.Pwa=function(){return!1};Q.Uea=function(){};Q.bz=function(){};Q.kf=function(a,b){this.H=document.createElement("p");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return Q.j.kf.call(this,a,b)};c.C0b=function(a){w.w.call(this,a)};var w=c.u(c.C0b,c.dn);w.Pwa=function(){return!1};w.Uea=function(){};
w.bz=function(){};w.kf=function(a,b){this.H=document.createElement("br");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return w.j.kf.call(this,a,b)};c.D0b=function(a){E.w.call(this,a)};var E=c.u(c.D0b,c.dn);E.Zc=function(a){this.H.src=a};E.Pwa=function(){return!1};E.Rg=function(b,c,d){this.H.style.width=0==c?"auto":c+"px";this.H.style.height=0==d?"auto":d+"px";switch(b){case a.lJ.Hjb:this.H.style.marginLeft="initial";this.H.style.marginRight="initial";this.H.style.display=
"inline";this.H.style.cssFloat="none";break;case a.lJ.D5b:this.H.style.marginLeft="initial";this.H.style.marginRight="initial";this.H.style.display="inline";this.H.style.cssFloat="left";break;case a.lJ.E5b:this.H.style.marginLeft="initial";this.H.style.marginRight="initial";this.H.style.display="inline";this.H.style.cssFloat="right";break;case a.lJ.C5b:this.H.style.marginLeft="auto",this.H.style.marginRight="auto",this.H.style.display="block",this.H.style.cssFloat="none"}};E.Uea=function(){};E.bz=
function(){this.H.style.borderStyle="solid"};E.kf=function(a,b){this.H=document.createElement("img");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return E.j.kf.call(this,a,b)};c.E0b=function(a){ea.w.call(this,a)};var ea=c.u(c.E0b,c.dn);ea.Bb=function(a){this.H.textContent=a};ea.Pwa=function(){return!1};ea.Uea=function(){};ea.bz=function(){};ea.kf=function(a,b){this.H=document.createElement("span");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",
this.fc);return ea.j.kf.call(this,a,b)};c.g0b=function(a){aa.w.call(this,a)};var aa=c.u(c.g0b,c.dn);aa.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return aa.j.kf.call(this,a,b)};c.G0b=function(a){fa.w.call(this,a);this.tH=this.on=null;this.Sec=this.Gxb=!1;this.Sub=null};var fa=c.u(c.G0b,c.dn);fa.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",
this.fc);this.H.style.msTouchAction="none";this.tH=document.createElement("canvas");this.tH.style.touchAction="none";this.H.appendChild(this.tH);this.on=this.tH.getContext("2d");this.lBb();return fa.j.kf.call(this,a,b)};fa.fo=function(a,b,c,d){fa.j.fo.call(this,a,b,c,d);a=this.on.getImageData(0,0,this.tH.width-1,this.tH.height-1);this.tH.width=this.Vc;this.tH.height=this.hd;this.on.putImageData(a,0,0)};fa.pM=function(a){this.U8b(a);return!0};fa.Pgb=function(a){this.T8b(a);return!0};fa.uOa=function(a){this.S8b(a);
return!0};fa.Ppa=function(a){this.U8b(a);return!0};fa.fw=function(a){this.T8b(a);return!0};fa.Oea=function(a){this.S8b(a);return!0};fa.ROb=function(a){this.H.onpointerdown===n&&a.touches!==n?(a.Rrb=a.touches[0].pageX-this.pa.es(),a.Srb=a.touches[0].pageY-this.pa.fs()):(a.Rrb=a.clientX-this.pa.es(),a.Srb=a.clientY-this.pa.fs());this.pa.qc()};fa.lBb=function(){this.B0a(!0);this.Sub=new Image;this.Sub.onload=function(){throw 0;};this.Sub.src=null};fa.B0a=function(a){(this.Sec||a)&&this.on.clearRect(0,
0,this.on.canvas.width,this.on.canvas.height);this.Sec=!1};fa.nwc=function(){var a=this.tH.toDataURL("image/png");return b.LHb(a)};fa.op=function(){this.lBb()};fa.U8b=function(a){a.preventDefault();this.B0a(!1);this.on.beginPath();this.ROb(a);this.on.moveTo(a.Rrb,a.Srb);this.Gxb=!0};fa.S8b=function(a){a.preventDefault();this.Gxb=!1};fa.$Ld=function(a){this.fw(a)};fa.T8b=function(a){this.Gxb&&(a.preventDefault(),this.B0a(!1),this.on.strokeStyle="rgb(0,0,0)",this.on.lineWidth=1,this.ROb(a),this.on.lineTo(a.Rrb,
a.Srb),this.on.stroke())};c.P_b=function(a){na.w.call(this,a);this.$sa=this.eb=null};var na=c.u(c.P_b,c.dn);na.Kl=function(a){this.$sa.src=a};na.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);this.$sa=document.createElement("iframe");this.r2(this.$sa);this.$sa.style.width="100%";this.$sa.style.height="100%";this.H.appendChild(this.$sa);return na.j.kf.call(this,a,b)};na.yX=function(){var a=this;na.j.yX.call(this);
a.H.addEventListener("load",function(){a.pa.Zuc()},!1)};na.r2=function(a){na.j.r2.call(this,a);this.H.style.overflowX="auto";this.H.style.overflowY="auto"};c.o0b=function(a){Y.w.call(this,a);this.UR=null};var Y=c.u(c.o0b,c.Vfb);Y.kf=function(a,b){var c=Y.j.kf.call(this,a,b);this.UR=document.createElement("input");this.UR.type="File";var d=this.UR.style;this.mb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.UR);return c};Y.Kd=function(){Y.j.Kd.call(this);
this.Dbd()};Y.fo=function(a,b,c,d){Y.j.fo.call(this,a,b,c,d);this.UR.style.left="0px";this.UR.style.top="0px";this.UR.style.width=c+"px";this.UR.style.height=d+"px"};Y.yX=function(){var a=this;this.w2();a.UR.addEventListener("change",function(b){a.vlc(b);a.UR.value=""},!1)};Y.Dbd=function(){this.UR.multiple=this.pa.j7a()};Y.vlc=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.Bfb,e=0,f;f=a[e];e++)f=new c.Afb(f),null==b&&(b=f),d.hs(f);b&&this.pa.e5a(b,d)}},{rp:["PRIM_LABL"]});
