window.LANSA.addSrc("wdgt",function(e,c,a,b,n){var q={};c.R0b=function(a){m.w.call(this);this.rEa=a;this.CVa=function(){};this.DW=this.vvb=!1;this.Rvb=[];this.Qvb=[];this.Mvb=[];this.Lvb=[];this.Ovb=[]};var m=c.u(c.R0b,c.we);m.kQ=function(){return this.vvb};m.oh=function(){return this.rEa.nm};m.wCc=function(){return this.rEa.js||[]};m.gDc=function(){return this.rEa.st||[]};m.dyc=function(){return this.rEa.fn};m.Xyc=function(){return this.rEa.fe};m.aY=function(){return this.CVa};m.XSc=function(){function a(){if(k<
m.length){var c=m[k],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;k++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.vvb){for(c.vvb=!0;0<c.Lvb.length;){var b=c.Lvb.shift();c.Y$a(b)}for(;0<c.Qvb.length;)b=c.Qvb.shift(),c.$$a(b.Vrb,b.tfd,b.value);for(;0<c.Ovb.length;)b=c.Ovb.shift(),c.SOb(b.Vrb,
b.parent);for(;0<c.Rvb.length;)b=c.Rvb.shift(),c.aab(b);for(;0<c.Mvb.length;)b=c.Mvb.shift(),c.Z$a(b)}}var d=c.dyc(),f=c.CVa.prototype;e&&e(f);var h={Loading:{},Completed:{},Finalize:function(){a()}};d(f,h)!==h.Loading&&a()}var c=this,d=c.oh(),e=c.Xyc();q[d]=c;for(var f=c.gDc(),h=0;h<f.length;h++){var g=f[h],l=document.createElement("link");l.type="text/css";l.rel="stylesheet";l.href=g;document.body.appendChild(l)}var k=0,m=c.wCc();a()};m.$$a=function(a,b,c){if(this.kQ()){var d=a["set"+b];if(!d)throw e.NTc("set"+
b);d&&d.call(a,c)}else this.Qvb.push({Vrb:a,tfd:b,value:c})};m.Z$a=function(a){this.kQ()?a.iJa():this.Mvb.push(a)};m.Y$a=function(a){if(this.kQ()){var b=a.onCreateInstance;b&&b.call(a)}else this.Lvb.push(a)};m.SOb=function(a,b){if(this.kQ()){var c=a.onRealizeControl;if(!c)throw e.MTc();c.call(a,b)}else this.Ovb.push({Vrb:a,parent:b})};m.aab=function(a){if(this.kQ()){var b=a.onSizeChanged;b&&b.call(a)}else this.Rvb.push(a)};c.xfb=function(){s.w.call(this)};var s=c.u(c.xfb,c.bn);s.Mx=function(){return this.Pa()&&
this.Pa().AFc()?this:null};s[a.$.gy]=function(b){var c=!1;this.Pa()&&(c=b.Mc!==n?b.Mc:a.Z.nJ,c=c==a.Z.nJ||c==a.Z.Xw||c==a.Z.EC?this.Pa().AIb(null):this.Pa().BIb(null));c||s.j.FT.call(this,b)};s[a.$.Sxa]=function(b){var c=!1;this.Pa()&&(c=(b.Mc!==n?b.Mc:a.Z.nJ)==a.Z.nJ?this.Pa().AIb(document.activeElement):this.Pa().BIb(document.activeElement));c||s.j.h3a.call(this,b)};c.L_b=function(){g.w.call(this)};var g=c.u(c.L_b,c.wd);e.kd(c.L_b,"PRIM_WDGT",{});c.N_b=function(){k.w.call(this);var a=this.LJa(),
a=this.WS=q[a],b=this.DH=new (a.aY());b.LANSA_Component=this;b.LANSA_Class=a;a.Y$a(b)};var k=c.u(c.N_b,c.wd);k.X$a=function(a,b){if(this.WS.kQ()){var c=this.DH[a];if(!c)throw e.Q4b(a);return c.apply(this.DH,b)}throw e.bQa();};k.ewa=function(a){if(this.WS.kQ()){var b=this.DH["get"+a];if(!b)throw e.P4b("get"+a);return b.call(this.DH)}throw e.bQa();};k.XAa=function(a,b){this.WS.$$a(this.DH,a,b)};k.k4=function(){l.j.k4.call();var a=this;setTimeout(function(){a.WS.Z$a(a)},5)};k.iJa=function(){this.Ga(a.K.UY)};
e.jb(c.N_b,"PRIM_WDGT","Object",{});var f=k;f.get=f.ewa;f.set=f.XAa;f.invoke=f.X$a;c.M_b=function(){l.w.call(this);var b=this.LJa(),b=this.WS=q[b],c=this.DH=new (b.aY());c.LANSA_Component=this;c.LANSA_Class=b;b.Y$a(c);this.rg&=~a.Ug.pQ;this.rg&=~a.Ug.cZ};var l=c.u(c.M_b,c.xfb);l.dh=function(){return c.Q0b};l.Kd=function(a,c,d){l.j.Kd.call(this,a,c,d);a=this.Pa().hb();b.Qd[a].OMc(this.DH)};l.X$a=function(a,b){if(this.WS.kQ()){var c=this.DH[a];if(!c)throw e.Q4b(a);return c.apply(this.DH,b)}throw e.bQa();
};l.ewa=function(a){if(this.WS.kQ()){var b=this.DH["get"+a];if(!b)throw e.P4b("get"+a);return b.call(this.DH)}throw e.bQa();};l.XAa=function(a,b){this.WS.$$a(this.DH,a,b)};l.tEd=function(){this.iJa()};l[a.$.vba]=function(){this.WS.Z$a(this)};l[a.$.xG]=function(){this.Pb()&&this.WS.aab(this.DH)};l.Jca=function(){l.j.Jca.call(this);this.Pb()&&this.WS.aab(this.DH)};e.jb(c.M_b,"PRIM_WDGT","Control",{});f=l;f.get=f.ewa;f.set=f.XAa;f.invoke=f.X$a;c.G_b=function(){d.w.call(this);this.qd=b.Cd(0,0,100,100);
this.TDa=this.wEa=""};var d=c.u(c.G_b,c.xfb);d.dh=function(){return c.q0b};d.Fzc=function(){return this.wEa};d.H_c=function(b){this.wEa!=b&&(this.wEa=b,this.ea(a.f.h),this.Id())};d.UT=function(){return this.TDa};d.ukb=function(a){this.TDa=a};d.BC=function(a){var d=this.zp(),e=this.mr();if(d||e){var f=new c.ha,h=[];h[0]=d;h[1]=e;h[2]=a;h[3]=0;h[4]=0;var g=this.hb();h[3]=0;h[4]=0;null!=g&&b.Qd[g].Sbd(h);f.Ra(h[3]);f.Ha(h[4]);d&&a.Ra(a.Q()+this.ca.mj()+f.aa()+this.ca.Dk());e&&a.Ha(a.O()+this.ca.Ek()+
f.ba()+this.ca.mm())}};e.jb(c.G_b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:d.Fzc,g:function(a){this.H_c(e.ma(a))}},Description:{a:d.UT,g:function(a){this.ukb(e.ma(a))}}},ig:{dg:"Html"}});c.Mfb=function(a){h.w.call(this,a)};var h=c.u(c.Mfb,c.dn);h.ELa=function(){return!1};h.HLa=function(){return this.pa.ds()||this.pa.wK?!1:!0};h.AFc=function(){return 0<this.g1a().length};h.pM=function(a){h.j.pM.call(this,a);return!1};h.AIb=function(a){var b=this.g1a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};h.BIb=function(a){var b=this.g1a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};h.g1a=function(){var a=[],b=[];this.a3b(this.H,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};h.a3b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===n&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.a3b(a,b)};h.d3=h[a.La.eN]=
function(b){b.Re=a.La.Hia|a.La.EHa};c.Q0b=function(a){z.w.call(this,a);this.eb=null};var z=c.u(c.Q0b,c.Mfb);z.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);return z.j.kf.call(this,a,b)};z.OMc=function(a){null==this.eb&&(this.eb=document.createElement("div"),this.eb.style.left="0px",this.eb.style.top="0px",this.eb.style.width="100%",this.eb.style.height="100%",a.LANSA_Class.SOb(a,this.eb),this.H.appendChild(this.eb))};
c.q0b=function(a){C.w.call(this,a);this.eb=null};var C=c.u(c.q0b,c.Mfb);C.bz=function(){C.j.bz.call(this);this.H.style.whiteSpace="normal"};C.kf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.fc);this.H.setAttribute("LANSAHandle",this.fc);this.eb=document.createElement("div");this.eb.style.left="0px";this.eb.style.top="0px";this.eb.style.width="100%";this.eb.style.height="100%";this.eb.innerHTML=this.pa.wEa;this.H.appendChild(this.eb);return C.j.kf.call(this,a,
b)};C.Fbd=function(){var a=this.pa.zp(),b=this.pa.mr();this.eb.style.width=a?"":"100%";this.eb.style.height=b?"":"100%";this.eb.innerHTML=this.pa.wEa};C.Kd=function(){C.j.Kd.call(this);this.Fbd()};C.Sbd=function(a){var b=a[0],c=a[2],d=this.eb.style.width;a[1]&&!b&&(this.eb.style.width=c.aa()+"px");a[3]=this.eb.clientWidth;a[4]=this.eb.clientHeight;this.eb.style.width=d}});
