window.LANSA.addSrc("imag",function(e,c,a,b){c.Wt=function(){n.w.call(this);this.Cs="";this.Yb=this.gb=this.jv=this.JVa=this.OR=this.ue=this.Xe=null;this.BW=a.he.qSa;this.gB=this.rB=this.nB=this.zB=0;this.Qc|=a.Xb.vMa;this.zEa=new c.bn;this.zEa.Gf(!1);this.zEa.Na(this);this.ue=new c.xQ;this.Xe=new c.pb;this.Xe.xd(this.ue);this.zEa.tda(this.Xe);this.Gf(!1)};var n=c.u(c.Wt,c.bn);n.wb=function(){b.la(this.ue);this.ue=null;b.la(this.Xe);this.Xe=null;n.j.wb.call(this)};n.U=function(){n.j.U.call(this);
this.Yna(null);this.JVa=null;this.vj(null);this.jo(null)};n.wh=function(){return this.Cs};n.$v=function(c){b.uC(this.Cs,c)||(this.Cs=c,this.Yna(b.nma(this.Cs)),this.l(a.f.h))};n.Npd=function(){return this.OR};n.Yna=function(b){this.OR!=b&&(this.vj(null),null!=this.OR&&this.OR.Ca(this,this.XCb),this.OR=b,null!=this.OR&&this.OR.Da(this,this.XCb),this.MJ(),this.ob(),this.l(a.f.h))};n.U5a=function(){return this.jv};n.vj=function(b){this.jv!=b&&(this.Yna(null),null!=this.jv&&(this.jv.Ca(this,this.Pm),
this.jv.xb()),this.jv=b,null!=this.jv&&(this.jv.Ba(),this.jv.Da(this,this.Pm)),this.MJ(),this.ob(),this.Id(),this.l(a.f.h))};n.C3=function(){return this.ue.Jk()};n.j_=function(b){this.ue.Jk()!=b&&(this.ue.qg(b),this.l(a.f.h))};n.mY=function(){return this.ue.Td()};n.i_=function(b){this.ue.Td()!=b&&(this.ue.Ta(b),this.l(a.f.h))};n.oY=function(){return this.ue.se()};n.k_=function(b){this.ue.se()!=b&&(this.ue.Ua(b),this.l(a.f.h))};n.YT=function(){return this.ue.Xa()};n.KM=function(b){this.ue.Xa()!=b&&
(this.ue.ac(b),this.l(a.f.h))};n.Fw=function(){return this.ue.Qa()};n.Vu=function(b){this.ue.Qa()!=b&&(this.ue.xc(b),this.l(a.f.h))};n.rL=function(){return this.BW};n.xJ=function(b){this.BW!=b&&(this.BW=b,this.ue.Vb(b),this.ob(),this.Id(),this.l(a.f.h))};n.nY=function(){return this.ue.kU()};n.TQ=function(b){this.ue.kU()!=b&&(this.ue.i6(b),this.l(a.f.h))};n.pY=function(){return this.ue.Li()};n.l_=function(b){this.ue.Li()!=b&&(this.ue.Ll(b),this.l(a.f.h))};n.gG=function(){return this.ue.fg()};n.JE=
function(b){this.ue.fg()!=b&&(this.ue.Hb(b),this.l(a.f.h))};n.zg=function(b){this.gb!=b&&(this.jo(b),this.l(a.f.h))};n.ib=function(){var a=null;return a=this.gb};n.hc=function(){return this.Yb};n.Ze=function(){return this.zB};n.De=function(c){this.zB!=c&&(this.zB=c,this.ob(),this.Id(),b.cb().Ad(this,!1),this.ea(a.f.h))};n.cf=function(){return this.nB};n.Oe=function(c){this.nB!=c&&(this.nB=c,this.ob(),this.Id(),b.cb().Ad(this,!1),this.ea(a.f.h))};n.Xf=function(){return this.rB};n.xe=function(c){this.rB!=
c&&(this.rB=c,this.ob(),this.Id(),b.cb().Ad(this,!1),this.ea(a.f.h))};n.ng=function(){return this.gB};n.Bf=function(c){this.gB!=c&&(this.gB=c,this.ob(),this.Id(),b.cb().Ad(this,!1),this.ea(a.f.h))};n.Ql=function(a,b,c,e,k){return k};n.LK=function(){var a=this.Yb.Uj();""!=a?this.OR&&this.OR.wh()==a||this.Yna(b.nma(a)):this.Yna(this.Yb.Cka());this.gb.AT(this.hc())};n.jo=function(a){var c=null;a&&(c=a.Ix(),this.gb==a?c.un(this.Yb):a.fz(c));this.gb&&(this.gb.Ca(this),this.Yb.Ca(this),b.la(this.Yb),this.Yb=
null);if(this.gb=a)this.gb.Da(this,this.Un),this.Yb=c,this.Yb.Da(this,this.Ev);this.fh()};n.MJ=function(){null==this.jv?this.ue.Zc(this.OR):this.JVa&&0<this.JVa.wh().length?this.ue.Zc(this.JVa):this.ue.Zc(this.jv)};n.Ue=function(b){var e=new c.ha(0,0,b.aa(),b.ba());n.j.Ue.call(this,b);e.Ua(e.O()+this.zB);e.Ta(e.Q()+this.nB);e.Ra(e.va-this.rB);e.Ha(e.ua-this.gB);this.zEa.Kc(this);this.zEa.kb(e);this.rL()==a.he.qSa&&this.ue.Ec()&&(this.ue.Ec().Qa()>e.ba()||this.ue.Ec().Xa()>e.aa()?this.ue.Vb(a.he.bH):
this.ue.Vb(a.he.Vd))};n.BC=function(b){var e=this.zp(),n=this.mr();if(0!=this.oY()||0!=this.mY()||100!=this.YT()||100!=this.Fw()||this.nY()!=a.zt.Xda||this.pY()!=a.cz.Wea||this.ue.ah()==a.he.wBa)n=e=!1;if(e||n){var g=new c.ha;if(this.ue.Ec())switch(g.Ra(this.ue.Ec().Xa()),g.Ha(this.ue.Ec().Qa()),this.ue.ah()){case a.he.bH:if(n&&!e&&0<b.aa()&&0<g.aa()){var k=b.aa()/g.aa();g.Ha(g.O()+g.ba()*k)}}e&&b.Ra(b.Q()+this.ca.mj()+this.nB+g.aa()+this.rB+this.ca.Dk());n&&b.Ha(b.O()+this.ca.Ek()+this.zB+g.ba()+
this.gB+this.ca.mm())}};n.yf=function(a){b.Feb();return n.j.yf.call(this,a)};n.Pm=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.vj(null);break;case a.f.h:this.ob(),this.Id()}};n.XCb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.Yna(null);break;case a.f.h:this.ob()}};n.Un=function(b,c){c.Ya==a.f.h?c.Vr==a.te.Rw?this.gb.fz(this.hc()):this.jo(this.gb):c.Ya==a.f.sb&&this.zg(null)};n.Ev=function(b,c){c.Ya==a.f.h&&c.Vr==a.te.Rw&&this.LK()};e.kd(c.Wt,"PRIM_IMAG",{Oa:{FileName:{a:n.wh,
g:function(a){this.$v(e.ma(a))}},Image:{a:n.U5a,g:function(a){this.vj(a)}},ImageTile:{a:function(){return e.ta(this.nY(),a.zt.v)},g:function(b){this.TQ(e.qa(b,a.zt.v))}},ImageUnits:{a:function(){return e.ta(this.pY(),a.cz.v)},g:function(b){this.l_(e.qa(b,a.cz.v))}},ImageSizing:{a:function(){return e.ta(this.rL(),a.he.v)},g:function(b){this.xJ(e.qa(b,a.he.v))}},ImageOpacity:{a:n.C3,g:function(a){this.j_(e.G(a))}},ImageLeft:{a:n.mY,g:function(a){this.i_(e.G(a))}},ImageTop:{a:n.oY,g:function(a){this.k_(e.G(a))}},
ImageWidth:{a:n.YT,g:function(a){this.KM(e.G(a))}},ImageHeight:{a:n.Fw,g:function(a){this.Vu(e.G(a))}},ImageAlignment:{a:function(){return e.ta(this.gG(),a.ee.v)},g:function(b){this.JE(e.qa(b,a.ee.v))}},DataClass:{a:n.ib,g:n.zg},MarginLeft:{a:n.cf,g:function(a){this.Oe(e.G(a))}},MarginTop:{a:n.Ze,g:function(a){this.De(e.G(a))}},MarginBottom:{a:n.ng,g:function(a){this.Bf(e.G(a))}},MarginRight:{a:n.Xf,g:function(a){this.xe(e.G(a))}}}})});
