window.LANSA.addSrc("coll",function(d,c,a,b,r){a.gPa={wqc:0,Q8a:1};var u=0;c.$na=function(){k.H.call(this)};var k=c.q(c.$na,c.Hd);k.CCb=function(){return!1};k.eUb=function(){return!1};k.xc=function(){return 0};k.pg=function(){return 0==this.xc()};k.$Y=function(a){a&&(a.Ba(),a.lmc(this))};k.oZ=function(a){a&&(a.Cb(),a.CYc(this))};k.p0=function(a,b){this.iSa(b);null!=this.hU&&this.hU.p0(a,b)};k.J6=function(a,b){this.jSa(b);null!=this.hU&&this.hU.J6(a,b)};d.wd(c.$na,"PRIM_COLL",{Pa:{AllowsDuplicates:{a:function(){return this.CCb()}},
IsEmpty:{a:function(){return this.pg()}},IsOrdered:{a:function(){return this.eUb()}},ItemCount:{a:function(){return this.xc()}}}});c.gQa=function(){t.H.call(this);this.cb=[];this.hU=null};var t=c.q(c.gQa,c.$na);t.R=function(){this.Qk();t.j.R.call(this)};t.CCb=function(){return!0};t.eUb=function(){return!0};t.xc=function(){return this.cb.length};t.be=function(a){if(0>a||a>=this.cb.length)throw d.JF(a,this.cb.length);return this.cb[a]};t.jl=function(a,b){if(0>a||a>this.cb.length)throw d.JF(a,this.cb.length);
a==this.cb.length?this.Os(b):this.Wmb(b,a)};t.O$a=function(a,b){return b===r?this.cb.indexOf(a):this.cb.indexOf(a,b)};t.JOb=function(a){return this.cb.lastIndexOf(a)+1};t.G$a=function(){return 0<this.cb.length?this.cb[0]:null};t.$$a=function(){return 0<this.cb.length?this.cb[this.cb.length-1]:null};t.Std=function(){return this.cha};t.G0=function(a){this.cha=a};t.nJa=function(a){this.G0(a.Q8b())};t.ye=function(a){return-1!=this.cb.indexOf(a)};t.Os=t.aTb=function(a){this.$Y(a);this.cb.push(a);this.p0(a,
this.xc()-1)};t.$Sb=function(a){this.$Y(a);this.cb.unshift(a);this.p0(a,0)};t.ZSb=function(a,b){if(0>b||b>=this.cb.length)throw d.JF(b,this.cb.length);this.$Y(a);this.cb.splice(b+1,0,a);this.p0(a,b+1)};t.udb=function(a,b){if(0>b||b>=this.cb.length)throw d.JF(b,this.cb.length);this.$Y(a);this.cb.splice(b,0,a);this.p0(a,b)};t.St=function(a){a=this.cb.indexOf(a);if(-1==a)throw d.bZc();return this.ds(a)};t.ds=function(a){if(0>a||a>=this.cb.length)throw d.JF(a,this.cb.length);var b=this.cb[a];this.cb.splice(a,
1);d.Xja(b);this.oZ(b);this.J6(b,a);return b};t.Qmb=function(){return this.ds(0)};t.Smb=function(){return this.ds(this.cb.length-1)};t.Qk=function(){for(var a=0;a<this.cb.length;a++)this.oZ(this.cb[a]);this.cb=[];this.lea()};t.alb=function(a){for(var b=0,c=0;c<this.cb.length;c++)this.cb[c]===a&&b++;return b};t.Wmb=function(a,b){if(0>b||b>=this.cb.length)throw d.JF(b,this.cb.length);var c=this.cb[b];d.Xja(c);this.oZ(c);this.cb[b]=a;this.$Y(a);return c};t.Ug=function(){var a=d.l6a(this.cha);if(a=d.$c(a.QRa,
a.xub))this.Poa(a),this.Os(a)};t.Dk=function(){this.Qk()};t.Ph=function(a){if(0<=a&&a<this.xc()){var b=this.be(a);b&&this.Gda(b);this.Vl=a;return"OK"}this.Vl=-1;return"NR"};t.jp=function(){return this.xc()};t.En=function(a){a===r&&(a=this.Vl);0<=a&&a<this.xc()&&this.ds(a)};t.Tl=function(){var a=this.Vl;0<=a&&a<this.xc()&&(a=this.be(a))&&this.Poa(a)};t.qo=function(a,b,c){for(var d=0;d<this.xc();d++){var e=this.be(d);if(e&&(e=e.m_())){var g={},f;for(f in e)g[f]=e[f].get();if(a(g))return null!=b&&b.set(d+
1),c&&this.Ph(d),this.Vl=d,"OK"}}return"NR"};t.fr=function(a){this.Qk();for(var b=0;b<a;b++)this.Ug()};t.Ss=function(){return new c.Whb(this)};t.ICa=function(){null==this.hU&&(this.hU=new c.W_b);return this.hU};c.W_b=function(){p.H.call(this)};var p=c.q(c.W_b,c.Xhb);c.R_b=function(){q.H.call(this);this.Vl=-1};var q=c.q(c.R_b,c.gQa);q.EV=function(){return"PRIM_LCOL<"+this.cha+">"};q.Smc=function(a){for(var b=0;b<a.xc();b++)this.Os(a.be(b))};q.Jqc=function(a){for(var b=d.$c("PRIM_LCOL"),c=0;c<this.xc();c++)b.Os(this.be(c));
for(c=0;c<a.xc();c++)b.Os(a.be(c));d.Xja(b);return b};d.wd(c.R_b,"PRIM_LCOL",{jO:a.sx.w4a,Pa:{First:{a:function(){return this.G$a()}},Last:{a:function(){return this.$$a()}},Item:{a:function(a){return this.be(d.v(a)-1)},f:function(a,b){this.jl(d.v(a)-1,b)}},IndexOf:{a:function(a,b){return this.O$a(a,b===r?r:d.v(b)-1)+1}},LastIndexOf:{a:q.JOb},Collects:{f:q.G0}},pc:{Append:q.Smc,Concatenate:q.Jqc,Contains:q.ye,Insert:q.Os,InsertFirst:q.$Sb,InsertLast:q.aTb,InsertAfter:function(a,b){return this.ZSb(a,
d.v(b)-1)},InsertBefore:function(a,b){return this.udb(a,d.v(b)-1)},Remove:q.St,RemoveAt:function(a){return this.ds(d.v(a)-1)},RemoveFirst:q.Qmb,RemoveLast:q.Smb,RemoveAll:q.Qk,OccurrencesOf:q.alb,ReplaceAt:function(a,b){return this.Wmb(a,d.v(b)-1)}},Cg:{wg:"Item"},Lq:{bda:function(a){var b=d.$c("PRIM_NMBR");b.set(a);return b},iq:function(a){return this.be(d.v(a)-1)},Iw:function(){return this.xc()}},Zy:{Ug:q.Ug,Ph:function(a){return this.Ph(d.v(a)-1)},fr:q.fr,Dk:q.Dk,jp:q.jp,En:function(a){return this.En(a?
d.v(a)-1:r)},Tl:q.Tl,qo:q.qo,Ss:q.Ss}});c.hXb=function(){f.H.call(this)};var f=c.q(c.hXb,c.gQa);f.EV=function(){return"PRIM_ACOL<"+this.cha+">"};d.wd(c.hXb,"PRIM_ACOL",{jO:a.sx.w4a,Pa:{First:{a:function(){return this.G$a()}},Last:{a:function(){return this.$$a()}},Item:{a:function(a){return this.be(d.v(a)-1)},f:function(a,b){this.jl(d.v(a)-1,b)}},IndexOf:{a:function(a,b){return this.O$a(a,b===r?r:d.v(b)-1)+1}},LastIndexOf:{a:f.JOb},Collects:{f:f.G0}},pc:{Contains:f.ye,Insert:f.Os,InsertFirst:f.$Sb,
InsertLast:f.aTb,InsertAfter:function(a,b){return this.ZSb(a,d.v(b)-1)},InsertBefore:function(a,b){return this.udb(a,d.v(b)-1)},Remove:f.St,RemoveAt:function(a){return this.ds(d.v(a)-1)},RemoveFirst:f.Qmb,RemoveLast:f.Smb,RemoveAll:f.Qk,OccurrencesOf:f.alb,ReplaceAt:function(a,b){return this.Wmb(a,d.v(b)-1)}},Cg:{wg:"Item"},Lq:{bda:function(a){var b=d.$c("PRIM_NMBR");b.set(a);return b},iq:function(a){return this.be(d.v(a)-1)},Iw:function(){return this.xc()}},Zy:{Ug:f.Ug,Ph:function(a){return this.Ph(d.v(a)-
1)},fr:f.fr,Dk:f.Dk,jp:f.jp,En:function(a){return this.En(a?d.v(a)-1:r)},Tl:f.Tl,qo:f.qo,Ss:f.Ss}});c.b0b=function(){h.H.call(this)};var h=c.q(c.b0b,c.gQa);h.Os=function(b){this.$Y(b);for(var c=0,d=this.cb.length-1;c<=d;){var e=Math.floor((c+d)/2);this.Pzc(b,this.cb[e])==a.Bc.Ck?d=e-1:c=e+1}this.cb.splice(c,0,b)};h.Pzc=function(b,c){var e=a.Bc.Pj,g=d.Yb();g.bc("SUBJECT",b);g.bc("OBJECT",c);g.AQ("RESULT",e,a.Bc.u);this.Da(a.w.PJa,g);e=g.C$a("RESULT",a.Bc.u);g.zc();return e};d.wd(c.b0b,"PRIM_SACO",
{Pa:{First:{a:function(){return this.G$a()}},Last:{a:function(){return this.$$a()}},Item:{a:function(a){return this.be(d.v(a)-1)},f:function(a,b){this.jl(d.v(a)-1,b)}},IndexOf:{a:function(a,b){return this.O$a(a,b===r?r:d.v(b)-1)+1}},Collects:{f:h.G0}},pc:{Remove:h.St,RemoveAt:function(a){return this.ds(d.v(a)-1)},RemoveAll:h.Qk,RemoveLast:h.Smb,RemoveFirst:h.Qmb,Contains:h.ye,OccurrencesOf:h.alb,Insert:h.Os},Cg:{wg:"Item"},Lq:{bda:function(a){var b=d.$c("PRIM_NMBR");b.set(a);return b},iq:function(a){return this.be(d.v(a)-
1)},Iw:function(){return this.xc()}}});c.U_=function(a){e.H.call(this);this.nkc=a};var e=c.q(c.U_,c.$na);e.be=function(a){if(0>a||a>=this.xc())throw d.JF(a,this.xc());return this.Ax(a)};e.xc=function(){return this.nkc.xc()};e.Ax=function(a){return this.nkc.Ax(a)};d.wd(c.U_,"PRIM_PCOL",{Pa:{Item:{a:function(a){return this.be(d.v(a)-1)},f:function(a,b){this.jl(d.v(a)-1,b)}}},Cg:{wg:"Item"},Lq:{iq:function(a){return this.Ax(d.v(a)-1)},Iw:function(){return this.xc()}}});c.Q_b=function(){m.H.call(this);
this.cb={};this.aU=null;this.mf=a.gPa.Q8a};var m=c.q(c.Q_b,c.$na);m.R=function(){this.Qk();m.j.R.call(this)};m.EV=function(){return"PRIM_KCOL<"+this.UYa+" "+this.XEc()+">"};m.Hg=function(){return this.mf};m.ub=function(a){this.mf=a};m.xc=function(){return this.Sda().length};m.be=function(b){b=this.Q4a(b);if(this.cb[b]===r&&this.mf==a.gPa.Q8a){var c=null;this.kxb?c=new this.kxb:this.UYa&&(c=d.l6a(this.UYa),c=d.$c(c.QRa,c.xub));c&&(this.cb[b]=c,this.$Y(c),this.gI())}return this.cb[b]};m.jl=function(a,
b){a=this.Q4a(a);var c=a.toString();this.cb[c]===r?this.gI():this.oZ(this.cb[c]);this.$Y(b);this.cb[c]=b};m.Ax=function(a){a=this.Sda()[a];return this.cb[a]};m.W$a=function(a){a=this.Sda()[a];this.aU.set(a);return this.aU};m.X$a=function(a){for(var b in this.cb)if(this.cb[b]===a)return this.T4a(b);return this.aU.CGc()};m.G0=function(a,b){"string"!==typeof a?this.kxb=a:(this.UYa=a,this.kxb=b)};m.eUa=function(a){this.aU=new a;this.aU.Ba()};m.Ttd=function(){return this.UYa};m.XEc=function(){var a="";
this.aU&&(a=this.aU.Hxa());return a};m.nJa=function(a){this.G0(a.Q8b(),a.mEb(0));this.eUa(a.mEb(1))};m.Q4a=function(a){this.aU.set(a);a=this.aU.get();return a.toString()};m.T4a=function(a){this.aU.set(a);return this.aU.get()};m.St=function(a){a=this.Q4a(a);var b=null;this.cb[a]!==r&&(b=this.cb[a],d.Xja(b),this.oZ(b),delete this.cb[a],this.gI(),this.J6(b,0));return b};m.Qk=function(){for(var a in this.cb)this.oZ(this.cb[a]);this.cb={};this.gI();this.lea()};m.gI=function(){delete this.BG};m.Sda=function(){var a=
this;if(this.BG===r){this.BG=[];for(var b in this.cb)this.BG.push(b);this.BG.sort(function(b,c){b=a.T4a(b);c=a.T4a(c);return d.cmp(b,c)})}return this.BG};var g={COLLECTION:a.gPa.wqc,FACTORY:a.gPa.Q8a};d.wd(c.Q_b,"PRIM_KCOL",{Pa:{Style:{a:function(){return d.sa(this.Hg(),g)},f:function(a){this.ub(d.qa(a,g))}},Item:{a:function(a){return this.be(a)},f:function(a,b){this.jl(a,b)},tx:"na"},Collects:{f:m.G0},KeyedBy:{f:m.eUa},KeyOf:{a:function(a){return this.X$a(a)},tx:"na"}},pc:{Remove:m.St,RemoveAll:m.Qk},
Cg:{wg:"Item"},Lq:{bda:function(a){return this.W$a(d.v(a)-1)},iq:function(a){return this.Ax(d.v(a)-1)},Iw:function(){return this.xc()}}});c.h_b=function(){A.H.call(this);this.ST=(u++).toString();this.ZI=[];this.cha=this.Vjc=""};var A=c.q(c.h_b,c.$na);A.EV=function(){return"PRIM_DCOL<"+this.cha+" "+this.Vjc+">"};A.xc=function(){return this.ZI.length};A.Ax=function(a){return this.ZI[a].JI[this.ST]};A.be=function(a){return a.JI===r||a.JI[this.ST]===r?null:a.JI[this.ST]};A.jl=function(a,b){a.JI===r&&
(a.JI={});var c=a.JI[this.ST];c===r?(this.ZI.push(a),a.Ba()):this.oZ(c);a.JI[this.ST]=b;this.$Y(b)};A.W$a=function(a){return this.ZI[a]};A.G0=function(a){this.cha=a};A.eUa=function(a){this.Vjc=a};A.X$a=function(a,b){for(var c=b;c<this.ZI.length;c++){var d=this.ZI[c];if(d.JI[this.ST]===a)return d}return null};A.uzc=function(a){return this.be(a)};A.ye=function(a){return-1!=this.ZI.indexOf(a)};A.Oqc=function(a){for(var b=0;b<this.ZI.length;b++)if(this.ZI[b].JI[this.ST]===a)return!0;return!1};A.Os=function(a,
b){var c=this.be(b);this.jl(b,a);return c};A.St=function(a){if(a.JI!==r){var b=a.JI[this.ST];if(b!==r)return delete a.JI[this.ST],this.ZI.splice(this.ZI.indexOf(a),1),d.Xja(b),this.oZ(b),a.Cb(),this.J6(b,0),b}return null};A.Qk=function(){for(var a=0;a<this.ZI.length;a++){var b=this.ZI[a],c=b.JI[this.ST];c!==r&&(delete b.JI[this.ST],this.oZ(c))}this.ZI=[];this.lea()};d.wd(c.h_b,"PRIM_DCOL",{Pa:{Item:{a:function(a){return this.be(a)},f:function(a,b){this.jl(a,b)},tx:"na"},Collects:{f:A.G0,tx:"na"},
KeyedBy:{f:A.eUa,tx:"na"},KeyOf:{a:function(a,b){return this.X$a(a,b!==r?d.v(b)-1:0)},tx:"na"}},pc:{Contains:A.ye,ContainsItem:A.Oqc,Insert:A.Os,Remove:A.St,RemoveAll:A.Qk,Find:A.uzc},Cg:{wg:"Item"},Lq:{bda:function(a){return this.W$a(d.v(a)-1)},iq:function(a){return this.Ax(d.v(a)-1)},Iw:function(){return this.xc()}}})});
