window.LANSA.addSrc("gpbx",function(d,c,a,b){a.Byc={FVd:0,EVd:9,ejd:6,GVd:5,HVd:10};a.zJc={HAc:0};c.k1b=function(){r.H.call(this);this.hyb=a.Byc.ejd;this.VI=a.zJc.HAc;this.pM=new c.ea;new c.ea;this.Vc=this.Vc|a.cc.cda|a.cc.$za|a.cc.wfb|a.cc.vF|a.cc.wW|a.cc.uF;this.Jg=this.Jg|a.ph.gS|a.ph.H_;this.Je(!1)};var r=c.q(c.k1b,c.uK);r.hh=function(){return c.F4b};r.KPd=function(b){this.hyb!=b&&(this.hyb=b,this.k(a.g.h),this.Hw())};r.Owd=function(){return this.hyb};r.jr=function(a){r.j.jr.call(this,a);this.cVc()};
r.Bub=function(){if(this.Vb()){var a=this.re(),a=Math.abs(a.Ia()),d=this.Te();this.Md();this.Md();d.Va(d.O()+a);new c.ea;""==this.eb()?(d.Ra(d.O()),d.Ha(a)):(this.eb(),d.Ra(d.O()+this.zR()),d.Ha(this.nla()),d.Ra(d.va+a));b.Mn(this.pM,d)||(this.pM=d,this.nb());this.jr(!0)}};r.ef=function(a){a.Ta(a.M()+this.pM.aa());a.Va(a.O()+4);a.Ra(a.va-4);a.Ha(a.ua-4);r.j.ef.call(this,a)};r.VXc=function(a,b,c){a.Ta(a.M()+this.pM.aa());a.Va(a.O()+4);a.Ra(a.va-4);a.Ha(a.ua-4);r.j.VXc.call(this,a,b,c)};r.Aj=function(){r.j.Aj.call(this);
this.Gd(a.Z.LB)};r.bd=function(){var b=this.DN()||this.Ol()&&(this.G_()||this.eS());this.nJ(a.cc.HN,b);r.j.bd.call(this)};r.HF=function(a){var b=!1,b=a.Dd().GSa(this,this.ba.Kh,this.G_(),this.eS(),a);!1==b&&r.j.HF.call(this,a)};r.OW=function(a){var b=!1;null!=a.Dd()&&a.fa().Ol()&&(b=a.Dd().HSa(this,this.ba.Kh,a,this.G_(),this.eS()));!1==b&&r.j.OW.call(this,a)};r.ve=function(b){""==b[1]&&(b[1]=a.mWb);r.j.ve.call(this,b)};r.cVc=function(){var a=this.Te(),a=this.TC(a,null),c=this.Te();c.Ta(c.M()+this.pM.aa()/
2+1);c.Va(c.O()+2);c.Ra(c.va-2);c.Ha(c.ua-2);var d=this.Sa().fb(),q=this.eb();b.Yd[d].mh(q,c,this.pM);b.ka(a)};r.Gt=r[a.Z.OH]=function(a){this.Bub();r.j.Gt.call(this,a)};r.vv=r[a.Z.NH]=function(){r.j.vv.call(this);this.Bub()};r.OM=r[a.Z.LB]=function(){this.Bub();this.Hw()};r.kwc=r[a.Z.agb]=function(){this.Ch()};d.wd(c.k1b,"PRIM_GPBX",{Pa:{Caption:{a:r.eb,f:function(a){this.sb(d.ja(a))}},ThemeStyle:{a:function(){return d.sa(this.vN(),a.$v.u)},f:function(b){this.HDa(d.qa(b,a.$v.u))}}}});c.F4b=function(a){u.H.call(this,
a);this.pb=this.fYa=this.DFa=this.oe=this.Qc=null};var u=c.q(c.F4b,c.$_);u.af=function(a,b){var c=null;u.j.af.call(this,a,b);this.fYa=4;this.Qc=document.createElement("div");this.oe=document.createElement("div");this.DFa=document.createElement("div");this.pb=document.createElement("span");this.G.appendChild(this.Qc);this.G.appendChild(this.oe);this.G.appendChild(this.DFa);this.G.appendChild(this.pb);this.pdb(this.Qc,this.fYa);this.pdb(this.oe,0);this.pdb(this.DFa,0);c=this.Qc.style;c.borderTopWidth=
"0px";c=this.oe.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.DFa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.pb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};u.pdb=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};u.mh=function(a,b,c){var d=this.Qc.style;d.left=b.O()+"px";d.top=b.M()+"px";d.width=b.$()+"px";d.height=b.aa()+"px";d.borderColor=this.km();d=this.oe.style;d.left=b.O()+this.fYa-1+"px";d.top=b.M()+"px";d.width=c.O()-b.O()+"px";d.height="1px";d.borderColor=this.km();d=this.DFa.style;d.left=c.va+2+"px";d.top=b.M()+"px";d.width=b.va-this.fYa-c.va+"px";d.height="1px";d.borderColor=this.km();d=this.pb.style;d.left=c.O()+7+"px";d.top=c.M()+2+"px";d.height=
c.aa()+"px";d.width=c.$()+"px";this.pb.textContent=a}});
