window.LANSA.addSrc("coll",function(e,c,a,b,n){a.ULa={fmc:0,H4a:1};var q=0;c.ola=function(){m.w.call(this)};var m=c.u(c.ola,c.jd);m.nyb=function(){return!1};m.PPb=function(){return!1};m.lc=function(){return 0};m.Wf=function(){return 0==this.lc()};m.WW=function(a){a&&(a.Ba(),a.bic(this))};m.nX=function(a){a&&(a.wb(),a.BTc(this))};m.nZ=function(a,b){this.TOa(b);null!=this.VR&&this.VR.nZ(a,b)};m.U4=function(a,b){this.UOa(b);null!=this.VR&&this.VR.U4(a,b)};e.ad(c.ola,"PRIM_COLL",{Oa:{AllowsDuplicates:{a:function(){return this.nyb()}},
IsEmpty:{a:function(){return this.Wf()}},IsOrdered:{a:function(){return this.PPb()}},ItemCount:{a:function(){return this.lc()}}}});c.SMa=function(){t.w.call(this);this.Za=[];this.VR=null};var t=c.u(c.SMa,c.ola);t.R=function(){this.Fj();t.j.R.call(this)};t.nyb=function(){return!0};t.PPb=function(){return!0};t.lc=function(){return this.Za.length};t.Od=function(a){if(0>a||a>=this.Za.length)throw e.iE(a,this.Za.length);return this.Za[a]};t.Ek=function(a,b){if(0>a||a>this.Za.length)throw e.iE(a,this.Za.length);
a==this.Za.length?this.Dr(b):this.Yib(b,a)};t.N6a=function(a,b){return b===n?this.Za.indexOf(a):this.Za.indexOf(a,b)};t.uKb=function(a){return this.Za.lastIndexOf(a)+1};t.D6a=function(){return 0<this.Za.length?this.Za[0]:null};t.Z6a=function(){return 0<this.Za.length?this.Za[this.Za.length-1]:null};t.fpd=function(){return this.Wea};t.DZ=function(a){this.Wea=a};t.kGa=function(a){this.DZ(a.y4b())};t.ae=function(a){return-1!=this.Za.indexOf(a)};t.Dr=t.NOb=function(a){this.WW(a);this.Za.push(a);this.nZ(a,
this.lc()-1)};t.MOb=function(a){this.WW(a);this.Za.unshift(a);this.nZ(a,0)};t.LOb=function(a,b){if(0>b||b>=this.Za.length)throw e.iE(b,this.Za.length);this.WW(a);this.Za.splice(b+1,0,a);this.nZ(a,b+1)};t.G$a=function(a,b){if(0>b||b>=this.Za.length)throw e.iE(b,this.Za.length);this.WW(a);this.Za.splice(b,0,a);this.nZ(a,b)};t.As=function(a){a=this.Za.indexOf(a);if(-1==a)throw e.bUc();return this.Nq(a)};t.Nq=function(a){if(0>a||a>=this.Za.length)throw e.iE(a,this.Za.length);var b=this.Za[a];this.Za.splice(a,
1);e.Kha(b);this.nX(b);this.U4(b,a);return b};t.Sib=function(){return this.Nq(0)};t.Uib=function(){return this.Nq(this.Za.length-1)};t.Fj=function(){for(var a=0;a<this.Za.length;a++)this.nX(this.Za[a]);this.Za=[];this.bca()};t.hhb=function(a){for(var b=0,c=0;c<this.Za.length;c++)this.Za[c]===a&&b++;return b};t.Yib=function(a,b){if(0>b||b>=this.Za.length)throw e.iE(b,this.Za.length);var c=this.Za[b];e.Kha(c);this.nX(c);this.Za[b]=a;this.WW(a);return c};t.tg=function(){var a=e.h2a(this.Wea);if(a=e.gd(a.DOa,
a.qqb))this.$la(a),this.Dr(a)};t.Bj=function(){this.Fj()};t.Fh=function(a){if(0<=a&&a<this.lc()){var b=this.Od(a);b&&this.yba(b);this.Jk=a;return"OK"}this.Jk=-1;return"NR"};t.Cn=function(){return this.lc()};t.dm=function(a){a===n&&(a=this.Jk);0<=a&&a<this.lc()&&this.Nq(a)};t.Hk=function(){var a=this.Jk;0<=a&&a<this.lc()&&(a=this.Od(a))&&this.$la(a)};t.Lm=function(a,b,c){for(var d=0;d<this.lc();d++){var e=this.Od(d);if(e&&(e=e.hY())){var g={},f;for(f in e)g[f]=e[f].get();if(a(g))return null!=b&&b.set(d+
1),c&&this.Fh(d),this.Jk=d,"OK"}}return"NR"};t.Sp=function(a){this.Fj();for(var b=0;b<a;b++)this.tg()};t.Hr=function(){return new c.beb(this)};t.Oza=function(){null==this.VR&&(this.VR=new c.GWb);return this.VR};c.GWb=function(){f.w.call(this)};var f=c.u(c.GWb,c.ceb);c.BWb=function(){h.w.call(this);this.Jk=-1};var h=c.u(c.BWb,c.SMa);h.tT=function(){return"PRIM_LCOL<"+this.Wea+">"};h.Hic=function(a){for(var b=0;b<a.lc();b++)this.Dr(a.Od(b))};h.smc=function(a){for(var b=e.gd("PRIM_LCOL"),c=0;c<this.lc();c++)b.Dr(this.Od(c));
for(c=0;c<a.lc();c++)b.Dr(a.Od(c));e.Kha(b);return b};e.ad(c.BWb,"PRIM_LCOL",{hM:a.nw.r0a,Oa:{First:{a:function(){return this.D6a()}},Last:{a:function(){return this.Z6a()}},Item:{a:function(a){return this.Od(e.L(a)-1)},g:function(a,b){this.Ek(e.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.N6a(a,b===n?n:e.L(b)-1)+1}},LastIndexOf:{a:h.uKb},Collects:{g:h.DZ}},jc:{Append:h.Hic,Concatenate:h.smc,Contains:h.ae,Insert:h.Dr,InsertFirst:h.MOb,InsertLast:h.NOb,InsertAfter:function(a,b){return this.LOb(a,
e.L(b)-1)},InsertBefore:function(a,b){return this.G$a(a,e.L(b)-1)},Remove:h.As,RemoveAt:function(a){return this.Nq(e.L(a)-1)},RemoveFirst:h.Sib,RemoveLast:h.Uib,RemoveAll:h.Fj,OccurrencesOf:h.hhb,ReplaceAt:function(a,b){return this.Yib(a,e.L(b)-1)}},Xf:{Sf:"Item"},wp:{Waa:function(a){var b=e.gd("PRIM_NMBR");b.set(a);return b},Fo:function(a){return this.Od(e.L(a)-1)},zv:function(){return this.lc()}},Wx:{tg:h.tg,Fh:function(a){return this.Fh(e.L(a)-1)},Sp:h.Sp,Bj:h.Bj,Cn:h.Cn,dm:function(a){return this.dm(a?
e.L(a)-1:n)},Hk:h.Hk,Lm:h.Lm,Hr:h.Hr}});c.VSb=function(){k.w.call(this)};var k=c.u(c.VSb,c.SMa);k.tT=function(){return"PRIM_ACOL<"+this.Wea+">"};e.ad(c.VSb,"PRIM_ACOL",{hM:a.nw.r0a,Oa:{First:{a:function(){return this.D6a()}},Last:{a:function(){return this.Z6a()}},Item:{a:function(a){return this.Od(e.L(a)-1)},g:function(a,b){this.Ek(e.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.N6a(a,b===n?n:e.L(b)-1)+1}},LastIndexOf:{a:k.uKb},Collects:{g:k.DZ}},jc:{Contains:k.ae,Insert:k.Dr,InsertFirst:k.MOb,
InsertLast:k.NOb,InsertAfter:function(a,b){return this.LOb(a,e.L(b)-1)},InsertBefore:function(a,b){return this.G$a(a,e.L(b)-1)},Remove:k.As,RemoveAt:function(a){return this.Nq(e.L(a)-1)},RemoveFirst:k.Sib,RemoveLast:k.Uib,RemoveAll:k.Fj,OccurrencesOf:k.hhb,ReplaceAt:function(a,b){return this.Yib(a,e.L(b)-1)}},Xf:{Sf:"Item"},wp:{Waa:function(a){var b=e.gd("PRIM_NMBR");b.set(a);return b},Fo:function(a){return this.Od(e.L(a)-1)},zv:function(){return this.lc()}},Wx:{tg:k.tg,Fh:function(a){return this.Fh(e.L(a)-
1)},Sp:k.Sp,Bj:k.Bj,Cn:k.Cn,dm:function(a){return this.dm(a?e.L(a)-1:n)},Hk:k.Hk,Lm:k.Lm,Hr:k.Hr}});c.NWb=function(){p.w.call(this)};var p=c.u(c.NWb,c.SMa);p.Dr=function(b){this.WW(b);for(var c=0,d=this.Za.length-1;c<=d;){var e=Math.floor((c+d)/2);this.ivc(b,this.Za[e])==a.Oc.tk?d=e-1:c=e+1}this.Za.splice(c,0,b)};p.ivc=function(b,c){var d=a.Oc.ck,g=e.Rb();g.Wb("SUBJECT",b);g.Wb("OBJECT",c);g.qO("RESULT",d,a.Oc.v);this.Ha(a.K.MGa,g);d=g.z6a("RESULT",a.Oc.v);g.nc();return d};e.ad(c.NWb,"PRIM_SACO",
{Oa:{First:{a:function(){return this.D6a()}},Last:{a:function(){return this.Z6a()}},Item:{a:function(a){return this.Od(e.L(a)-1)},g:function(a,b){this.Ek(e.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.N6a(a,b===n?n:e.L(b)-1)+1}},Collects:{g:p.DZ}},jc:{Remove:p.As,RemoveAt:function(a){return this.Nq(e.L(a)-1)},RemoveAll:p.Fj,RemoveLast:p.Uib,RemoveFirst:p.Sib,Contains:p.ae,OccurrencesOf:p.hhb,Insert:p.Dr},Xf:{Sf:"Item"},wp:{Waa:function(a){var b=e.gd("PRIM_NMBR");b.set(a);return b},Fo:function(a){return this.Od(e.L(a)-
1)},zv:function(){return this.lc()}}});c.TY=function(a){d.w.call(this);this.Yfc=a};var d=c.u(c.TY,c.ola);d.Od=function(a){if(0>a||a>=this.lc())throw e.iE(a,this.lc());return this.ww(a)};d.lc=function(){return this.Yfc.lc()};d.ww=function(a){return this.Yfc.ww(a)};e.ad(c.TY,"PRIM_PCOL",{Oa:{Item:{a:function(a){return this.Od(e.L(a)-1)},g:function(a,b){this.Ek(e.L(a)-1,b)}}},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.ww(e.L(a)-1)},zv:function(){return this.lc()}}});c.AWb=function(){g.w.call(this);
this.Za={};this.PR=null;this.Qe=a.ULa.H4a};var g=c.u(c.AWb,c.ola);g.R=function(){this.Fj();g.j.R.call(this)};g.tT=function(){return"PRIM_KCOL<"+this.cVa+" "+this.nAc()+">"};g.dg=function(){return this.Qe};g.sb=function(a){this.Qe=a};g.lc=function(){return this.Kba().length};g.Od=function(b){b=this.N0a(b);if(this.Za[b]===n&&this.Qe==a.ULa.H4a){var c=null;this.ctb?c=new this.ctb:this.cVa&&(c=e.h2a(this.cVa),c=e.gd(c.DOa,c.qqb));c&&(this.Za[b]=c,this.WW(c),this.AG())}return this.Za[b]};g.Ek=function(a,
b){a=this.N0a(a);var c=a.toString();this.Za[c]===n?this.AG():this.nX(this.Za[c]);this.WW(b);this.Za[c]=b};g.ww=function(a){a=this.Kba()[a];return this.Za[a]};g.V6a=function(a){a=this.Kba()[a];this.PR.set(a);return this.PR};g.W6a=function(a){for(var b in this.Za)if(this.Za[b]===a)return this.Q0a(b);return this.PR.KBc()};g.DZ=function(a,b){"string"!==typeof a?this.ctb=a:(this.cVa=a,this.ctb=b)};g.NQa=function(a){this.PR=new a;this.PR.Ba()};g.gpd=function(){return this.cVa};g.nAc=function(){var a="";
this.PR&&(a=this.PR.Qua());return a};g.kGa=function(a){this.DZ(a.y4b(),a.$zb(0));this.NQa(a.$zb(1))};g.N0a=function(a){this.PR.set(a);a=this.PR.get();return a.toString()};g.Q0a=function(a){this.PR.set(a);return this.PR.get()};g.As=function(a){a=this.N0a(a);var b=null;this.Za[a]!==n&&(b=this.Za[a],e.Kha(b),this.nX(b),delete this.Za[a],this.AG(),this.U4(b,0));return b};g.Fj=function(){for(var a in this.Za)this.nX(this.Za[a]);this.Za={};this.AG();this.bca()};g.AG=function(){delete this.bF};g.Kba=function(){var a=
this;if(this.bF===n){this.bF=[];for(var b in this.Za)this.bF.push(b);this.bF.sort(function(b,c){b=a.Q0a(b);c=a.Q0a(c);return e.cmp(b,c)})}return this.bF};var C={COLLECTION:a.ULa.fmc,FACTORY:a.ULa.H4a};e.ad(c.AWb,"PRIM_KCOL",{Oa:{Style:{a:function(){return e.ta(this.dg(),C)},g:function(a){this.sb(e.qa(a,C))}},Item:{a:function(a){return this.Od(a)},g:function(a,b){this.Ek(a,b)},ow:"na"},Collects:{g:g.DZ},KeyedBy:{g:g.NQa},KeyOf:{a:function(a){return this.W6a(a)},ow:"na"}},jc:{Remove:g.As,RemoveAll:g.Fj},
Xf:{Sf:"Item"},wp:{Waa:function(a){return this.V6a(e.L(a)-1)},Fo:function(a){return this.ww(e.L(a)-1)},zv:function(){return this.lc()}}});c.SVb=function(){A.w.call(this);this.JR=(q++).toString();this.oH=[];this.Wea=this.Hfc=""};var A=c.u(c.SVb,c.ola);A.tT=function(){return"PRIM_DCOL<"+this.Wea+" "+this.Hfc+">"};A.lc=function(){return this.oH.length};A.ww=function(a){return this.oH[a].XG[this.JR]};A.Od=function(a){return a.XG===n||a.XG[this.JR]===n?null:a.XG[this.JR]};A.Ek=function(a,b){a.XG===n&&
(a.XG={});var c=a.XG[this.JR];c===n?(this.oH.push(a),a.Ba()):this.nX(c);a.XG[this.JR]=b;this.WW(b)};A.V6a=function(a){return this.oH[a]};A.DZ=function(a){this.Wea=a};A.NQa=function(a){this.Hfc=a};A.W6a=function(a,b){for(var c=b;c<this.oH.length;c++){var d=this.oH[c];if(d.XG[this.JR]===a)return d}return null};A.Ruc=function(a){return this.Od(a)};A.ae=function(a){return-1!=this.oH.indexOf(a)};A.xmc=function(a){for(var b=0;b<this.oH.length;b++)if(this.oH[b].XG[this.JR]===a)return!0;return!1};A.Dr=function(a,
b){var c=this.Od(b);this.Ek(b,a);return c};A.As=function(a){if(a.XG!==n){var b=a.XG[this.JR];if(b!==n)return delete a.XG[this.JR],this.oH.splice(this.oH.indexOf(a),1),e.Kha(b),this.nX(b),a.wb(),this.U4(b,0),b}return null};A.Fj=function(){for(var a=0;a<this.oH.length;a++){var b=this.oH[a],c=b.XG[this.JR];c!==n&&(delete b.XG[this.JR],this.nX(c))}this.oH=[];this.bca()};e.ad(c.SVb,"PRIM_DCOL",{Oa:{Item:{a:function(a){return this.Od(a)},g:function(a,b){this.Ek(a,b)},ow:"na"},Collects:{g:A.DZ,ow:"na"},
KeyedBy:{g:A.NQa,ow:"na"},KeyOf:{a:function(a,b){return this.W6a(a,b!==n?e.L(b)-1:0)},ow:"na"}},jc:{Contains:A.ae,ContainsItem:A.xmc,Insert:A.Dr,Remove:A.As,RemoveAll:A.Fj,Find:A.Ruc},Xf:{Sf:"Item"},wp:{Waa:function(a){return this.V6a(e.L(a)-1)},Fo:function(a){return this.ww(e.L(a)-1)},zv:function(){return this.lc()}}})});
