window.LANSA.addSrc("web",function(e,c,a,b,n){e.Hb("PRIM_LABL");var q=null,m=null;a.ZI={Bjb:0,L5b:1,M5b:2,K5b:3};a.ZI.v={INLINE:a.ZI.Bjb,LEFT:a.ZI.L5b,RIGHT:a.ZI.M5b,CENTER:a.ZI.K5b};a.WD={sIa:0,KGb:1,OGb:2,PGb:3,RGb:4,f4a:5};a.WD.v={NONE:a.WD.sIa,NOTLOADED:a.WD.KGb,PERMISSIONDENIED:a.WD.OGb,POSITIONUNAVAILABLE:a.WD.PGb,TIMEOUT:a.WD.RGb,UNKNOWNERROR:a.WD.f4a};a.PS={Bzb:0,zzb:1,Czb:2,Azb:4};a.PS.v={NONE:a.PS.Bzb,ERROR:a.PS.zzb,WARNING:a.PS.Czb,INFORMATION:a.PS.Azb};c.yfb=function(){t.w.call(this);
this.Za=[]};var t=c.u(c.yfb,c.jd);t.R=function(){t.j.R.call(this)};t.lc=function(){return this.Za.length};t.Od=function(a){return this.Za[a-1]};t.$H=function(a){for(var c=null,d=0;d<this.Za.length;d++){var e=this.Za[d];if(b.nz(e.Yl,a)){c=e;break}}return c};e.ib(c.yfb,"PRIM_WEB","URLParameters",{Oa:{Item:{a:function(a){return this.$H(e.na(a))},ow:"na"},ItemCount:{a:t.lc}},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.Od(e.L(a))},zv:t.lc}});c.xfb=function(){f.w.call(this);this.ab=this.Yl=""};var f=
c.u(c.xfb,c.jd);f.Pg=function(){return this.Yl.toUpperCase()};f.Ja=function(){return this.ab};e.ib(c.xfb,"PRIM_WEB","URLParameter",{Oa:{Name:{a:f.Pg},Value:{a:f.Ja}}});c.vfb=function(){h.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(q=localStorage)}catch(c){}this.nq=null};var h=c.u(c.vfb,c.jd);h.R=function(){h.j.R.call(this)};h.C5a=function(){return null!=q};h.lc=function(){return this.tP().length};h.Od=function(a){return this.tP()[a-
1]};h.$H=function(a){for(var b=null,c=this.tP(),d=0;d<c.length;d++){var e=c[d];if(e.Yl==a){b=e;break}}return b};h.tP=function(){if(null==this.nq&&(this.nq=[],q))for(var a=0;a<q.length;a++){var b=q.key(a);""!=b&&q[b]!=n&&this.nq.push(new c.JNa(b))}return this.nq};h.Hza=function(){this.nq=null};h.Ng=function(a,b){var d=this.tP(),e=this.$H(a);null==e&&(e=new c.JNa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};h.As=function(c){var d=this.tP(),e=this.$H(c);null!=e&&(q.removeItem(c),d.splice(d.indexOf(e),
1),b.Jo().Y9(a.zE.Rna))};h.zn=function(){q&&(q.clear(),this.Hza(),b.Jo().Y9(a.zE.Rna))};e.ib(c.vfb,"PRIM_WEB","LocalStorage",{Oa:{Available:{a:h.C5a},Item:{a:function(a){return this.$H(e.na(a))},ow:"na"},ItemCount:{a:h.lc}},jc:{Add:h.Ng,Remove:h.As,Clear:h.zn},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.Od(e.L(a))},zv:h.lc}});c.JNa=function(a){k.w.call(this);this.Yl=a};var k=c.u(c.JNa,c.jd);k.Pg=function(){return this.Yl};k.Ja=function(){var a="";q&&(a=q[this.Yl],a===n&&(a=""));return a};k.Wa=function(c){var d=
!0;try{q[this.Yl]=c,b.Jo().Y9(a.zE.Rna)}catch(e){b.Jo().vIb(a.zE.Rna),d=!1}return d};e.ib(c.JNa,"PRIM_WEB","LocalStorageItem",{Oa:{Name:{a:k.Pg},Value:{a:k.Ja,g:function(a){this.Wa(e.na(a))}}},Xf:{Sf:"Value"}});c.wfb=function(){p.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(m=sessionStorage)}catch(c){}this.nq=null};var p=c.u(c.wfb,c.jd);p.R=function(){p.j.R.call(this)};p.C5a=function(){return null!=m};p.lc=
function(){return this.tP().length};p.Od=function(a){return this.tP()[a-1]};p.$H=function(a){for(var b=null,c=this.tP(),d=0;d<c.length;d++){var e=c[d];if(e.Yl==a){b=e;break}}return b};p.tP=function(){if(null==this.nq&&(this.nq=[],m))for(var a=0;a<m.length;a++){var b=m.key(a);""!=b&&m[b]!=n&&this.nq.push(new c.KNa(b))}return this.nq};p.Hza=function(){this.nq=null};p.Ng=function(a,b){var d=this.tP(),e=this.$H(a);null==e&&(e=new c.KNa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};p.As=function(c){var d=
this.tP(),e=this.$H(c);null!=e&&(m.removeItem(c),d.splice(d.indexOf(e),1),b.Jo().Y9(a.zE.Sna))};p.zn=function(){m&&(m.clear(),this.Hza(),b.Jo().Y9(a.zE.Sna))};e.ib(c.wfb,"PRIM_WEB","SessionStorage",{Oa:{Available:{a:p.C5a},Item:{a:function(a){return this.$H(e.na(a))},ow:"na"},ItemCount:{a:p.lc}},jc:{Add:p.Ng,Remove:p.As,Clear:p.zn},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.Od(e.L(a))},zv:p.lc}});c.KNa=function(a){d.w.call(this);this.Yl=a};var d=c.u(c.KNa,c.jd);d.Pg=function(){return this.Yl};
d.Ja=function(){var a="";m&&(a=m[this.Yl],a===n&&(a=""));return a};d.Wa=function(c){var d=!0;try{m[this.Yl]=c,b.Jo().Y9(a.zE.Sna)}catch(e){b.Jo().vIb(a.zE.Sna),d=!1}return d};e.ib(c.KNa,"PRIM_WEB","SessionStorageItem",{Oa:{Name:{a:d.Pg},Value:{a:d.Ja,g:function(a){this.Wa(e.na(a))}}},Xf:{Sf:"Value"}});c.ufb=function(){g.w.call(this)};var g=c.u(c.ufb,c.jd);g.R=function(){g.j.R.call(this)};g.zEc=function(a){0<a&&window.history.go(0-a)};g.AEc=function(a){0<a&&window.history.go(a)};g.Ng=function(a,c){var d=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.Jo().ljb();c&&b.Jo().MIa()};g.UTc=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.Jo().ljb();c&&b.Jo().MIa()};e.ib(c.ufb,"PRIM_WEB","History",{jc:{Add:function(a,b){this.Ng(e.na(a),b===n?!0:e.ya(b))},Replace:function(a,b){this.UTc(e.na(a),b===n?!0:e.ya(b))},
GoBack:function(a){this.zEc(a===n?1:e.L(a))},GoForward:function(a){this.AEc(a===n?1:e.L(a))}}});c.G_b=function(){C.w.call(this);this.qd=b.Cd(0,0,400,400);this.xDa=this.Pe="";this.pg&=~a.$g.XP;this.pg&=~a.$g.EY};var C=c.u(c.G_b,c.mm);C.Sg=function(){return c.Y_b};C.fI=function(){return this.Pe};C.yl=function(b){this.Pe!=b&&(this.Pe=b,this.ea(a.f.i))};C.vT=function(){return this.xDa};C.qkb=function(a){this.xDa=a};C.Hd=function(a,c,d){C.j.Hd.call(this,a,c,d);a=this.Pa().gb();b.Jd[a].yl(this.Pe)};C.rvc=
function(){this.Ha(a.K.RSb)};e.ib(c.G_b,"PRIM_WEB","Page",{Oa:{Source:{a:C.fI,g:function(a){this.yl(e.na(a))}},Description:{a:C.vT,g:function(a){this.qkb(e.na(a))}}}});c.Ula=function(){A.w.call(this)};var A=c.u(c.Ula,c.mm);A.E7a=function(){for(var a=null,b=this;b;){if(b instanceof c.zfb){a=b;break}b=b.Ib}return a};A.hca=function(){A.j.hca.call(this);var a=this.E7a();a&&a.uX(this)};A.oZ=function(){A.j.oZ.call(this);var a=this.E7a();a&&a.vX(this)};A.jf=function(a){A.j.jf.call(this,a);var b=this.E7a();
b==this&&b.jA(a,!1)};e.ib(c.Ula,"PRIM_WEB","RichTextItem",{});c.Dfb=function(){s.w.call(this)};var s=c.u(c.Dfb,c.Ula);s.Sg=function(){return c.N0b};e.ib(c.Dfb,"PRIM_WEB","RichTextLine",{});c.Afb=function(){w.w.call(this)};var w=c.u(c.Afb,c.Ula);w.Sg=function(){return c.L0b};e.ib(c.Afb,"PRIM_WEB","RichTextBreak",{});c.Bfb=function(){J.w.call(this);this.wW=null;this.cFa=a.ZI.Bjb;this.vYa=this.wYa=0};var J=c.u(c.Bfb,c.Ula);J.R=function(){J.j.R.call(this);this.kRa(null)};J.Sg=function(){return c.M0b};
J.CCc=function(){return this.wW};J.kRa=function(b){this.wW!=b&&(null!=this.wW&&(this.wW.Aa(this,this.eEb),this.wW.wb()),this.wW=b,null!=this.wW&&(this.wW.Ba(),this.wW.Ca(this,this.eEb)),this.ea(a.f.i))};J.Evd=function(){return this.cFa};J.a8b=function(b){this.cFa!=b&&(this.cFa=b,this.ea(a.f.i))};J.DCc=function(){return this.wYa};J.c8b=function(b){this.wYa!=b&&(this.wYa=b,this.ea(a.f.i))};J.BCc=function(){return this.vYa};J.b8b=function(b){this.vYa!=b&&(this.vYa=b,this.ea(a.f.i))};J.Hd=function(a,
c,d){J.j.Hd.call(this,a,c,d);a=this.Pa().gb();b.Jd[a].Hg(this.cFa,this.wYa,this.vYa)};J.Xib=function(){var a=this.wW,c=this.Pa().gb(),a=a?a.kh():"";b.Jd[c].Xc(a)};J.eEb=function(b,c){switch(c.Ya){case a.f.qb:case a.f.Ob:this.kRa(null);break;case a.f.i:this.ea(a.f.i)}};e.ib(c.Bfb,"PRIM_WEB","RichTextImage",{Oa:{Image:{a:J.CCc,g:function(a){this.kRa(a)}},Width:{a:J.DCc,g:function(a){this.c8b(e.L(a))}},Height:{a:J.BCc,g:function(a){this.b8b(e.L(a))}},Alignment:{a:function(){return e.ta(this.cFa,a.ZI.v)},
g:function(b){this.a8b(e.qa(b,a.ZI.v))}}}});c.LNa=function(){D.w.call(this);this.xy=null};var D=c.u(c.LNa,c.Ula);D.Sg=function(){return c.O0b};D.$y=function(){null==this.xy&&(this.xy=new c.Cfb(this));return this.xy};e.ib(c.LNa,"PRIM_WEB","RichTextParagraph",{Oa:{Items:{a:D.$y}}});c.zfb=function(){P.w.call(this);this.qd=b.Cd(0,0,100,100)};var P=c.u(c.zfb,c.LNa);P.Sg=function(){return c.K0b};P.uX=function(b){if(!this.$c()){var c=e.Rb();c.Wb("ITEM",b);this.Ha(a.K.CI,c);c.nc()}};P.vX=function(b){if(!this.$c()){var c=
e.Rb();c.Wb("ITEM",b);this.Ha(a.K.EI,c);c.nc()}};P.R2=function(b){if(!this.$c()){var c=e.Rb();c.Wb("ITEM",b);this.Ha(a.K.DI,c);c.nc()}};P.jA=function(b,c){if(!c&&!this.$c()){var d=e.Rb();d.Wb("ITEM",b);d.gf("CONTINUE",!0);this.Ha(a.K.BI,d);c=!d.Uf("CONTINUE");d.nc()}return c};e.ib(c.zfb,"PRIM_WEB","RichText",{});c.Cfb=function(a){u.w.call(this);this.Za=[];this.Vz=a};var u=c.u(c.Cfb,c.jd);u.R=function(){u.j.R.call(this)};u.lc=function(){return this.Za.length};u.Od=function(a){return this.Za[a-1]};
u.Ng=function(b,d,e,g){var f=new c.Dfb;f.Ba();f.Ab(b);d!=n&&f.sb(d);e!=n&&f.um(e);g!=n&&f.Yn(g);f.Ma(this.Vz);this.Za[this.Za.length]=f;this.Vz.ea(a.f.i);this.Vz.Qb()&&this.Vz.Ug();return f};u.Xhc=function(){var b=new c.Afb;b.Ba();b.Ma(this.Vz);this.Za[this.Za.length]=b;this.Vz.ea(a.f.i);this.Vz.Qb()&&this.Vz.Ug();return b};u.fic=function(b,d,e,g,f,k,h){var m=new c.Bfb;m.Ba();m.kRa(b);d!=n&&m.a8b(d);e!=n&&m.c8b(e);g!=n&&m.b8b(g);f!=n&&m.sb(f);k!=n&&m.um(k);h!=n&&m.Yn(h);m.Ma(this.Vz);this.Za[this.Za.length]=
m;this.Vz.ea(a.f.i);this.Vz.Qb()&&this.Vz.Ug();return m};u.kic=function(b,d,e,g){var f=new c.LNa;f.Ba();b!=n&&f.Ab(b);d!=n&&f.sb(d);e!=n&&f.um(e);g!=n&&f.Yn(g);f.Ma(this.Vz);this.Za[this.Za.length]=f;this.Vz.ea(a.f.i);this.Vz.Qb()&&this.Vz.Ug();return f};u.As=function(b){this.Za.splice(this.Za.indexOf(b),1);b.Ma(null);b.wb();this.Vz.ea(a.f.i)};u.Fj=function(){for(;0<this.Za.length;)this.As(this.Za[0]);this.Vz.ea(a.f.i)};e.ib(c.Cfb,"PRIM_WEB","RichTextItems",{Oa:{Item:{a:function(a){return this.Od(e.L(a))},
ow:"na"},ItemCount:{a:u.lc}},jc:{Add:u.Ng,AddBreak:u.Xhc,AddImage:function(b,c,d,g,f,k,h){return this.fic(b,e.qa(c,a.ZI.v),d,g,f,k,h)},AddParagraph:u.kic,Remove:u.As,RemoveAll:u.Fj},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.Od(e.L(a))},zv:u.lc}});c.I_b=function(){B.w.call(this);this.qd=b.Cd(0,0,100,100)};var B=c.u(c.I_b,c.mm);B.Sg=function(){return c.p0b};B.Hd=function(a,b,c){B.j.Hd.call(this,a,b,c)};B.ng=function(a){this.VI();a&&this.iza();b.cb().rB(this)};B.gC=function(){this.ca.QW()};e.ib(c.I_b,
"PRIM_WEB","Camera",{});c.T_b=function(){E.w.call(this);this.qd=b.Cd(0,0,100,100);this.JE=null;this.SGa("")};var E=c.u(c.T_b,c.mm);E.R=function(){this.JE=null;E.j.R.call(this)};E.Sg=function(){return c.P0b};E.Iua=function(){this.Pa()&&this.SGa(this.Pa().Hwc());return this.JE};E.SGa=function(a){this.JE=new c.mG({data:a,mimetype:"image/png",filename:"signature.png"})};E.zn=function(){if(this.Pa()){var a=this.Pa().gb();b.Jd[a].zn();this.wc()}};E.Hd=function(a,b,c){E.j.Hd.call(this,a,b,c)};E.ng=function(a){this.VI();
a&&this.iza();b.cb().rB(this)};E.gC=function(){this.ca.QW()};E.wc=function(){this.Ha(a.K.Dh)};e.ib(c.T_b,"PRIM_WEB","Signature",{Oa:{Blob:{a:E.Iua}},jc:{Clear:E.zn}});c.O_b=function(){T.w.call(this);this.rwb=this.Dub=this.Wrb=this.Vrb=this.Rrb=this.AXa=this.svb=0;this.v7=a.WD.KGb};var T=c.u(c.O_b,c.jd);T.hBc=function(){return this.svb};T.sAc=function(){return this.AXa};T.cwc=function(){return this.Rrb};T.nwc=function(){return this.Vrb};T.owc=function(){return this.Wrb};T.Mzc=function(){return this.Dub};
T.cDc=function(){return this.rwb};T.gsd=function(){return this.v7};T.bTc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.svb=d.coords.longitude;b.AXa=d.coords.latitude;b.Rrb=d.coords.accuracy;b.Vrb=d.coords.altitude?d.coords.altitude:0;b.Wrb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.Dub=d.coords.heading?d.coords.heading:0;b.rwb=d.coords.speed?d.coords.speed:0;b.v7=a.WD.sIa;d=new c.vla;b.Ha(a.K.F4b,d)},function(d){b.svb=0;b.AXa=0;b.Rrb=
0;b.Vrb=0;b.Wrb=0;b.Dub=0;b.rwb=0;b.v7=a.WD.f4a;switch(d.code){case d.PERMISSION_DENIED:b.v7=a.WD.OGb;break;case d.POSITION_UNAVAILABLE:b.v7=a.WD.PGb;break;case d.TIMEOUT:b.v7=a.WD.RGb;break;case d.UNKNOWN_ERROR:b.v7=a.WD.f4a}d=new c.vla;b.Ha(a.K.F4b,d)});return this.AXa};e.ib(c.O_b,"PRIM_WEB","Geolocation",{Oa:{Longitude:{a:T.hBc},Latitude:{a:T.sAc},Accuracy:{a:T.cwc},Altitude:{a:T.nwc},AltitudeAccuracy:{a:T.owc},Heading:{a:T.Mzc},Speed:{a:T.cDc},ErrorCode:{a:function(){return e.ta(this.v7,a.WD.v)}}},
jc:{Refresh:T.bTc}});c.K_b=function(){y.w.call(this)};var y=c.u(c.K_b,c.jd);y.hNc=function(b,c){if("undefined"!==typeof console)switch(c){case a.PS.zzb:console.error(b);break;case a.PS.Czb:console.warn(b);break;case a.PS.Azb:console.info(b);break;default:console.log(b)}};e.ib(c.K_b,"PRIM_WEB","Console",{Oa:{},jc:{Log:function(b,c){return this.hNc(e.na(b),c?e.qa(c,a.PS.v):a.PS.Bzb)}}});c.N_b=function(){O.w.call(this);this.Yb=this.fb=null;this.Kz=this.Zr="";this.yvb=!1};var O=c.u(c.N_b,c.xs);O.R=function(){O.j.R.call(this);
this.sn(null)};O.Sg=function(){return c.x0b};O.kh=function(){return this.Zr};O.C6a=function(){return this.Kz};O.Eg=function(b){this.fb!=b&&(this.sn(b),this.m(a.f.i))};O.hb=function(){var a=null;return a=this.fb};O.hc=function(){return this.Yb};O.g7a=function(){return this.yvb};O.N7b=function(b){this.yvb!=b&&(this.yvb=b,this.ea(a.f.i))};O.wc=function(){this.Ha(a.K.Dh)};O.W4a=function(b,c){var d=e.Rb();d.Wb("FILE",b);d.Wb("FILES",c);this.Ha(a.K.ZHb,d);d.nc()};O.wO=function(){this.vR=b.Ola(this.Yb.Ak());
this.fb.eT(this.hc())};O.sn=function(a){var c=null;a&&(c=a.vx(),this.fb==a?c.qo(this.Yb):a.Ry(c));this.fb&&(this.fb.Aa(this),this.Yb.Aa(this),b.la(this.Yb),this.Yb=null);if(this.fb=a)this.fb.Ca(this,this.Zm),this.Yb=c,this.Yb.Ca(this,this.pv);this.Vg()};O.EOd=function(){};O.Zm=function(b,c){c.Ya==a.f.i?c.qr==a.me.Gw?this.fb.Ry(this.hc()):this.sn(this.fb):c.Ya==a.f.qb&&this.Eg(null)};O.pv=function(b,c){c.Ya==a.f.i&&c.qr==a.me.Gw&&this.wO()};e.ib(c.N_b,"PRIM_WEB","FilePicker",{Oa:{MultiSelect:{a:O.g7a,
g:function(a){this.N7b(e.ya(a))}}}});c.sfb=function(a){G.w.call(this);this.vXa=a;this.oW=this.JE=null};var G=c.u(c.sfb,c.jd);G.R=function(){null!=this.JE&&(this.JE=null);null!=this.oW&&(b.kBb(this.oW),this.oW=null);G.j.R.call(this)};G.Pg=function(){return this.vXa.name};G.Iua=function(){null==this.JE&&(this.JE=new c.uWb(this.vXa));return this.JE};G.P7a=function(){return this.vXa.size};G.xBc=function(){return this.vXa.type};e.ib(c.sfb,"PRIM_WEB","File",{Oa:{Name:{a:G.Pg},Blob:{a:G.Iua},FileSize:{a:G.P7a},
MimeType:{a:G.xBc}}});c.tfb=function(){ha.w.call(this);this.Za=[]};var ha=c.u(c.tfb,c.jd);ha.R=function(){for(var a=0;a<this.Za.length;a++)this.Za[a].wb();this.Za=[];ha.j.R.call(this)};ha.lc=function(){return this.Za.length};ha.Od=function(a){return this.Za[a-1]};ha.Dr=function(a){this.Za.push(a);a.Ba()};e.ib(c.tfb,"PRIM_WEB","Files",{Oa:{Item:{a:function(a){return this.Od(e.L(a))},ow:"na"},ItemCount:{a:ha.lc}},Xf:{Sf:"Item"},wp:{Fo:function(a){return this.Od(e.L(a))},zv:ha.lc}});c.J_b=function(){ea.w.call(this)};
var ea=c.u(c.J_b,c.jd);ea.Lib=function(a){var d=this;if(window.FileReader&&a instanceof c.mG){if(a=a.xja()){var e=b.IQ(),g=new FileReader;g.onload=function(a){d.tX(a.target.result);b.hy(e)};g.readAsText(a)}}else d.tX("")};ea.tX=function(b){var c=e.Rb();c.EF("DATA",b);this.Ha(a.K.n2,c)};e.ib(c.J_b,"PRIM_WEB","ClobReader",{jc:{Read:ea.Lib}});c.H_b=function(){na.w.call(this)};var na=c.u(c.H_b,c.jd);na.Lib=function(a){var d=this;if(window.FileReader&&a instanceof c.mG){if(a=a.xja()){var e=b.IQ(),g=new FileReader;
g.onload=function(a){d.tX(b.IHb(a.target.result));b.hy(e)};g.readAsDataURL(a)}}else d.tX("","")};na.tX=function(b){var c=e.Rb();c.EF("DATA",b);this.Ha(a.K.n2,c)};e.ib(c.H_b,"PRIM_WEB","BlobReader",{jc:{Read:na.Lib}});c.K0b=function(a){W.w.call(this,a)};var W=c.u(c.K0b,c.om);W.Ab=function(a){this.G.textContent=a};W.Ny=function(){W.j.Ny.call(this);this.G.style.whiteSpace="normal";this.G.style.overflowX="auto";this.G.style.overflowY="auto"};W.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",
a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return W.j.df.call(this,a,b)};c.O0b=function(a){Q.w.call(this,a)};var Q=c.u(c.O0b,c.om);Q.Ab=function(a){this.G.textContent=a};Q.rwa=function(){return!1};Q.xea=function(){};Q.Ny=function(){};Q.df=function(a,b){this.G=document.createElement("p");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return Q.j.df.call(this,a,b)};c.L0b=function(a){x.w.call(this,a)};var x=c.u(c.L0b,c.om);x.rwa=function(){return!1};x.xea=function(){};
x.Ny=function(){};x.df=function(a,b){this.G=document.createElement("br");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return x.j.df.call(this,a,b)};c.M0b=function(a){F.w.call(this,a)};var F=c.u(c.M0b,c.om);F.Xc=function(a){this.G.src=a};F.rwa=function(){return!1};F.Hg=function(b,c,d){this.G.style.width=0==c?"auto":c+"px";this.G.style.height=0==d?"auto":d+"px";switch(b){case a.ZI.Bjb:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display=
"inline";this.G.style.cssFloat="none";break;case a.ZI.L5b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="left";break;case a.ZI.M5b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="right";break;case a.ZI.K5b:this.G.style.marginLeft="auto",this.G.style.marginRight="auto",this.G.style.display="block",this.G.style.cssFloat="none"}};F.xea=function(){};F.Ny=
function(){this.G.style.borderStyle="solid"};F.df=function(a,b){this.G=document.createElement("img");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return F.j.df.call(this,a,b)};c.N0b=function(a){da.w.call(this,a)};var da=c.u(c.N0b,c.om);da.Ab=function(a){this.G.textContent=a};da.rwa=function(){return!1};da.xea=function(){};da.Ny=function(){};da.df=function(a,b){this.G=document.createElement("span");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",
this.cc);return da.j.df.call(this,a,b)};c.p0b=function(a){ba.w.call(this,a)};var ba=c.u(c.p0b,c.om);ba.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return ba.j.df.call(this,a,b)};c.P0b=function(a){fa.w.call(this,a);this.dH=this.ym=null;this.dfc=this.Bxb=!1;this.Oub=null};var fa=c.u(c.P0b,c.om);fa.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",
this.cc);this.G.style.msTouchAction="none";this.dH=document.createElement("canvas");this.dH.style.touchAction="none";this.G.appendChild(this.dH);this.ym=this.dH.getContext("2d");this.hBb();return fa.j.df.call(this,a,b)};fa.nn=function(a,b,c,d){fa.j.nn.call(this,a,b,c,d);a=this.ym.getImageData(0,0,this.dH.width-1,this.dH.height-1);this.dH.width=this.Uc;this.dH.height=this.ed;this.ym.putImageData(a,0,0)};fa.YL=function(a){this.d9b(a);return!0};fa.Hgb=function(a){this.c9b(a);return!0};fa.$Na=function(a){this.b9b(a);
return!0};fa.npa=function(a){this.d9b(a);return!0};fa.Sv=function(a){this.c9b(a);return!0};fa.rea=function(a){this.b9b(a);return!0};fa.SOb=function(a){this.G.onpointerdown===n&&a.touches!==n?(a.Jrb=a.touches[0].pageX-this.pa.qs(),a.Krb=a.touches[0].pageY-this.pa.rs()):(a.Jrb=a.clientX-this.pa.qs(),a.Krb=a.clientY-this.pa.rs());this.pa.wc()};fa.hBb=function(){this.o0a(!0);this.Oub=new Image;this.Oub.onload=function(){throw 0;};this.Oub.src=null};fa.o0a=function(a){(this.dfc||a)&&this.ym.clearRect(0,
0,this.ym.canvas.width,this.ym.canvas.height);this.dfc=!1};fa.Hwc=function(){var a=this.dH.toDataURL("image/png");return b.IHb(a)};fa.zn=function(){this.hBb()};fa.d9b=function(a){a.preventDefault();this.o0a(!1);this.ym.beginPath();this.SOb(a);this.ym.moveTo(a.Jrb,a.Krb);this.Bxb=!0};fa.b9b=function(a){a.preventDefault();this.Bxb=!1};fa.zMd=function(a){this.Sv(a)};fa.c9b=function(a){this.Bxb&&(a.preventDefault(),this.o0a(!1),this.ym.strokeStyle="rgb(0,0,0)",this.ym.lineWidth=1,this.SOb(a),this.ym.lineTo(a.Jrb,
a.Krb),this.ym.stroke())};c.Y_b=function(a){oa.w.call(this,a);this.Bsa=this.$a=null};var oa=c.u(c.Y_b,c.om);oa.yl=function(a){this.Bsa.src=a};oa.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);this.Bsa=document.createElement("iframe");this.iGa(this.Bsa);this.Bsa.style.width="100%";this.Bsa.style.height="100%";this.G.appendChild(this.Bsa);return oa.j.df.call(this,a,b)};oa.XW=function(){var a=this;oa.j.XW.call(this);
a.G.addEventListener("load",function(){a.pa.rvc()},!1)};oa.iGa=function(a){oa.j.iGa.call(this,a);this.G.style.overflowX="auto";this.G.style.overflowY="auto"};c.x0b=function(a){$.w.call(this,a);this.BR=null};var $=c.u(c.x0b,c.Nfb);$.df=function(a,b){var c=$.j.df.call(this,a,b);this.BR=document.createElement("input");this.BR.type="File";var d=this.BR.style;this.jb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.BR);return c};$.Hd=function(){$.j.Hd.call(this);
this.Zbd()};$.nn=function(a,b,c,d){$.j.nn.call(this,a,b,c,d);this.BR.style.left="0px";this.BR.style.top="0px";this.BR.style.width=c+"px";this.BR.style.height=d+"px"};$.XW=function(){var a=this;this.d2();a.BR.addEventListener("change",function(b){a.Ilc(b);a.BR.value=""},!1)};$.Zbd=function(){this.BR.multiple=this.pa.g7a()};$.Ilc=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.tfb,e=0,g;g=a[e];e++)g=new c.sfb(g),null==b&&(b=g),d.Dr(g);b&&this.pa.W4a(b,d)}},{rp:["PRIM_LABL"]});
