window.LANSA.addSrc("msg",function(e,c,a,b,n){e.Fb("PRIM_PPNL");a.Lla={u4:0,JNc:1,LNc:2,GNc:4,HNc:8};a.Lla.v={NONE:a.Lla.u4,TEXT:a.Lla.JNc,WARNING:a.Lla.LNc,ERROR:a.Lla.GNc,FATAL:a.Lla.HNc};a.QY={h0b:1,j0b:2,i0b:4};a.QY.v={ERROR:a.QY.h0b,QUESTION:a.QY.j0b,INFORMATION:a.QY.i0b};a.oo={Dfd:16,b_a:1,QFa:16,NFa:32,SFa:64,PFa:128,RFa:256,OFa:512};a.oo.v={NONE:a.oo.b_a,OK:a.oo.QFa,CANCEL:a.oo.NFa,YES:a.oo.SFa,NO:a.oo.PFa,RETRY:a.oo.RFa,IGNORE:a.oo.OFa};a.lG={sfb:16,l0b:48,m0b:192,n0b:224,k0b:768};a.lG.v=
{OK:a.lG.sfb,OKCANCEL:a.lG.l0b,YESNO:a.lG.m0b,YESNOCANCEL:a.lG.n0b,IGNORERETRY:a.lG.k0b};c.lVb=function(){s.w.call(this)};var s=c.u(c.lVb,c.ld);e.ad(c.lVb,"PRIM_MSG",{});c.lcb=function(){p.w.call(this);this.IC=[]};var p=c.u(c.lcb,c.ld);p.iAc=function(){e.Fb("PRIM_PCOL");var a=new c.oTb(this);return new c.HY(a)};p.Lg=function(a,b){var e=new c.mcb(this,a);this.IC.push(e);e.aj(b);this.cuc(e);return e};p.un=function(a){if(a)for(var b=0;b<this.IC.length;b++){var c=this.IC[b];c.ea()==a&&(this.qHb(c),this.IC.splice(b--,
1),c.QAb())}};p.Gkc=function(){for(;0<this.IC.length;){var a=this.IC.shift();this.qHb(a);a.QAb()}};p.cuc=function(b){var c=e.Rb();c.Vb("MESSAGE",b);this.Ha(a.K.qNc,c);c.mc()};p.qHb=function(b){var c=e.Rb();c.Vb("MESSAGE",b);this.Ha(a.K.rNc,c);c.mc()};e.ad(c.lcb,"PRIM_MSGQ",{Pa:{Messages:{a:p.iAc}},jc:{Add:function(a,b){return this.Lg(e.na(a),b===n?null:b)},Clear:function(a){return this.un(a===n?null:a)},ClearAll:function(){return this.Gkc()}}});c.oTb=function(a){t.w.call(this);this.WDa=a};var t=c.u(c.oTb,
c.Waa);t.pc=function(){return this.WDa.IC.length};t.Dx=function(a){return this.WDa.IC[a]};c.mcb=function(a,b){f.w.call(this);this.WDa=a;this.Fg=b;this.$a=null};var f=c.u(c.mcb,c.ld);f.Np=function(){return this.Fg};f.ea=function(){return this.$a};f.aj=function(a){this.Yf()&&this.$a!=a&&(null!=this.$a&&(this.$a.VL(this),this.$a.Ba(this,this.rq)),this.$a=a)&&(a.kK(this),a.Ea(this,this.rq))};f.Yf=function(){return null!==this.WDa};f.QAb=function(){this.aj(null);this.Fg="";this.WDa=null};f.rq=function(b,
c){switch(c.Ya){case a.f.rb:this.aj(null)}};e.kb(c.mcb,"PRIM_MSGQ","Message",{Pa:{Text:{a:f.Np},Control:{a:f.ea,g:f.aj}}});c.yZb=function(){h.w.call(this);this.Npa=[]};var h=c.u(c.yZb,c.ld);h.U=function(){this.Cj();h.j.U.call(this)};h.be=function(a){return this.Npa[a]};h.pc=function(){return this.Npa.length};h.Lg=function(b){this.Npa.push(b);this.m(a.f.i)};h.Cj=function(){this.Npa=[];this.m(a.f.i)};h.Tzc=function(){for(var a="",b=0;b<this.Npa.length;b++){var c=this.Npa[b];c.length>a.length&&(a=c)}return a};
e.kb(c.yZb,"PRIM_WEB","MessageBoxCaptions",{jc:{Add:h.Lg,RemoveAll:h.Cj}});c.xZb=function(){l.w.call(this);e.Fb("PRIM_PHBN");e.Fb("PRIM_LABL");this.IEa=this.e8=this.Vga=null;this.VDa=a.QY.i0b;this.EA=a.lG.sfb;this.Je=a.oo.b_a;this.lUa=[];this.$Q=null;this.GYa=new c.ss;this.FYa=new c.WP;this.OC=new c.em;this.WG=e.gd("PRIM_WEB","MessageBoxCaptions");this.WG.Aa();this.WG.Ea(this,this.BBb);this.cg=new c.Ldb;this.KM=new c.WP;this.iH=new c.WP;this.iK=new c.WP;this.oN=new c.WP;this.AN=new c.WP;this.PJ=new c.WP;
this.iH.Ga(this,a.K.gc,this.Hpc);this.KM.Ga(this,a.K.gc,this.Unc);this.iK.Ga(this,a.K.gc,this.xrc);this.oN.Ga(this,a.K.gc,this.Fpc);this.AN.Ga(this,a.K.gc,this.kqc);this.PJ.Ga(this,a.K.gc,this.gpc);this.OC.Na(this);this.cg.Na(this);this.KM.Na(this);this.iH.Na(this);this.iK.Na(this);this.oN.Na(this);this.AN.Na(this);this.PJ.Na(this);this.e8=new c.ob;this.IEa=new c.ig;this.e8.zd(this.IEa);this.IEa.Ad(a.l.xQ);this.IEa.kg(9);this.W6b(this.e8);this.e8.Aa();this.IEa.Aa();this.OC.Ua(90);this.OC.tf(!1);this.OC.Va(57);
this.OC.Mb(!0);this.OC.uQ(!0);this.OC.AZ(!0);this.cg.Re(6);this.cg.iE(a.mh.Yq);this.cg.Ua(20);this.cg.Va(57);this.cg.wu(64);this.cg.kM(64);this.cg.vc(64);this.cg.$b(64);this.cg.tf(!1);this.iH.Ab(b.Cn().ok||"OK");this.oN.Ab(b.Cn().no||"No");this.iK.Ab(b.Cn().yes||"Yes");this.AN.Ab(b.Cn().retry||"Retry");this.KM.Ab(b.Cn().cancel||"Cancel");this.PJ.Ab(b.Cn().ignore||"Ignore");this.p5b(this.EA);this.wPa(!1);this.Wkb(!0)};var l=c.u(c.xZb,c.Aw);l.U=function(){this.WG.Ba(this,this.BBb);this.WG.vb();this.WG=
null;this.jAb();l.j.U.call(this)};l.fYc=function(a){this.GYa.tb(a)};l.Ivc=function(){return this.GYa.Xf()};l.Jvc=function(){return this.GYa.Aj()};l.Dia=function(){return this.FYa.Xf()};l.xG=function(a){this.FYa.tb(a)};l.Cvc=function(){return this.FYa.Aj()};l.nAa=function(b){b!=this.xT()&&(this.Ab(b),this.rTa(),this.m(a.f.i))};l.xT=function(){return this.mb()};l.E_c=function(b){this.WG.Cj();b!=this.HJb()&&(this.WG.Lg(b),this.m(a.f.i))};l.Lvc=function(){return this.WG};l.HJb=function(){return 0<this.WG.pc()?
this.WG.be(0):""};l.F5b=function(b){this.$Q!==b&&(null!=this.$Q&&(this.$Q.Ba(this,this.QBb),this.$Q.vb()),this.$Q=b,null!==this.$Q&&(this.$Q.Aa(),this.$Q.Ea(this,this.QBb)),this.rTa(),this.m(a.f.i))};l.Iwc=function(){return this.$Q};l.F_c=function(b){this.VDa!=b&&(this.VDa=b,this.rTa(),this.m(a.f.i))};l.rsd=function(){return this.VDa};l.p5b=function(b){this.EA=b;this.iH.Mb(0!=(this.EA&a.oo.QFa));this.KM.Mb(0!=(this.EA&a.oo.NFa));this.iK.Mb(0!=(this.EA&a.oo.SFa));this.oN.Mb(0!=(this.EA&a.oo.PFa));
this.PJ.Mb(0!=(this.EA&a.oo.OFa));this.AN.Mb(0!=(this.EA&a.oo.RFa))};l.$md=function(){return this.EA};l.UJd=function(a){this.Je=a};l.dud=function(){return this.Je};l.emc=function(b,e,f){var h=new c.ss;h.Na(this.OC);h.Ua(0);h.tf(!1);h.Va(e);h.Vn(a.mh.Yq);h.$b(f.Wa());h.vc(f.Sa());h.nf(!1);h.Ab(b);return h};l.P7b=function(a,e){var f=b.zw(0,0),h=new c.ja(0,0,0,0);b.MB(a,h,0,e);f.$b(h.aa()+2);f.vc(h.ba()+2);return f};l.fBc=function(){if(null!=this.$Q)return this.$Q;var d="";switch(this.VDa){case a.QY.h0b:d=
"lansa_error.png";break;case a.QY.j0b:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.vL;e.Gv(b.qc(d));return e};l.Bhc=function(){var a=this.FYa.Aj().bb.AD(),b=null;this.iH.Aj().Cj();this.KM.Aj().Cj();this.iK.Aj().Cj();this.oN.Aj().Cj();this.AN.Aj().Cj();this.PJ.Aj().Cj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.iH.Aj().Lg(b),this.KM.Aj().Lg(b),this.iK.Aj().Lg(b),this.oN.Aj().Lg(b),this.AN.Aj().Lg(b),this.PJ.Aj().Lg(b);this.iH.Ak(!1,!0);this.KM.Ak(!1,!0);
this.iK.Ak(!1,!0);this.oN.Ak(!1,!0);this.AN.Ak(!1,!0);this.PJ.Ak(!1,!0)};l.Hhc=function(){var a=this.GYa.Aj().bb.AD(),b=null;this.OC.Aj().Cj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.OC.Aj().Lg(b);this.OC.Ak(!1,!0)};l.sna=function(){this.Vga=b.vQ();this.Je=a.oo.b_a;this.pzb();var c=b.Hl();this.iz(a.Zi.I4,null,c,null);this.dZc()};l.rTa=function(){this.lL()&&(this.pzb(),this.Qg())};l.pzb=function(){var a;this.jAb();this.cg.Xc(this.fBc());this.Bhc();this.Hhc();a=this.ixb();this.sPc(a)};
l.kza=function(){this.ixb();l.j.kza.call(this)};l.ixb=function(){var a=this.Nz(),b=this.bkc(),c=this.hkc(),c=this.gkc(c),e=this.dkc(a),f=this.ckc(b),h=this.jkc(c,e,f);this.KTc(h,b,e);this.hhc(b,c,f,h);return a};l.KTc=function(a,b,c){this.$b(a.Wa());this.vc(a.Sa());a=b.Wa();b=b.Sa();this.KM.$b(a);this.iH.$b(a);this.iK.$b(a);this.oN.$b(a);this.AN.$b(a);this.PJ.$b(a);this.KM.vc(b);this.iH.vc(b);this.iK.vc(b);this.oN.vc(b);this.AN.vc(b);this.PJ.vc(b);this.OC.$b(c.Wa());this.OC.vc(c.Sa())};l.hhc=function(a,
b,c,e){this.dYc(a);a=e.Sa()-c.Sa();this.KM.Va(a);this.iH.Va(a);this.iK.Va(a);this.oN.Va(a);this.AN.Va(a);this.PJ.Va(a);this.cg.Ua(20);this.cg.Va(this.nq.Sa()+20);this.OC.Ua(40+b.Wa());this.OC.Va(this.nq.Sa()+20)};l.jkc=function(a,c,e){var f=b.PD(),h=b.zw(0,0);a=this.fkc(a,c);c=this.Hz.cKa(this.Hz.mb(),this.Hz.Am().length)+10;h.$b(Math.max(a.Wa(),c,e.Wa())+60);h.vc(this.nq.Sa()+a.Sa()+e.Sa()+40);h.$b(Math.min(f.aa()-40,h.Wa()));h.vc(Math.min(f.ba()-40,h.Sa()));return h};l.gja=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};l.Szc=function(){var a="",a=this.gja(this.iH.mb(),a),a=this.gja(this.KM.mb(),a),a=this.gja(this.iK.mb(),a),a=this.gja(this.oN.mb(),a),a=this.gja(this.AN.mb(),a),a=this.gja(this.PJ.mb(),a);return" "+a+" "};l.bkc=function(){var a=this.Szc(),c=b.zw(0,0),c=this.iH.Xd();return c=this.P7b(a,c)};l.Nz=function(){var a=this.WG.Tzc(),c=b.zw(0,0),c=this.OC.Xd();return c=this.P7b(a,c)};l.hkc=function(){var a=b.zw(0,0);a.$b(this.cg.Wa());a.vc(this.cg.Sa());return a};l.dkc=function(a){var c=
b.zw(0,0),e=a.Wa()+4;a=this.WG.pc()*(a.Sa()+4);e+=20;a+=20;e=170>e?170:e;a=70>a?70:a;a=630<a?630:a;c.$b(630<e?630:e);c.vc(a);return c};l.gkc=function(a){var c=b.zw(0,0);c.vc(a.Sa()+16);c.$b(a.Wa()+8);return c};l.fkc=function(a,c){var e=b.zw(0,0);e.vc(Math.max(a.Sa(),c.Sa()));e.$b(2+a.Wa()+2+c.Wa()+2);return e};l.ckc=function(a){var c=b.zw(0,0),e=66>a.Wa()?66:a.Wa(),f=25>a.Sa()?25:a.Sa();a.$b(e);a.vc(f);c.vc(a.Sa()+24);c.$b(3*a.Wa()+8);return c};l.dYc=function(b){b=b.Wa()+20;var c=1;this.EA&a.oo.RFa&&
(this.AN.Ua(this.Wa()-c*b),++c);this.EA&a.oo.OFa&&(this.PJ.Ua(this.Wa()-c*b),++c);this.EA&a.oo.NFa&&(this.KM.Ua(this.Wa()-c*b),++c);this.EA&a.oo.QFa&&(this.iH.Ua(this.Wa()-c*b),++c);this.EA&a.oo.PFa&&(this.oN.Ua(this.Wa()-c*b),++c);this.EA&a.oo.SFa&&this.iK.Ua(this.Wa()-c*b)};l.sPc=function(a){for(var b=0,c=a.Sa(),e=0;e<this.WG.pc();e++)this.lUa.push(this.emc(this.WG.be(e),b,a)),b+=c};l.dZc=function(){switch(this.EA){case a.lG.sfb:case a.lG.l0b:this.iH.Se(!0,!0);break;case a.lG.m0b:case a.lG.n0b:this.iK.Se(!0,
!0);break;case a.lG.k0b:this.PJ.Se(!0,!0)}};l.Kja=function(a){this.Je=a;this.Vl();b.$x(this.Vga);this.Vga=null};l.jAb=function(){for(var a=0;a<this.lUa.length;++a)this.lUa[a].Na(null);this.lUa=[]};l.BBb=function(){this.rTa()};l.Hpc=function(){this.Kja(a.oo.QFa)};l.Unc=function(){this.Kja(a.oo.NFa)};l.xrc=function(){this.Kja(a.oo.SFa)};l.Fpc=function(){this.Kja(a.oo.PFa)};l.kqc=function(){this.Kja(a.oo.RFa)};l.gpc=function(){this.Kja(a.oo.OFa)};l.QBb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.F5b(null);
break;case a.f.i:this.m(a.f.i)}};e.kb(c.xZb,"PRIM_WEB","MessageBox",{Pa:{Title:{a:l.xT,g:function(a){this.nAa(e.na(a))}},Caption:{a:l.HJb,g:function(a){this.E_c(e.na(a))}},Text:{a:l.Np,g:function(a){this.tM(e.na(a))}},Captions:{a:l.Lvc},Image:{a:function(){return e.ta(this.VDa,a.QY.v)},g:function(b){this.F_c(e.qa(b,a.QY.v))}},CustomImage:{a:l.Iwc,g:function(a){this.F5b(a)}},Result:{a:function(){return e.ta(this.Je,a.oo.v)}},Buttons:{a:function(){return e.ta(this.EA,a.lG.v)},g:function(b){this.p5b(e.qa(b,
a.lG.v))}},CaptionStyle:{a:l.Ivc,g:function(a){this.fYc(a)}},CaptionStyles:{a:l.Jvc},ButtonStyle:{a:l.Dia,g:function(a){this.xG(a)}},ButtonStyles:{a:l.Cvc}},jc:{Show:l.sna}});c.xdb=function(b){m.w.call(this);this.PWa=[];this.IC=[];this.$a=b;this.Mc=new c.Aw;this.Mc.Ga(this,a.K.lA,this.j9);this.Mc.Ga(this,a.K.tha,this.i2a);this.fga=new c.em;this.fga.jb(new c.ja(0,0,100,25));this.fga.Na(this.Mc);this.fga.tf(!1);this.fga.Zb(a.WQb)};var m=c.u(c.xdb,c.mj);m.ur=function(){return this.Mc};m.Zf=function(){return 0==
this.IC.length};m.kK=function(a){this.IC.push(a)};m.VL=function(a){this.IC.splice(this.IC.indexOf(a),1);this.Zf()&&this.Mc.Vl()};m.j9=function(){e.Fb("PRIM_LABL");for(var b=0,g=6,f=100;b<this.IC.length;b++){var h=this.PWa[b],m=this.IC[b];h||(h=new c.ss,h.Ua(5),h.tf(!1),h.Va(g),h.Vn(a.mh.Yq),h.$b(320),h.vc(20),h.nf(!1),this.PWa.push(h));h.Na(this.fga);h.Ab(m.Np());h.zkc();f<h.Wa()+15&&(f=h.Wa()+15);g+=25}for(;b<this.PWa.length;b++)h=this.PWa[b],h.Na(null);this.fga.vc(g+6);this.fga.$b(f);this.Mc.vc(g+
6);this.Mc.$b(f)};m.i2a=function(){this.$a.Ak(!0)}},{rp:["PRIM_PPNL"]});
