window.LANSA.addSrc("sound",function(e,c,a,b,n){var s,p;s={ALL:0,METADATA:1,NONE:2};p={auto:0,metadata:1,none:2};c.lMa=function(a){t.w.call(this);this.N0=this.Ur="";this.xea=a};var t=c.u(c.lMa,c.ld);t.U=function(){t.j.U.call(this)};t.gh=function(){return this.Ur};t.Gv=function(a){this.Ur=a};t.rX=function(){return this.N0==n?"":this.N0};t.vZ=function(a){this.N0=a};t.qq=function(){for(var a=0;a<this.xea.pc();a++)this.xea.xq(a)===this&&this.xea.Iq(a)};e.kb(c.lMa,"PRIM_SOND","File",{Pa:{FileName:{a:t.gh,
g:function(a){this.Gv(e.na(a))}},FileExtension:{a:t.rX,g:function(a){this.vZ(e.na(a))}}},jc:{Delete:t.qq},Uf:{Pf:"FileExtension"}});c.adb=function(a){f.w.call(this);this.Sec=a;this.Za=[]};var f=c.u(c.adb,c.ld);f.pc=function(){return this.Za.length};f.be=function(a){return this.xq(a)};f.xq=function(a){if(0>a||a>=this.Za.length)throw e.WD(a,this.Za.length);return this.Za[a]};f.Lg=function(a,b){var e=new c.lMa(this);e.Gv(a);e.vZ(b);this.Za.push(e);(e=this.Sec.Oa())&&e.Xq()};f.Iua=function(){0==this.pc()&&
this.Za.push(new c.lMa(this));return this.xq(0)};f.Cj=function(){this.Za=[];var a=this.Sec.Oa();a&&a.Xq()};f.Iq=function(a){if(null==this.xq(a))throw e.WD(a,this.Za.length);this.Za.splice(a,1)};f.jSc=function(a){for(var b=!1,c=0;c<this.pc()&&!(b=this.xq(c).gh()==a);c++);b&&this.Iq(c)};e.kb(c.adb,"PRIM_SOND","Files",{Pa:{Item:{a:function(a){return this.xq(e.L(a)-1)}}},jc:{Add:f.Lg,RemoveAll:f.Cj,Remove:function(a){return this.Iq(e.L(a)-1)}},op:{Co:function(a){return this.xq(e.L(a)-1)},rv:function(){return this.pc()}},
Uf:{Pf:"Item"}});c.cYb=function(){h.w.call(this);this.n0=0;this.a0=this.v1=!0;this.SR=1;this.Vv=new c.adb(this);this.yi=-1;this.Cfa=this.Efa=this.yR=!1;this.YA=50};var h=c.u(c.cYb,c.rs);h.Og=function(){return c.w_b};h.U=function(){h.j.U.call(this)};h.gh=function(){return 0<this.Vv.pc()?this.Vv.xq(0).gh():""};h.Gv=function(b){this.Vv.Cj();var c=this.Vv.Iua();c.gh()!=b&&(c.Gv(b),(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.rX=function(){return 0<this.Vv.pc()?this.Vv.xq(0).rX():""};h.vZ=function(b){var c=
this.Vv.Iua();c.rX()!=b&&(c.vZ(b),(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.lyc=function(){return this.Vv};h.r5a=function(){return this.n0};h.rjb=function(b){this.n0!=b&&(this.n0=b,(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.Z5a=function(){return this.yR};h.Q6a=function(){return this.v1};h.Kkb=function(b){this.v1!=b&&(this.v1=b,(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.K4a=function(){return this.a0};h.Uib=function(b){this.a0!=b&&(this.a0=b,(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.Tia=function(){return this.yi};
h.$5a=function(){return this.Efa};h.Y5a=function(){return this.Cfa};h.O7a=function(){return this.YA};h.rAa=function(c){c=b.Gg(c,0,100);this.YA!=c&&(this.YA=c,this.yR=0==this.YA,(c=this.Oa())&&c.Xq(),this.m(a.f.i))};h.QAc=function(){return this.SR};h.Akb=function(b){this.SR!=b&&(this.SR=b,(b=this.Oa())&&b.Xq(),this.m(a.f.i))};h.Play=function(){this.Oa()&&this.Oa().Play()};h.bi=function(){this.Oa()&&this.Oa().bi()};h.cgb=function(){this.rAa(0)};e.ad(c.cYb,"PRIM_SOND",{Pa:{FileName:{a:h.gh,g:function(a){this.Gv(e.na(a))}},
CycleToStart:{a:h.r5a,g:function(a){this.rjb(e.ya(a))}},ShowControls:{a:h.Q6a,g:function(a){this.Kkb(e.ya(a))}},Autoplay:{a:h.K4a,g:function(a){this.Uib(e.ya(a))}},Preload:{a:function(){return e.ta(this.SR,s)},g:function(a){this.Akb(e.qa(a,s))}},Duration:{a:h.Tia},IsMuted:{a:h.Z5a},IsPlaying:{a:h.$5a},IsEnded:{a:h.Y5a},Volume:{a:h.O7a,g:function(a){this.rAa(e.L(a))}}},jc:{Play:h.Play,Stop:h.bi,Mute:h.cgb}});c.w_b=function(a){l.w.call(this,a)};var l=c.u(c.w_b,c.fm);l.bf=function(b,c){this.G=document.createElement("audio");
this.xCa=b+this.cc;this.G.setAttribute("id",this.xCa);this.G.setAttribute("LANSAHandle",this.cc);this.G.style.position="absolute";this.G.style.overflow="hidden";this.G.style.whiteSpace="nowrap";this.Xq();var e=this.G,f=this;e.addEventListener("loadedmetadata",function(){f.pa.yi=e.duration;f.pa.Ha(a.K.ARb)},!1);e.addEventListener("loadeddata",function(){f.pa.Ha(a.K.zRb)},!1);e.addEventListener("play",function(){f.pa.Efa=!0;f.pa.Cfa=!1;f.pa.Ha(a.K.H1b)},!1);e.addEventListener("pause",function(){f.pa.Efa=
!1;f.pa.Ha(a.K.X7b)},!1);e.addEventListener("ended",function(){f.G.pause();f.G.paused=!0;f.pa.Cfa=!0;f.pa.Ha(a.K.Tz)},!1);e.addEventListener("volumechange",function(){e.muted||0==e.volume?(f.G.muted=!0,f.pa.yR=!0,f.pa.YA=0,f.pa.Ha(a.K.E0b)):(f.pa.yR=!1,f.pa.YA=Math.round(100*e.volume))},!1);return l.j.bf.call(this,b,c)};l.Xq=function(){this.Xma("controls",this.pa.v1);this.Xma("autoplay",this.pa.a0);this.Xma("loop",this.pa.n0);this.G.setAttribute("preload",e.ta(this.pa.SR,p));this.G.volume=0<this.pa.YA?
this.pa.YA/100:0;this.G.muted=this.pa.yR;this.Ppb()};l.Ppb=function(){this.$hb();var a=this.pa.Vv.pc();if(0!=a)for(var b=0;b<a;b++){var c=this.pa.Vv.xq(b);this.bhc(this.G,c.Ur,c.N0)}};l.bhc=function(a,b,c){var e=document.createElement("source");e.src=b;c&&(e.type="audio/"+c);a.appendChild(e)};l.$hb=function(){var a=document.getElementById(this.xCa);if(a&&(a=a.childNodes)){var b,c,e=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&e.push(b);for(c=0;c<e.length;c++)b=e[c],b.parentNode.removeChild(b)}};
l.ML=function(){return!1};l.qNa=function(){};l.Play=function(){this.G.play!==n&&this.G.play()};l.bi=function(){this.G.pause!==n&&this.G.pause()}});
