window.LANSA.addSrc("ver",function(e,c,a,b,n){c.YSb=function(){q.w.call(this);this.uf=new c.kd;this.gra=this.$a=null};var q=c.u(c.YSb,c.jd);q.Lzc=function(){return document.hasFocus()};q.q4c=function(a,t,f){var h=e.gd("PRIM_VS","Style"),k=null,p=null;t===n&&(t=0);f===n&&(f=0);if(a){if(0==t&&0==f)a.mk(!0),k=a.ca;else if(0!=t){var d=a.sB(new c.ha,null);t=a.L7.Nb[t-1];a.Cf().Pa().uhb(d,t,a.gga,null,null,t.gb());k=t.wv();if(0!=f&&(f=a.A2a(f-1)))for(var g in t.gb().eu)if(p=t.gb().eu[g],p.un.zb==f){a.Cf().Pa().shb(d,
p.un,p.un.qaa(),p.un.td.rKa(),p.un.zb.Hva(),null);k=p.un.qaa();break}b.la(d)}k&&(h.Fk(k.mi),h.Un(k.xX()),h.Vh(k.wy),h.Nw(k.az()),h.Uh(k.Jx()),h.zd(k.rw()),h.og(k.yD()),h.Yn(k.iu()),h.Mv(k.Fx()),h.Nv(k.Gx()),h.Kv(k.Dx()),h.Lv(k.Ex()),h.pn(k.Wi()),h.Vn(k.fk()),h.Pl(k.Jl()),h.Ql(k.ek()),h.qM(k.Zd().Hx()),h.Ft(k.Zd().Qa()),h.AA(k.Zd().zi()),h.mE(k.Zd().Bx()),h.wM(k.Zd().Lx()),h.BQ(k.Zd().$F()),h.FQ(k.Zd().cG()));p&&(a.Cf().Pa().Kj.Hp&&h.Uh(a.Cf().Pa().Kj.Hp),a.Cf().Pa().Kj.tj&&h.zd(a.Cf().Pa().Kj.tj))}return h};
q.Lad=function(a,b){return a.N4a(b,[[]])};q.Rmc=function(){null.Xkd()};q.Ulc=function(a,e,f){var h;f===n&&(f=1);h===n&&(h=!0);a=new c.kd(a,e);if((e=b.pU(a))&&e.be()){var k=e.Th(a),p=new c.xt(e,k,a,1),d=new c.xt(e,k,a,1),g=new c.xt(e,k,a,2);b.zC(a.Cb(),a.Db(),k.Cb(),k.Db());h?(h=b.W(),e.Uj(p),null==h.Xj?e.Rn(d):(h=h.Xj.gb(),b.Hrb(null,h,k.Cb(),k.Db(),a.Cb(),a.Db())),2==f&&(g=new c.xt(e,k,a,2),e.Uj(g))):(e.DU(p),e.Nma(d));b.la(p);b.la(g);b.la(d)}};q.hbd=function(a,e){var f=new c.kd(a,e),h=b.pU(f);if(h&&
h.be()){var k=h.Th(f),n=new c.xt(h,k,f,1),d=new c.xt(h,k,f,1),g=new c.xt(h,k,f,1),q=!1;b.zC(f.Cb(),f.Db(),k.Cb(),k.Db());h.rza(k,h,!1);h.qza(g);q=g.Xg;q||(h.Uj(n),h.Rn(d));b.la(n);b.la(d);b.la(g)}};q.nGc=function(a,e){var f=new c.kd(a,e),h=b.pU(f);if(h&&h.be()){var k=h.Th(f);for(b.zC(f.Cb(),f.Db(),k.Cb(),k.Db());h;)k=h.Th(f),b.Sdc(null,h.gb(),k.Cb(),k.Db(),f.Cb(),f.Db()),h=h.U()}};q.l_c=function(a,e){var f=new c.kd(a,e),h=b.pU(f);h&&h.be()&&(h=h.Th(f),b.zC(f.Cb(),f.Db(),h.Cb(),h.Db()))};q.R_c=function(a,
e){(this.gra=b.pU(new c.kd(a,e)))&&document.hasFocus()&&(b.Erb(this.gra.gb()),this.gra=null)};q.NJc=function(a,c){if(""!=a||0!=c){var e=0==c?a.charCodeAt(0):c,h;if(document.hasFocus())h=b.Frb();else if(this.gra)h=this.gra.gb();else return;b.Pdc(null,h,e);""!=a&&b.Qdc(null,h,a,a.charCodeAt(0));b.Rdc(null,h,e)}};q.DOc=function(a,e){this.uf=new c.kd(this.uf.Cb()+(0<a?1:0==a?0:-1),this.uf.Db()+(0<e?1:0==e?0:-1));if(this.$a){var f=this.$a.Th(this.uf);b.zC(this.uf.Cb(),this.uf.Db(),f.Cb(),f.Db());b.sZb(this.$a,
f,this.uf)}};q.XMc=function(a,e,f){f===n&&(f=1);this.uf=new c.kd(a,e);if(this.$a=b.pU(this.uf))a=!1,e=this.$a.Th(this.uf),this.$a.Qf.Lk&&(new c.ha(this.$a.Qf.Lk.hf,this.$a.Qf.Lk.Af,this.$a.Qf.Lk.Uc,this.$a.Qf.Lk.ed)).ae(e)&&(this.$a.Qf.Lk.mza(null),a=this.$a.Qf.Lk.nF),a||(b.zC(this.uf.Cb(),this.uf.Db(),e.Cb(),e.Db()),b.qZb(this.$a,e,this.uf,f))};q.YMc=function(){if(this.$a){var a=!1,e=this.$a.Th(this.uf);this.$a.Qf.Lk&&(new c.ha(this.$a.Qf.Lk.hf,this.$a.Qf.Lk.Af,this.$a.Qf.Lk.Uc,this.$a.Qf.Lk.ed)).ae(e)&&
(this.$a.Qf.Lk.nza(null),a=this.$a.Qf.Lk.nF);a||(b.zC(this.uf.Cb(),this.uf.Db(),e.Cb(),e.Db()),b.rZb(this.$a,e,this.uf,1));this.$a=null}};q.CVc=function(a,e){this.uf=new c.kd(a,e);if(this.$a=b.pU(this.uf)){var f=this.$a.Th(this.uf);b.zC(this.uf.Cb(),this.uf.Db(),f.Cb(),f.Db());b.tZb(this.$a,f,this.uf,1)}};q.DVc=function(){if(this.$a){var a=this.$a.Th(this.uf);b.zC(this.uf.Cb(),this.uf.Db(),a.Cb(),a.Db());b.uZb(this.$a,a,this.uf,1);this.$a=null}};e.ib(c.YSb,"PRIM_VER","Debugger",{Oa:{HasFocus:{a:q.Lzc}},
jc:{Crash:function(){this.Rmc()},Click:function(a,b,c){this.Ulc(e.L(a),e.L(b),c===n?1:e.L(c))},Touch:function(a,b){this.hbd(e.L(a),e.L(b))},Hover:function(a,b){this.nGc(e.L(a),e.L(b))},SetCursorPos:function(a,b){this.l_c(e.L(a),e.L(b))},SetFocus:function(a,b){this.R_c(a,b)},KeyPress:function(a,b){this.NJc(e.na(a),b===n?0:e.L(b))},MouseMove:function(a,b){this.DOc(a,b)},LeftMouseDown:function(a,b,c){this.XMc(e.L(a),e.L(b),c===n?1:e.L(c))},LeftMouseUp:function(){this.YMc()},RightMouseDown:function(a,
b){this.CVc(a,b)},RightMouseUp:function(){this.DVc()},StyleSnapshot:function(a,b,c){return this.q4c(a,b===n?0:e.L(b),c===n?0:e.L(c))},ThemeDrawStyle:function(a,b){return this.Lad(a,e.na(b))}}})});
