window.LANSA.addSrc("ppnl",function(e,c,a,b,n){e.Fb("PRIM_PHBN");e.Fb("PRIM_IMAG");e.Fb("PRIM_TBLO");a.tpa=9999;a.Bfb={iya:0,B0b:3};a.DI={u4:0,Jla:1,x0b:2};a.DI.v={NONE:a.DI.u4,POPUP:a.DI.Jla};a.hk={whb:129,COa:1,shb:2,Dhb:4,yhb:8,thb:16,vhb:32,xhb:64,zhb:128,Chb:256,uhb:512,Bhb:1024,EEd:2048,Ahb:4096};a.gU={bya:0,lba:1,mba:2};a.GDd={e3b:0};a.vK={r0a:0,n0a:268435456,t0a:536870912};a.vK.v={HIDDEN:a.vK.r0a,ALL:a.vK.n0a,NONE:a.vK.t0a};a.bma={oPc:0,Ngb:1,M1b:805306368};a.Dg={L_:0,ZSa:1,lpb:3,mpb:4,xac:5,
wac:6,yac:7,oac:8,pac:9,sac:10,Aac:11,tac:12,qac:13,rac:14,uac:15,vac:16,zac:17};a.Dg.v={NONE:a.Dg.L_,FADEINANDSCALE:a.Dg.ZSa,SLIDEINLEFT:a.Dg.lpb,SLIDEINRIGHT:a.Dg.mpb,SLIDEINBOTTOM:a.Dg.xac,NEWSPAPER:a.Dg.wac,SLIDEINTOP:a.Dg.yac,"3DFLIPHORIZONTAL":a.Dg.oac,"3DFLIPVERTICAL":a.Dg.pac,"3DSIGN":a.Dg.sac,SUPERSCALED:a.Dg.Aac,"3DSLIT":a.Dg.tac,"3DROTATEBOTTOM":a.Dg.qac,"3DROTATEINLEFT":a.Dg.rac,LETMEIN:a.Dg.uac,MAKEWAY:a.Dg.vac,SLIPFROMTOP:a.Dg.zac};a.Dg.Txa={NONE:a.Dg.L_,FADEINANDSCALE:a.Dg.ZSa};a.Dg.TFb=
{"":a.Dg.L_,"md-effect-1":a.Dg.ZSa,"md-effect-21":a.Dg.lpb,"md-effect-2":a.Dg.mpb,"md-effect-3":a.Dg.xac,"md-effect-4":a.Dg.wac,"md-effect-7":a.Dg.yac,"md-effect-8":a.Dg.oac,"md-effect-9":a.Dg.pac,"md-effect-10":a.Dg.sac,"md-effect-11":a.Dg.Aac,"md-effect-13":a.Dg.tac,"md-effect-14":a.Dg.qac,"md-effect-15":a.Dg.rac,"md-effect-17":a.Dg.uac,"md-effect-18":a.Dg.vac,"md-effect-19":a.Dg.zac};c.SXb=function(a){s.w.call(this,a);this.Mc=a};var s=c.u(c.SXb,c.l4);s.xb=function(){s.j.xb.call(this)};s.U=function(){this.bb.gZ();
s.j.U.call(this)};s.ea=function(){return this.Mc.pb()};s.Oa=function(){return null};s.kaa=function(){return!0};s.s5=function(){};s.Bca=function(){};s.Aca=function(){};s.Gw=function(){};s.Eu=function(){};s.tja=function(){return null};s.XF=function(){return!1};s.yd=function(){return!0};s.GP=function(){return!0};s.WF=function(){return!1};s.eL=function(){return!1};s.ue=function(b){b[0]=a.ILa;b[1]=a.GLa};s.$ed=function(){};s.rS=function(a){s.j.rS.call(this,a)};s.yhc=function(){return!1};s.Jba=function(){};
s.sf=function(){};s.K4=function(){};s.qu=function(){};s.N4=function(){};s.mA=function(){};c.Aw=function(){e.Fb("PRIM_IMAG");e.Fb("PRIM_TBLO");e.Fb("PRIM_LABL");p.w.call(this);this.qd=b.Ed(10,10,280,120);this.rf=a.hk.whb;this.dl=this.uh=this.LQ=this.qm=null;this.ix=a.Dg.L_;this.O7=a.Zi.Vx;this.lEa=this.cW=this.bW=null;this.qf=new c.jd(0,0);this.VXa=this.e8=this.Js=this.Hz=this.WA=this.yy=this.ra=this.nq=this.QN=this.pm=null;this.ZEa="";this.UXa=12;this.vga=a.l.ac;b.W().AGc(this);this.rhc();b.W().Tsc();
var d=null;this.ra=new c.wv;b.Jn(this.ra);b.$m(this.ra);this.nq=new c.em;this.nq.jb(new c.ja(0,0,0,30));this.nq.tf(!1);this.nq.Bt(!1);this.nq.rl(this.ra);this.nq.Cca();this.yy=new c.rt;this.yy.tf(!1);this.yy.ZI(a.Oe.gJ);this.yy.Na(this.nq);this.yy.iE(a.ee.SD);this.WA=new c.rt;this.WA.ZI(a.Oe.oRa);this.WA.Na(this.nq);this.WA.tf(!1);this.WA.Ga(this,a.K.gc,this.Ync);this.WA.Ga(this,a.K.NL,this.Znc);this.WA.Ga(this,a.K.OL,this.$nc);this.Hz=new c.ss;this.Hz.Na(this.nq);this.Hz.tf(!1);this.Hz.Vn(a.mh.Yq);
this.Hz.nf(!1);this.Hz.sg(a.wn.UFb);b.Pc(this.ra,this.nq,null,null,1,1);d=b.Pc(this.ra,this.yy,this.ra.Cc(0),this.ra.Gc(0),1,1);d.Hb(a.sa.yl);d.Xb(a.ka.oj);d.Le(2);d=b.Pc(this.ra,this.WA,this.ra.Cc(0),this.ra.Gc(0),1,1);d.Hb(a.sa.dw);d.Xb(a.ka.Sd);d.ve(2);d=b.Pc(this.ra,this.Hz,this.ra.Cc(0),this.ra.Gc(0),1,1);d.Hb(a.sa.Ue);d.Xb(a.ka.oj);this.tf(!1);this.fgb(c.vMa)};var p=c.u(c.Aw,c.em);p.xb=function(){b.la(this.bed);this.bed=null;b.la(this.nq);this.nq=null;b.la(this.yy);this.yy=null;b.la(this.WA);
this.WA=null;b.la(this.Hz);this.Hz=null;p.j.xb.call(this)};p.U=function(){p.j.U.call(this);this.oca(null);this.vPa(null);this.rQa(null);this.sQa(null);this.nca(null);this.Xkb(null);b.W().xSc(this);b.la(this.dl);this.dl=null;b.la(this.lEa);this.lEa=null};p.Og=function(){var a=c.r4;this.lL()&&(a=c.o_b);return a};p.Btd=function(){return this.O7};p.oja=function(){if(null==this.lEa){var a=new c.SXb(this);this.lEa=b.Yaa(a);this.Ea(this,this.aqc)}return this.lEa};p.oca=function(b){this.qm!=b&&(this.qm&&
this.qm.Ba(this),(this.qm=b)&&this.qm.Ea(this,this.HBb),this.m(a.f.i))};p.Dwc=function(){return this.qm};p.vua=function(){var a=null;this.qm&&this.qm instanceof c.rs&&(a=this.qm);return a};p.vPa=function(b){this.LQ!=b&&(this.LQ&&this.LQ.Ba(this),(this.LQ=b)&&this.LQ.Ea(this,this.Fnc),this.m(a.f.i))};p.Uld=function(){return this.LQ};p.rQa=function(b){this.bW!=b&&(this.bW&&this.bW.Ba(this),(this.bW=b)&&this.bW.Ea(this,this.Zpc),this.m(a.f.i))};p.ztd=function(){return this.bW};p.sQa=function(b){this.cW!=
b&&(this.cW&&this.cW.Ba(this),(this.cW=b)&&this.cW.Ea(this,this.$pc),this.m(a.f.i))};p.Atd=function(){return this.cW};p.pb=function(){var a=this.uh;!this.uh||this.uh instanceof c.Aw||(a=this.uh);!a&&this.Y$a()&&(a=this);return a};p.Und=function(){return this.uh};p.OX=function(){null==this.dl&&(this.dl=new c.$aa,this.dl.D6b(),this.dl.mAa(a.Lu.USa));return this.dl};p.NAc=function(){return this.dl};p.Oud=function(){return this.qf};p.En=function(){this.Qg();return this.Nf};p.e5=function(b){b=this.rf&
~a.hk.shb|(b?a.hk.shb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.wPa=function(b){b=this.rf&~a.hk.COa|(b?a.hk.COa:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.I4a=function(){return 0!=(this.rf&a.hk.COa)};p.c5b=function(b){b=this.rf&~a.hk.thb|(b?a.hk.thb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.J4a=function(){return 0!=(this.rf&a.hk.thb)};p.Wkb=function(b){b=this.rf&~a.hk.Chb|(b?a.hk.Chb:0);this.rf!=b&&(this.rf=b,this.EQ(this.Ge()),this.m(a.f.i))};p.G7a=function(){return 0!=(this.rf&a.hk.Chb)};p.NBc=
function(){return this.UXa};p.V6b=function(b){b!=this.UXa&&(this.UXa=b,this.qb(),this.fa(a.f.i))};p.Pud=function(){return this.vga};p.hAa=function(b){if(this.bab()||this.vga!=b)this.vga=b,this.m(a.f.i)};p.H0c=function(){!1==this.bab()&&(this.vga=a.l.ac,this.m(a.f.i))};p.v5b=function(b){b=this.rf&~a.hk.uhb|(b?a.hk.uhb:0);this.rf!=b&&(this.rf=b,this.EQ(this.Ge()),this.m(a.f.i))};p.CIa=function(){return 0!=(this.rf&a.hk.uhb)};p.SJd=function(b){b=this.rf&~a.hk.Ahb|(b?a.hk.Ahb:0);this.rf!=b&&(this.rf=
b,this.m(a.f.i))};p.dBc=function(){return 0!=(this.rf&a.hk.Ahb)};p.dC=function(b){b=this.rf&~a.hk.yhb|(b?a.hk.yhb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.QZc=function(b){b=this.rf&~a.hk.xhb|(b?a.hk.xhb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.JJd=function(b){b=this.rf&~a.hk.zhb|(b?a.hk.zhb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.i5=function(b){b=this.rf&~a.hk.vhb|(b?a.hk.vhb:0);this.rf!=b&&(this.rf=b,this.m(a.f.i))};p.oIb=function(){return 0!=(this.rf&a.hk.vhb)};p.nIb=function(){return this.pm};
p.nca=function(b){this.pm!=b&&(null!=this.pm&&(this.pm.Ba(this,this.T1a),this.pm.vb()),this.pm=b,null!=this.pm&&(this.pm.Aa(),this.pm.Ea(this,this.T1a)),this.EQ(this.Ge()),this.fa(a.f.i))};p.JCc=function(){return this.QN};p.Xkb=function(b){this.QN!=b&&(null!=this.QN&&(this.QN.Ba(this,this.DDb),this.QN.vb()),this.QN=b,null!=this.QN&&(this.QN.Aa(),this.QN.Ea(this,this.DDb)),this.EQ(this.Ge()),this.fa(a.f.i))};p.OBc=function(){return this.oja().Xf()};p.W6b=function(b){this.oja().Xf()!=b&&(this.oja().tb(b),
this.m(a.f.i))};p.PBc=function(){return this.oja().Aj()};p.gb=function(){var a=null;null!=this.Oa()&&(a=this.Oa().gb());return a};p.Vuc=function(){var a=!1;if(this.lL()||!this.Y$a())a=!0;return a};p.ICc=function(){return this.ZEa};p.B1c=function(b){this.ZEa!=b&&(this.ZEa=b,this.qb(),this.fa(a.f.i))};p.aAc=function(){return this.ra};p.hua=function(){return this.ra};p.ih=function(){var a=!1;null!=this.Oa()&&(a=this.Oa().gb(),a=b.Id[a].KQ);return a};p.f$a=function(){return 0!=(this.rf&a.hk.shb)};p.aLa=
function(){return 0!=(this.rf&a.hk.COa)};p.M$a=function(){return 0!=(this.rf&a.hk.yhb)};p.vyd=function(){return 0!=(this.rf&a.hk.xhb)};p.Y$a=function(){return 0!=(this.rf&a.hk.zhb)};p.zka=function(){return 0!=(this.rf&a.hk.Dhb)};p.lL=function(){return 0!=(this.rf&a.hk.Bhb)};p.C$a=function(){return!1};p.bab=function(){return!1==this.bMb()};p.bMb=function(){return this.vga!=a.l.ac};p.dY=function(){var a=!1;this.pb()==this&&this.pb().R()&&this.pb().R()!=this.dl&&(a=!0);return a};p.mU=function(){if(null!=
this.Oa()){var a=this.caa()?this.caa().rh():"DEFAULT";b.PTa(this.Oa().gb(),a)}};p.eRc=function(a){var c=!1;this.ih()&&this.aLa()&&!this.zka()&&this.vua()&&null!=a&&b.W().SB(this.vua())==a&&(c=!0);return c};p.fRc=function(a){var c=!1;if(this.ih()&&this.aLa()&&!this.C$a()&&!this.zka())if(null==a)c=!0;else for(var d=b.W().SB(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.vua()?(d=d.vua(),a=a!=d?d:null):a=null),d=b.W().SB(a);return c};p.EQ=function(d,e){e===n&&(e=!1);if(!b.W().eY()){var g=
new c.ja(0,0,d.aa(),30),f=d.aa()-4;this.CIa()&&(f-=g.ba());this.QN&&(f-=g.ba());this.Hz.Ab(this.mb());this.Hz.$b(Math.min(f,this.Hz.cKa(this.Hz.mb(),this.Hz.Am().length)+10));this.nq.Na(this.G7a()?this:null);this.nq.jb(g);this.nq.Zb(""==this.ZEa?a.b4:this.ZEa);this.yy.Mb(this.CIa());this.yy.$b(g.ba());this.yy.Mb(null!=this.QN);this.yy.Xc(this.QN);this.yy.jb(new c.ja(this.yy.Yd(),this.yy.qe(),Math.min(this.yy.Ac()?this.yy.Ac().Wa():this.nq.Sa(),this.nq.Sa()-4),Math.min(this.yy.Ac()?this.yy.Ac().Sa():
this.nq.Sa(),this.nq.Sa()-4)));this.WA.Mb(this.CIa());this.WA.jb(new c.ja(this.WA.Yd(),this.WA.qe(),30,29));this.WA.$i(this.pm?this.pm:a.Tb.zcd);e?b.W().ghc(this.WA):b.W().GSc(this.WA);this.nq.R()&&d.Va(d.M()+g.ba());this.Ob()&&this.Qg()}};p.Qe=function(a){this.EQ(a);p.j.Qe.call(this,a)};p.Qg=function(){this.dY()||this.Na(this.OX());this.XYc(this.lL());this.Vuc()&&p.j.Qg.call(this)};p.ij=function(){p.j.ij.call(this);this.EQ(this.Ge())};p.ohb=function(b,c,d){p.j.ohb(b,c,d);d[0]&&this.vP()!=a.Kv.Roa&&
this.G7a()&&(d[0]=this.nq==c||this.Hz==c)};p.ue=function(b){""==b[0]&&(b[0]=a.ILa);""==b[1]&&(b[1]=a.GLa);p.j.ue.call(this,b)};p.sma=function(a){return this.L9(this.qm,a)};p.ihb=function(a){return this.Tta(a)};p.vOa=function(){null!=this.dl&&(null!=this.pb()&&this.ts(this.pb(),a.$.BLa),this.oca(null),this.M$a()||null==this.LQ||this.I4a()||b.fla()!=this.LQ||this.LQ.oA(this.LQ.qD()),this.vPa(null),this.rQa(null),this.sQa(null));this.f$a()&&this.ep()};p.Qya=function(){};p.kza=function(){this.qf.ul(this.Yd());
this.qf.Dk(this.qe());this.ih()&&this.iz(this.O7,this.bW,this.qf,this.qm,this.cW,this.ix)};p.K5=function(d,e,g,f,h){var m=b.Hl();this.dY()&&(m.ul(this.Yd()),m.Dk(this.qe()));d==n&&(d=m.Cb());e==n&&(e=m.Db());g==n&&(g=a.Zi.Vx);f==n&&(f=a.Dg.L_);this.iz(g,null,new c.jd(d,e),h,null,f)};p.iz=function(d,e,g,f,h,m){d==n&&(d=a.Zi.Vx);e==n&&(e=null);g==n&&(g=b.Hl());f==n&&(f=null);h==n&&(h=null);m==n&&(m=a.Dg.L_);if(this.ih()&&this.Y$a()){if(this.bW==e&&this.cW==h&&this.qm==f&&this.O7==d&&this.ix==m){d=b.Ed(g.Cb(),
g.Db(),this.pb().Wa(),this.pb().Sa());b.TXb(this,d);this.OX().jb(new c.ja(0,0,d.aa(),d.ba()));g.ul(d.Q());g.Dk(d.M());this.pb().jb(d);this.H7b(this.oja().AD());this.qf=g;return}var l=this.f$a();this.e5(!1);this.Vl();this.vOa();this.e5(l)}this.O7!=a.Zi.Vx&&this.R()!=this.dl&&this.Na(null);this.rf|=a.hk.Bhb;this.Ekb(!1);null!=this.En()&&(this.oca(f),this.OX(),this.dBc()&&this.ts(this.OX(),a.$.ALa),this.vPa(b.fla()),this.O7=d,this.ix=m,this.EQ(this.Ge()),this.tPc(g,this.M$a()),this.R()==this.OX()?this.ts(this.OX(),
a.$.Maa):this.ts(this,a.$.Maa),this.rQa(e),this.sQa(h),this.J4a()&&this.ix==a.Dg.L_&&this.pb().Se(!0),this.huc())};p.Vl=function(){if(this.ih()){var c=b.W().Uj;c&&c.Pp(this)&&this.ts(c,a.$.fA);b.W().Mkc(this);null!=this.Oa()&&(c=this.Oa().gb(),b.Id[c].Fsa());this.Stc();this.vOa()}else b.W().g1&&(c=b.W().g1,c.Oa()&&c.Oa().KQ&&c==this.qm&&b.W().Ps(c,!1))};p.zhc=function(a){for(var b=this.ga.AD(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,0,c)};p.tPc=function(a,c){this.Oa()&&(c||
(b.W().Wu&&b.W().Wu.$Ec(),b.W().fw(this.vua(),!1,this)),this.uPc(a))};p.uPc=function(c){if(this.sma(c)&&this.pb()){this.pb().Qg();this.pb().dA(!0);c=this.dl;c.FP()||c.ZNa();c=this.Oa().gb();a.tpa+=2;b.Id[c].mEa=a.tpa;b.Cqb(c,b.Id[c].Sf());b.Id[c].sna();var d=b.Id[c].pa.Js?b.Id[c].pa.Js.Oa():null;d&&d.G.parentElement!=document.body&&(null!=d.G.parentElement&&d.G.parentElement.removeChild(d.G),d.G.style.zIndex=b.Id[c].mEa-1,document.body.appendChild(d.G))}};b.TXb=function(d,e){switch(d.O7){case a.Zi.$Na:var g=
b.PD(),g=new c.ja(g.Yd()-d.ga.Si(),g.qe()-d.ga.bk(),g.Wa()+(d.ga.Si()+d.ga.ak()),g.Sa()+(d.ga.bk()+d.ga.Dl()));e.ds(g);break;case a.Zi.I4:var g=b.PD(),f=0,h=0,f=(g.aa()-e.Wa())/2,h=(g.ba()-e.Sa())/2;e.Bb(f,h);d.dY()&&e.ds(d.R().Aza(e));break;case a.Zi.mPc:g=b.PD();f=(g.aa()-e.Wa())/2;h=g.ua-e.Sa();e.Bb(f,h);d.dY()&&e.ds(d.R().Aza(e));break;case a.Zi.nPc:g=b.PD();f=(g.aa()-e.Wa())/2;e.Bb(f,0);d.dY()&&e.ds(d.R().Aza(e));break;case a.Zi.L1b:g=b.PD();h=(g.ba()-e.Sa())/2;f=g.va-e.Wa();e.Bb(f,h);d.dY()&&
e.ds(d.R().Aza(e));break;case a.Zi.K1b:g=b.PD();h=(g.ba()-e.Sa())/2;e.Bb(0,h);d.dY()&&e.ds(d.R().Aza(e));break;default:g=b.PD(),e.va>g.va&&e.Bb(Math.max(0,g.va-e.aa()),e.M()),e.ua>g.ua&&e.Bb(e.Q(),Math.max(0,g.ua-e.ba())),e.Q()<g.Q()&&e.Bb(0,e.M()),e.M()<g.M()&&e.Bb(e.Q(),0)}};p.fNc=function(){b.W();this.Js=new c.em;this.Js.Ga(this,a.K.mZa,this.rqc);this.Js.Ga(this,a.K.gc,this.sqc);this.Js.Re(1);this.Js.Ua(0);this.Js.Ica(1);this.Js.Va(0);this.Js.Mb(!1);this.VXa=new c.ig;this.e8=new c.ob;this.e8.zd(this.VXa)};
p.H7b=function(a){var d=b.W().Qr;this.Js||this.fNc();if(!this.Js.Ob()){this.VXa.Ad(this.vga);this.VXa.kg(this.UXa);this.Js.tb(this.bMb()?this.e8:null);for(var e=0;e<a.length;e++)this.Js.Ao(a[e]);null==this.Js.Xf()?this.Js.Na(null):(this.Js.Ic(d),this.Js.Re(1),this.Js.QO())}this.Js.jb(new c.ja(0,0,d.Wa(),d.Sa()))};p.bFc=function(){this.Js.nb()&&this.Js.ro()};p.zk=function(c){var d=this.Oa().gb();a.tpa+=2;b.Id[d].mEa=a.tpa;b.Cqb(d,b.Id[d].Sf());p.j.zk.call(this,c)};p.L9=function(d,g){var f=!0,h=e.Rb(),
m=this.pb().Wa(),l=this.pb().Sa();h.Vb("CONTEXT",d);h.$A("LEFT",g.Cb());h.$A("TOP",g.Db());h.$A("WIDTH",m);h.$A("HEIGHT",l);h.gO("TRANSITION",this.ix,a.Dg.v);h.ef("CONTINUE",!0);this.Ha(a.K.lA,h);g.ul(h.aja("LEFT"));g.Dk(h.aja("TOP"));f=h.Rf("CONTINUE");m=m==h.aja("WIDTH")?this.pb().Wa():h.aja("WIDTH");l=l==h.aja("HEIGHT")?this.pb().Sa():h.aja("HEIGHT");m=new c.ja(g.Cb(),g.Db(),m,l);b.TXb(this,m);this.OX().jb(new c.ja(0,0,m.aa(),m.ba()));g.ul(m.Q());g.Dk(m.M());this.pb().jb(m);this.ix=h.H5a("TRANSITION",
a.Dg.v);h.mc();this.qf=g;return f};p.Tta=function(b){var c=!1,c=e.Rb();c.ef("IMMEDIATE",b);c.ef("CLOSEPOPUP",!0);this.Ha(a.K.NW,c);b||this.ix!=a.Dg.L_?c=!0:(c=c.Rf("CLOSEPOPUP"),c||(this.rf|=a.hk.Dhb));return c};p.Stc=function(){this.Ha(a.K.tha);this.rf&=~a.hk.Dhb;this.rf&=~a.hk.Bhb;this.Ekb(!0);this.dY()&&this.R().qb()};p.huc=function(){this.Ha(a.K.PNa)};p.rqc=function(){this.Js.nb()||(this.Js.Na(null),this.Qya())};p.sqc=function(){this.C$a()&&this.aLa()&&this.Vl()};p.Znc=function(){this.EQ(this.Ge(),
!0)};p.$nc=function(){this.EQ(this.Ge())};p.Ync=function(a,c){b.W().Ps(this,!1);c.Dj("HANDLED",!0)};p.aqc=function(){};p.HBb=function(b,c){switch(c.Ya){case a.f.rb:this.oca(null)}};p.Zpc=function(b,c){switch(c.Ya){case a.f.rb:this.rQa(null)}};p.$pc=function(b,c){switch(c.Ya){case a.f.rb:this.sQa(null)}};p.Fnc=function(b,c){switch(c.Ya){case a.f.rb:this.vPa(null)}};p.T1a=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.nca(null)}};p.DDb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.Xkb(null)}};
p.mta=p[a.$.Ika]=function(){this.lL()&&this.kza()};p.EF=p[a.$.cz]=function(a){p.j.EF.call(this,a);this.EQ(this.Ge())};p.rr=p[a.$.dG]=function(a){p.j.rr.call(this,a);this.EQ(this.Ge())};e.ad(c.Aw,"PRIM_PPNL",{Pa:{CloseOnClick:{a:p.oIb,g:function(a){this.i5(e.ya(a))}},AutoClose:{a:p.I4a,g:function(a){this.wPa(e.ya(a))}},AutoFocus:{a:p.J4a,g:function(a){this.c5b(e.ya(a))}},TitleBar:{a:p.G7a,g:function(a){this.Wkb(e.ya(a))}},ShroudColor:{a:function(){return this.bab()?e.Kd:b.ag(this.vga)},g:function(a){a===
e.Kd?this.H0c():this.hAa(b.$f(e.na(a)))}},ShroudOpacity:{a:p.NBc,g:function(a){this.V6b(e.L(a))}},CloseButton:{a:p.CIa,g:function(a){this.v5b(e.ya(a))}},CloseImage:{a:p.nIb,g:p.nca},TitleImage:{a:p.JCc,g:p.Xkb},ShroudStyle:{a:p.OBc,g:p.W6b},ShroudStyles:{a:p.PBc},TitleBarThemeDrawStyle:{a:p.ICc,g:function(a){this.B1c(e.na(a))}},IsOpen:{a:p.ih}},jc:{ShowPopup:function(b,c,d,g,f){this.K5(b,c,d?e.qa(d,a.Zi.OMc):d,g?e.qa(g,a.Dg.v):g,f)},ClosePopup:p.Vl}});c.beb=function(d){t.w.call(this,d);this.qd=new c.ja(0,
0,300,30);this.ora=a.bma.oPc;this.SDa=new c.wv;this.h0=this.AJ=this.zJ=null;this.TQ=[];this.cXa=null;b.Jn(this.SDa);b.$m(this.SDa);this.rl(this.SDa);this.tf(!1);this.h0=new c.SMa;this.h0.Rza(a.DI.x0b);this.h0.Ga(this,a.K.lA,this.doc);this.zJ=new c.rt;this.zJ.Na(this);this.zJ.jb(new c.ja);this.zJ.Ga(this,a.K.gc,this.eoc);this.zJ.JZ();this.cXa=new c.PXb(this)};var t=c.u(c.beb,c.em);t.xb=function(){t.j.xb.call(this)};t.U=function(){t.j.U.call(this);b.la(this.cXa);this.cXa=null};t.iwc=function(){return this.AJ};
t.x5b=function(b){this.AJ!=b&&(null!=this.AJ&&(this.AJ.Ba(this,this.DBb),this.AJ.vb()),this.AJ=b,null!=this.AJ&&(this.AJ.Aa(),this.AJ.Ea(this,this.DBb)),this.qb(),this.m(a.f.i))};t.D0c=function(b){b=this.rf&~a.bma.Ngb|(b?a.bma.Ngb:0);this.ora!=b&&(this.ora=b,this.m(a.f.i))};t.T6a=function(){return 0!=(this.ora&a.bma.Ngb)};t.GYc=function(b){this.DIa()!=b&&(this.ora=this.ora&~a.bma.M1b|b,this.qb(),this.dA(),this.l2b(this.Ge()),this.fa(a.f.i))};t.DIa=function(){return this.ora&a.bma.M1b};t.p5a=function(){var b=
null;switch(this.DIa()){case a.vK.t0a:case a.vK.r0a:b=t.j.p5a.call(this);break;case a.vK.n0a:e.Fb("PRIM_PCOL"),b=new c.wdb(this.h0),b=new c.HY(b)}return b};t.ue=function(b){""==b[0]&&(b[0]=a.iRb);""==b[1]&&(b[1]=a.hKc);t.j.ue.call(this,b)};t.jhb=function(){this.rl(this.SDa)};t.Cw=function(c,d){t.j.Cw.call(this,c,d);this.jhb();b.QXb(this,this.SDa,a.za.kj,a.sa.xF,a.ka.oj,this.S1a)};t.Qe=function(a){t.j.Qe.call(this,a);this.l2b(a)};t.l2b=function(d){switch(this.DIa()){case a.vK.t0a:for(this.zJ.Mb(!1);0<
this.TQ.length;)this.TQ[0].ep();break;case a.vK.r0a:for(var e=this.TQ.length,g=0,f=null,h=this.tn,m=h.length-1;0<=m&&null!=(f=h[m]);m--)g=Math.max(g,f.Oc().va),f.Ys()>d.va&&(b.OXb(this,f),e++);h=this.TQ;for(m=0;m<h.length&&null!=(f=h[m]);m++)g+f.$a.Wa()<d.va?(f.ep(),m--,e--):f.ea().Re(m+1);if(0<e)this.zJ.$i(this.AJ?this.AJ:a.Tb.Afb),this.zJ.jb(new c.ja(d.va-(d.ba()+2),0,d.ba(),d.ba())),this.zJ.Mb(!0),this.h0.sOa();else for(this.zJ.Mb(!1);0<this.TQ.length;)this.TQ[0].ep();break;case a.vK.n0a:for(;0<
this.tn.length;)b.OXb(this,this.tn[this.tn.length-1]);this.zJ.$i(this.AJ?this.AJ:a.Tb.Afb);this.zJ.jb(new c.ja(d.va-(d.ba()+2),0,d.ba(),d.ba()));this.zJ.Mb(!0);this.h0.sOa()}this.Ob()&&this.Qg()};b.QXb=function(c,d,e,g,f,h){for(var m=null,l=c.tn,n=1,p=0;p<l.length&&null!=(m=l[p]);p++,n++){var t=d.Pe(m);t||(t=b.Pc(d,m,d.Cc(0),d.Gc(0),1,1),m.Ga(c,a.K.SY,h));t.Fh(e);t.Hb(g);t.Xb(f)}};t.DBb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.x5b(null);break;case a.f.i:this.qb()}};t.doc=function(b,
c){this.Ha(a.K.lA,c)};t.eoc=function(b,d){this.h0.iz(a.Zi.Vx,this,new c.jd(this.is()+this.Wa()-this.h0.Wa(),this.ls()+this.Sa()),this);d.Dj("HANDLED",!0)};t.S1a=function(a){this.T6a()&&(a=a instanceof c.cba?a:null)&&a.wB()&&!a.wB().ih()&&(a.Sq(),this.cXa.kh())};e.kb(c.beb,"PRIM_PPNL","MenuBar",{Pa:{CollapsedMenuImage:{a:t.iwc,g:t.x5b},ShowOnHover:{a:t.T6a,g:function(a){this.D0c(e.ya(a))}},CollapseStyle:{a:function(){return e.ta(this.DIa(),a.vK.v)},g:function(b){this.GYc(e.qa(b,a.vK.v))}}}});c.PXb=
function(a){f.w.call(this,500);this.JR=a};var f=c.u(c.PXb,c.MY);f.$S=function(){if(this.JR.T6a()){var a=!1,c=!1,d=b.W().Ogb(b.Hl());d?a=!0:(d=b.aU(b.Hl()))&&(d==this.JR||d.Pp(this.JR))&&(a=!0);!a&&(d=b.W().SB(b.TP()))&&(c=a=!0);a||(this.JR.fw(),c=!0);c&&this.bi()}return!1};c.SMa=function(){h.w.call(this);this.qd=new c.ja(0,0,150,150);this.Lk=new c.wv;this.lN=a.Bfb.iya;b.Jn(this.Lk);b.$m(this.Lk);this.rl(this.Lk)};var h=c.u(c.SMa,c.Aw);h.xb=function(){h.j.xb.call(this)};h.U=function(){h.j.U.call(this)};
h.Rza=function(b){this.Xua()!=b&&(this.lN=this.lN&~a.Bfb.B0b|b,this.qb(),this.fa(a.f.i))};h.Xua=function(){return this.lN&a.Bfb.B0b};h.ue=function(b){""==b[0]&&(b[0]=a.kRb);""==b[1]&&(b[1]=a.iKc);h.j.ue.call(this,b)};h.jhb=function(){this.rl(this.Lk);this.i5(!0)};h.Cw=function(c,d){h.j.Cw.call(this,c,d);this.jhb();b.QXb(this,this.Lk,a.za.jj,a.sa.bB,a.ka.ci,this.S1a)};h.sOa=function(){if(this.Xua()!=a.DI.u4){for(var b=null,d=this.tn,e=[!0,2,2,0,0],g=0;g<d.length&&null!=(b=d[g]);g++){var f=b instanceof
c.cba?b:null;switch(this.Xua()){case a.DI.Jla:f?f.A2b(e):e[2]+=b.nb()?b.Sa():0;break;case a.DI.x0b:e[1]=Math.max(e[1],b.Wa()),e[2]+=b.nb()?b.Sa():0}}for(g=0;g<d.length&&null!=(b=d[g]);g++)switch(this.Xua()){case a.DI.Jla:(f=b instanceof c.cba?b:null)&&f.$b(e[1])}this.$b(e[1]);this.vc(e[2])}};h.sma=function(a){this.sOa();return h.j.sma.call(this,a)};h.Qe=function(a){h.j.Qe.call(this,a)};h.KBb=h[a.$.Pab]=function(a){h.j.KBb.call(this,a);this.sOa()};h.S1a=function(a){(a=a instanceof c.cba?a:null)&&a.Sq()};
e.kb(c.SMa,"PRIM_PPNL","Menu",{Pa:{MenuSizing:{a:function(){return e.ta(this.Xua(),a.DI.v)},g:function(b){this.Rza(e.qa(b,a.DI.v))}}}});c.RXb=function(){l.w.call(this)};var l=c.u(c.RXb,c.zI);l.wPb=function(){return!0};l.ue=function(){};c.cba=function(){m.w.call(this);this.qd=new c.ja(0,0,100,25);this.x7=a.gU.bya;this.Wr=0;this.KWa=this.Ttb=this.vm=this.dN=this.Y0=this.zR=this.eK=null;this.Z0=new c.wv;this.Yu=0;this.qH=a.ee.XY;b.Jn(this.Z0);b.$m(this.Z0);this.rl(this.Z0);this.SPa(!0);this.dN=new c.ob;
this.dN.On(a.l.Ld);this.dN.Zk(a.l.Ld);this.dN.hn(1);this.dN.Pn(1);this.dN.Jl(1);this.dN.Kl(1);this.Y0=new c.rt;this.Y0.Na(this);this.Y0.jb(new c.ja(0,0,18,18));this.Y0.tb(this.dN);this.vm=new c.RXb;this.vm.Na(this);this.vm.Le(2);this.vm.ve(2);this.Ttb=b.Pc(this.Z0,this.vm,this.Z0.Cc(0),this.Z0.Gc(0),1,1);this.KWa=b.Pc(this.Z0,this.Y0,this.Z0.Cc(0),this.Z0.Gc(0),1,1)};var m=c.u(c.cba,c.em);m.xb=function(){m.j.xb.call(this)};m.U=function(){m.j.U.call(this);this.aQa(null)};m.wB=function(){return this.vm.wB()};
m.GZ=function(b){this.wB()!=b&&(this.vm.wB()&&this.vm.wB().ru(this,a.K.lA,this.yCb),this.vm.GZ(b),this.vm.wB()&&this.vm.wB().Ga(this,a.K.lA,this.yCb),this.m(a.f.i))};m.j3=function(){return this.vm.j3()};m.Tyc=function(){return this.zR};m.aQa=function(b){this.zR!=b&&(null!=this.zR&&(this.zR.Ba(this,this.xCb),this.zR.vb()),this.zR=b,null!=this.zR&&(this.zR.Aa(),this.zR.Ea(this,this.xCb)),this.$t(),this.m(a.f.i))};m.pw=function(){return this.Yu};m.wu=function(b){b!=this.Yu&&(this.Yu=b,this.$t(),this.fa(a.f.i))};
m.Qq=function(b){this.qH!=b&&(this.qH=b,this.$t(),this.fa(a.f.i))};m.We=function(){return this.vm.We()};m.He=function(b){this.We()!=b&&(this.vm.He(b),this.m(a.f.i))};m.$e=function(){return this.vm.$e()};m.Le=function(b){this.$e()!=b&&(this.vm.Le(b),this.m(a.f.i))};m.Tf=function(){return this.vm.Tf()};m.ve=function(b){this.Tf()!=b&&(this.vm.ve(b),this.m(a.f.i))};m.gg=function(){return this.vm.gg()};m.zf=function(b){this.gg()!=b&&(this.vm.zf(b),this.m(a.f.i))};m.Fl=function(){return this.qH};m.qja=
function(){return 0!=(this.x7&a.gU.mba)?!0:!1};m.BQa=function(b){b=this.x7&~a.gU.mba|(b?a.gU.mba:0);this.x7!=b&&(this.x7=b,this.$t(),this.fa(a.f.i))};m.eg=function(){return 0!=(this.x7&a.gU.lba)?!0:!1};m.Eh=function(b){var d=this.rD();if(b&&0!=d&&null!=this.R())for(var e=null,g=this.R().Ni,f=0;f<g.length&&null!=(e=g[f]);f++)if(e instanceof c.cba){var h=e;h!=this&&h.rD()==d&&h.Eh(!1)}b=this.x7&~a.gU.lba|(b?a.gU.lba:0);this.x7!=b&&(this.x7=b,this.$t(),this.fa(a.f.i))};m.rD=function(){return this.Wr};
m.wZ=function(b){this.Wr!=b&&(this.Wr=b,this.$t(),this.fa(a.f.i))};m.a7a=function(){return this.eK};m.QQa=function(a){this.eK!=a&&(this.eK=a)};m.ue=function(b){""==b[0]&&(b[0]=a.hRb);m.j.ue.call(this,b)};m.Sq=function(){var a=b.W().SB(this);(null==a||a.ih())&&this.wB()&&!this.wB().ih()&&this.vm.d$b(!0)};m.cwa=function(){};m.A2b=function(b){var d=null,e=this.Lb&&this.Lb instanceof c.beb?this.Lb:null,g=this.Yu;this.eg()?(d=this.qja()?a.Tb.s0b:a.Tb.r0b,this.dN.On(a.l.OU),this.dN.Zk(a.l.S5)):(this.dN.On(a.l.Ld),
this.dN.Zk(a.l.Ld));this.zR&&(d=this.zR);d&&0==g&&(g=Math.min(this.Sa(),d.Sa()));this.vm.Zb(a.KKc);this.vm.bM(!1);this.vm.Qq(this.Fl());this.vm.jQa(e?a.QD.cya:a.QD.dya);this.vm.dkb(e?a.bn.u4:a.bn.Kla);this.vm.xG(a.Dt.rK);this.vm.ina(!1);this.vm.Ab(this.mb());this.vm.Vn(a.mh.Yq);this.Y0.$i(d);this.Y0.jb(new c.ja(this.Y0.Yd(),this.Y0.qe(),g,g));this.Ttb.Xb(a.ka.uf);this.Ttb.Le(e?0:g+2);this.KWa.Xb(a.ka.Sd);this.KWa.Hb(a.sa.yl);this.KWa.Le(e?0:2);this.vm.Ak(!1,!0);var f=this.vm.nX(),h=this.vm.Eia();
e?(f+=g+4,d&&(f+=g+4)):(f+=60,h+=10);!0==b[0]&&(this.vc(h),b[1]=Math.max(b[1],f),b[2]+=this.nb()?h:0,b[3]+=f,b[4]+=h)};m.Cw=function(a,b){m.j.Cw.call(this,a,b);this.A2b([!1,0,0])};m.of=function(a){var d=!1;this.rD()&&this.Eh(!0);d=m.j.of.call(this,a);if(!d){a=b.W().bx;for(var e=null,g=0;g<a.length&&null!=(e=a[g]);g++)e instanceof c.SMa&&b.W().Ps(e,!1)}return d};m.yCb=function(a,b){b.j0c(this)};m.xCb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.aQa(null);break;case a.f.i:this.$t()}};e.kb(c.cba,
"PRIM_PPNL","MenuItem",{Pa:{Checked:{a:m.eg,g:function(a){this.Eh(e.ya(a))}},MenuPopup:{a:m.wB,g:m.GZ},RadioItem:{a:m.qja,g:function(a){this.BQa(e.ya(a))}},GroupIndex:{a:m.rD,g:function(a){this.wZ(e.L(a))}},Image:{a:m.Tyc,g:m.aQa},ImageHeight:{a:m.pw,g:function(a){this.wu(e.L(a))}},MarginLeft:{a:m.$e,g:function(a){this.Le(e.L(a))}},MarginTop:{a:m.We,g:function(a){this.He(e.L(a))}},MarginBottom:{a:m.gg,g:function(a){this.zf(e.L(a))}},MarginRight:{a:m.Tf,g:function(a){this.ve(e.L(a))}},Alignment:{a:function(){return e.ta(this.Fl(),
a.ee.sK)},g:function(b){this.Qq(e.qa(b,a.ee.sK))}}},jc:{ShowMenu:m.Sq,HideMenu:m.cwa}});c.NXb=function(a,b,c){d.w.call(this);this.JR=a;this.$a=b;this.odd=b.Oc();-1==c&&(c=this.JR.TQ.length);this.JR.TQ.splice(c,0,this);this.$a.Ea(this,this.rq);this.$a.Na(a.h0)};var d=c.u(c.NXb,c.ld);d.U=function(){var a=this.JR.tn.length+1;this.$a.Ba(this,this.rq);this.JR.TQ.splice(this.JR.TQ.indexOf(this),1);this.$a.Ic(this.JR);this.$a.Re(a);this.$a.jb(this.odd);d.j.U.call(this)};d.ea=function(){return this.$a};b.OXb=
function(a,b){-1==a.TQ.indexOf(b)&&new c.NXb(a,b,0)};d.Yl=function(b,c){switch(c.Ya){case a.f.rb:this.ep()}};c.o_b=function(a){g.w.call(this,a);this.KQ=!1;this.oW=null;this.Tv="";this.mEa=null};var g=c.u(c.o_b,c.r4);g.YLb=function(){var b=!1,c=e.ta(this.pa.ix,a.Dg.TFb);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};g.bf=function(a){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);this.oW=document.createElement("div");
this.oW.setAttribute("LANSAHandle",this.cc);return this.G};g.Yoa=function(){this.Fsa()};g.Dpb=function(b){this.Tv=e.ta(this.pa.ix,a.Dg.TFb);null!=this.mEa&&(b=this.mEa);9999<b&&(""==this.Tv?g.j.Dpb.call(this,b):this.oW.style.zIndex=b)};g.Wq=function(a,c,d,e){a=b.Ed(a,c,d,e);this.pa.dY()&&a.ds(this.pa.R().Iyb(a));g.j.Wq.call(this,a.Q(),a.M(),a.aa(),a.ba())};g.sna=function(){var a=this,c=this.KQ;this.pa.H7b(this.pa.oja().AD());""==this.Tv?(this.KQ=!0,c||document.body.appendChild(this.G)):this.KQ||(b.W().Qr.Oa().G.classList.add("container"),
this.oW.setAttribute("class","md-modal "+this.Tv),c=b.Id[this.pa.pb().Oa().gb()],c.G.style.opacity="",c.G.setAttribute("class","md-content"),this.oW.appendChild(this.G),document.body.insertBefore(this.oW,b.W().Qr.Oa().G),this.YLb()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25),setTimeout(function(){a.oW.classList.add("md-show");setTimeout(function(){if(a.pa.J4a()){var c=b.TP();c&&c.Pp(a.pa)||a.pa.pb().Se(!0)}},300)},100),this.KQ=!0)};g.Fsa=function(){this.KQ&&
(this.oW.classList.contains("md-show")?this.y3b():(this.KQ=!1,this.YLb()&&document.documentElement.classList.remove("md-perspective"),""==this.Tv?document.body.removeChild(this.G):(document.body.removeChild(this.oW),b.W().Qr.Oa().G.classList.remove("container"))),this.pa.bFc())};g.y3b=function(){var a=this;this.oW.classList.remove("md-show");setTimeout(function(){a.pa.Vl()},500)};g.eFd=function(){this.y3b()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
