window.LANSA.addSrc("ver",function(e,c,a,b,n){c.FRb=function(){s.w.call(this);this.qf=new c.jd;this.Mqa=this.$a=null};var s=c.u(c.FRb,c.ld);s.Byc=function(){return document.hasFocus()};s.W2c=function(a,t,f){var h=e.gd("PRIM_VS","Style"),l=null,m=null;t===n&&(t=0);f===n&&(f=0);if(a){if(0==t&&0==f)a.Ak(!0),l=a.ga;else if(0!=t){var d=a.iB(new c.ja,null);t=a.C7.Nb[t-1];a.Af().Oa().ygb(d,t,a.Jfa,null,null,t.gb());l=t.ov();if(0!=f&&(f=a.O1a(f-1)))for(var g in t.gb().Yt)if(m=t.gb().Yt[g],m.pn.zb==f){a.Af().Oa().wgb(d,
m.pn,m.pn.baa(),m.pn.td.LJa(),m.pn.zb.lva(),null);l=m.pn.baa();break}b.la(d)}l&&(h.Zk(l.ii),h.On(l.kX()),h.ai(l.ny),h.Fw(l.Ty()),h.Rh(l.Ax()),h.zd(l.lw()),h.jg(l.mD()),h.Tn(l.cu()),h.Ev(l.vx()),h.Fv(l.wx()),h.Cv(l.tx()),h.Dv(l.ux()),h.hn(l.Si()),h.Pn(l.bk()),h.Jl(l.Dl()),h.Kl(l.ak()),h.fM(l.Xd().xx()),h.vt(l.Xd().Sa()),h.pA(l.Xd().ti()),h.$D(l.Xd().rx()),h.lM(l.Xd().Cx()),h.oQ(l.Xd().SF()),h.sQ(l.Xd().VF()));m&&(a.Af().Oa().Ij.Dp&&h.Rh(a.Af().Oa().Ij.Dp),a.Af().Oa().Ij.pj&&h.zd(a.Af().Oa().Ij.pj))}return h};
s.q$c=function(a,b){return a.Y3a(b,[[]])};s.Elc=function(){null.wjd()};s.Hkc=function(a,e,f){var h;f===n&&(f=1);h===n&&(h=!0);a=new c.jd(a,e);if((e=b.aU(a))&&e.ae()){var l=e.Qh(a),m=new c.nt(e,l,a,1),d=new c.nt(e,l,a,1),g=new c.nt(e,l,a,2);b.oC(a.Cb(),a.Db(),l.Cb(),l.Db());h?(h=b.W(),e.zk(m),null==h.Uj?e.Mn(d):(h=h.Uj.gb(),b.Gqb(null,h,l.Cb(),l.Db(),a.Cb(),a.Db())),2==f&&(g=new c.nt(e,l,a,2),e.zk(g))):(e.nU(m),e.rma(d));b.la(m);b.la(g);b.la(d)}};s.N$c=function(a,e){var f=new c.jd(a,e),h=b.aU(f);if(h&&
h.ae()){var l=h.Qh(f),m=new c.nt(h,l,f,1),d=new c.nt(h,l,f,1),g=new c.nt(h,l,f,1),n=!1;b.oC(f.Cb(),f.Db(),l.Cb(),l.Db());h.Tya(l,h,!1);h.Sya(g);n=g.Ug;n||(h.zk(m),h.Mn(d));b.la(m);b.la(d);b.la(g)}};s.dFc=function(a,e){var f=new c.jd(a,e),h=b.aU(f);if(h&&h.ae()){var l=h.Qh(f);for(b.oC(f.Cb(),f.Db(),l.Cb(),l.Db());h;)l=h.Qh(f),b.Fcc(null,h.gb(),l.Cb(),l.Db(),f.Cb(),f.Db()),h=h.R()}};s.bZc=function(a,e){var f=new c.jd(a,e),h=b.aU(f);h&&h.ae()&&(h=h.Qh(f),b.oC(f.Cb(),f.Db(),h.Cb(),h.Db()))};s.HZc=function(a,
e){(this.Mqa=b.aU(new c.jd(a,e)))&&document.hasFocus()&&(b.Dqb(this.Mqa.gb()),this.Mqa=null)};s.EIc=function(a,c){if(""!=a||0!=c){var e=0==c?a.charCodeAt(0):c,h;if(document.hasFocus())h=b.Eqb();else if(this.Mqa)h=this.Mqa.gb();else return;b.Ccc(null,h,e);""!=a&&b.Dcc(null,h,a,a.charCodeAt(0));b.Ecc(null,h,e)}};s.uNc=function(a,e){this.qf=new c.jd(this.qf.Cb()+(0<a?1:0==a?0:-1),this.qf.Db()+(0<e?1:0==e?0:-1));if(this.$a){var f=this.$a.Qh(this.qf);b.oC(this.qf.Cb(),this.qf.Db(),f.Cb(),f.Db());b.ZXb(this.$a,
f,this.qf)}};s.OLc=function(a,e,f){f===n&&(f=1);this.qf=new c.jd(a,e);if(this.$a=b.aU(this.qf))a=!1,e=this.$a.Qh(this.qf),this.$a.Nf.Ik&&(new c.ja(this.$a.Nf.Ik.ff,this.$a.Nf.Ik.vf,this.$a.Nf.Ik.Uc,this.$a.Nf.Ik.ed)).$d(e)&&(this.$a.Nf.Ik.Oya(null),a=this.$a.Nf.Ik.eF),a||(b.oC(this.qf.Cb(),this.qf.Db(),e.Cb(),e.Db()),b.XXb(this.$a,e,this.qf,f))};s.PLc=function(){if(this.$a){var a=!1,e=this.$a.Qh(this.qf);this.$a.Nf.Ik&&(new c.ja(this.$a.Nf.Ik.ff,this.$a.Nf.Ik.vf,this.$a.Nf.Ik.Uc,this.$a.Nf.Ik.ed)).$d(e)&&
(this.$a.Nf.Ik.Pya(null),a=this.$a.Nf.Ik.eF);a||(b.oC(this.qf.Cb(),this.qf.Db(),e.Cb(),e.Db()),b.YXb(this.$a,e,this.qf,1));this.$a=null}};s.sUc=function(a,e){this.qf=new c.jd(a,e);if(this.$a=b.aU(this.qf)){var f=this.$a.Qh(this.qf);b.oC(this.qf.Cb(),this.qf.Db(),f.Cb(),f.Db());b.$Xb(this.$a,f,this.qf,1)}};s.tUc=function(){if(this.$a){var a=this.$a.Qh(this.qf);b.oC(this.qf.Cb(),this.qf.Db(),a.Cb(),a.Db());b.aYb(this.$a,a,this.qf,1);this.$a=null}};e.kb(c.FRb,"PRIM_VER","Debugger",{Pa:{HasFocus:{a:s.Byc}},
jc:{Crash:function(){this.Elc()},Click:function(a,b,c){this.Hkc(e.L(a),e.L(b),c===n?1:e.L(c))},Touch:function(a,b){this.N$c(e.L(a),e.L(b))},Hover:function(a,b){this.dFc(e.L(a),e.L(b))},SetCursorPos:function(a,b){this.bZc(e.L(a),e.L(b))},SetFocus:function(a,b){this.HZc(a,b)},KeyPress:function(a,b){this.EIc(e.na(a),b===n?0:e.L(b))},MouseMove:function(a,b){this.uNc(a,b)},LeftMouseDown:function(a,b,c){this.OLc(e.L(a),e.L(b),c===n?1:e.L(c))},LeftMouseUp:function(){this.PLc()},RightMouseDown:function(a,
b){this.sUc(a,b)},RightMouseUp:function(){this.tUc()},StyleSnapshot:function(a,b,c){return this.W2c(a,b===n?0:e.L(b),c===n?0:e.L(c))},ThemeDrawStyle:function(a,b){return this.q$c(a,e.na(b))}}})});
