window.LANSA.addSrc("web",function(e,c,a,b,n){e.Fb("PRIM_LABL");var s=null,p=null;a.MI={Fib:0,t4b:1,u4b:2,s4b:3};a.MI.v={INLINE:a.MI.Fib,LEFT:a.MI.t4b,RIGHT:a.MI.u4b,CENTER:a.MI.s4b};a.ND={OHa:0,KFb:1,OFb:2,PFb:3,RFb:4,p3a:5};a.ND.v={NONE:a.ND.OHa,NOTLOADED:a.ND.KFb,PERMISSIONDENIED:a.ND.OFb,POSITIONUNAVAILABLE:a.ND.PFb,TIMEOUT:a.ND.RFb,UNKNOWNERROR:a.ND.p3a};a.CS={zyb:0,xyb:1,Ayb:2,yyb:4};a.CS.v={NONE:a.CS.zyb,ERROR:a.CS.xyb,WARNING:a.CS.Ayb,INFORMATION:a.CS.yyb};c.Beb=function(){t.w.call(this);
this.Za=[]};var t=c.u(c.Beb,c.ld);t.U=function(){t.j.U.call(this)};t.pc=function(){return this.Za.length};t.be=function(a){return this.Za[a-1]};t.RH=function(a){for(var c=null,d=0;d<this.Za.length;d++){var e=this.Za[d];if(b.OB(e.Ql,a)){c=e;break}}return c};e.kb(c.Beb,"PRIM_WEB","URLParameters",{Pa:{Item:{a:function(a){return this.RH(e.na(a))},iw:"na"},ItemCount:{a:t.pc}},Uf:{Pf:"Item"},op:{Co:function(a){return this.be(e.L(a))},rv:t.pc}});c.Aeb=function(){f.w.call(this);this.ab=this.Ql=""};var f=
c.u(c.Aeb,c.ld);f.rh=function(){return this.Ql.toUpperCase()};f.Ja=function(){return this.ab};e.kb(c.Aeb,"PRIM_WEB","URLParameter",{Pa:{Name:{a:f.rh},Value:{a:f.Ja}}});c.yeb=function(){h.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(s=localStorage)}catch(c){}this.hq=null};var h=c.u(c.yeb,c.ld);h.U=function(){h.j.U.call(this)};h.L4a=function(){return null!=s};h.pc=function(){return this.jP().length};h.be=function(a){return this.jP()[a-
1]};h.RH=function(a){for(var b=null,c=this.jP(),d=0;d<c.length;d++){var e=c[d];if(e.Ql==a){b=e;break}}return b};h.jP=function(){if(null==this.hq&&(this.hq=[],s))for(var a=0;a<s.length;a++){var b=s.key(a);""!=b&&s[b]!=n&&this.hq.push(new c.aNa(b))}return this.hq};h.iza=function(){this.hq=null};h.Lg=function(a,b){var d=this.jP(),e=this.RH(a);null==e&&(e=new c.aNa(a),d.push(e));e.Xa(b)||d.splice(d.indexOf(e),1)};h.vs=function(c){var d=this.jP(),e=this.RH(c);null!=e&&(s.removeItem(c),d.splice(d.indexOf(e),
1),b.Eo().M9(a.oE.vna))};h.un=function(){s&&(s.clear(),this.iza(),b.Eo().M9(a.oE.vna))};e.kb(c.yeb,"PRIM_WEB","LocalStorage",{Pa:{Available:{a:h.L4a},Item:{a:function(a){return this.RH(e.na(a))},iw:"na"},ItemCount:{a:h.pc}},jc:{Add:h.Lg,Remove:h.vs,Clear:h.un},Uf:{Pf:"Item"},op:{Co:function(a){return this.be(e.L(a))},rv:h.pc}});c.aNa=function(a){l.w.call(this);this.Ql=a};var l=c.u(c.aNa,c.ld);l.rh=function(){return this.Ql};l.Ja=function(){var a="";s&&(a=s[this.Ql],a===n&&(a=""));return a};l.Xa=function(c){var d=
!0;try{s[this.Ql]=c,b.Eo().M9(a.oE.vna)}catch(e){b.Eo().vHb(a.oE.vna),d=!1}return d};e.kb(c.aNa,"PRIM_WEB","LocalStorageItem",{Pa:{Name:{a:l.rh},Value:{a:l.Ja,g:function(a){this.Xa(e.na(a))}}},Uf:{Pf:"Value"}});c.zeb=function(){m.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(p=sessionStorage)}catch(c){}this.hq=null};var m=c.u(c.zeb,c.ld);m.U=function(){m.j.U.call(this)};m.L4a=function(){return null!=p};m.pc=
function(){return this.jP().length};m.be=function(a){return this.jP()[a-1]};m.RH=function(a){for(var b=null,c=this.jP(),d=0;d<c.length;d++){var e=c[d];if(e.Ql==a){b=e;break}}return b};m.jP=function(){if(null==this.hq&&(this.hq=[],p))for(var a=0;a<p.length;a++){var b=p.key(a);""!=b&&p[b]!=n&&this.hq.push(new c.bNa(b))}return this.hq};m.iza=function(){this.hq=null};m.Lg=function(a,b){var d=this.jP(),e=this.RH(a);null==e&&(e=new c.bNa(a),d.push(e));e.Xa(b)||d.splice(d.indexOf(e),1)};m.vs=function(c){var d=
this.jP(),e=this.RH(c);null!=e&&(p.removeItem(c),d.splice(d.indexOf(e),1),b.Eo().M9(a.oE.wna))};m.un=function(){p&&(p.clear(),this.iza(),b.Eo().M9(a.oE.wna))};e.kb(c.zeb,"PRIM_WEB","SessionStorage",{Pa:{Available:{a:m.L4a},Item:{a:function(a){return this.RH(e.na(a))},iw:"na"},ItemCount:{a:m.pc}},jc:{Add:m.Lg,Remove:m.vs,Clear:m.un},Uf:{Pf:"Item"},op:{Co:function(a){return this.be(e.L(a))},rv:m.pc}});c.bNa=function(a){d.w.call(this);this.Ql=a};var d=c.u(c.bNa,c.ld);d.rh=function(){return this.Ql};
d.Ja=function(){var a="";p&&(a=p[this.Ql],a===n&&(a=""));return a};d.Xa=function(c){var d=!0;try{p[this.Ql]=c,b.Eo().M9(a.oE.wna)}catch(e){b.Eo().vHb(a.oE.wna),d=!1}return d};e.kb(c.bNa,"PRIM_WEB","SessionStorageItem",{Pa:{Name:{a:d.rh},Value:{a:d.Ja,g:function(a){this.Xa(e.na(a))}}},Uf:{Pf:"Value"}});c.xeb=function(){g.w.call(this)};var g=c.u(c.xeb,c.ld);g.U=function(){g.j.U.call(this)};g.pDc=function(a){0<a&&window.history.go(0-a)};g.qDc=function(a){0<a&&window.history.go(a)};g.Lg=function(a,c){var d=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.Eo().pib();c&&b.Eo().gIa()};g.KSc=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.Eo().pib();c&&b.Eo().gIa()};e.kb(c.xeb,"PRIM_WEB","History",{jc:{Add:function(a,b){this.Lg(e.na(a),b===n?!0:e.ya(b))},Replace:function(a,b){this.KSc(e.na(a),b===n?!0:e.ya(b))},
GoBack:function(a){this.pDc(a===n?1:e.L(a))},GoForward:function(a){this.qDc(a===n?1:e.L(a))}}});c.mZb=function(){v.w.call(this);this.qd=b.Ed(0,0,400,400);this.VCa=this.Me="";this.Kg&=~a.zh.MP;this.Kg&=~a.zh.tY};var v=c.u(c.mZb,c.em);v.Og=function(){return c.EZb};v.VH=function(){return this.Me};v.sl=function(b){this.Me!=b&&(this.Me=b,this.fa(a.f.i))};v.gT=function(){return this.VCa};v.ujb=function(a){this.VCa=a};v.Hd=function(a,c,d){v.j.Hd.call(this,a,c,d);a=this.Oa().gb();b.Id[a].sl(this.Me)};v.buc=
function(){this.Ha(a.K.yRb)};e.kb(c.mZb,"PRIM_WEB","Page",{Pa:{Source:{a:v.VH,g:function(a){this.sl(e.na(a))}},Description:{a:v.gT,g:function(a){this.ujb(e.na(a))}}}});c.zla=function(){E.w.call(this)};var E=c.u(c.zla,c.em);E.K6a=function(){for(var a=null,b=this;b;){if(b instanceof c.Ceb){a=b;break}b=b.Lb}return a};E.Qba=function(){E.j.Qba.call(this);var a=this.K6a();a&&a.hX(this)};E.cZ=function(){E.j.cZ.call(this);var a=this.K6a();a&&a.iX(this)};E.of=function(a){E.j.of.call(this,a);var b=this.K6a();
b==this&&b.Wz(a,!1)};e.kb(c.zla,"PRIM_WEB","RichTextItem",{});c.Geb=function(){q.w.call(this)};var q=c.u(c.Geb,c.zla);q.Og=function(){return c.t_b};e.kb(c.Geb,"PRIM_WEB","RichTextLine",{});c.Deb=function(){x.w.call(this)};var x=c.u(c.Deb,c.zla);x.Og=function(){return c.r_b};e.kb(c.Deb,"PRIM_WEB","RichTextBreak",{});c.Eeb=function(){L.w.call(this);this.eW=null;this.yEa=a.MI.Fib;this.KXa=this.LXa=0};var L=c.u(c.Eeb,c.zla);L.U=function(){L.j.U.call(this);this.CQa(null)};L.Og=function(){return c.s_b};
L.qBc=function(){return this.eW};L.CQa=function(b){this.eW!=b&&(null!=this.eW&&(this.eW.Ba(this,this.cDb),this.eW.vb()),this.eW=b,null!=this.eW&&(this.eW.Aa(),this.eW.Ea(this,this.cDb)),this.fa(a.f.i))};L.eud=function(){return this.yEa};L.J6b=function(b){this.yEa!=b&&(this.yEa=b,this.fa(a.f.i))};L.rBc=function(){return this.LXa};L.L6b=function(b){this.LXa!=b&&(this.LXa=b,this.fa(a.f.i))};L.pBc=function(){return this.KXa};L.K6b=function(b){this.KXa!=b&&(this.KXa=b,this.fa(a.f.i))};L.Hd=function(a,
c,d){L.j.Hd.call(this,a,c,d);a=this.Oa().gb();b.Id[a].Eg(this.yEa,this.LXa,this.KXa)};L.aib=function(){var a=this.eW,c=this.Oa().gb(),a=a?a.gh():"";b.Id[c].Xc(a)};L.cDb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Qb:this.CQa(null);break;case a.f.i:this.fa(a.f.i)}};e.kb(c.Eeb,"PRIM_WEB","RichTextImage",{Pa:{Image:{a:L.qBc,g:function(a){this.CQa(a)}},Width:{a:L.rBc,g:function(a){this.L6b(e.L(a))}},Height:{a:L.pBc,g:function(a){this.K6b(e.L(a))}},Alignment:{a:function(){return e.ta(this.yEa,a.MI.v)},
g:function(b){this.J6b(e.qa(b,a.MI.v))}}}});c.cNa=function(){B.w.call(this);this.oy=null};var B=c.u(c.cNa,c.zla);B.Og=function(){return c.u_b};B.Sy=function(){null==this.oy&&(this.oy=new c.Feb(this));return this.oy};e.kb(c.cNa,"PRIM_WEB","RichTextParagraph",{Pa:{Items:{a:B.Sy}}});c.Ceb=function(){S.w.call(this);this.qd=b.Ed(0,0,100,100)};var S=c.u(c.Ceb,c.cNa);S.Og=function(){return c.q_b};S.hX=function(b){if(!this.$c()){var c=e.Rb();c.Vb("ITEM",b);this.Ha(a.K.qI,c);c.mc()}};S.iX=function(b){if(!this.$c()){var c=
e.Rb();c.Vb("ITEM",b);this.Ha(a.K.sI,c);c.mc()}};S.I2=function(b){if(!this.$c()){var c=e.Rb();c.Vb("ITEM",b);this.Ha(a.K.rI,c);c.mc()}};S.Wz=function(b,c){if(!c&&!this.$c()){var d=e.Rb();d.Vb("ITEM",b);d.ef("CONTINUE",!0);this.Ha(a.K.pI,d);c=!d.Rf("CONTINUE");d.mc()}return c};e.kb(c.Ceb,"PRIM_WEB","RichText",{});c.Feb=function(a){u.w.call(this);this.Za=[];this.Jz=a};var u=c.u(c.Feb,c.ld);u.U=function(){u.j.U.call(this)};u.pc=function(){return this.Za.length};u.be=function(a){return this.Za[a-1]};
u.Lg=function(b,d,e,g){var f=new c.Geb;f.Aa();f.Ab(b);d!=n&&f.tb(d);e!=n&&f.km(e);g!=n&&f.Tn(g);f.Na(this.Jz);this.Za[this.Za.length]=f;this.Jz.fa(a.f.i);this.Jz.Ob()&&this.Jz.Qg();return f};u.Kgc=function(){var b=new c.Deb;b.Aa();b.Na(this.Jz);this.Za[this.Za.length]=b;this.Jz.fa(a.f.i);this.Jz.Ob()&&this.Jz.Qg();return b};u.Tgc=function(b,d,e,g,f,h,m){var l=new c.Eeb;l.Aa();l.CQa(b);d!=n&&l.J6b(d);e!=n&&l.L6b(e);g!=n&&l.K6b(g);f!=n&&l.tb(f);h!=n&&l.km(h);m!=n&&l.Tn(m);l.Na(this.Jz);this.Za[this.Za.length]=
l;this.Jz.fa(a.f.i);this.Jz.Ob()&&this.Jz.Qg();return l};u.Ygc=function(b,d,e,g){var f=new c.cNa;f.Aa();b!=n&&f.Ab(b);d!=n&&f.tb(d);e!=n&&f.km(e);g!=n&&f.Tn(g);f.Na(this.Jz);this.Za[this.Za.length]=f;this.Jz.fa(a.f.i);this.Jz.Ob()&&this.Jz.Qg();return f};u.vs=function(b){this.Za.splice(this.Za.indexOf(b),1);b.Na(null);b.vb();this.Jz.fa(a.f.i)};u.Cj=function(){for(;0<this.Za.length;)this.vs(this.Za[0]);this.Jz.fa(a.f.i)};e.kb(c.Feb,"PRIM_WEB","RichTextItems",{Pa:{Item:{a:function(a){return this.be(e.L(a))},
iw:"na"},ItemCount:{a:u.pc}},jc:{Add:u.Lg,AddBreak:u.Kgc,AddImage:function(b,c,d,g,f,h,m){return this.Tgc(b,e.qa(c,a.MI.v),d,g,f,h,m)},AddParagraph:u.Ygc,Remove:u.vs,RemoveAll:u.Cj},Uf:{Pf:"Item"},op:{Co:function(a){return this.be(e.L(a))},rv:u.pc}});c.oZb=function(){A.w.call(this);this.qd=b.Ed(0,0,100,100)};var A=c.u(c.oZb,c.em);A.Og=function(){return c.WZb};A.Hd=function(a,b,c){A.j.Hd.call(this,a,b,c)};A.Ag=function(a){this.II();a&&this.Kya();b.cb().hB(this)};A.UB=function(){this.ga.zW()};e.kb(c.oZb,
"PRIM_WEB","Camera",{});c.zZb=function(){D.w.call(this);this.qd=b.Ed(0,0,100,100);this.zE=null;this.nGa("")};var D=c.u(c.zZb,c.em);D.U=function(){this.zE=null;D.j.U.call(this)};D.Og=function(){return c.v_b};D.mua=function(){this.Oa()&&this.nGa(this.Oa().svc());return this.zE};D.nGa=function(a){this.zE=new c.fG({data:a,mimetype:"image/png",filename:"signature.png"})};D.un=function(){if(this.Oa()){var a=this.Oa().gb();b.Id[a].un();this.xc()}};D.Hd=function(a,b,c){D.j.Hd.call(this,a,b,c)};D.Ag=function(a){this.II();
a&&this.Kya();b.cb().hB(this)};D.UB=function(){this.ga.zW()};D.xc=function(){this.Ha(a.K.yh)};e.kb(c.zZb,"PRIM_WEB","Signature",{Pa:{Blob:{a:D.mua}},jc:{Clear:D.un}});c.uZb=function(){Q.w.call(this);this.qvb=this.Btb=this.Vqb=this.Uqb=this.Qqb=this.QWa=this.qub=0;this.n7=a.ND.KFb};var Q=c.u(c.uZb,c.ld);Q.Uzc=function(){return this.qub};Q.fzc=function(){return this.QWa};Q.Nuc=function(){return this.Qqb};Q.Zuc=function(){return this.Uqb};Q.$uc=function(){return this.Vqb};Q.Cyc=function(){return this.Btb};
Q.SBc=function(){return this.qvb};Q.Gqd=function(){return this.n7};Q.SRc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.qub=d.coords.longitude;b.QWa=d.coords.latitude;b.Qqb=d.coords.accuracy;b.Uqb=d.coords.altitude?d.coords.altitude:0;b.Vqb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.Btb=d.coords.heading?d.coords.heading:0;b.qvb=d.coords.speed?d.coords.speed:0;b.n7=a.ND.OHa;d=new c.bla;b.Ha(a.K.n3b,d)},function(d){b.qub=0;b.QWa=0;b.Qqb=
0;b.Uqb=0;b.Vqb=0;b.Btb=0;b.qvb=0;b.n7=a.ND.p3a;switch(d.code){case d.PERMISSION_DENIED:b.n7=a.ND.OFb;break;case d.POSITION_UNAVAILABLE:b.n7=a.ND.PFb;break;case d.TIMEOUT:b.n7=a.ND.RFb;break;case d.UNKNOWN_ERROR:b.n7=a.ND.p3a}d=new c.bla;b.Ha(a.K.n3b,d)});return this.QWa};e.kb(c.uZb,"PRIM_WEB","Geolocation",{Pa:{Longitude:{a:Q.Uzc},Latitude:{a:Q.fzc},Accuracy:{a:Q.Nuc},Altitude:{a:Q.Zuc},AltitudeAccuracy:{a:Q.$uc},Heading:{a:Q.Cyc},Speed:{a:Q.SBc},ErrorCode:{a:function(){return e.ta(this.n7,a.ND.v)}}},
jc:{Refresh:Q.SRc}});c.qZb=function(){y.w.call(this)};var y=c.u(c.qZb,c.ld);y.ZLc=function(b,c){if("undefined"!==typeof console)switch(c){case a.CS.xyb:console.error(b);break;case a.CS.Ayb:console.warn(b);break;case a.CS.yyb:console.info(b);break;default:console.log(b)}};e.kb(c.qZb,"PRIM_WEB","Console",{Pa:{},jc:{Log:function(b,c){return this.ZLc(e.na(b),c?e.qa(c,a.CS.v):a.CS.zyb)}}});c.tZb=function(){K.w.call(this);this.Yb=this.fb=null;this.zz=this.Ur="";this.xub=!1};var K=c.u(c.tZb,c.ss);K.U=function(){K.j.U.call(this);
this.nn(null)};K.Og=function(){return c.d_b};K.gh=function(){return this.Ur};K.K5a=function(){return this.zz};K.Bg=function(b){this.fb!=b&&(this.nn(b),this.m(a.f.i))};K.hb=function(){var a=null;return a=this.fb};K.hc=function(){return this.Yb};K.n6a=function(){return this.xub};K.v6b=function(b){this.xub!=b&&(this.xub=b,this.fa(a.f.i))};K.xc=function(){this.Ha(a.K.yh)};K.f4a=function(b,c){var d=e.Rb();d.Vb("FILE",b);d.Vb("FILES",c);this.Ha(a.K.ZGb,d);d.mc()};K.mO=function(){this.aR=b.tla(this.Yb.wk());
this.fb.SS(this.hc())};K.nn=function(a){var c=null;a&&(c=a.lx(),this.fb==a?c.mo(this.Yb):a.Iy(c));this.fb&&(this.fb.Ba(this),this.Yb.Ba(this),b.la(this.Yb),this.Yb=null);if(this.fb=a)this.fb.Ea(this,this.Bl),this.Yb=c,this.Yb.Ea(this,this.jv);this.Rg()};K.dNd=function(){};K.Bl=function(b,c){c.Ya==a.f.i?c.jr==a.je.yw?this.fb.Iy(this.hc()):this.nn(this.fb):c.Ya==a.f.rb&&this.Bg(null)};K.jv=function(b,c){c.Ya==a.f.i&&c.jr==a.je.yw&&this.mO()};e.kb(c.tZb,"PRIM_WEB","FilePicker",{Pa:{MultiSelect:{a:K.n6a,
g:function(a){this.v6b(e.ya(a))}}}});c.ueb=function(a){H.w.call(this);this.LWa=a;this.YV=this.zE=null};var H=c.u(c.ueb,c.ld);H.U=function(){null!=this.zE&&(this.zE=null);null!=this.YV&&(b.iAb(this.YV),this.YV=null);H.j.U.call(this)};H.rh=function(){return this.LWa.name};H.mua=function(){null==this.zE&&(this.zE=new c.cVb(this.LWa));return this.zE};H.V6a=function(){return this.LWa.size};H.kAc=function(){return this.LWa.type};e.kb(c.ueb,"PRIM_WEB","File",{Pa:{Name:{a:H.rh},Blob:{a:H.mua},FileSize:{a:H.V6a},
MimeType:{a:H.kAc}}});c.veb=function(){$.w.call(this);this.Za=[]};var $=c.u(c.veb,c.ld);$.U=function(){for(var a=0;a<this.Za.length;a++)this.Za[a].vb();this.Za=[];$.j.U.call(this)};$.pc=function(){return this.Za.length};$.be=function(a){return this.Za[a-1]};$.zr=function(a){this.Za.push(a);a.Aa()};e.kb(c.veb,"PRIM_WEB","Files",{Pa:{Item:{a:function(a){return this.be(e.L(a))},iw:"na"},ItemCount:{a:$.pc}},Uf:{Pf:"Item"},op:{Co:function(a){return this.be(e.L(a))},rv:$.pc}});c.pZb=function(){sa.w.call(this)};
var sa=c.u(c.pZb,c.ld);sa.Phb=function(a){var d=this;if(window.FileReader&&a instanceof c.fG){if(a=a.cja()){var e=b.vQ(),g=new FileReader;g.onload=function(a){d.gX(a.target.result);b.$x(e)};g.readAsText(a)}}else d.gX("")};sa.gX=function(b){var c=e.Rb();c.vF("DATA",b);this.Ha(a.K.e2,c)};e.kb(c.pZb,"PRIM_WEB","ClobReader",{jc:{Read:sa.Phb}});c.nZb=function(){ka.w.call(this)};var ka=c.u(c.nZb,c.ld);ka.Phb=function(a){var d=this;if(window.FileReader&&a instanceof c.fG){if(a=a.cja()){var e=b.vQ(),g=new FileReader;
g.onload=function(a){d.gX(b.IGb(a.target.result));b.$x(e)};g.readAsDataURL(a)}}else d.gX("","")};ka.gX=function(b){var c=e.Rb();c.vF("DATA",b);this.Ha(a.K.e2,c)};e.kb(c.nZb,"PRIM_WEB","BlobReader",{jc:{Read:ka.Phb}});c.q_b=function(a){Y.w.call(this,a)};var Y=c.u(c.q_b,c.fm);Y.Ab=function(a){this.G.textContent=a};Y.Ey=function(){Y.j.Ey.call(this);this.G.style.whiteSpace="normal";this.G.style.overflowX="auto";this.G.style.overflowY="auto"};Y.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",
a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return Y.j.bf.call(this,a,b)};c.u_b=function(a){F.w.call(this,a)};var F=c.u(c.u_b,c.fm);F.Ab=function(a){this.G.textContent=a};F.Vva=function(){return!1};F.aea=function(){};F.Ey=function(){};F.bf=function(a,b){this.G=document.createElement("p");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return F.j.bf.call(this,a,b)};c.r_b=function(a){J.w.call(this,a)};var J=c.u(c.r_b,c.fm);J.Vva=function(){return!1};J.aea=function(){};
J.Ey=function(){};J.bf=function(a,b){this.G=document.createElement("br");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return J.j.bf.call(this,a,b)};c.s_b=function(a){C.w.call(this,a)};var C=c.u(c.s_b,c.fm);C.Xc=function(a){this.G.src=a};C.Vva=function(){return!1};C.Eg=function(b,c,d){this.G.style.width=0==c?"auto":c+"px";this.G.style.height=0==d?"auto":d+"px";switch(b){case a.MI.Fib:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display=
"inline";this.G.style.cssFloat="none";break;case a.MI.t4b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="left";break;case a.MI.u4b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="right";break;case a.MI.s4b:this.G.style.marginLeft="auto",this.G.style.marginRight="auto",this.G.style.display="block",this.G.style.cssFloat="none"}};C.aea=function(){};C.Ey=
function(){this.G.style.borderStyle="solid"};C.bf=function(a,b){this.G=document.createElement("img");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return C.j.bf.call(this,a,b)};c.t_b=function(a){ea.w.call(this,a)};var ea=c.u(c.t_b,c.fm);ea.Ab=function(a){this.G.textContent=a};ea.Vva=function(){return!1};ea.aea=function(){};ea.Ey=function(){};ea.bf=function(a,b){this.G=document.createElement("span");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",
this.cc);return ea.j.bf.call(this,a,b)};c.WZb=function(a){ca.w.call(this,a)};var ca=c.u(c.WZb,c.fm);ca.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return ca.j.bf.call(this,a,b)};c.v_b=function(a){fa.w.call(this,a);this.VG=this.qm=null;this.Rdc=this.Awb=!1;this.Mtb=null};var fa=c.u(c.v_b,c.fm);fa.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",
this.cc);this.G.style.msTouchAction="none";this.VG=document.createElement("canvas");this.VG.style.touchAction="none";this.G.appendChild(this.VG);this.qm=this.VG.getContext("2d");this.fAb();return fa.j.bf.call(this,a,b)};fa.dn=function(a,b,c,d){fa.j.dn.call(this,a,b,c,d);a=this.qm.getImageData(0,0,this.VG.width-1,this.VG.height-1);this.VG.width=this.Uc;this.VG.height=this.ed;this.qm.putImageData(a,0,0)};fa.ML=function(a){this.M7b(a);return!0};fa.Kfb=function(a){this.L7b(a);return!0};fa.qNa=function(a){this.K7b(a);
return!0};fa.Toa=function(a){this.M7b(a);return!0};fa.Kv=function(a){this.L7b(a);return!0};fa.Wda=function(a){this.K7b(a);return!0};fa.zNb=function(a){this.G.onpointerdown===n&&a.touches!==n?(a.Iqb=a.touches[0].pageX-this.pa.is(),a.Jqb=a.touches[0].pageY-this.pa.ls()):(a.Iqb=a.clientX-this.pa.is(),a.Jqb=a.clientY-this.pa.ls());this.pa.xc()};fa.fAb=function(){this.C_a(!0);this.Mtb=new Image;this.Mtb.onload=function(){throw 0;};this.Mtb.src=null};fa.C_a=function(a){(this.Rdc||a)&&this.qm.clearRect(0,
0,this.qm.canvas.width,this.qm.canvas.height);this.Rdc=!1};fa.svc=function(){var a=this.VG.toDataURL("image/png");return b.IGb(a)};fa.un=function(){this.fAb()};fa.M7b=function(a){a.preventDefault();this.C_a(!1);this.qm.beginPath();this.zNb(a);this.qm.moveTo(a.Iqb,a.Jqb);this.Awb=!0};fa.K7b=function(a){a.preventDefault();this.Awb=!1};fa.ZKd=function(a){this.Kv(a)};fa.L7b=function(a){this.Awb&&(a.preventDefault(),this.C_a(!1),this.qm.strokeStyle="rgb(0,0,0)",this.qm.lineWidth=1,this.zNb(a),this.qm.lineTo(a.Iqb,
a.Jqb),this.qm.stroke())};c.EZb=function(a){na.w.call(this,a);this.gsa=this.$a=null};var na=c.u(c.EZb,c.fm);na.sl=function(a){this.gsa.src=a};na.bf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);this.gsa=document.createElement("iframe");this.EFa(this.gsa);this.gsa.style.width="100%";this.gsa.style.height="100%";this.G.appendChild(this.gsa);return na.j.bf.call(this,a,b)};na.HW=function(){var a=this;na.j.HW.call(this);
a.G.addEventListener("load",function(){a.pa.buc()},!1)};na.EFa=function(a){na.j.EFa.call(this,a);this.G.style.overflowX="auto";this.G.style.overflowY="auto"};c.d_b=function(a){aa.w.call(this,a);this.jR=null};var aa=c.u(c.d_b,c.Qeb);aa.bf=function(a,b){var c=aa.j.bf.call(this,a,b);this.jR=document.createElement("input");this.jR.type="File";var d=this.jR.style;this.ib.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.jR);return c};aa.Hd=
function(){aa.j.Hd.call(this);this.Dad()};aa.dn=function(a,b,c,d){aa.j.dn.call(this,a,b,c,d);this.jR.style.left="0px";this.jR.style.top="0px";this.jR.style.width=c+"px";this.jR.style.height=d+"px"};aa.HW=function(){var a=this;this.V1();a.jR.addEventListener("change",function(b){a.vkc(b);a.jR.value=""},!1)};aa.Dad=function(){this.jR.multiple=this.pa.n6a()};aa.vkc=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.veb,e=0,g;g=a[e];e++)g=new c.ueb(g),null==b&&(b=g),d.zr(g);b&&
this.pa.f4a(b,d)}},{rp:["PRIM_LABL"]});
