window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Jsc={LOd:0,KOd:9,Ncd:6,MOd:5,NOd:10};a.rDc={Muc:0};c.LWb=function(){n.w.call(this);this.Xsb=a.Jsc.Ncd;this.bH=a.rDc.Muc;this.sH=new c.ja;this.Qc=this.Qc|a.Wb.Iaa|a.Wb.Kwa|a.Wb.Iab|a.Wb.MD|a.Wb.ST|a.Wb.LD;this.Kg=this.Kg|a.zh.MP|a.zh.tY;this.tf(!1)};var n=c.u(c.LWb,c.$T);n.Og=function(){return c.e_b};n.kJd=function(b){this.Xsb!=b&&(this.Xsb=b,this.m(a.f.i),this.qv())};n.xqd=function(){return this.Xsb};n.Tp=function(a){n.j.Tp.call(this,a);this.ROc()};n.vpb=
function(){if(this.Ob()){var a=this.Xd(),a=Math.abs(a.Sa()),c=this.Ge();this.yd();this.yd();c.Ua(c.Q()+a);""==this.mb()?(c.Qa(c.Q()),c.Fa(a)):(this.mb(),c.Qa(c.Q()+this.nX()),c.Fa(this.Eia()),c.Qa(c.va+a));b.Rp(this.sH,c)||(this.sH=c,this.qb());this.Tp(!0)}};n.Qe=function(a){a.Va(a.M()+this.sH.ba());a.Ua(a.Q()+4);a.Qa(a.va-4);a.Fa(a.ua-4);n.j.Qe.call(this,a)};n.KRc=function(a,b,c){a.Va(a.M()+this.sH.ba());a.Ua(a.Q()+4);a.Qa(a.va-4);a.Fa(a.ua-4);n.j.KRc.call(this,a,b,c)};n.ij=function(){n.j.ij.call(this);
this.Cd(a.$.cz)};n.Wc=function(){var b=this.kL()||this.xk()&&(this.rY()||this.LP());this.vH(a.Wb.pL,b);n.j.Wc.call(this)};n.UD=function(a){var b=!1,b=a.Wd().HOa(this,this.ga.ii,this.rY(),this.LP(),a);!1==b&&n.j.UD.call(this,a)};n.oU=function(a){var b=!1;null!=a.Wd()&&a.ea().xk()&&(b=a.Wd().IOa(this,this.ga.ii,a,this.rY(),this.LP()));!1==b&&n.j.oU.call(this,a)};n.ue=function(b){""==b[1]&&(b[1]=a.FQb);n.j.ue.call(this,b)};n.ROc=function(){var a=this.Ge(),a=this.iB(a,null),c=this.Ge();c.Va(c.M()+this.sH.ba()/
2+1);c.Ua(c.Q()+2);c.Qa(c.va-2);c.Fa(c.ua-2);var e=this.Oa().gb(),h=this.mb();b.Id[e].Eg(h,c,this.sH);b.la(a)};n.rr=n[a.$.dG]=function(a){this.vpb();n.j.rr.call(this,a)};n.au=n[a.$.cG]=function(){n.j.au.call(this);this.vpb()};n.EF=n[a.$.cz]=function(){this.vpb();this.qv()};n.tqc=n[a.$.mbb]=function(){this.Rg()};e.ad(c.LWb,"PRIM_GPBX",{Pa:{Caption:{a:n.mb,g:function(a){this.Ab(e.na(a))}},ThemeStyle:{a:function(){return e.ta(this.ZK(),a.Lu.v)},g:function(b){this.mAa(e.qa(b,a.Lu.v))}}}});c.e_b=function(a){s.w.call(this,
a);this.ib=this.fUa=this.hCa=this.Td=this.Ec=null};var s=c.u(c.e_b,c.r4);s.bf=function(a,b){var c=null;s.j.bf.call(this,a,b);this.fUa=4;this.Ec=document.createElement("div");this.Td=document.createElement("div");this.hCa=document.createElement("div");this.ib=document.createElement("span");this.G.appendChild(this.Ec);this.G.appendChild(this.Td);this.G.appendChild(this.hCa);this.G.appendChild(this.ib);this.E9a(this.Ec,this.fUa);this.E9a(this.Td,0);this.E9a(this.hCa,0);c=this.Ec.style;c.borderTopWidth=
"0px";c=this.Td.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.hCa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.ib.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};s.E9a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};s.Eg=function(a,b,c){var e=this.Ec.style;e.left=b.Q()+"px";e.top=b.M()+"px";e.width=b.aa()+"px";e.height=b.ba()+"px";e.borderColor=this.Uk();e=this.Td.style;e.left=b.Q()+this.fUa-1+"px";e.top=b.M()+"px";e.width=c.Q()-b.Q()+"px";e.height="1px";e.borderColor=this.Uk();e=this.hCa.style;e.left=c.va+2+"px";e.top=b.M()+"px";e.width=b.va-this.fUa-c.va+"px";e.height="1px";e.borderColor=this.Uk();e=this.ib.style;e.left=c.Q()+7+"px";e.top=c.M()+2+"px";e.height=
c.ba()+"px";e.width=c.aa()+"px";this.ib.textContent=a}});
