window.LANSA.addSrc("json",function(e,c,a,b,n){function s(a,b,d){var g=null;if(null===d)g=e.et(new c.Vxa(a,b));else switch(typeof d){case "object":g=Array.isArray(d)?e.et(new c.wla(a,b)):e.et(new c.xla(a,b));g.ozb(d);break;case "number":g=e.et(new c.Wxa(a,b,d));break;case "string":g=e.et(new c.Xxa(a,b,d));break;case "boolean":g=e.et(new c.Uxa(a,b,d))}return g}e.Fb("PRIM_PCOL");a.KD={H3a:0,AGb:1,xGb:2,BGb:3,zGb:4,yGb:5};a.KD.v={NULL:a.KD.H3a,OBJECT:a.KD.AGb,ARRAY:a.KD.xGb,STRING:a.KD.BGb,NUMBER:a.KD.zGb,
BOOLEAN:a.KD.yGb};c.wZb=function(){p.w.call(this);this.Fg="";this.zEa=null;this.J1=!1};var p=c.u(c.wZb,c.ld);p.U=function(){this.DQa(null);p.j.U.call(this)};p.uBc=function(){return this.zEa};p.DQa=function(a){this.zEa=a};p.dDc=function(){return this.J1};p.SQa=function(a){this.J1=a};p.Np=function(){return this.J1?JSON.stringify(this.zEa.SK()):this.Fg};p.tM=function(a){this.Fg=a;var b=null,c=null;try{b=JSON.parse(a)}catch(d){}b?(c=s(this,null,b),this.SQa(!0)):this.SQa(!1);this.DQa(c)};p.kmc=function(){this.DQa(e.et(new c.wla(this,
null)));this.SQa(!0);return this.zEa};p.lmc=function(){this.DQa(e.et(new c.xla(this,null)));this.SQa(!0);return this.zEa};e.kb(c.wZb,"PRIM_WEB","Json",{Pa:{Text:{a:p.Np,g:function(a){this.tM(e.na(a))}},IsValid:{a:p.dDc},RootItem:{a:p.uBc}},jc:{CreateRootArray:p.kmc,CreateRootObject:p.lmc},Uf:{Pf:"Text"}});c.p4=function(a,b){t.w.call(this);this.ME=a;this.Dz=b};var t=c.u(c.p4,c.ld);t.H$=function(){return a.KD.H3a};t.SK=function(){return null};t.pc=function(){return 0};t.be=function(){return null};t.Dx=
function(){return null};t.$pd=function(){return this.ME};t.t6a=function(){return this.Dz};t.dja=function(){return this.Dz?this.Dz.jJb(this):""};t.jJb=function(){return""};t.Ki=function(){return this.Dz?this.Dz.W5a(this):-1};t.W5a=function(){return-1};t.B8=function(){throw e.RSc(JSON.stringify(this.SK()));};t.FZa=function(){throw e.hza(JSON.stringify(this.SK()));};t.vZa=function(){throw e.cib(JSON.stringify(this.SK()));};t.vs=function(){return null};t.Cj=function(){};e.kb(c.p4,"PRIM_WEB","JsonElement",
{Pa:{Key:{a:t.dja},Index:{a:function(){return this.Ki()+1}},Type:{a:function(){return e.ta(this.H$(),a.KD.v)}},Item:{a:function(a){return this.be(e.na(a))}},ItemAt:{a:function(a){return this.Dx(e.L(a)-1)}},ItemCount:{a:function(){return this.pc()}},ParentItem:{a:t.t6a}},jc:{AsString:function(){return this.B8()},AsNumber:function(){return e.Qo(this.FZa())},AsBoolean:function(){return this.vZa()},Remove:function(a){return this.vs(e.na(a))},RemoveAt:function(a){return this.Iq(e.L(a)-1)},RemoveAll:function(){this.Cj()}},
Uf:{Pf:"Item"},op:{Co:function(a){return this.Dx(e.L(a)-1)},rv:function(){return this.pc()}}});c.wla=function(a,b){f.w.call(this,a,b);this.Za=[]};var f=c.u(c.wla,c.p4);f.H$=function(){return a.KD.xGb};f.SK=function(){for(var a=[],b=0;b<this.Za.length;b++)a.push(this.Za[b].SK());return a};f.Dx=function(a){return 0<=a&&a<this.Za.length?this.Za[a]:null};f.pc=function(){return this.Za.length};f.W5a=function(a){for(var b=0;b<this.Za.length;b++)if(this.Za[b]===a)return b;return-1};f.ozb=function(a){for(var b=
0;b<a.length;b++){var c=s(this.ME,this,a[b]);c&&this.Za.push(c)}};f.H9a=function(){var a=e.et(new c.wla(this.ME,this));this.Za.push(a);return a};f.P9a=function(){var a=e.et(new c.xla(this.ME,this));this.Za.push(a);return a};f.T9a=function(a){a=e.et(new c.Xxa(this.ME,this,a));this.Za.push(a);return a};f.O9a=function(a){a=e.et(new c.Wxa(this.ME,this,a));this.Za.push(a);return a};f.K9a=function(a){a=e.et(new c.Uxa(this.ME,this,a));this.Za.push(a);return a};f.N9a=function(){var a=e.et(new c.Vxa(this.ME,
this));this.Za.push(a);return a};f.Iq=function(a){var b=null;0<=a&&a<this.Za.length&&(b=this.Za[a],this.Za.splice(a,1));return b};f.Cj=function(){this.Za=[]};e.kb(c.wla,"PRIM_WEB","JsonArray",{jc:{InsertArray:f.H9a,InsertObject:f.P9a,InsertNumber:function(a){return this.O9a(e.Jv(a))},InsertString:function(a){return this.T9a(e.na(a))},InsertBoolean:function(a){return this.K9a(e.ya(a))},InsertNull:f.N9a}});c.xla=function(a,b){h.w.call(this,a,b);this.Za={}};var h=c.u(c.xla,c.p4);h.H$=function(){return a.KD.AGb};
h.SK=function(){var a={},b;for(b in this.Za)a[b]=this.Za[b].SK();return a};h.be=function(a){a=this.Za[a];return a===n?null:a};h.Dx=function(a){var b=this.tba();return 0<=a&&a<b.length?this.Za[b[a]]:null};h.pc=function(){return this.tba().length};h.jJb=function(a){for(var b in this.Za)if(this.Za[b]===a)return b};h.W5a=function(a){var b=-1,c;for(c in this.Za)if(b++,this.Za[c]===a)break;return b};h.ozb=function(a){for(var b in a){var c=s(this.ME,this,a[b]);c&&(this.Za[b]=c)}this.tG()};h.tG=function(){delete this.SE};
h.tba=function(){if(this.SE===n){this.SE=[];for(var a in this.Za)this.SE.push(a)}return this.SE};h.H9a=function(a){var b=e.et(new c.wla(this.ME,this));this.Za[a]=b;this.tG();return b};h.P9a=function(a){var b=e.et(new c.xla(this.ME,this));this.Za[a]=b;this.tG();return b};h.T9a=function(a,b){var d=e.et(new c.Xxa(this.ME,this,b));this.Za[a]=d;this.tG();return d};h.K9a=function(a,b){var d=e.et(new c.Uxa(this.ME,this,b));this.Za[a]=d;this.tG();return d};h.N9a=function(a){var b=e.et(new c.Vxa(this.ME,this));
this.Za[a]=b;this.tG();return b};h.O9a=function(a,b){var d=e.et(new c.Wxa(this.ME,this,b));this.Za[a]=d;this.tG();return d};h.vs=function(a){var b=null;this.Za[a]!==n&&(b=this.Za[a],delete this.Za[a],this.tG());return b};h.Iq=function(a){var b=this.tba();return 0<=a&&a<b.length?this.vs(b[a]):null};h.Cj=function(){this.Za={};this.tG()};e.kb(c.xla,"PRIM_WEB","JsonObject",{jc:{InsertArray:function(a){return this.H9a(e.na(a))},InsertObject:function(a){return this.P9a(e.na(a))},InsertNumber:function(a,
b){return this.O9a(e.na(a),e.Jv(b))},InsertString:function(a,b){return this.T9a(e.na(a),e.na(b))},InsertBoolean:function(a,b){return this.K9a(e.na(a),e.ya(b))},InsertNull:function(a){return this.N9a(e.na(a))}}});c.Wxa=function(a,b,c){l.w.call(this,a,b);this.ab=c};var l=c.u(c.Wxa,c.p4);l.H$=function(){return a.KD.zGb};l.SK=function(){return this.ab};l.FZa=function(){return this.ab};l.B8=function(){return this.ab.toString()};e.kb(c.Wxa,"PRIM_WEB","JsonNumber",{});c.Xxa=function(a,b,c){m.w.call(this,
a,b);this.ab=c};var m=c.u(c.Xxa,c.p4);m.H$=function(){return a.KD.BGb};m.SK=function(){return this.ab};m.B8=function(){return this.ab};m.FZa=function(){if(isNaN(Number(this.ab)))throw e.hza(this.ab);return new c.Yi(this.ab)};m.vZa=function(){if("TRUE"==this.ab.toUpperCase())return!0;if("FALSE"==this.ab.toUpperCase())return!1;throw e.cib(this.ab);};e.kb(c.Xxa,"PRIM_WEB","JsonString",{});c.Uxa=function(a,b,c){d.w.call(this,a,b);this.ab=c};var d=c.u(c.Uxa,c.p4);d.H$=function(){return a.KD.yGb};d.SK=
function(){return this.ab};d.vZa=function(){return this.ab};d.B8=function(){return this.ab?"true":"false"};e.kb(c.Uxa,"PRIM_WEB","JsonBoolean",{});c.Vxa=function(a,b){g.w.call(this,a,b)};var g=c.u(c.Vxa,c.p4);g.H$=function(){return a.KD.H3a};g.SK=function(){return null};e.kb(c.Vxa,"PRIM_WEB","JsonNull",{})},{rp:["PRIM_PCOL"]});
