window.LANSA.addSrc("wdgt",function(e,c,a,b,n){var q={};c.$0b=function(a){m.w.call(this);this.WDa=a;this.lVa=function(){};this.aW=this.rvb=!1;this.Mvb=[];this.Lvb=[];this.Ivb=[];this.Hvb=[];this.Jvb=[]};var m=c.u(c.$0b,c.qe);m.SP=function(){return this.rvb};m.Pg=function(){return this.WDa.nm};m.JCc=function(){return this.WDa.js||[]};m.sDc=function(){return this.WDa.st||[]};m.vyc=function(){return this.WDa.fn};m.ozc=function(){return this.WDa.fe};m.BX=function(){return this.lVa};m.mTc=function(){function a(){if(p<
m.length){var c=m[p],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;p++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.rvb){for(c.rvb=!0;0<c.Hvb.length;){var b=c.Hvb.shift();c.U$a(b)}for(;0<c.Lvb.length;)b=c.Lvb.shift(),c.W$a(b.Nrb,b.Qfd,b.value);for(;0<c.Jvb.length;)b=c.Jvb.shift(),c.TOb(b.Nrb,
b.parent);for(;0<c.Mvb.length;)b=c.Mvb.shift(),c.X$a(b);for(;0<c.Ivb.length;)b=c.Ivb.shift(),c.V$a(b)}}var d=c.vyc(),g=c.lVa.prototype;e&&e(g);var f={Loading:{},Completed:{},Finalize:function(){a()}};d(g,f)!==f.Loading&&a()}var c=this,d=c.Pg(),e=c.ozc();q[d]=c;for(var g=c.sDc(),f=0;f<g.length;f++){var k=g[f],h=document.createElement("link");h.type="text/css";h.rel="stylesheet";h.href=k;document.body.appendChild(h)}var p=0,m=c.JCc();a()};m.W$a=function(a,b,c){if(this.SP()){var d=a["set"+b];if(!d)throw e.dUc("set"+
b);d&&d.call(a,c)}else this.Lvb.push({Nrb:a,Qfd:b,value:c})};m.V$a=function(a){this.SP()?a.KIa():this.Ivb.push(a)};m.U$a=function(a){if(this.SP()){var b=a.onCreateInstance;b&&b.call(a)}else this.Hvb.push(a)};m.TOb=function(a,b){if(this.SP()){var c=a.onRealizeControl;if(!c)throw e.cUc();c.call(a,b)}else this.Jvb.push({Nrb:a,parent:b})};m.X$a=function(a){if(this.SP()){var b=a.onSizeChanged;b&&b.call(a)}else this.Mvb.push(a)};c.pfb=function(){t.w.call(this)};var t=c.u(c.pfb,c.mm);t.Ax=function(){return this.Pa()&&
this.Pa().LFc()?this:null};t[a.$.Ux]=function(b){var c=!1;this.Pa()&&(c=b.Mc!==n?b.Mc:a.Z.$I,c=c==a.Z.$I||c==a.Z.Lw||c==a.Z.mC?this.Pa().yIb(null):this.Pa().zIb(null));c||t.j.hT.call(this,b)};t[a.$.uxa]=function(b){var c=!1;this.Pa()&&(c=(b.Mc!==n?b.Mc:a.Z.$I)==a.Z.$I?this.Pa().yIb(document.activeElement):this.Pa().zIb(document.activeElement));c||t.j.Y2a.call(this,b)};c.U_b=function(){f.w.call(this)};var f=c.u(c.U_b,c.jd);e.ad(c.U_b,"PRIM_WDGT",{});c.W_b=function(){h.w.call(this);var a=this.lJa(),
a=this.BS=q[a],b=this.nH=new (a.BX());b.LANSA_Component=this;b.LANSA_Class=a;a.U$a(b)};var h=c.u(c.W_b,c.jd);h.T$a=function(a,b){if(this.BS.SP()){var c=this.nH[a];if(!c)throw e.Y4b(a);return c.apply(this.nH,b)}throw e.GPa();};h.Gva=function(a){if(this.BS.SP()){var b=this.nH["get"+a];if(!b)throw e.X4b("get"+a);return b.call(this.nH)}throw e.GPa();};h.yAa=function(a,b){this.BS.W$a(this.nH,a,b)};h.V3=function(){p.j.V3.call();var a=this;setTimeout(function(){a.BS.V$a(a)},5)};h.KIa=function(){this.Ha(a.K.tY)};
e.ib(c.W_b,"PRIM_WDGT","Object",{});var k=h;k.get=k.Gva;k.set=k.yAa;k.invoke=k.T$a;c.V_b=function(){p.w.call(this);var b=this.lJa(),b=this.BS=q[b],c=this.nH=new (b.BX());c.LANSA_Component=this;c.LANSA_Class=b;b.U$a(c);this.pg&=~a.$g.XP;this.pg&=~a.$g.EY};var p=c.u(c.V_b,c.pfb);p.Sg=function(){return c.Z0b};p.Hd=function(a,c,d){p.j.Hd.call(this,a,c,d);a=this.Pa().gb();b.Jd[a].$Mc(this.nH)};p.T$a=function(a,b){if(this.BS.SP()){var c=this.nH[a];if(!c)throw e.Y4b(a);return c.apply(this.nH,b)}throw e.GPa();
};p.Gva=function(a){if(this.BS.SP()){var b=this.nH["get"+a];if(!b)throw e.X4b("get"+a);return b.call(this.nH)}throw e.GPa();};p.yAa=function(a,b){this.BS.W$a(this.nH,a,b)};p.TEd=function(){this.KIa()};p[a.$.$aa]=function(){this.BS.V$a(this)};p[a.$.kG]=function(){this.Qb()&&this.BS.X$a(this.nH)};p.lca=function(){p.j.lca.call(this);this.Qb()&&this.BS.X$a(this.nH)};e.ib(c.V_b,"PRIM_WDGT","Control",{});k=p;k.get=k.Gva;k.set=k.yAa;k.invoke=k.T$a;c.P_b=function(){d.w.call(this);this.qd=b.Cd(0,0,100,100);
this.xDa=this.$Da=""};var d=c.u(c.P_b,c.pfb);d.Sg=function(){return c.z0b};d.Xzc=function(){return this.$Da};d.c0c=function(b){this.$Da!=b&&(this.$Da=b,this.ea(a.f.i),this.Gd())};d.vT=function(){return this.xDa};d.qkb=function(a){this.xDa=a};d.jC=function(a){var d=this.Eo(),e=this.Iq();if(d||e){var g=new c.ha,f=[];f[0]=d;f[1]=e;f[2]=a;f[3]=0;f[4]=0;var k=this.gb();f[3]=0;f[4]=0;null!=k&&b.Jd[k].ncd(f);g.Ra(f[3]);g.Ga(f[4]);d&&a.Ra(a.Q()+this.ca.Wi()+g.aa()+this.ca.ek());e&&a.Ga(a.M()+this.ca.fk()+
g.ba()+this.ca.Jl())}};e.ib(c.P_b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:d.Xzc,g:function(a){this.c0c(e.na(a))}},Description:{a:d.vT,g:function(a){this.qkb(e.na(a))}}},Xf:{Sf:"Html"}});c.Efb=function(a){g.w.call(this,a)};var g=c.u(c.Efb,c.om);g.fLa=function(){return!1};g.iLa=function(){return this.pa.Ar()||this.pa.jK?!1:!0};g.LFc=function(){return 0<this.U0a().length};g.YL=function(a){g.j.YL.call(this,a);return!1};g.yIb=function(a){var b=this.U0a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};g.zIb=function(a){var b=this.U0a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};g.U0a=function(){var a=[],b=[];this.i3b(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};g.i3b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===n&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.i3b(a,b)};g.L2=g[a.La.NM]=
function(b){b.Me=a.La.jia|a.La.iHa};c.Z0b=function(a){C.w.call(this,a);this.$a=null};var C=c.u(c.Z0b,c.Efb);C.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);return C.j.df.call(this,a,b)};C.$Mc=function(a){null==this.$a&&(this.$a=document.createElement("div"),this.$a.style.left="0px",this.$a.style.top="0px",this.$a.style.width="100%",this.$a.style.height="100%",a.LANSA_Class.TOb(a,this.$a),this.G.appendChild(this.$a))};
c.z0b=function(a){A.w.call(this,a);this.$a=null};var A=c.u(c.z0b,c.Efb);A.Ny=function(){A.j.Ny.call(this);this.G.style.whiteSpace="normal"};A.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.cc);this.G.setAttribute("LANSAHandle",this.cc);this.$a=document.createElement("div");this.$a.style.left="0px";this.$a.style.top="0px";this.$a.style.width="100%";this.$a.style.height="100%";this.$a.innerHTML=this.pa.$Da;this.G.appendChild(this.$a);return A.j.df.call(this,a,
b)};A.acd=function(){var a=this.pa.Eo(),b=this.pa.Iq();this.$a.style.width=a?"":"100%";this.$a.style.height=b?"":"100%";this.$a.innerHTML=this.pa.$Da};A.Hd=function(){A.j.Hd.call(this);this.acd()};A.ncd=function(a){var b=a[0],c=a[2],d=this.$a.style.width;a[1]&&!b&&(this.$a.style.width=c.aa()+"px");a[3]=this.$a.clientWidth;a[4]=this.$a.clientHeight;this.$a.style.width=d}});
