window.LANSA.addSrc("ver",function(e,c,a,b,p){c.vSb=function(){r.w.call(this);this.uf=new c.jd;this.jra=this.cb=null};var r=c.u(c.vSb,c.td);r.Uyc=function(){return document.hasFocus()};r.x3c=function(a,s,f){var h=e.ed("PRIM_VS","Style"),n=null,k=null;s===p&&(s=0);f===p&&(f=0);if(a){if(0==s&&0==f)a.mk(!0),n=a.ca;else if(0!=s){var d=a.sB(new c.ha,null);s=a.O7.Mb[s-1];a.Cf().Oa().ehb(d,s,a.ega,null,null,s.gb());n=s.Av();if(0!=f&&(f=a.m2a(f-1)))for(var g in s.gb().gu)if(k=s.gb().gu[g],k.wn.yb==f){a.Cf().Oa().chb(d,
k.wn,k.wn.paa(),k.wn.ud.jKa(),k.wn.yb.Gva(),null);n=k.wn.paa();break}b.la(d)}n&&(h.pk(n.ni),h.Xn(n.DX()),h.dh(n.jx),h.Rw(n.ez()),h.Wh(n.xv()),h.yd(n.vw()),h.pg(n.CD()),h.ao(n.ku()),h.Qv(n.Ix()),h.Rv(n.Jx()),h.Ov(n.Gx()),h.Pv(n.Hx()),h.rn(n.Xi()),h.Yn(n.fk()),h.Ql(n.Jl()),h.Rl(n.ek()),h.wM(n.ae().Kx()),h.Kt(n.ae().Pa()),h.AA(n.ae().zi()),h.qE(n.ae().Ex()),h.DM(n.ae().Nx()),h.GQ(n.ae().bG()),h.KQ(n.ae().dG()));k&&(a.Cf().Oa().Jj.Lp&&h.Wh(a.Cf().Oa().Jj.Lp),a.Cf().Oa().Jj.sj&&h.yd(a.Cf().Oa().Jj.sj))}return h};
r.S$c=function(a,b){return a.z4a(b,[[]])};r.dmc=function(){null.ckd()};r.glc=function(a,e,f){var h;f===p&&(f=1);h===p&&(h=!0);a=new c.jd(a,e);if((e=b.uU(a))&&e.ee()){var n=e.Vh(a),k=new c.Et(e,n,a,1),d=new c.Et(e,n,a,1),g=new c.Et(e,n,a,2);b.AC(a.Cb(),a.Db(),n.Cb(),n.Db());h?(h=b.U(),e.Vj(k),null==h.uj?e.Tn(d):(h=h.uj.gb(),b.orb(null,h,n.Cb(),n.Db(),a.Cb(),a.Db())),2==f&&(g=new c.Et(e,n,a,2),e.Vj(g))):(e.IU(k),e.Oma(d));b.la(k);b.la(g);b.la(d)}};r.oad=function(a,e){var f=new c.jd(a,e),h=b.uU(f);if(h&&
h.ee()){var n=h.Vh(f),k=new c.Et(h,n,f,1),d=new c.Et(h,n,f,1),g=new c.Et(h,n,f,1),p=!1;b.AC(f.Cb(),f.Db(),n.Cb(),n.Db());h.oza(n,h,!1);h.nza(g);p=g.Xg;p||(h.Vj(k),h.Tn(d));b.la(k);b.la(d);b.la(g)}};r.DFc=function(a,e){var f=new c.jd(a,e),h=b.uU(f);if(h&&h.ee()){var n=h.Vh(f);for(b.AC(f.Cb(),f.Db(),n.Cb(),n.Db());h;)n=h.Vh(f),b.fdc(null,h.gb(),n.Cb(),n.Db(),f.Cb(),f.Db()),h=h.M()}};r.sZc=function(a,e){var f=new c.jd(a,e),h=b.uU(f);h&&h.ee()&&(h=h.Vh(f),b.AC(f.Cb(),f.Db(),h.Cb(),h.Db()))};r.YZc=function(a,
e){(this.jra=b.uU(new c.jd(a,e)))&&document.hasFocus()&&(b.lrb(this.jra.gb()),this.jra=null)};r.cJc=function(a,c){if(""!=a||0!=c){var e=0==c?a.charCodeAt(0):c,h;if(document.hasFocus())h=b.mrb();else if(this.jra)h=this.jra.gb();else return;b.cdc(null,h,e);""!=a&&b.ddc(null,h,a,a.charCodeAt(0));b.edc(null,h,e)}};r.TNc=function(a,e){this.uf=new c.jd(this.uf.Cb()+(0<a?1:0==a?0:-1),this.uf.Db()+(0<e?1:0==e?0:-1));if(this.cb){var f=this.cb.Vh(this.uf);b.AC(this.uf.Cb(),this.uf.Db(),f.Cb(),f.Db());b.LYb(this.cb,
f,this.uf)}};r.mMc=function(a,e,f){f===p&&(f=1);this.uf=new c.jd(a,e);if(this.cb=b.uU(this.uf))a=!1,e=this.cb.Vh(this.uf),this.cb.Rf.Mk&&(new c.ha(this.cb.Rf.Mk.hf,this.cb.Rf.Mk.Af,this.cb.Rf.Mk.Uc,this.cb.Rf.Mk.dd)).ce(e)&&(this.cb.Rf.Mk.jza(null),a=this.cb.Rf.Mk.rF),a||(b.AC(this.uf.Cb(),this.uf.Db(),e.Cb(),e.Db()),b.JYb(this.cb,e,this.uf,f))};r.nMc=function(){if(this.cb){var a=!1,e=this.cb.Vh(this.uf);this.cb.Rf.Mk&&(new c.ha(this.cb.Rf.Mk.hf,this.cb.Rf.Mk.Af,this.cb.Rf.Mk.Uc,this.cb.Rf.Mk.dd)).ce(e)&&
(this.cb.Rf.Mk.kza(null),a=this.cb.Rf.Mk.rF);a||(b.AC(this.uf.Cb(),this.uf.Db(),e.Cb(),e.Db()),b.KYb(this.cb,e,this.uf,1));this.cb=null}};r.LUc=function(a,e){this.uf=new c.jd(a,e);if(this.cb=b.uU(this.uf)){var f=this.cb.Vh(this.uf);b.AC(this.uf.Cb(),this.uf.Db(),f.Cb(),f.Db());b.MYb(this.cb,f,this.uf,1)}};r.MUc=function(){if(this.cb){var a=this.cb.Vh(this.uf);b.AC(this.uf.Cb(),this.uf.Db(),a.Cb(),a.Db());b.NYb(this.cb,a,this.uf,1);this.cb=null}};e.kb(c.vSb,"PRIM_VER","Debugger",{Qa:{HasFocus:{a:r.Uyc}},
jc:{Crash:function(){this.dmc()},Click:function(a,b,c){this.glc(e.L(a),e.L(b),c===p?1:e.L(c))},Touch:function(a,b){this.oad(e.L(a),e.L(b))},Hover:function(a,b){this.DFc(e.L(a),e.L(b))},SetCursorPos:function(a,b){this.sZc(e.L(a),e.L(b))},SetFocus:function(a,b){this.YZc(a,b)},KeyPress:function(a,b){this.cJc(e.na(a),b===p?0:e.L(b))},MouseMove:function(a,b){this.TNc(a,b)},LeftMouseDown:function(a,b,c){this.mMc(e.L(a),e.L(b),c===p?1:e.L(c))},LeftMouseUp:function(){this.nMc()},RightMouseDown:function(a,
b){this.LUc(a,b)},RightMouseUp:function(){this.MUc()},StyleSnapshot:function(a,b,c){return this.x3c(a,b===p?0:e.L(b),c===p?0:e.L(c))},ThemeDrawStyle:function(a,b){return this.S$c(a,e.na(b))}}})});
