window.LANSA.addSrc("web",function(e,c,a,b,p){e.Gb("PRIM_LABL");var r=null,m=null;a.ZI={jjb:0,Y4b:1,Z4b:2,X4b:3};a.ZI.v={INLINE:a.ZI.jjb,LEFT:a.ZI.Y4b,RIGHT:a.ZI.Z4b,CENTER:a.ZI.X4b};a.bE={mIa:0,oGb:1,sGb:2,tGb:3,vGb:4,S3a:5};a.bE.v={NONE:a.bE.mIa,NOTLOADED:a.bE.oGb,PERMISSIONDENIED:a.bE.sGb,POSITIONUNAVAILABLE:a.bE.tGb,TIMEOUT:a.bE.vGb,UNKNOWNERROR:a.bE.S3a};a.SS={gzb:0,ezb:1,hzb:2,fzb:4};a.SS.v={NONE:a.SS.gzb,ERROR:a.SS.ezb,WARNING:a.SS.hzb,INFORMATION:a.SS.fzb};c.jfb=function(){s.w.call(this);
this.Za=[]};var s=c.u(c.jfb,c.td);s.W=function(){s.j.W.call(this)};s.lc=function(){return this.Za.length};s.Pd=function(a){return this.Za[a-1]};s.XF=function(a){for(var c=null,d=0;d<this.Za.length;d++){var e=this.Za[d];if(b.$B(e.Zl,a)){c=e;break}}return c};e.kb(c.jfb,"PRIM_WEB","URLParameters",{Qa:{Item:{a:function(a){return this.XF(e.na(a))},sw:"na"},ItemCount:{a:s.lc}},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Pd(e.L(a))},Dv:s.lc}});c.ifb=function(){f.w.call(this);this.$a=this.Zl=""};var f=
c.u(c.ifb,c.td);f.ah=function(){return this.Zl.toUpperCase()};f.Ja=function(){return this.$a};e.kb(c.ifb,"PRIM_WEB","URLParameter",{Qa:{Name:{a:f.ah},Value:{a:f.Ja}}});c.gfb=function(){h.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(r=localStorage)}catch(c){}this.pq=null};var h=c.u(c.gfb,c.td);h.W=function(){h.j.W.call(this)};h.m5a=function(){return null!=r};h.lc=function(){return this.AP().length};h.Pd=function(a){return this.AP()[a-
1]};h.XF=function(a){for(var b=null,c=this.AP(),d=0;d<c.length;d++){var e=c[d];if(e.Zl==a){b=e;break}}return b};h.AP=function(){if(null==this.pq&&(this.pq=[],r))for(var a=0;a<r.length;a++){var b=r.key(a);""!=b&&r[b]!=p&&this.pq.push(new c.ANa(b))}return this.pq};h.Eza=function(){this.pq=null};h.$g=function(a,b){var d=this.AP(),e=this.XF(a);null==e&&(e=new c.ANa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};h.Es=function(c){var d=this.AP(),e=this.XF(c);null!=e&&(r.removeItem(c),d.splice(d.indexOf(e),
1),b.No().Y9(a.DE.Tna))};h.wo=function(){r&&(r.clear(),this.Eza(),b.No().Y9(a.DE.Tna))};e.kb(c.gfb,"PRIM_WEB","LocalStorage",{Qa:{Available:{a:h.m5a},Item:{a:function(a){return this.XF(e.na(a))},sw:"na"},ItemCount:{a:h.lc}},jc:{Add:h.$g,Remove:h.Es,Clear:h.wo},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Pd(e.L(a))},Dv:h.lc}});c.ANa=function(a){n.w.call(this);this.Zl=a};var n=c.u(c.ANa,c.td);n.ah=function(){return this.Zl};n.Ja=function(){var a="";r&&(a=r[this.Zl],a===p&&(a=""));return a};n.Wa=function(c){var d=
!0;try{r[this.Zl]=c,b.No().Y9(a.DE.Tna)}catch(e){b.No().ZHb(a.DE.Tna),d=!1}return d};e.kb(c.ANa,"PRIM_WEB","LocalStorageItem",{Qa:{Name:{a:n.ah},Value:{a:n.Ja,g:function(a){this.Wa(e.na(a))}}},Zf:{Tf:"Value"}});c.hfb=function(){k.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(m=sessionStorage)}catch(c){}this.pq=null};var k=c.u(c.hfb,c.td);k.W=function(){k.j.W.call(this)};k.m5a=function(){return null!=m};k.lc=
function(){return this.AP().length};k.Pd=function(a){return this.AP()[a-1]};k.XF=function(a){for(var b=null,c=this.AP(),d=0;d<c.length;d++){var e=c[d];if(e.Zl==a){b=e;break}}return b};k.AP=function(){if(null==this.pq&&(this.pq=[],m))for(var a=0;a<m.length;a++){var b=m.key(a);""!=b&&m[b]!=p&&this.pq.push(new c.BNa(b))}return this.pq};k.Eza=function(){this.pq=null};k.$g=function(a,b){var d=this.AP(),e=this.XF(a);null==e&&(e=new c.BNa(a),d.push(e));e.Wa(b)||d.splice(d.indexOf(e),1)};k.Es=function(c){var d=
this.AP(),e=this.XF(c);null!=e&&(m.removeItem(c),d.splice(d.indexOf(e),1),b.No().Y9(a.DE.Una))};k.wo=function(){m&&(m.clear(),this.Eza(),b.No().Y9(a.DE.Una))};e.kb(c.hfb,"PRIM_WEB","SessionStorage",{Qa:{Available:{a:k.m5a},Item:{a:function(a){return this.XF(e.na(a))},sw:"na"},ItemCount:{a:k.lc}},jc:{Add:k.$g,Remove:k.Es,Clear:k.wo},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Pd(e.L(a))},Dv:k.lc}});c.BNa=function(a){d.w.call(this);this.Zl=a};var d=c.u(c.BNa,c.td);d.ah=function(){return this.Zl};
d.Ja=function(){var a="";m&&(a=m[this.Zl],a===p&&(a=""));return a};d.Wa=function(c){var d=!0;try{m[this.Zl]=c,b.No().Y9(a.DE.Una)}catch(e){b.No().ZHb(a.DE.Una),d=!1}return d};e.kb(c.BNa,"PRIM_WEB","SessionStorageItem",{Qa:{Name:{a:d.ah},Value:{a:d.Ja,g:function(a){this.Wa(e.na(a))}}},Zf:{Tf:"Value"}});c.ffb=function(){g.w.call(this)};var g=c.u(c.ffb,c.td);g.W=function(){g.j.W.call(this)};g.ODc=function(a){0<a&&window.history.go(0-a)};g.PDc=function(a){0<a&&window.history.go(a)};g.$g=function(a,c){var d=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.No().Uib();c&&b.No().EIa()};g.eTc=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.No().Uib();c&&b.No().EIa()};e.kb(c.ffb,"PRIM_WEB","History",{jc:{Add:function(a,b){this.$g(e.na(a),b===p?!0:e.za(b))},Replace:function(a,b){this.eTc(e.na(a),b===p?!0:e.za(b))},
GoBack:function(a){this.ODc(a===p?1:e.L(a))},GoForward:function(a){this.PDc(a===p?1:e.L(a))}}});c.TZb=function(){y.w.call(this);this.qd=b.Dd(0,0,400,400);this.sDa=this.Pe="";this.ig&=~a.Jg.dQ;this.ig&=~a.Jg.JY};var y=c.u(c.TZb,c.pm);y.Sg=function(){return c.k_b};y.gI=function(){return this.Pe};y.yl=function(b){this.Pe!=b&&(this.Pe=b,this.ea(a.f.i))};y.yT=function(){return this.sDa};y.Yjb=function(a){this.sDa=a};y.Id=function(a,c,d){y.j.Id.call(this,a,c,d);a=this.Oa().gb();b.Ld[a].yl(this.Pe)};y.yuc=
function(){this.Ha(a.J.oSb)};e.kb(c.TZb,"PRIM_WEB","Page",{Qa:{Source:{a:y.gI,g:function(a){this.yl(e.na(a))}},Description:{a:y.yT,g:function(a){this.Yjb(e.na(a))}}}});c.Vla=function(){z.w.call(this)};var z=c.u(c.Vla,c.pm);z.m7a=function(){for(var a=null,b=this;b;){if(b instanceof c.kfb){a=b;break}b=b.Sb}return a};z.hca=function(){z.j.hca.call(this);var a=this.m7a();a&&a.AX(this)};z.uZ=function(){z.j.uZ.call(this);var a=this.m7a();a&&a.BX(this)};z.rf=function(a){z.j.rf.call(this,a);var b=this.m7a();
b==this&&b.jA(a,!1)};e.kb(c.Vla,"PRIM_WEB","RichTextItem",{});c.ofb=function(){u.w.call(this)};var u=c.u(c.ofb,c.Vla);u.Sg=function(){return c.$_b};e.kb(c.ofb,"PRIM_WEB","RichTextLine",{});c.lfb=function(){x.w.call(this)};var x=c.u(c.lfb,c.Vla);x.Sg=function(){return c.Y_b};e.kb(c.lfb,"PRIM_WEB","RichTextBreak",{});c.mfb=function(){K.w.call(this);this.AW=null;this.YEa=a.ZI.jjb;this.jYa=this.kYa=0};var K=c.u(c.mfb,c.Vla);K.W=function(){K.j.W.call(this);this.aRa(null)};K.Sg=function(){return c.Z_b};
K.PBc=function(){return this.AW};K.aRa=function(b){this.AW!=b&&(null!=this.AW&&(this.AW.Aa(this,this.JDb),this.AW.wb()),this.AW=b,null!=this.AW&&(this.AW.Ca(),this.AW.Ea(this,this.JDb)),this.ea(a.f.i))};K.Kud=function(){return this.YEa};K.n7b=function(b){this.YEa!=b&&(this.YEa=b,this.ea(a.f.i))};K.QBc=function(){return this.kYa};K.p7b=function(b){this.kYa!=b&&(this.kYa=b,this.ea(a.f.i))};K.OBc=function(){return this.jYa};K.o7b=function(b){this.jYa!=b&&(this.jYa=b,this.ea(a.f.i))};K.Id=function(a,
c,d){K.j.Id.call(this,a,c,d);a=this.Oa().gb();b.Ld[a].Hg(this.YEa,this.kYa,this.jYa)};K.Fib=function(){var a=this.AW,c=this.Oa().gb(),a=a?a.mh():"";b.Ld[c].Xc(a)};K.JDb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Ob:this.aRa(null);break;case a.f.i:this.ea(a.f.i)}};e.kb(c.mfb,"PRIM_WEB","RichTextImage",{Qa:{Image:{a:K.PBc,g:function(a){this.aRa(a)}},Width:{a:K.QBc,g:function(a){this.p7b(e.L(a))}},Height:{a:K.OBc,g:function(a){this.o7b(e.L(a))}},Alignment:{a:function(){return e.ta(this.YEa,a.ZI.v)},
g:function(b){this.n7b(e.qa(b,a.ZI.v))}}}});c.CNa=function(){D.w.call(this);this.Ay=null};var D=c.u(c.CNa,c.Vla);D.Sg=function(){return c.a0b};D.dz=function(){null==this.Ay&&(this.Ay=new c.nfb(this));return this.Ay};e.kb(c.CNa,"PRIM_WEB","RichTextParagraph",{Qa:{Items:{a:D.dz}}});c.kfb=function(){P.w.call(this);this.qd=b.Dd(0,0,100,100)};var P=c.u(c.kfb,c.CNa);P.Sg=function(){return c.X_b};P.AX=function(b){if(!this.$c()){var c=e.Qb();c.Vb("ITEM",b);this.Ha(a.J.DI,c);c.nc()}};P.BX=function(b){if(!this.$c()){var c=
e.Qb();c.Vb("ITEM",b);this.Ha(a.J.FI,c);c.nc()}};P.T2=function(b){if(!this.$c()){var c=e.Qb();c.Vb("ITEM",b);this.Ha(a.J.EI,c);c.nc()}};P.jA=function(b,c){if(!c&&!this.$c()){var d=e.Qb();d.Vb("ITEM",b);d.gf("CONTINUE",!0);this.Ha(a.J.CI,d);c=!d.Vf("CONTINUE");d.nc()}return c};e.kb(c.kfb,"PRIM_WEB","RichText",{});c.nfb=function(a){t.w.call(this);this.Za=[];this.Vz=a};var t=c.u(c.nfb,c.td);t.W=function(){t.j.W.call(this)};t.lc=function(){return this.Za.length};t.Pd=function(a){return this.Za[a-1]};
t.$g=function(b,d,e,g){var f=new c.ofb;f.Ca();f.Bb(b);d!=p&&f.sb(d);e!=p&&f.xm(e);g!=p&&f.ao(g);f.Na(this.Vz);this.Za[this.Za.length]=f;this.Vz.ea(a.f.i);this.Vz.Pb()&&this.Vz.Ug();return f};t.jhc=function(){var b=new c.lfb;b.Ca();b.Na(this.Vz);this.Za[this.Za.length]=b;this.Vz.ea(a.f.i);this.Vz.Pb()&&this.Vz.Ug();return b};t.shc=function(b,d,e,g,f,k,h){var n=new c.mfb;n.Ca();n.aRa(b);d!=p&&n.n7b(d);e!=p&&n.p7b(e);g!=p&&n.o7b(g);f!=p&&n.sb(f);k!=p&&n.xm(k);h!=p&&n.ao(h);n.Na(this.Vz);this.Za[this.Za.length]=
n;this.Vz.ea(a.f.i);this.Vz.Pb()&&this.Vz.Ug();return n};t.xhc=function(b,d,e,g){var f=new c.CNa;f.Ca();b!=p&&f.Bb(b);d!=p&&f.sb(d);e!=p&&f.xm(e);g!=p&&f.ao(g);f.Na(this.Vz);this.Za[this.Za.length]=f;this.Vz.ea(a.f.i);this.Vz.Pb()&&this.Vz.Ug();return f};t.Es=function(b){this.Za.splice(this.Za.indexOf(b),1);b.Na(null);b.wb();this.Vz.ea(a.f.i)};t.Fj=function(){for(;0<this.Za.length;)this.Es(this.Za[0]);this.Vz.ea(a.f.i)};e.kb(c.nfb,"PRIM_WEB","RichTextItems",{Qa:{Item:{a:function(a){return this.Pd(e.L(a))},
sw:"na"},ItemCount:{a:t.lc}},jc:{Add:t.$g,AddBreak:t.jhc,AddImage:function(b,c,d,g,f,k,h){return this.shc(b,e.qa(c,a.ZI.v),d,g,f,k,h)},AddParagraph:t.xhc,Remove:t.Es,RemoveAll:t.Fj},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Pd(e.L(a))},Dv:t.lc}});c.VZb=function(){C.w.call(this);this.qd=b.Dd(0,0,100,100)};var C=c.u(c.VZb,c.pm);C.Sg=function(){return c.C_b};C.Id=function(a,b,c){C.j.Id.call(this,a,b,c)};C.og=function(a){this.VI();a&&this.fza();b.bb().rB(this)};C.hC=function(){this.ca.UW()};e.kb(c.VZb,
"PRIM_WEB","Camera",{});c.f_b=function(){I.w.call(this);this.qd=b.Dd(0,0,100,100);this.NE=null;this.MGa("")};var I=c.u(c.f_b,c.pm);I.W=function(){this.NE=null;I.j.W.call(this)};I.Sg=function(){return c.b0b};I.Iua=function(){this.Oa()&&this.MGa(this.Oa().Nvc());return this.NE};I.MGa=function(a){this.NE=new c.nG({data:a,mimetype:"image/png",filename:"signature.png"})};I.wo=function(){if(this.Oa()){var a=this.Oa().gb();b.Ld[a].wo();this.tc()}};I.Id=function(a,b,c){I.j.Id.call(this,a,b,c)};I.og=function(a){this.VI();
a&&this.fza();b.bb().rB(this)};I.hC=function(){this.ca.UW()};I.tc=function(){this.Ha(a.J.kh)};e.kb(c.f_b,"PRIM_WEB","Signature",{Qa:{Blob:{a:I.Iua}},jc:{Clear:I.wo}});c.a_b=function(){H.w.call(this);this.Zvb=this.iub=this.Drb=this.Crb=this.yrb=this.pXa=this.Zub=0;this.x7=a.bE.oGb};var H=c.u(c.a_b,c.td);H.qAc=function(){return this.Zub};H.Bzc=function(){return this.pXa};H.ivc=function(){return this.yrb};H.tvc=function(){return this.Crb};H.uvc=function(){return this.Drb};H.Vyc=function(){return this.iub};
H.rCc=function(){return this.Zvb};H.nrd=function(){return this.x7};H.nSc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.Zub=d.coords.longitude;b.pXa=d.coords.latitude;b.yrb=d.coords.accuracy;b.Crb=d.coords.altitude?d.coords.altitude:0;b.Drb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.iub=d.coords.heading?d.coords.heading:0;b.Zvb=d.coords.speed?d.coords.speed:0;b.x7=a.bE.mIa;d=new c.vla;b.Ha(a.J.S3b,d)},function(d){b.Zub=0;b.pXa=0;b.yrb=
0;b.Crb=0;b.Drb=0;b.iub=0;b.Zvb=0;b.x7=a.bE.S3a;switch(d.code){case d.PERMISSION_DENIED:b.x7=a.bE.sGb;break;case d.POSITION_UNAVAILABLE:b.x7=a.bE.tGb;break;case d.TIMEOUT:b.x7=a.bE.vGb;break;case d.UNKNOWN_ERROR:b.x7=a.bE.S3a}d=new c.vla;b.Ha(a.J.S3b,d)});return this.pXa};e.kb(c.a_b,"PRIM_WEB","Geolocation",{Qa:{Longitude:{a:H.qAc},Latitude:{a:H.Bzc},Accuracy:{a:H.ivc},Altitude:{a:H.tvc},AltitudeAccuracy:{a:H.uvc},Heading:{a:H.Vyc},Speed:{a:H.rCc},ErrorCode:{a:function(){return e.ta(this.x7,a.bE.v)}}},
jc:{Refresh:H.nSc}});c.XZb=function(){A.w.call(this)};var A=c.u(c.XZb,c.td);A.xMc=function(b,c){if("undefined"!==typeof console)switch(c){case a.SS.ezb:console.error(b);break;case a.SS.hzb:console.warn(b);break;case a.SS.fzb:console.info(b);break;default:console.log(b)}};e.kb(c.XZb,"PRIM_WEB","Console",{Qa:{},jc:{Log:function(b,c){return this.xMc(e.na(b),c?e.qa(c,a.SS.v):a.SS.gzb)}}});c.$Zb=function(){Q.w.call(this);this.Yb=this.fb=null;this.qN=this.as="";this.evb=!1};var Q=c.u(c.$Zb,c.Bs);Q.W=function(){Q.j.W.call(this);
this.un(null)};Q.Sg=function(){return c.K_b};Q.mh=function(){return this.as};Q.uJb=function(){return this.qN};Q.Eg=function(b){this.fb!=b&&(this.un(b),this.m(a.f.i))};Q.hb=function(){var a=null;return a=this.fb};Q.ic=function(){return this.Yb};Q.P6a=function(){return this.evb};Q.$6b=function(b){this.evb!=b&&(this.evb=b,this.ea(a.f.i))};Q.tc=function(){this.Ha(a.J.kh)};Q.I4a=function(b,c){var d=e.Qb();d.Vb("FILE",b);d.Vb("FILES",c);this.Ha(a.J.DHb,d);d.nc()};Q.CK=function(){this.yR=b.Pla(this.Yb.Ck());
this.fb.hT(this.ic())};Q.un=function(a){var c=null;a&&(c=a.zx(),this.fb==a?c.so(this.Yb):a.Uy(c));this.fb&&(this.fb.Aa(this),this.Yb.Aa(this),b.la(this.Yb),this.Yb=null);if(this.fb=a)this.fb.Ea(this,this.bn),this.Yb=c,this.Yb.Ea(this,this.tv);this.Vg()};Q.JNd=function(){};Q.bn=function(b,c){c.Ya==a.f.i?c.sr==a.pe.Kw?this.fb.Uy(this.ic()):this.un(this.fb):c.Ya==a.f.rb&&this.Eg(null)};Q.tv=function(b,c){c.Ya==a.f.i&&c.sr==a.pe.Kw&&this.CK()};e.kb(c.$Zb,"PRIM_WEB","FilePicker",{Qa:{MultiSelect:{a:Q.P6a,
g:function(a){this.$6b(e.za(a))}}}});c.dfb=function(a){G.w.call(this);this.kXa=a;this.tW=this.NE=null};var G=c.u(c.dfb,c.td);G.W=function(){null!=this.NE&&(this.NE=null);null!=this.tW&&(b.QAb(this.tW),this.tW=null);G.j.W.call(this)};G.ah=function(){return this.kXa.name};G.Iua=function(){null==this.NE&&(this.NE=new c.SVb(this.kXa));return this.NE};G.x7a=function(){return this.kXa.size};G.IAc=function(){return this.kXa.type};e.kb(c.dfb,"PRIM_WEB","File",{Qa:{Name:{a:G.ah},Blob:{a:G.Iua},FileSize:{a:G.x7a},
MimeType:{a:G.IAc}}});c.efb=function(){ga.w.call(this);this.Za=[]};var ga=c.u(c.efb,c.td);ga.W=function(){for(var a=0;a<this.Za.length;a++)this.Za[a].wb();this.Za=[];ga.j.W.call(this)};ga.lc=function(){return this.Za.length};ga.Pd=function(a){return this.Za[a-1]};ga.Fr=function(a){this.Za.push(a);a.Ca()};e.kb(c.efb,"PRIM_WEB","Files",{Qa:{Item:{a:function(a){return this.Pd(e.L(a))},sw:"na"},ItemCount:{a:ga.lc}},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Pd(e.L(a))},Dv:ga.lc}});c.WZb=function(){la.w.call(this)};
var la=c.u(c.WZb,c.td);la.tib=function(a){var d=this;if(window.FileReader&&a instanceof c.nG){if(a=a.yja()){var e=b.NQ(),g=new FileReader;g.onload=function(a){d.xX(a.target.result);b.ly(e)};g.readAsText(a)}}else d.xX("")};la.xX=function(b){var c=e.Qb();c.GH("DATA",b);this.Ha(a.J.q2,c)};e.kb(c.WZb,"PRIM_WEB","ClobReader",{jc:{Read:la.tib}});c.UZb=function(){oa.w.call(this)};var oa=c.u(c.UZb,c.td);oa.tib=function(a){var d=this;if(window.FileReader&&a instanceof c.nG){if(a=a.yja()){var e=b.NQ(),g=new FileReader;
g.onload=function(a){d.xX(b.mHb(a.target.result));b.ly(e)};g.readAsDataURL(a)}}else d.xX("","")};oa.xX=function(b){var c=e.Qb();c.GH("DATA",b);this.Ha(a.J.q2,c)};e.kb(c.UZb,"PRIM_WEB","BlobReader",{jc:{Read:oa.tib}});c.X_b=function(a){W.w.call(this,a)};var W=c.u(c.X_b,c.qm);W.Bb=function(a){this.G.textContent=a};W.Qy=function(){W.j.Qy.call(this);this.G.style.whiteSpace="normal";this.G.style.overflowX="auto";this.G.style.overflowY="auto"};W.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",
a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return W.j.df.call(this,a,b)};c.a0b=function(a){R.w.call(this,a)};var R=c.u(c.a0b,c.qm);R.Bb=function(a){this.G.textContent=a};R.pwa=function(){return!1};R.wea=function(){};R.Qy=function(){};R.df=function(a,b){this.G=document.createElement("p");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return R.j.df.call(this,a,b)};c.Y_b=function(a){w.w.call(this,a)};var w=c.u(c.Y_b,c.qm);w.pwa=function(){return!1};w.wea=function(){};
w.Qy=function(){};w.df=function(a,b){this.G=document.createElement("br");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return w.j.df.call(this,a,b)};c.Z_b=function(a){E.w.call(this,a)};var E=c.u(c.Z_b,c.qm);E.Xc=function(a){this.G.src=a};E.pwa=function(){return!1};E.Hg=function(b,c,d){this.G.style.width=0==c?"auto":c+"px";this.G.style.height=0==d?"auto":d+"px";switch(b){case a.ZI.jjb:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display=
"inline";this.G.style.cssFloat="none";break;case a.ZI.Y4b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="left";break;case a.ZI.Z4b:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="right";break;case a.ZI.X4b:this.G.style.marginLeft="auto",this.G.style.marginRight="auto",this.G.style.display="block",this.G.style.cssFloat="none"}};E.wea=function(){};E.Qy=
function(){this.G.style.borderStyle="solid"};E.df=function(a,b){this.G=document.createElement("img");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return E.j.df.call(this,a,b)};c.$_b=function(a){da.w.call(this,a)};var da=c.u(c.$_b,c.qm);da.Bb=function(a){this.G.textContent=a};da.pwa=function(){return!1};da.wea=function(){};da.Qy=function(){};da.df=function(a,b){this.G=document.createElement("span");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",
this.fc);return da.j.df.call(this,a,b)};c.C_b=function(a){ba.w.call(this,a)};var ba=c.u(c.C_b,c.qm);ba.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return ba.j.df.call(this,a,b)};c.b0b=function(a){ea.w.call(this,a);this.eH=this.Bm=null;this.qec=this.ixb=!1;this.uub=null};var ea=c.u(c.b0b,c.qm);ea.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",
this.fc);this.G.style.msTouchAction="none";this.eH=document.createElement("canvas");this.eH.style.touchAction="none";this.G.appendChild(this.eH);this.Bm=this.eH.getContext("2d");this.NAb();return ea.j.df.call(this,a,b)};ea.qn=function(a,b,c,d){ea.j.qn.call(this,a,b,c,d);a=this.Bm.getImageData(0,0,this.eH.width-1,this.eH.height-1);this.eH.width=this.Uc;this.eH.height=this.dd;this.Bm.putImageData(a,0,0)};ea.eM=function(a){this.p8b(a);return!0};ea.sgb=function(a){this.o8b(a);return!0};ea.RNa=function(a){this.n8b(a);
return!0};ea.qpa=function(a){this.p8b(a);return!0};ea.Wv=function(a){this.o8b(a);return!0};ea.qea=function(a){this.n8b(a);return!0};ea.oOb=function(a){this.G.onpointerdown===p&&a.touches!==p?(a.qrb=a.touches[0].pageX-this.pa.ts(),a.rrb=a.touches[0].pageY-this.pa.us()):(a.qrb=a.clientX-this.pa.ts(),a.rrb=a.clientY-this.pa.us());this.pa.tc()};ea.NAb=function(){this.a0a(!0);this.uub=new Image;this.uub.onload=function(){throw 0;};this.uub.src=null};ea.a0a=function(a){(this.qec||a)&&this.Bm.clearRect(0,
0,this.Bm.canvas.width,this.Bm.canvas.height);this.qec=!1};ea.Nvc=function(){var a=this.eH.toDataURL("image/png");return b.mHb(a)};ea.wo=function(){this.NAb()};ea.p8b=function(a){a.preventDefault();this.a0a(!1);this.Bm.beginPath();this.oOb(a);this.Bm.moveTo(a.qrb,a.rrb);this.ixb=!0};ea.n8b=function(a){a.preventDefault();this.ixb=!1};ea.ELd=function(a){this.Wv(a)};ea.o8b=function(a){this.ixb&&(a.preventDefault(),this.a0a(!1),this.Bm.strokeStyle="rgb(0,0,0)",this.Bm.lineWidth=1,this.oOb(a),this.Bm.lineTo(a.qrb,
a.rrb),this.Bm.stroke())};c.k_b=function(a){ma.w.call(this,a);this.Csa=this.cb=null};var ma=c.u(c.k_b,c.qm);ma.yl=function(a){this.Csa.src=a};ma.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);this.Csa=document.createElement("iframe");this.dGa(this.Csa);this.Csa.style.width="100%";this.Csa.style.height="100%";this.G.appendChild(this.Csa);return ma.j.df.call(this,a,b)};ma.aX=function(){var a=this;ma.j.aX.call(this);
a.G.addEventListener("load",function(){a.pa.yuc()},!1)};ma.dGa=function(a){ma.j.dGa.call(this,a);this.G.style.overflowX="auto";this.G.style.overflowY="auto"};c.K_b=function(a){Z.w.call(this,a);this.ER=null};var Z=c.u(c.K_b,c.yfb);Z.df=function(a,b){var c=Z.j.df.call(this,a,b);this.ER=document.createElement("input");this.ER.type="File";var d=this.ER.style;this.ib.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.ER);return c};Z.Id=function(){Z.j.Id.call(this);
this.fbd()};Z.qn=function(a,b,c,d){Z.j.qn.call(this,a,b,c,d);this.ER.style.left="0px";this.ER.style.top="0px";this.ER.style.width=c+"px";this.ER.style.height=d+"px"};Z.aX=function(){var a=this;this.g2();a.ER.addEventListener("change",function(b){a.Vkc(b);a.ER.value=""},!1)};Z.fbd=function(){this.ER.multiple=this.pa.P6a()};Z.Vkc=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.efb,e=0,g;g=a[e];e++)g=new c.dfb(g),null==b&&(b=g),d.Fr(g);b&&this.pa.I4a(b,d)}},{rp:["PRIM_LABL"]});
