window.LANSA.addSrc("http",function(e,c,a,b,p){c.wfb=function(){r.w.call(this);this.$a=this.Fub=""};var r=c.u(c.wfb,c.td);r.W=function(){r.j.W.call(this)};r.zja=function(){return this.Fub};r.G6b=function(a){this.Fub=a};r.Ja=function(){return this.$a};r.Wa=function(a){this.$a=a};e.kb(c.wfb,"PRIM_WEB","HttpHeader",{Qa:{Key:{a:r.zja,g:function(a){this.G6b(e.na(a))}},Value:{a:r.Ja,g:function(a){this.Wa(e.na(a))}}}});c.yNa=function(){m.w.call(this);this.Za=[]};var m=c.u(c.yNa,c.td);m.lc=function(){return this.Za.length};
m.Pd=function(a){for(var c=0;c<this.lc();c++){var d=this.Eq(c);if(b.$B(d.zja(),a))return d}return null};m.Eq=function(a){if(0>a||a>=this.Za.length)throw e.mE(a,this.Za.length);return this.Za[a]};m.$g=function(a,b){var d=new c.wfb;d.G6b(a);d.Wa(b);this.Za.push(d)};m.Fj=function(){this.Za=[]};m.Es=function(a){for(var b=!1,c=0;c<this.lc()&&!(b=this.Eq(c).zja()==a);c++);b&&this.Za.splice(c,1)};e.kb(c.yNa,"PRIM_WEB","HttpHeaders",{Qa:{Item:{a:function(a){return this.Pd(a)}},ItemCount:{a:m.lc}},jc:{Add:m.$g,
Remove:m.Es,RemoveAll:m.Fj},Zf:{Tf:"Item"},xp:{Jo:function(a){return this.Eq(e.L(a-1))},Dv:m.lc}});a.jG={a:1,wFc:2,fQc:3,TRc:4,yq:5,tad:6,fPc:7,Hlc:8,sPc:9};a.jG.v={GET:a.jG.a,HEAD:a.jG.wFc,POST:a.jG.fQc,PUT:a.jG.TRc,DELETE:a.jG.yq,TRACE:a.jG.tad,OPTIONS:a.jG.fPc,CONNECT:a.jG.Hlc,PATCH:a.jG.sPc};a.XI={p1b:1,E3b:2,q2:3,wX:4,azb:5};a.XI.v={NOTEXECUTED:a.XI.p1b,PROCESSING:a.XI.E3b,COMPLETED:a.XI.q2,FAILED:a.XI.wX,CANCELLED:a.XI.azb};c.N_b=function(){s.w.call(this);this.qZa="";this.i1=null;this.CXa=a.jG.a;
this.Nra=null;this.ZJ=new c.yNa;this.Wga=a.XI.p1b;this.Uwb=0;this.Pec=!1;this.Bh=null};var s=c.u(c.N_b,c.td);s.W=function(){this.i1=null;this.hlb(null);this.Bh&&(this.Bh.wb(),this.Bh=null);s.j.W.call(this)};s.qb=function(){null==this.Bh&&(this.Bh=e.yt(new c.GNa("")),this.Bh.Ca());return this.Bh};s.mA=function(){return this.qZa};s.p2c=function(a){this.qZa=a};s.Zsd=function(){return this.CXa};s.Z_c=function(a){this.CXa=a};s.s6a=function(){return this.ZJ};s.NBc=function(){return this.Nra};s.hlb=function(a){null!=
this.Nra&&this.Nra.wb();this.Nra=a;null!=this.Nra&&this.Nra.Ca()};s.Dvd=function(){return this.Wga};s.fDc=function(){return this.Uwb};s.Z1c=function(a){this.Uwb=a};s.bsd=function(){return this.Pec};s.eKd=function(a){this.Pec=a};s.C8b=function(f,k){var d=this;d.hlb(null);var g=d.i1=new XMLHttpRequest,h=e.ta(d.CXa,a.jG.v),m=d.mA();g.onreadystatechange=function(){4==g.readyState?(d.hlb(e.yt(new c.xfb(g))),0!==g.status&&(d.Wga=a.XI.q2,d.Ha(a.J.q2),b.ly(k))):d.Wga=a.XI.E3b};g.onerror=function(){d.Wga=
a.XI.wX;d.Ha(a.J.wX);b.ly(k)};g.ontimeout=function(){d.Wga=a.XI.wX;d.Ha(a.J.wX);b.ly(k)};g.open(h,m,f);f&&(g.timeout=this.Uwb);this.rhc(g);h="";null!=this.Bh&&(h=this.Bh.Vp());g.send(h)};s.Wsa=function(){this.i1!==p&&(this.i1.abort(),this.Wga=a.XI.azb)};s.rT=function(){this.C8b(!1,null)};s.O9=function(){this.C8b(!0,b.NQ())};s.rhc=function(a){var b=this.ZJ.lc();if(0!=b)for(var c=0;c<b;c++){var e=this.ZJ.Eq(c);a.setRequestHeader(e.zja(),e.Ja())}};e.kb(c.N_b,"PRIM_WEB","HttpRequest",{Qa:{Url:{a:s.mA,
g:function(a){this.p2c(e.na(a))}},Method:{a:function(){return e.ta(this.CXa,a.jG.v)},g:function(b){this.Z_c(e.qa(b,a.jG.v))}},Content:{a:s.qb},Response:{a:s.NBc},Headers:{a:s.s6a},Status:{a:function(){return e.ta(this.Wga,a.XI.v)}},Timeout:{a:s.fDc,g:function(a){this.Z1c(e.L(a))}}},jc:{Cancel:s.Wsa,Execute:s.rT,ExecuteAsync:s.O9}});c.xfb=function(a){f.w.call(this);this.i1=a;this.ZJ=new c.yNa;this.Bh=null;this.tMc(a.getAllResponseHeaders())};var f=c.u(c.xfb,c.td);f.W=function(){this.i1=null;this.Bh&&
(this.Bh.wb(),this.Bh=null);f.j.W.call(this)};f.qb=function(){null==this.Bh&&(this.Bh=e.yt(new c.GNa(this.i1.responseText)),this.Bh.Ca());return this.Bh};f.ECc=function(){return this.i1.status};f.FCc=function(){return this.i1.statusText};f.s6a=function(){return this.ZJ};f.tMc=function(a){for(var b=0,c="",e="";""!=a;){b=a.indexOf(":");if(-1==b)break;c=a.substring(0,b);a=a.slice(b+2);b=a.indexOf("\r\n");e=a.substring(0,b);a=a.slice(b+2);this.ZJ.$g(c,e)}};e.kb(c.xfb,"PRIM_WEB","HttpResponse",{Qa:{Content:{a:f.qb},
StatusCode:{a:f.ECc},StatusText:{a:f.FCc},Headers:{a:f.s6a}}});c.GNa=function(a){h.w.call(this);this.Ig=a};var h=c.u(c.GNa,c.td);h.Vp=function(){return this.Ig};h.JM=function(a){this.Ig=a};e.kb(c.GNa,"PRIM_WEB","HttpContent",{Qa:{Text:{a:h.Vp,g:function(a){this.JM(e.na(a))}}},Zf:{Tf:"Text"}})});
