window.LANSA.addSrc("wrtn",function(e,c,a,b,p){function r(a){return null===a?e.Kd:"object"==typeof a?a.mimetype&&a.data&&a.filename?new c.nG(a):"":a}function m(a){if(a===e.Kd)return null;switch(typeof a){case "object":if(a instanceof c.ej)return a.toString();if(c.yp&&a instanceof c.yp)return a.D$b();if(a instanceof c.nG)return a.fra}return a}function s(b,c,d){var e=document.createElement("form");e.setAttribute("method","post");e.setAttribute("action",b);d==a.DV.h9b&&e.setAttribute("target","_blank");
for(var g in c)c.hasOwnProperty(g)&&(b=document.createElement("input"),b.setAttribute("type","hidden"),b.setAttribute("name",g),b.setAttribute("value",c[g]),e.appendChild(b));document.body.appendChild(e);e.submit()}function f(a){return(a=a.sm)&&"M"==a}function h(a,b){g&&b.append("_SESSIONKEY",g);var d=a.FLD;if(d!==p)for(var f in d){var k=d[f];k!==e.Kd&&(k instanceof c.nG?b.append(f,k.yja(),k.mh()):b.append(f,m(k)))}d=a.LIST;if(d!==p)for(var h in d){for(var n=d[h],u=n.Zo={},s=n.entryCount(),r=1;r<=
s;r++)for(f in n.getEntry(r),1==r&&b.append(h+"..",1),u){k=r.toString();4>k.length&&(k="000"+k,k=k.substr(k.length-4));var z=h+"."+k+"."+f,k=u[f];k instanceof c.nG?b.append(z,k.yja(),k.mh()):b.append(z,m(k))}delete n.Zo}}function n(a,b){var c=b.webroutine={},d=c.context={};g&&(d["session-key"]=g);y&&(d["session-key-name"]=y);z&&(d["session-key-method"]=z);d=a.FLD;if(d!==p){var e=c.fields={},f;for(f in d)(e[f]={}).value=m(d[f])}d=a.LIST;if(d!==p){var c=c.lists={},k;for(k in d){for(var h=c[k]={},e=
h.header=[],h=h.entries=[],n=d[k],u=n.Zo={},s=n.entryCount(),r=1;r<=s;r++){n.getEntry(r);if(1==r)for(f in u){var x={};e.push(x);x.name=f}x=[];h.push(x);for(f in u)x.push(m(u[f]))}delete n.Zo}}}function k(a){if(a=a.context)g=a["session-key"],y=a["session-key-name"],z=a["session-key-method"]}function d(a,b,c){function d(a){if(a!=p){var b=a.FLD;g(a.LIST);g(b)}}function g(b){if(b!=p)for(var c in b)if(null===b[c])throw e.rTc(c,a.Pra,a.Ora);}d(b);d(c)}var g=p,y=p,z=p;a.DV={Knb:0,h9b:1};a.DV.v={CURRENT:a.DV.Knb,
NEW:a.DV.h9b};e.hd(function(){},"PRIM_WRTN",{});c.xya=function(a,b){u.w.call(this);this.Pra=a;this.Ora=b;this.mvb=this.nub=""};var u=c.u(c.xya,c.td);u.Trd=function(){return this.nub};u.cKd=function(a){this.nub=a};u.Ttd=function(){return this.mvb};u.qKd=function(a){this.mvb=a};u.gCc=function(){return this.Pra};u.UBc=function(){return this.Ora};u.mA=function(){return b.Lmc(this.nub,b.jJa(),this.Pra,this.Ora,this.FBc())};u.FBc=function(){var a=this.mvb;""==a&&(a=b.iJa());return a};e.kb(c.xya,"PRIM_WEB",
"ServerRequest",{Qa:{ServerModule:{a:u.gCc},Routine:{a:u.UBc}}});c.Ala=function(a,b){x.w.call(this,a,b)};var x=c.u(c.Ala,c.xya);x.rT=function(a,b){this.jHb(a,b,!1,null)};x.O9=function(a,c){this.jHb(a,c,!0,b.NQ())};x.jHb=function(c,m,u,s){function x(c){var d=null;try{d=JSON.parse(c)}catch(f){d=null}if(d){if(c=d.webroutine)if(c=c.messages)for(var h=e.EAc(),n=0;n<c.length;n++)h.$g(c[n],null);if(c=d["vlweb-error"]){var u=a.aR.GIa;switch(c["message-id"]){case "HM42":case "HM43":u=a.aR.mIb;z=y=g=p;break;
case "HM05":u=a.aR.lIb}u=ga.pua(u);if(!u&&c.message!==p)throw e.Jib(ga.Pra,ga.Ora,c.message);}else{h=m;if(d=d.webroutine){n=h.FLD;if(n!==p){var K=d.fields;if(K)for(var D in n)c=K[D],c!==p&&(c=r(c.value),n[D].set(c))}D=h.LIST;if(D!==p&&(h=d.lists))for(u in D)if(n=D[u],n.Bj(),c=h[u])for(var K=c.header,A=c.entries,C=0;C<A.length;C++){for(var na=n.Zo={},ya=A[C],G=0;G<ya.length;G++)c=r(ya[G]),na[K[G].name]=c;n.tg();delete n.Zo}k(d)}ga.xX()}}else if(u=ga.pua(a.aR.GIa),!u)throw e.Jib(ga.Pra,ga.Ora,"Invalid JSON");
b.ly(s)}function K(c){if(!ga.pua(a.aR.GIa))throw e.Jib(ga.Pra,ga.Ora,"response code "+c);b.ly(s)}function D(a){a.lengthComputable&&ga.Ouc(a.loaded,a.total,e.L(a.loaded/a.total*100))}function G(a){if(a.lengthComputable){var b=a.loaded/a.total*100;ga.OHb(a.loaded,a.total,e.L(b))}else ga.OHb(a.loaded,-1,-1)}var ga=this;d(ga,c,m);if(f(c)){var la=new FormData;h(c,la);b.hQc(this.mA(),la,x,K,D,G,u)}else la={},n(c,la),b.E2b(this.mA(),la,x,K,D,G,u)};x.pua=function(c){var d=!1,d=e.Qb();d.yO("REASON",c,a.aR.v);
d.gf("HANDLED",!1);this.Ha(a.J.wX,d);(d=d.Vf("HANDLED"))||(d=b.No().Guc(this,c));return d};x.xX=function(){this.Ha(a.J.q2)};x.Ouc=function(b,c,d){var g=e.Qb();g.lB("LOADED",b);g.lB("TOTAL",c);g.lB("PROGRESS",d);this.Ha(a.J.Pbd,g)};x.OHb=function(b,c,d){var g=e.Qb();g.lB("LOADED",b);g.lB("TOTAL",c);g.lB("PROGRESS",d);this.Ha(a.J.qsc,g)};e.kb(c.Ala,"PRIM_WEB","DataRequest",{jc:{Execute:x.rT,ExecuteAsync:x.O9}});c.Ula=function(b,c){K.w.call(this,b,c);this.gl=a.DV.Knb};var K=c.u(c.Ula,c.xya);K.NCc=function(){return this.gl};
K.zlb=function(a){this.gl=a};K.rT=function(a,b){d(this,a,b);var c={};g&&(c._SESSIONKEY=g);var e=a.FLD;if(e!==p)for(var f in e)c[f]=m(e[f]);e=a.LIST;if(e!==p)for(var k in e){for(var h=e[k],n=h.Zo={},u=h.entryCount(),r=1;r<=u;r++)for(f in h.getEntry(r),1==r&&(c[k+".."]=1),n){var z=r.toString();4>z.length&&(z="000"+z,z=z.substr(z.length-4));c[k+"."+z+"."+f]=m(n[f])}delete h.Zo}s(this.mA(),c,this.gl)};e.kb(c.Ula,"PRIM_WEB","WebPageRequest",{Qa:{Target:{a:function(){return e.ta(this.gl,a.DV.v)},g:function(b){this.zlb(e.qa(b,
a.DV.v))}}},jc:{Execute:K.rT}});c.Ola=function(b,c){D.w.call(this,b,c);this.gl=a.DV.Knb};var D=c.u(c.Ola,c.xya);D.NCc=function(){return this.gl};D.zlb=function(a){this.gl=a};D.rT=function(a,b){d(this,a,b);var c={};g&&(c._SESSIONKEY=g);var e=a.FLD;if(e!==p)for(var f in e)c[f]=m(e[f]);e=a.LIST;if(e!==p)for(var k in e){for(var h=e[k],n=h.Zo={},u=h.entryCount(),r=1;r<=u;r++)for(f in h.getEntry(r),1==r&&(c[k+".."]=1),n){var z=r.toString();4>z.length&&(z="000"+z,z=z.substr(z.length-4));c[k+"."+z+"."+f]=
m(n[f])}delete h.Zo}s(this.mA(),c,this.gl)};e.kb(c.Ola,"PRIM_WEB","ResourceRequest",{Qa:{Target:{a:function(){return e.ta(this.gl,a.DV.v)},g:function(b){this.zlb(e.qa(b,a.DV.v))}}},jc:{Execute:D.rT}});b.Htc=function(b,c){var d=c.webroutine;if(d){var e=b.Lz.lva(),g=d.fields;if(g){var f=b.Oza(e),k;for(k in g){var h=null,n=b.Hi[k];n&&(h=n.Hha());if(!h&&f)for(var m in f)if(n=f[m],n.ah()==k){h=n;break}h&&(n=r(g[k].value),h.set(n))}}if(d=d.lists){var e=b.AUc(e),p;for(p in d){g=null;if(n=b.Hi[p])switch(n.Qua()){case a.rw.wcc:case a.rw.YTa:case a.rw.d0a:g=
n}!g&&e&&(g=e[p]);if(g)for(n=d[p],f=n.header,k=n.entries,h=0;h<k.length;h++){m=g.Zo={};for(var u=k[h],s=0;s<u.length;s++)n=r(u[s]),m[f[s].name]=n;g.tg();delete g.Zo}}}}};b.Gtc=function(a){(a=a.webroutine)&&k(a)}});
