window.LANSA.addSrc("ppnl",function(e,c,a,b,p){e.Gb("PRIM_PHBN");e.Gb("PRIM_IMAG");e.Gb("PRIM_TBLO");a.Rpa=9999;a.jgb={Fya:0,h1b:3};a.QI={G4:0,fma:1,d1b:2};a.QI.v={NONE:a.QI.G4,POPUP:a.QI.fma};a.lk={aib:129,dPa:1,Xhb:2,hib:4,cib:8,Yhb:16,$hb:32,bib:64,dib:128,gib:256,Zhb:512,fib:1024,jFd:2048,eib:4096};a.zba={Aba:0,mQ:1,nQ:2};a.lEd={J3b:0};a.LK={Q0a:0,M0a:268435456,S0a:536870912};a.LK.v={HIDDEN:a.LK.Q0a,ALL:a.LK.M0a,NONE:a.LK.S0a};a.yma={JPc:0,rhb:1,q2b:805306368};a.tf={uV:0,spa:1,wTa:3,xTa:4,Qpb:5,
Xac:6,Rpb:7,Pac:8,Qac:9,Tac:10,Zac:11,Uac:12,Rac:13,Sac:14,Vac:15,Wac:16,Yac:17};a.tf.v={NONE:a.tf.uV,FADEINANDSCALE:a.tf.spa,SLIDEINLEFT:a.tf.wTa,SLIDEINRIGHT:a.tf.xTa,SLIDEINBOTTOM:a.tf.Qpb,NEWSPAPER:a.tf.Xac,SLIDEINTOP:a.tf.Rpb,"3DFLIPHORIZONTAL":a.tf.Pac,"3DFLIPVERTICAL":a.tf.Qac,"3DSIGN":a.tf.Tac,SUPERSCALED:a.tf.Zac,"3DSLIT":a.tf.Uac,"3DROTATEBOTTOM":a.tf.Rac,"3DROTATEINLEFT":a.tf.Sac,LETMEIN:a.tf.Vac,MAKEWAY:a.tf.Wac,SLIPFROMTOP:a.tf.Yac};a.tf.rya={NONE:a.tf.uV,FADEINANDSCALE:a.tf.spa};a.tf.MXb=
{NONE:a.tf.uV,FADEIN:a.tf.spa,SLIDEINLEFT:a.tf.wTa,SLIDEINRIGHT:a.tf.xTa,SLIDEINTOP:a.tf.Rpb,SLIDEINBOTTOM:a.tf.Qpb};a.tf.xGb={"":a.tf.uV,"md-effect-1":a.tf.spa,"md-effect-21":a.tf.wTa,"md-effect-2":a.tf.xTa,"md-effect-3":a.tf.Qpb,"md-effect-4":a.tf.Xac,"md-effect-7":a.tf.Rpb,"md-effect-8":a.tf.Pac,"md-effect-9":a.tf.Qac,"md-effect-10":a.tf.Tac,"md-effect-11":a.tf.Zac,"md-effect-13":a.tf.Uac,"md-effect-14":a.tf.Rac,"md-effect-15":a.tf.Sac,"md-effect-17":a.tf.Vac,"md-effect-18":a.tf.Wac,"md-effect-19":a.tf.Yac};
c.EYb=function(a){r.w.call(this,a);this.Nc=a};var r=c.u(c.EYb,c.w4);r.vb=function(){r.j.vb.call(this)};r.W=function(){this.ab.yZ();r.j.W.call(this)};r.ga=function(){return this.Nc.qb()};r.Oa=function(){return null};r.yaa=function(){return!0};r.D5=function(){};r.Tca=function(){};r.Sca=function(){};r.Sw=function(){};r.Nu=function(){};r.Rja=function(){return null};r.fG=function(){return!1};r.Ad=function(){return!0};r.YP=function(){return!0};r.eG=function(){return!1};r.VT=function(){return!1};r.je=function(b){b[0]=
a.hMa;b[1]=a.fMa};r.Ffd=function(){};r.IS=function(a){r.j.IS.call(this,a)};r.Xhc=function(){return!1};r.$ba=function(){};r.xf=function(){};r.V4=function(){};r.zu=function(){};r.Y4=function(){};r.xA=function(){};c.Mw=function(){e.Gb("PRIM_IMAG");e.Gb("PRIM_TBLO");e.Gb("PRIM_LABL");m.w.call(this);this.qd=b.Dd(10,10,280,120);this.vf=a.lk.aib;this.hl=this.Bh=this.fR=this.Bm=null;this.wx=a.tf.uV;this.Z7=a.fj.gy;this.LEa=this.yW=this.xW=null;this.uf=new c.jd(0,0);this.uYa=this.p8=this.Us=this.Tz=this.hB=
this.Ky=this.ra=this.vq=this.hO=this.Am=null;this.yFa="";this.tYa=12;this.Sga=a.l.Wb;b.U().$Gc(this);this.Qhc();b.U().ptc();var d=null;this.ra=new c.Iv;b.Qn(this.ra);b.on(this.ra);this.vq=new c.pm;this.vq.jb(new c.ha(0,0,0,30));this.vq.yf(!1);this.vq.Ks(!1);this.vq.wl(this.ra);this.vq.Uca();this.Ky=new c.Gt;this.Ky.yf(!1);this.Ky.jJ(a.Se.rJ);this.Ky.Na(this.vq);this.Ky.yE(a.ie.iE);this.hB=new c.Gt;this.hB.jJ(a.Se.MRa);this.hB.Na(this.vq);this.hB.yf(!1);this.hB.Da(this,a.J.bc,this.toc);this.hB.Da(this,
a.J.fM,this.uoc);this.hB.Da(this,a.J.gM,this.voc);this.Tz=new c.Bs;this.Tz.Na(this.vq);this.Tz.yf(!1);this.Tz.bo(a.sh.dr);this.Tz.qf(!1);this.Tz.wg(a.En.yGb);b.Pc(this.ra,this.vq,null,null,1,1);d=b.Pc(this.ra,this.Ky,this.ra.Bc(0),this.ra.Fc(0),1,1);d.Hb(a.sa.Sk);d.Ub(a.ja.Ri);d.Je(2);d=b.Pc(this.ra,this.hB,this.ra.Bc(0),this.ra.Fc(0),1,1);d.Hb(a.sa.ow);d.Ub(a.ja.Wd);d.te(2);d=b.Pc(this.ra,this.Tz,this.ra.Bc(0),this.ra.Fc(0),1,1);d.Hb(a.sa.Re);d.Ub(a.ja.Ri);this.yf(!1);this.Ogb(c.WMa)};var m=c.u(c.Mw,
c.pm);m.vb=function(){b.la(this.Ged);this.Ged=null;b.la(this.vq);this.vq=null;b.la(this.Ky);this.Ky=null;b.la(this.hB);this.hB=null;b.la(this.Tz);this.Tz=null;m.j.vb.call(this)};m.W=function(){m.j.W.call(this);this.Fca(null);this.XPa(null);this.RQa(null);this.SQa(null);this.Eca(null);this.Clb(null);b.U().TSc(this);b.la(this.hl);this.hl=null;b.la(this.LEa);this.LEa=null};m.Sg=function(){var a=c.B4;this.EL()&&(a=c.V_b);return a};m.gud=function(){return this.Z7};m.Lja=function(){if(null==this.LEa){var a=
new c.EYb(this);this.LEa=b.nba(a);this.Ea(this,this.vqc)}return this.LEa};m.Fca=function(b){this.Bm!=b&&(this.Bm&&this.Bm.Aa(this),(this.Bm=b)&&this.Bm.Ea(this,this.oCb),this.m(a.f.i))};m.Xwc=function(){return this.Bm};m.K$=function(){var a=null;this.Bm&&this.Bm instanceof c.As&&(a=this.Bm);return a};m.XPa=function(b){this.fR!=b&&(this.fR&&this.fR.Aa(this),(this.fR=b)&&this.fR.Ea(this,this.aoc),this.m(a.f.i))};m.Cmd=function(){return this.fR};m.RQa=function(b){this.xW!=b&&(this.xW&&this.xW.Aa(this),
(this.xW=b)&&this.xW.Ea(this,this.tqc),this.m(a.f.i))};m.eud=function(){return this.xW};m.SQa=function(b){this.yW!=b&&(this.yW&&this.yW.Aa(this),(this.yW=b)&&this.yW.Ea(this,this.uqc),this.m(a.f.i))};m.fud=function(){return this.yW};m.qb=function(){var a=this.Bh;!this.Bh||this.Bh instanceof c.Mw||(a=this.Bh);!a&&this.Eab()&&(a=this);return a};m.Cod=function(){return this.Bh};m.fY=function(){null==this.hl&&(this.hl=new c.pba,this.hl.h7b(),this.hl.JAa(a.Uu.rTa));return this.hl};m.jBc=function(){return this.hl};
m.tvd=function(){return this.uf};m.Mn=function(){this.Ug();return this.Rf};m.p5=function(b){b=this.vf&~a.lk.Xhb|(b?a.lk.Xhb:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.YPa=function(b){b=this.vf&~a.lk.dPa|(b?a.lk.dPa:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.j5a=function(){return 0!=(this.vf&a.lk.dPa)};m.H5b=function(b){b=this.vf&~a.lk.Yhb|(b?a.lk.Yhb:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.k5a=function(){return 0!=(this.vf&a.lk.Yhb)};m.Blb=function(b){b=this.vf&~a.lk.gib|(b?a.lk.gib:0);this.vf!=
b&&(this.vf=b,this.WQ(this.Ke()),this.m(a.f.i))};m.j8a=function(){return 0!=(this.vf&a.lk.gib)};m.mCc=function(){return this.tYa};m.z7b=function(b){b!=this.tYa&&(this.tYa=b,this.mb(),this.ea(a.f.i))};m.uvd=function(){return this.Sga};m.EAa=function(b){if(this.Jab()||this.Sga!=b)this.Sga=b,this.m(a.f.i)};m.b1c=function(){!1==this.Jab()&&(this.Sga=a.l.Wb,this.m(a.f.i))};m.$5b=function(b){b=this.vf&~a.lk.Zhb|(b?a.lk.Zhb:0);this.vf!=b&&(this.vf=b,this.WQ(this.Ke()),this.m(a.f.i))};m.bJa=function(){return 0!=
(this.vf&a.lk.Zhb)};m.xKd=function(b){b=this.vf&~a.lk.eib|(b?a.lk.eib:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.BBc=function(){return 0!=(this.vf&a.lk.eib)};m.qC=function(b){b=this.vf&~a.lk.cib|(b?a.lk.cib:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.f_c=function(b){b=this.vf&~a.lk.bib|(b?a.lk.bib:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.oKd=function(b){b=this.vf&~a.lk.dib|(b?a.lk.dib:0);this.vf!=b&&(this.vf=b,this.m(a.f.i))};m.t5=function(b){b=this.vf&~a.lk.$hb|(b?a.lk.$hb:0);this.vf!=b&&(this.vf=
b,this.m(a.f.i))};m.SIb=function(){return 0!=(this.vf&a.lk.$hb)};m.RIb=function(){return this.Am};m.Eca=function(b){this.Am!=b&&(null!=this.Am&&(this.Am.Aa(this,this.r2a),this.Am.wb()),this.Am=b,null!=this.Am&&(this.Am.Ca(),this.Am.Ea(this,this.r2a)),this.WQ(this.Ke()),this.ea(a.f.i))};m.iDc=function(){return this.hO};m.Clb=function(b){this.hO!=b&&(null!=this.hO&&(this.hO.Aa(this,this.iEb),this.hO.wb()),this.hO=b,null!=this.hO&&(this.hO.Ca(),this.hO.Ea(this,this.iEb)),this.WQ(this.Ke()),this.ea(a.f.i))};
m.nCc=function(){return this.Lja().fg()};m.A7b=function(b){this.Lja().fg()!=b&&(this.Lja().sb(b),this.m(a.f.i))};m.oCc=function(){return this.Lja().Dj()};m.gb=function(){var a=null;null!=this.Oa()&&(a=this.Oa().gb());return a};m.qvc=function(){var a=!1;if(this.EL()||!this.Eab())a=!0;return a};m.hDc=function(){return this.yFa};m.c2c=function(b){this.yFa!=b&&(this.yFa=b,this.mb(),this.ea(a.f.i))};m.xAc=function(){return this.ra};m.Eua=function(){return this.ra};m.oh=function(){var a=!1;null!=this.Oa()&&
(a=this.Oa().gb(),a=b.Ld[a].bR);return a};m.M$a=function(){return 0!=(this.vf&a.lk.Xhb)};m.zLa=function(){return 0!=(this.vf&a.lk.dPa)};m.rab=function(){return 0!=(this.vf&a.lk.cib)};m.$yd=function(){return 0!=(this.vf&a.lk.bib)};m.Eab=function(){return 0!=(this.vf&a.lk.dib)};m.Vka=function(){return 0!=(this.vf&a.lk.hib)};m.EL=function(){return 0!=(this.vf&a.lk.fib)};m.hab=function(){return!1};m.Jab=function(){return!1==this.TMb()};m.TMb=function(){return this.Sga!=a.l.Wb};m.vY=function(){var a=!1;
this.qb()==this&&this.qb().M()&&this.qb().M()!=this.hl&&(a=!0);return a};m.HU=function(){if(null!=this.Oa()){var a=this.qaa()?this.qaa().ah():"DEFAULT";b.mUa(this.Oa().gb(),a)}};m.zRc=function(a){var c=!1;this.oh()&&this.zLa()&&!this.Vka()&&this.K$()&&null!=a&&b.U().fC(this.K$())==a&&(c=!0);return c};m.ARc=function(a){var c=!1;if(this.oh()&&this.zLa()&&!this.hab()&&!this.Vka())if(null==a)c=!0;else for(var d=b.U().fC(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.K$()?(d=d.K$(),a=a!=d?
d:null):a=null),d=b.U().fC(a);return c};m.WQ=function(d,e){e===p&&(e=!1);if(!b.U().wY()){var g=new c.ha(0,0,d.aa(),30),f=d.aa()-4;this.bJa()&&(f-=g.ba());this.hO&&(f-=g.ba());this.Tz.Bb(this.ob());this.Tz.$b(Math.min(f,this.Tz.BKa(this.Tz.ob(),this.Tz.Jm().length)+10));this.vq.Na(this.j8a()?this:null);this.vq.jb(g);this.vq.ac(""==this.yFa?a.m4:this.yFa);this.Ky.Ib(this.bJa());this.Ky.$b(g.ba());this.Ky.Ib(null!=this.hO);this.Ky.Xc(this.hO);this.Ky.jb(new c.ha(this.Ky.Qd(),this.Ky.oe(),Math.min(this.Ky.Cc()?
this.Ky.Cc().Xa():this.vq.Pa(),this.vq.Pa()-4),Math.min(this.Ky.Cc()?this.Ky.Cc().Pa():this.vq.Pa(),this.vq.Pa()-4)));this.hB.Ib(this.bJa());this.hB.jb(new c.ha(this.hB.Qd(),this.hB.oe(),30,29));this.hB.gj(this.Am?this.Am:a.Tb.ddd);e?b.U().Ghc(this.hB):b.U().aTc(this.hB);this.vq.M()&&d.Va(d.O()+g.ba());this.Pb()&&this.Ug()}};m.Ue=function(a){this.WQ(a);m.j.Ue.call(this,a)};m.Ug=function(){this.vY()||this.Na(this.fY());this.nZc(this.EL());this.qvc()&&m.j.Ug.call(this)};m.oj=function(){m.j.oj.call(this);
this.WQ(this.Ke())};m.Thb=function(b,c,d){m.j.Thb(b,c,d);d[0]&&this.NP()!=a.Wv.opa&&this.j8a()&&(d[0]=this.vq==c||this.Tz==c)};m.je=function(b){""==b[0]&&(b[0]=a.hMa);""==b[1]&&(b[1]=a.fMa);m.j.je.call(this,b)};m.Pma=function(a){return this.X9(this.Bm,a)};m.Nhb=function(a){return this.oua(a)};m.YOa=function(){null!=this.hl&&(null!=this.qb()&&this.Cs(this.qb(),a.$.aMa),this.Fca(null),this.rab()||null==this.fR||this.j5a()||b.zla()!=this.fR||this.fR.zA(this.fR.FD()),this.XPa(null),this.RQa(null),this.SQa(null));
this.M$a()&&this.kp()};m.lza=function(){};m.Gza=function(){this.uf.Al(this.Qd());this.uf.Hk(this.oe());this.oh()&&this.tz(this.Z7,this.xW,this.uf,this.Bm,this.yW,this.wx)};m.V5=function(d,e,g,f,k){var h=b.Ol();this.vY()&&(h.Al(this.Qd()),h.Hk(this.oe()));d==p&&(d=h.Cb());e==p&&(e=h.Db());g==p&&(g=a.fj.gy);f==p&&(f=a.tf.uV);this.tz(g,null,new c.jd(d,e),k,null,f)};m.tz=function(d,e,g,f,k,h){d==p&&(d=a.fj.gy);e==p&&(e=null);g==p&&(g=b.Ol());f==p&&(f=null);k==p&&(k=null);h==p&&(h=a.tf.uV);if(this.oh()&&
this.Eab()){if(this.xW==e&&this.yW==k&&this.Bm==f&&this.Z7==d&&this.wx==h){d=b.Dd(g.Cb(),g.Db(),this.qb().Xa(),this.qb().Pa());b.FYb(this,d);this.fY().jb(new c.ha(0,0,d.aa(),d.ba()));g.Al(d.R());g.Hk(d.O());this.qb().jb(d);this.k8b(this.Lja().OD());this.uf=g;return}var n=this.M$a();this.p5(!1);this.cm();this.YOa();this.p5(n)}this.Z7!=a.fj.gy&&this.M()!=this.hl&&this.Na(null);this.vf|=a.lk.fib;this.jlb(!1);null!=this.Mn()&&(this.Fca(f),this.ca.tAa(this.K$()?this.K$().ca:null),this.fY(),this.BBc()&&
this.Cs(this.fY(),a.$.$La),this.XPa(b.zla()),this.Z7=d,this.wx=h,this.WQ(this.Ke()),this.OPc(g,this.rab()),this.M()==this.fY()?this.Cs(this.fY(),a.$.bba):this.Cs(this,a.$.bba),this.RQa(e),this.SQa(k),this.k5a()&&this.wx==a.tf.uV&&this.qb().Oe(!0),this.Euc())};m.cm=function(){if(this.oh()){var c=b.U().uj;c&&c.wp(this)&&this.Cs(c,a.$.rA);b.U().llc(this);null!=this.Oa()&&(c=this.Oa().gb(),b.Ld[c].$sa());this.D4a();this.YOa()}else b.U().w1&&(c=b.U().w1,c.Oa()&&c.Oa().bR&&c==this.Bm&&b.U().$s(c,!1))};
m.Yhc=function(a){for(var b=this.ca.OD(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,0,c)};m.OPc=function(a,c){this.Oa()&&(c||(b.U().gv&&b.U().gv.zFc(),b.U().pw(this.K$(),!1,this)),this.PPc(a))};m.PPc=function(c){if(this.Pma(c)&&this.qb()){this.qb().Ug();this.qb().pA(!0);c=this.hl;c.XP()||c.BOa();c=this.Oa().gb();a.Rpa+=2;b.Ld[c].MEa=a.Rpa;b.krb(c,b.Ld[c].Wf());b.Ld[c].Rna();var d=b.Ld[c].pa.Us?b.Ld[c].pa.Us.Oa():null;d&&d.G.parentElement!=document.body&&(null!=d.G.parentElement&&
d.G.parentElement.removeChild(d.G),d.G.style.zIndex=b.Ld[c].MEa-1,document.body.appendChild(d.G))}};b.FYb=function(d,e){switch(d.Z7){case a.fj.COa:var g=b.eE(),g=new c.ha(g.Qd()-d.ca.Xi(),g.oe()-d.ca.fk(),g.Xa()+(d.ca.Xi()+d.ca.ek()),g.Pa()+(d.ca.fk()+d.ca.Jl()));e.ms(g);break;case a.fj.T4:var g=b.eE(),f=0,k=0,f=(g.aa()-e.Xa())/2,k=(g.ba()-e.Pa())/2;e.Ab(f,k);d.vY()&&e.ms(d.M().Wza(e));break;case a.fj.HPc:g=b.eE();f=(g.aa()-e.Xa())/2;k=g.ua-e.Pa();e.Ab(f,k);d.vY()&&e.ms(d.M().Wza(e));break;case a.fj.IPc:g=
b.eE();f=(g.aa()-e.Xa())/2;e.Ab(f,0);d.vY()&&e.ms(d.M().Wza(e));break;case a.fj.p2b:g=b.eE();k=(g.ba()-e.Pa())/2;f=g.va-e.Xa();e.Ab(f,k);d.vY()&&e.ms(d.M().Wza(e));break;case a.fj.o2b:g=b.eE();k=(g.ba()-e.Pa())/2;e.Ab(0,k);d.vY()&&e.ms(d.M().Wza(e));break;default:g=b.eE(),e.va>g.va&&e.Ab(Math.max(0,g.va-e.aa()),e.O()),e.ua>g.ua&&e.Ab(e.R(),Math.max(0,g.ua-e.ba())),e.R()<g.R()&&e.Ab(0,e.O()),e.O()<g.O()&&e.Ab(e.R(),0)}};m.ENc=function(){b.U();this.Us=new c.pm;this.Us.Da(this,a.J.LZa,this.Mqc);this.Us.Da(this,
a.J.bc,this.Nqc);this.Us.Ve(1);this.Us.Ua(0);this.Us.$ca(1);this.Us.Va(0);this.Us.Ib(!1);this.uYa=new c.ng;this.p8=new c.nb;this.p8.yd(this.uYa)};m.k8b=function(a){var d=b.U().Xr;this.Us||this.ENc();if(!this.Us.Pb()){this.uYa.Bd(this.Sga);this.uYa.hg(this.tYa);this.Us.sb(this.TMb()?this.p8:null);for(var e=0;e<a.length;e++)this.Us.Go(a[e]);null==this.Us.fg()?this.Us.Na(null):(this.Us.Hc(d),this.Us.Ve(1),this.Us.hP())}this.Us.jb(new c.ha(0,0,d.Xa(),d.Pa()))};m.BFc=function(){this.Us.pb()&&this.Us.yo()};
m.Vj=function(c){var d=this.Oa().gb();a.Rpa+=2;b.Ld[d].MEa=a.Rpa;b.krb(d,b.Ld[d].Wf());m.j.Vj.call(this,c)};m.X9=function(d,g){var f=!0,k=e.Qb(),h=this.qb().Xa(),n=this.qb().Pa();k.Vb("CONTEXT",d);k.lB("LEFT",g.Cb());k.lB("TOP",g.Db());k.lB("WIDTH",h);k.lB("HEIGHT",n);k.yO("TRANSITION",this.wx,a.tf.v);k.gf("CONTINUE",!0);this.Ha(a.J.Mv,k);g.Al(k.vja("LEFT"));g.Hk(k.vja("TOP"));f=k.Vf("CONTINUE");h=h==k.vja("WIDTH")?this.qb().Xa():k.vja("WIDTH");n=n==k.vja("HEIGHT")?this.qb().Pa():k.vja("HEIGHT");
h=new c.ha(g.Cb(),g.Db(),h,n);b.FYb(this,h);this.fY().jb(new c.ha(0,0,h.aa(),h.ba()));g.Al(h.R());g.Hk(h.O());this.qb().jb(h);this.wx=k.j6a("TRANSITION",a.tf.v);k.nc();this.uf=g;return f};m.oua=function(b){var c=!1,c=e.Qb();c.gf("IMMEDIATE",b);c.gf("CLOSEPOPUP",!0);this.Ha(a.J.MH,c);b||this.wx!=a.tf.uV?c=!0:(c=c.Vf("CLOSEPOPUP"),c||(this.vf|=a.lk.hib));return c};m.D4a=function(){this.Ha(a.J.MO);this.vf&=~a.lk.hib;this.vf&=~a.lk.fib;this.jlb(!0);this.vY()&&this.M().mb()};m.Euc=function(){this.Ha(a.J.pOa)};
m.Mqc=function(){this.Us.pb()||(this.Us.Na(null),this.lza())};m.Nqc=function(){this.hab()&&this.zLa()&&this.cm()};m.uoc=function(){this.WQ(this.Ke(),!0)};m.voc=function(){this.WQ(this.Ke())};m.toc=function(a,c){b.U().$s(this,!1);c.nk("HANDLED",!0)};m.vqc=function(){};m.oCb=function(b,c){switch(c.Ya){case a.f.rb:this.Fca(null)}};m.tqc=function(b,c){switch(c.Ya){case a.f.rb:this.RQa(null)}};m.uqc=function(b,c){switch(c.Ya){case a.f.rb:this.SQa(null)}};m.aoc=function(b,c){switch(c.Ya){case a.f.rb:this.XPa(null)}};
m.r2a=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Ob:this.Eca(null)}};m.iEb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Ob:this.Clb(null)}};m.Hta=m[a.$.cla]=function(){this.EL()&&this.Gza()};m.NF=m[a.$.nz]=function(a){m.j.NF.call(this,a);this.WQ(this.Ke())};m.zr=m[a.$.mG]=function(a){m.j.zr.call(this,a);this.WQ(this.Ke())};e.hd(c.Mw,"PRIM_PPNL",{Qa:{CloseOnClick:{a:m.SIb,g:function(a){this.t5(e.za(a))}},AutoClose:{a:m.j5a,g:function(a){this.YPa(e.za(a))}},AutoFocus:{a:m.k5a,g:function(a){this.H5b(e.za(a))}},
TitleBar:{a:m.j8a,g:function(a){this.Blb(e.za(a))}},ShroudColor:{a:function(){return this.Jab()?e.Kd:b.Yf(this.Sga)},g:function(a){a===e.Kd?this.b1c():this.EAa(b.Xf(e.na(a)))}},ShroudOpacity:{a:m.mCc,g:function(a){this.z7b(e.L(a))}},CloseButton:{a:m.bJa,g:function(a){this.$5b(e.za(a))}},CloseImage:{a:m.RIb,g:m.Eca},TitleImage:{a:m.iDc,g:m.Clb},ShroudStyle:{a:m.nCc,g:m.A7b},ShroudStyles:{a:m.oCc},TitleBarThemeDrawStyle:{a:m.hDc,g:function(a){this.c2c(e.na(a))}},IsOpen:{a:m.oh}},jc:{ShowPopup:function(b,
c,d,g,f){this.V5(b,c,d?e.qa(d,a.fj.mNc):d,g?e.qa(g,a.tf.v):g,f)},ClosePopup:m.cm}});c.Leb=function(d){s.w.call(this,d);this.qd=new c.ha(0,0,300,30);this.Lra=a.yma.JPc;this.rEa=new c.Iv;this.y0=this.MJ=this.LJ=null;this.oR=[];this.BXa=null;b.Qn(this.rEa);b.on(this.rEa);this.wl(this.rEa);this.yf(!1);this.y0=new c.sNa;this.y0.lAa(a.QI.d1b);this.y0.Da(this,a.J.Mv,this.zoc);this.LJ=new c.Gt;this.LJ.Na(this);this.LJ.jb(new c.ha);this.LJ.Da(this,a.J.bc,this.Aoc);this.LJ.b_();this.BXa=new c.BYb(this)};var s=
c.u(c.Leb,c.pm);s.vb=function(){s.j.vb.call(this)};s.W=function(){s.j.W.call(this);b.la(this.BXa);this.BXa=null};s.Dwc=function(){return this.MJ};s.b6b=function(b){this.MJ!=b&&(null!=this.MJ&&(this.MJ.Aa(this,this.kCb),this.MJ.wb()),this.MJ=b,null!=this.MJ&&(this.MJ.Ca(),this.MJ.Ea(this,this.kCb)),this.mb(),this.m(a.f.i))};s.Y0c=function(b){b=this.vf&~a.yma.rhb|(b?a.yma.rhb:0);this.Lra!=b&&(this.Lra=b,this.m(a.f.i))};s.v7a=function(){return 0!=(this.Lra&a.yma.rhb)};s.XYc=function(b){this.cJa()!=b&&
(this.Lra=this.Lra&~a.yma.q2b|b,this.mb(),this.pA(),this.Q2b(this.Ke()),this.ea(a.f.i))};s.cJa=function(){return this.Lra&a.yma.q2b};s.R5a=function(){var b=null;switch(this.cJa()){case a.LK.S0a:case a.LK.Q0a:b=s.j.R5a.call(this);break;case a.LK.M0a:e.Gb("PRIM_PCOL"),b=new c.eeb(this.y0),b=new c.YY(b)}return b};s.je=function(b){""==b[0]&&(b[0]=a.ZRb);""==b[1]&&(b[1]=a.GKc);s.j.je.call(this,b)};s.Ohb=function(){this.wl(this.rEa)};s.Ow=function(c,d){s.j.Ow.call(this,c,d);this.Ohb();b.CYb(this,this.rEa,
a.ya.Wi,a.sa.HF,a.ja.Ri,this.q2a)};s.Ue=function(a){s.j.Ue.call(this,a);this.Q2b(a)};s.Q2b=function(d){switch(this.cJa()){case a.LK.S0a:for(this.LJ.Ib(!1);0<this.oR.length;)this.oR[0].kp();break;case a.LK.Q0a:for(var e=this.oR.length,g=0,f=null,k=this.Bn,h=k.length-1;0<=h&&null!=(f=k[h]);h--)g=Math.max(g,f.Ic().va),f.qt()>d.va&&(b.AYb(this,f),e++);k=this.oR;for(h=0;h<k.length&&null!=(f=k[h]);h++)g+f.cb.Xa()<d.va?(f.kp(),h--,e--):f.ga().Ve(h+1);if(0<e)this.LJ.gj(this.MJ?this.MJ:a.Tb.igb),this.LJ.jb(new c.ha(d.va-
(d.ba()+2),0,d.ba(),d.ba())),this.LJ.Ib(!0),this.y0.VOa();else for(this.LJ.Ib(!1);0<this.oR.length;)this.oR[0].kp();break;case a.LK.M0a:for(;0<this.Bn.length;)b.AYb(this,this.Bn[this.Bn.length-1]);this.LJ.gj(this.MJ?this.MJ:a.Tb.igb);this.LJ.jb(new c.ha(d.va-(d.ba()+2),0,d.ba(),d.ba()));this.LJ.Ib(!0);this.y0.VOa()}this.Pb()&&this.Ug()};b.CYb=function(c,d,e,g,f,k){for(var h=null,n=c.Bn,m=1,p=0;p<n.length&&null!=(h=n[p]);p++,m++){var s=d.Ge(h);s||(s=b.Pc(d,h,d.Bc(0),d.Fc(0),1,1),h.Da(c,a.J.jZ,k));
s.bh(e);s.Hb(g);s.Ub(f)}};s.kCb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Ob:this.b6b(null);break;case a.f.i:this.mb()}};s.zoc=function(b,c){this.Ha(a.J.Mv,c)};s.Aoc=function(b,d){this.y0.tz(a.fj.gy,this,new c.jd(this.ts()+this.Xa()-this.y0.Xa(),this.us()+this.Pa()),this);d.nk("HANDLED",!0)};s.q2a=function(a){this.v7a()&&(a=a instanceof c.rba?a:null)&&a.HB()&&!a.HB().oh()&&(a.Zq(),this.BXa.qh())};e.kb(c.Leb,"PRIM_PPNL","MenuBar",{Qa:{CollapsedMenuImage:{a:s.Dwc,g:s.b6b},ShowOnHover:{a:s.v7a,
g:function(a){this.Y0c(e.za(a))}},CollapseStyle:{a:function(){return e.ta(this.cJa(),a.LK.v)},g:function(b){this.XYc(e.qa(b,a.LK.v))}}}});c.BYb=function(a){f.w.call(this,500);this.ZR=a};var f=c.u(c.BYb,c.cZ);f.sT=function(){if(this.ZR.v7a()){var a=!1,c=!1,d=b.U().shb(b.Ol());d?a=!0:(d=b.uU(b.Ol()))&&(d==this.ZR||d.wp(this.ZR))&&(a=!0);!a&&(d=b.U().fC(b.jQ()))&&(c=a=!0);a||(this.ZR.pw(),c=!0);c&&this.Kh()}return!1};c.sNa=function(){h.w.call(this);this.qd=new c.ha(0,0,150,150);this.Pk=new c.Iv;this.fK=
a.jgb.Fya;b.Qn(this.Pk);b.on(this.Pk);this.wl(this.Pk)};var h=c.u(c.sNa,c.Mw);h.vb=function(){h.j.vb.call(this)};h.W=function(){h.j.W.call(this)};h.lAa=function(b){this.rva()!=b&&(this.fK=this.fK&~a.jgb.h1b|b,this.mb(),this.ea(a.f.i))};h.rva=function(){return this.fK&a.jgb.h1b};h.je=function(b){""==b[0]&&(b[0]=a.aSb);""==b[1]&&(b[1]=a.HKc);h.j.je.call(this,b)};h.Ohb=function(){this.wl(this.Pk);this.t5(!0)};h.Ow=function(c,d){h.j.Ow.call(this,c,d);this.Ohb();b.CYb(this,this.Pk,a.ya.pj,a.sa.mB,a.ja.fi,
this.q2a)};h.VOa=function(){if(this.rva()!=a.QI.G4){for(var b=null,d=this.Bn,e=[!0,2,2,0,0],g=0;g<d.length&&null!=(b=d[g]);g++){var f=b instanceof c.rba?b:null;switch(this.rva()){case a.QI.fma:f?f.e3b(e):e[2]+=b.pb()?b.Pa():0;break;case a.QI.d1b:e[1]=Math.max(e[1],b.Xa()),e[2]+=b.pb()?b.Pa():0}}for(g=0;g<d.length&&null!=(b=d[g]);g++)switch(this.rva()){case a.QI.fma:(f=b instanceof c.rba?b:null)&&f.$b(e[1])}this.$b(e[1]);this.xc(e[2])}};h.Pma=function(a){this.VOa();return h.j.Pma.call(this,a)};h.Ue=
function(a){h.j.Ue.call(this,a)};h.qCb=h[a.$.xbb]=function(a){h.j.qCb.call(this,a);this.VOa()};h.q2a=function(a){(a=a instanceof c.rba?a:null)&&a.Zq()};e.kb(c.sNa,"PRIM_PPNL","Menu",{Qa:{MenuSizing:{a:function(){return e.ta(this.rva(),a.QI.v)},g:function(b){this.lAa(e.qa(b,a.QI.v))}}}});c.DYb=function(){n.w.call(this)};var n=c.u(c.DYb,c.KI);n.lQb=function(){return!0};n.je=function(){};c.rba=function(){k.w.call(this);this.qd=new c.ha(0,0,100,25);this.J7=a.zba.Aba;this.ds=0;this.hXa=this.Bub=this.Fm=
this.xN=this.o1=this.QR=this.tK=null;this.p1=new c.Iv;this.iv=0;this.AH=a.ie.oZ;b.Qn(this.p1);b.on(this.p1);this.wl(this.p1);this.tQa(!0);this.xN=new c.nb;this.xN.Xn(a.l.Nd);this.xN.pk(a.l.Nd);this.xN.rn(1);this.xN.Yn(1);this.xN.Ql(1);this.xN.Rl(1);this.o1=new c.Gt;this.o1.Na(this);this.o1.jb(new c.ha(0,0,18,18));this.o1.sb(this.xN);this.Fm=new c.DYb;this.Fm.Na(this);this.Fm.Je(2);this.Fm.te(2);this.Bub=b.Pc(this.p1,this.Fm,this.p1.Bc(0),this.p1.Fc(0),1,1);this.hXa=b.Pc(this.p1,this.o1,this.p1.Bc(0),
this.p1.Fc(0),1,1)};var k=c.u(c.rba,c.pm);k.vb=function(){k.j.vb.call(this)};k.W=function(){k.j.W.call(this);this.CQa(null)};k.HB=function(){return this.Fm.HB()};k.ZZ=function(b){this.HB()!=b&&(this.Fm.HB()&&this.Fm.HB().Vn(this,a.J.Mv,this.eDb),this.Fm.ZZ(b),this.Fm.HB()&&this.Fm.HB().Da(this,a.J.Mv,this.eDb),this.m(a.f.i))};k.u3=function(){return this.Fm.u3()};k.lzc=function(){return this.QR};k.CQa=function(b){this.QR!=b&&(null!=this.QR&&(this.QR.Aa(this,this.dDb),this.QR.wb()),this.QR=b,null!=
this.QR&&(this.QR.Ca(),this.QR.Ea(this,this.dDb)),this.os(),this.m(a.f.i))};k.zw=function(){return this.iv};k.Eu=function(b){b!=this.iv&&(this.iv=b,this.os(),this.ea(a.f.i))};k.Xq=function(b){this.AH!=b&&(this.AH=b,this.os(),this.ea(a.f.i))};k.Te=function(){return this.Fm.Te()};k.Ae=function(b){this.Te()!=b&&(this.Fm.Ae(b),this.m(a.f.i))};k.Ye=function(){return this.Fm.Ye()};k.Je=function(b){this.Ye()!=b&&(this.Fm.Je(b),this.m(a.f.i))};k.Mf=function(){return this.Fm.Mf()};k.te=function(b){this.Mf()!=
b&&(this.Fm.te(b),this.m(a.f.i))};k.eg=function(){return this.Fm.eg()};k.sf=function(b){this.eg()!=b&&(this.Fm.sf(b),this.m(a.f.i))};k.Ll=function(){return this.AH};k.naa=function(){return 0!=(this.J7&a.zba.nQ)?!0:!1};k.xAa=function(b){b=this.J7&~a.zba.nQ|(b?a.zba.nQ:0);this.J7!=b&&(this.J7=b,this.os(),this.ea(a.f.i))};k.dg=function(){return 0!=(this.J7&a.zba.mQ)?!0:!1};k.Ah=function(b){var d=this.GD();if(b&&0!=d&&null!=this.M())for(var e=null,g=this.M().Xh,f=0;f<g.length&&null!=(e=g[f]);f++)if(e instanceof
c.rba){var k=e;k!=this&&k.GD()==d&&k.Ah(!1)}b=this.J7&~a.zba.mQ|(b?a.zba.mQ:0);this.J7!=b&&(this.J7=b,this.os(),this.ea(a.f.i))};k.GD=function(){return this.ds};k.OZ=function(b){this.ds!=b&&(this.ds=b,this.os(),this.ea(a.f.i))};k.E7a=function(){return this.tK};k.oRa=function(a){this.tK!=a&&(this.tK=a)};k.je=function(b){""==b[0]&&(b[0]=a.YRb);k.j.je.call(this,b)};k.Zq=function(){var a=b.U().fC(this);(null==a||a.oh())&&this.HB()&&!this.HB().oh()&&this.Fm.E$b(!0)};k.ywa=function(){};k.e3b=function(b){var d=
null,e=this.Sb&&this.Sb instanceof c.Leb?this.Sb:null,g=this.iv;this.dg()?(d=this.naa()?a.Tb.Z0b:a.Tb.Y0b,this.xN.Xn(a.l.OM),this.xN.pk(a.l.d6)):(this.xN.Xn(a.l.Nd),this.xN.pk(a.l.Nd));this.QR&&(d=this.QR);d&&0==g&&(g=Math.min(this.Pa(),d.Pa()));this.Fm.ac(a.iLc);this.Fm.sM(!1);this.Fm.Xq(this.Ll());this.Fm.LQa(e?a.gE.Aya:a.gE.Bya);this.Fm.Ikb(e?a.pn.G4:a.pn.gma);this.Fm.FG(a.Nt.HK);this.Fm.Gna(!1);this.Fm.Bb(this.ob());this.Fm.bo(a.sh.dr);this.o1.gj(d);this.o1.jb(new c.ha(this.o1.Qd(),this.o1.oe(),
g,g));this.Bub.Ub(a.ja.zf);this.Bub.Je(e?0:g+2);this.hXa.Ub(a.ja.Wd);this.hXa.Hb(a.sa.Sk);this.hXa.Je(e?0:2);this.Fm.mk(!1,!0);var f=this.Fm.GX(),k=this.Fm.$ia();e?(f+=g+4,d&&(f+=g+4)):(f+=60,k+=10);!0==b[0]&&(this.xc(k),b[1]=Math.max(b[1],f),b[2]+=this.pb()?k:0,b[3]+=f,b[4]+=k)};k.Ow=function(a,b){k.j.Ow.call(this,a,b);this.e3b([!1,0,0])};k.rf=function(a){var d=!1;this.GD()&&this.Ah(!0);d=k.j.rf.call(this,a);if(!d){a=b.U().qx;for(var e=null,g=0;g<a.length&&null!=(e=a[g]);g++)e instanceof c.sNa&&
b.U().$s(e,!1)}return d};k.eDb=function(a,b){b.C0c(this)};k.dDb=function(b,c){switch(c.Ya){case a.f.rb:case a.f.Ob:this.CQa(null);break;case a.f.i:this.os()}};e.kb(c.rba,"PRIM_PPNL","MenuItem",{Qa:{Checked:{a:k.dg,g:function(a){this.Ah(e.za(a))}},MenuPopup:{a:k.HB,g:k.ZZ},RadioItem:{a:k.naa,g:function(a){this.xAa(e.za(a))}},GroupIndex:{a:k.GD,g:function(a){this.OZ(e.L(a))}},Image:{a:k.lzc,g:k.CQa},ImageHeight:{a:k.zw,g:function(a){this.Eu(e.L(a))}},MarginLeft:{a:k.Ye,g:function(a){this.Je(e.L(a))}},
MarginTop:{a:k.Te,g:function(a){this.Ae(e.L(a))}},MarginBottom:{a:k.eg,g:function(a){this.sf(e.L(a))}},MarginRight:{a:k.Mf,g:function(a){this.te(e.L(a))}},Alignment:{a:function(){return e.ta(this.Ll(),a.ie.IK)},g:function(b){this.Xq(e.qa(b,a.ie.IK))}}},jc:{ShowMenu:k.Zq,HideMenu:k.ywa}});c.zYb=function(a,b,c){d.w.call(this);this.ZR=a;this.cb=b;this.Tdd=b.Ic();-1==c&&(c=this.ZR.oR.length);this.ZR.oR.splice(c,0,this);this.cb.Ea(this,this.qs);this.cb.Na(a.y0)};var d=c.u(c.zYb,c.td);d.W=function(){var a=
this.ZR.Bn.length+1;this.cb.Aa(this,this.qs);this.ZR.oR.splice(this.ZR.oR.indexOf(this),1);this.cb.Hc(this.ZR);this.cb.Ve(a);this.cb.jb(this.Tdd);d.j.W.call(this)};d.ga=function(){return this.cb};b.AYb=function(a,b){-1==a.oR.indexOf(b)&&new c.zYb(a,b,0)};d.fm=function(b,c){switch(c.Ya){case a.f.rb:this.kp()}};c.V_b=function(a){g.w.call(this,a);this.bR=!1;this.KW=null;this.dw="";this.MEa=null};var g=c.u(c.V_b,c.B4);g.OMb=function(){var b=!1,c=e.ta(this.pa.wx,a.tf.xGb);if("md-effect-17"==c||"md-effect-18"==
c||"md-effect-19"==c)b=!0;return b};g.df=function(a){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);this.KW=document.createElement("div");this.KW.setAttribute("LANSAHandle",this.fc);return this.G};g.wpa=function(){this.$sa()};g.iqb=function(b){this.dw=e.ta(this.pa.wx,a.tf.xGb);null!=this.MEa&&(b=this.MEa);9999<b&&(""==this.dw?g.j.iqb.call(this,b):this.KW.style.zIndex=b)};g.Yo=function(a,c,d,e){a=b.Dd(a,c,d,e);this.pa.vY()&&a.ms(this.pa.M().pzb(a));
g.j.Yo.call(this,a.R(),a.O(),a.aa(),a.ba())};g.Rna=function(){var a=this,c=this.bR;this.pa.k8b(this.pa.Lja().OD());""==this.dw?(this.bR=!0,c||document.body.appendChild(this.G)):this.bR||(b.U().Xr.Oa().G.classList.add("container"),this.KW.setAttribute("class","md-modal "+this.dw),c=b.Ld[this.pa.qb().Oa().gb()],c.G.style.opacity="",c.G.setAttribute("class","md-content"),this.KW.appendChild(this.G),document.body.insertBefore(this.KW,b.U().Xr.Oa().G),this.OMb()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},
25),setTimeout(function(){a.KW.classList.add("md-show");setTimeout(function(){if(a.pa.k5a()){var c=b.jQ();c&&c.wp(a.pa)||a.pa.qb().Oe(!0)}},300)},100),this.bR=!0)};g.$sa=function(){this.bR&&(this.KW.classList.contains("md-show")?this.c4b():(this.bR=!1,this.OMb()&&document.documentElement.classList.remove("md-perspective"),""==this.dw?document.body.removeChild(this.G):(document.body.removeChild(this.KW),b.U().Xr.Oa().G.classList.remove("container"))),this.pa.BFc())};g.c4b=function(){var a=this;this.KW.classList.remove("md-show");
setTimeout(function(){a.pa.cm()},500)};g.KFd=function(){this.c4b()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
