LANSA.addComponent({id:"XEXDSKAPP",nm:"XEXDesktop",ot:"wv",tp:"View",de:"Desktop Application",tl:14020008},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XEXEXPENS",an:"XEXExpenseMerchant",ft:"N",ln:256,dc:0,lb:"Expense Manager",h1:"Expense",h2:"Manager",h3:"-",de:"Expense Manager - Merchant Field",dv:"",ia:["FE","LC"]},F2:{nm:"XEXEXPE_2",an:"XEXExpenseComment",ft:"N",ln:512,dc:0,lb:"Expense Manager",h1:"Expense",h2:"Manager",h3:"-",
de:"Expense Manager - Comment Field",dv:"",ia:["FE","LC"]},F3:{nm:"STD_TEXTS",ft:"A",ln:30,dc:0,lb:{"ENG":"Text","FRA":"Texte","JPN":"Text","LLL":"Text"}[cL],h1:{"ENG":"Text","FRA":"Texte","JPN":"Text","LLL":"Text"}[cL],h2:" ",h3:" ",de:{"ENG":"Standard TEXT, SHORT","FRA":"Texte Court Standard","JPN":"Standard TEXT, SHORT","LLL":"Standard TEXT, SHORT"}[cL],dv:"",ia:["LC"],vr:[{wt:"E",wf:"N",vi:"Y",vu:"Y",vd:"N",rd:rl1,mt:{"ENG":"Text must be specified","FRA":"Texte must be specified","JPN":"Text must be specified","LLL":"Text must be specified"}[cL]
}]},F4:{nm:"XEXEXPE_3",an:"XEXExpenseDate",ft:"D",ln:10,dc:0,lb:"Expense Manager",h1:"Expense",h2:"Manager",h3:"-",de:"Expense Manager - Date Field",dv:l.SqlNull,ia:["ASQN","FE","ISO"]},F5:{nm:"XEXEXPE_1",an:"XEXExpenseStatus",ft:"A",ln:10,dc:0,lb:"Expense Manager",h1:"Expense",h2:"Manager",h3:"-",de:"Expense Manager - Status Field",dv:"",ia:["FE","LC"]},F6:{nm:"XEXEXPE_4",an:"XEXExpenseAmount",ft:"P",ln:9,dc:2,lb:"Expense Manager",h1:"Expense",h2:"Manager",h3:"-",de:"Expense Manager - Amount Field",
dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"PRIM_VIEW",fd:Fd,mt:{Refresh:{}},co:function(){cO.aN.call(this);var f=this.aF("XEXDSKAPP",Fd);var C0=this.cR("STYLECOLUMNHEADER","PRIM_VS","Style");var C1=this.cR("LAYOUTMAIN","PRIM_TBLO");var C2=this.cR("COLUMN1MAIN","PRIM_TBLO","Column");var C3=this.cR("COLUMN2MAIN","PRIM_TBLO","Column");var C4=this.cR("ROW2MAIN","PRIM_TBLO","Row");var C5=this.cR("ITEM1MAIN","PRIM_TBLO","Item");var C6=this.cR("ITEM2MAIN","PRIM_TBLO","Item");var C7=this.cR("SUMMARYPANEL","XEXSUMPNL");
var C8=this.cR("LIST","PRIM_LIST");var C9=this.cR("COLUMNMERCHANT","PRIM_LIST","String");var C10=this.cR("COLUMNCOMMENT","PRIM_LIST","String");var C11=this.cR("COLUMNAMOUNT","PRIM_LIST","String");var C12=this.cR("COLUMNDATE","PRIM_LIST","DateTime");var C13=this.cR("COLUMNSTATUS","PRIM_LIST","String");var C14=this.cA("APPLICATION","XEXAPP");C0.setBorderBottom(1);C0.setBorderLeft(0);C0.setBorderRight(0);C0.setBorderTop(0);C0.setFontSize(14);C0.setFontUnits("PIXEL");C0.iC();C1.iC();C2.setDisplayPosition(1);
C2.setParent(C1);C2.iC();C3.setDisplayPosition(2);C3.setParent(C1);C3.setUnits("PIXELS");C3.setWidth(300);C3.iC();C4.setDisplayPosition(1);C4.setParent(C1);C4.iC();C5.setColumn(C3);C5.setManage(C7);C5.setParent(C1);C5.setRow(C4);C5.iC();C6.setColumn(C2);C6.setManage(C8);C6.setParent(C1);C6.setRow(C4);C6.iC();C7.setLeft(804);C7.setParent(this);C7.setTabStop(false);C7.setHeight(616);C7.iC();C8.setDisplayPosition(2);C8.setLeft(0);C8.setParent(this);C8.setTabPosition(2);C8.setTop(0);C8.setHeight(616);
C8.setWidth(804);C8.setRowHeight(50);C8.setColumnHeaderHeight(60);C8.setColumnLines(false);C8.iC();C9.setColumnWidth(160);C9.setDisplayPosition(2);C9.setParent(C8);C9.setSource(f.F1);C9.setSortOnClick(true);C9.setColumnCaption("      Merchant");C9.setColumnCaptionType("CAPTION");C9.setCellMarginLeft(18);C9.setCellAlignment("CENTERLEFT");C9.setColumnCaptionAlign("LEFT");C9.setColumnStyle(C0);C9.iC();C10.setColumnWidth(493);C10.setDisplayPosition(5);C10.setParent(C8);C10.setSource(f.F2);C10.setColumnStyle(C0);
C10.setSortOnClick(true);C10.setColumnCaptionType("CAPTION");C10.setColumnCaption("      Comment");C10.setCellMarginLeft(18);C10.setColumnCaptionAlign("LEFT");C10.setColumnUnits("PROPORTION");C10.setColumnMinWidth(200);C10.iC();C11.setColumnWidth(90);C11.setDisplayPosition(3);C11.setParent(C8);C11.setSource(f.F3);C11.setColumnStyle(C0);C11.setSortOnClick(true);C11.setColumnCaption("      Total");C11.setColumnCaptionType("CAPTION");C11.setCellMarginRight(15);C11.setCellMarginLeft(18);C11.setColumnCaptionAlign("LEFT");
C11.iC();C12.setColumnWidth(118);C12.setDisplayPosition(1);C12.setParent(C8);C12.setShowTime(false);C12.setSource(f.F4);C12.setColumnCaptionType("CAPTION");C12.setColumnCaption("      Date");C12.setColumnStyle(C0);C12.setSortOnClick(true);C12.setCellMarginLeft(18);C12.setColumnCaptionAlign("LEFT");C12.iC();C13.setColumnWidth(120);C13.setDisplayPosition(4);C13.setParent(C8);C13.setSource(f.F5);C13.setColumnStyle(C0);C13.setColumnCaption("     Status");C13.setColumnCaptionAlign("LEFT");C13.setColumnCaptionType("CAPTION");
C13.setSortOnClick(true);C13.setCellMarginLeft(18);C13.iC();if((C14!=null)&&(C14.iI()==false)){C14.iC();}l.WEB().aH("DEVICECHANGED",this,e2);C14.aH("LOGINCOMPLETED",this,e1);this.setDisplayPosition(1);this.setHeight(616);this.setWidth(1104);this.setLayoutManager(C1);this.setVerticalScroll(true);this.aH("CREATEINSTANCE",this,e1);}});function e1(sender,Ps){var r=l.eR(this,cO,"#COM_OWNER.CreateInstance #Application.LoginCompleted",29);r.ln=29;{r.ln=31;this.mthREFRESH();}r.ln=33;r.e();};function e2(sender,Ps)
{var m=this.REF,r=l.eR(this,cO,"#SYS_WEB.DeviceChanged",35);r.ln=35;{r.ln=37;if(l.s.eq(l.WEB().getDevice(),"DESKTOP")){r.ln=39;m.SUMMARYPANEL.setVisible(true);r.ln=41;m.COLUMN2MAIN.setWidth(300);}else{r.ln=45;m.SUMMARYPANEL.setVisible(false);r.ln=47;m.COLUMN2MAIN.setWidth(0);}}r.ln=51;r.e();};cO.mthREFRESH=function(){var f=this.FLD.XEXDSKAPP,m=this.REF,r=l.mR(this,cO,"Refresh",57);var C0=r.cR("EXPENSES","PRIM_LCOL");C0.setCollects("XEXEXPOBJ");C0.iC();C0.aLF({"XEXEXPE_3":f.F4,"XEXEXPENS":f.F1,"XEXEXPE_4":f.F6,"XEXEXPE_2":f.F2,"XEXEXPE_1":f.F5});
r.ln=57;{r.ln=60;m.APPLICATION.ref.mthFINDALL(C0);r.ln=62;m.LIST.clearList();r.ln=64;{var l1=C0.selectList();while(l1.step()){r.ln=66;m.LIST.addEntry();r.ln=68;m.COLUMNAMOUNT.getCurrentItem().setValue(l.cat("$",l.n.AsString(f.F6.get())));r.ln=70;}l1.end();}}r.ln=72;r.e();};function rl1(F3){var v=F3.get();return(l.s.eq(v,""));};},{rc:["XEXSUMPNL","XEXAPP"],rp:["PRIM_VIEW","PRIM_VS.Style","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LIST","PRIM_LIST.String","PRIM_LIST.DateTime"],
dc:["XEXEXPOBJ"],dp:["PRIM_LCOL"]});