LANSA.addComponent({id:"XFLTPRT01",nm:"xFlightTrackerAirportsDropDown",ot:"rp",tp:"Reusable Part",de:"Airports",tl:14020006},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XFLTFLD04",an:"xFlightTrackerAirportName",ft:"NV",ln:512,dc:0,lb:"Airport Name",h1:"Airport",h2:"Name",h3:"",de:"Airport Name",dv:"",ia:["FE","LC"]},F2:{nm:"XFLTFLD03",an:"xFlightTrackerAirportCode",ft:"NV",ln:512,dc:0,lb:"Airport Code",h1:"Airport",h2:"Code",h3:"",
de:"Airport Code",dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,pt:{AirportCode:{da:"rw"},ItemCount:{da:"na"},AirportName:{da:"na"}},mt:{ClearList:{},AddtoDropDown:{ps:{"Iterator":{pt:"i"},"Flight":{pt:"i"}}},SetAirport:{ps:{"Airport":{pt:"i"}}},Changed:{},RemoveAll:{}},ev:{DropDownChanged:{ps:{"AirportData":{pt:"i"}}},AutoSuggest:{ps:{"AirportData":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("XFLTPRT01",Fd);var C0=this.cR("LAYOUTMAIN","PRIM_TBLO");var C1=this.cR("LAYOUTMAINROW1","PRIM_TBLO","Row");
var C2=this.cR("LAYOUTMAINCOLUMN1","PRIM_TBLO","Column");var C3=this.cR("LAYOUTMAINITEM1","PRIM_TBLO","Item");var C4=this.cR("AIRPORTINFORMATION","PRIM_MD","Dropdown");var C5=this.cR("DROPDOWNTYPE","PRIM_ALPH");C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.iC();C3.setColumn(C2);C3.setManage(C4);C3.setParent(C0);C3.setRow(C1);C3.iC();C4.setParent(this);C4.setDisplayPosition(1);C4.setTabPosition(1);C4.setHeight(60);C4.setLeft(0);C4.setTop(0);
C4.setWidth(500);C4.setHelperPosition("NONE");C4.setPromptPosition("BOTTOM");C4.setCaption("Airport");C4.iC();C5.iC();C4.aH("CHANGED",this,e1);this.setDisplayPosition(1);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(500);this.setLayoutManager(C0);this.setHeight(60);}});cO.mthGETAIRPORTNAME=function(){var m=this.REF,r=l.pR(this,cO,"GetAirportName",32);var P0=r.cPF("AIRPORT",Fd.F1.Dc);r.ln=32;{r.ln=35;P0.set(m.AIRPORTINFORMATION.get());}r.ln=37;return r.rV(P0.get());};cO.mthSETAIRPORTNAME=function(p0)
{var m=this.REF,r=l.pR(this,cO,"SetAirportName",39);var P0=r.cPF("AIRPORT",Fd.F1.Dc);P0.set(p0);r.ln=39;{r.ln=42;m.AIRPORTINFORMATION.set(P0.get());}r.ln=44;r.e();};cO.mthGETITEMCOUNT=function(){var m=this.REF,r=l.pR(this,cO,"GetItemCount",46);var P0=r.cP("ITEMCOUNT","PRIM_NMBR");r.ln=46;{r.ln=49;P0.set(m.AIRPORTINFORMATION.getItems().getItemCount());}r.ln=51;return r.rV(P0.get());};cO.mthCLEARLIST=function(){var m=this.REF,r=l.mR(this,cO,"ClearList",57);r.ln=57;{r.ln=59;m.AIRPORTINFORMATION.getItems().mthREMOVEALL();
}r.ln=61;r.e();};cO.mthADDTODROPDOWN=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"AddtoDropDown",63);var P0=r.cP("ITERATOR","PRIM_NMBR");var P1=r.cPD("FLIGHT");P0.set(p0);P1=(p1===u)?(null):(p1);r.ln=63;{r.ln=67;m.AIRPORTINFORMATION.getItems().mthADD(l.s.Substitute("&1, &2",P1.getAIRPORTNAME(),P1.getAIRPORTCOUNTRY()));r.ln=69;m.AIRPORTINFORMATION.getItems().get(P0.get()).setRelatedReference(l.cast(P1,"XFLTOBJ03"));}r.ln=71;r.e();};cO.mthSETAIRPORT=function(p0){var m=this.REF,r=l.mR(this,cO,"SetAirport",73);
var P0=r.cPD("AIRPORT");P0=p0;r.ln=73;{r.ln=76;m.AIRPORTINFORMATION.set(l.s.Substitute("&1, &2",P0.getAIRPORTNAME(),P0.getAIRPORTCOUNTRY()));}r.ln=78;r.e();};cO.mthCHANGED=function(){var m=this.REF,r=l.mR(this,cO,"Changed",80);var C0=r.cR("ITERATOR","PRIM_NMBR");var C1=r.cR("AIRPORTCODE","PRIM_ALPH");var C2=r.cR("ITEMFOUND","PRIM_BOLN");C0.iC();C1.iC();C2.setValue(false);C2.iC();r.ln=80;{r.ln=85;{var l1=m.AIRPORTINFORMATION.getItems().cI();while(l1.step()){var ENTRY=r.sR("ENTRY",l1.item());r.ln=87;
C0.set(l.add(C0.get(),1));r.ln=89;if(l.s.ne(ENTRY.getValue(),m.AIRPORTINFORMATION.getValue())){continue;}r.ln=91;C2.set(true);r.ln=93;if(l.s.eq(ENTRY.getValue(),m.AIRPORTINFORMATION.getValue())){break;}r.ln=95;}l1.end();r.dR("ENTRY");}r.ln=97;if(l.tB(C2.get())){r.ln=99;{var eP=l.ePs();eP.cD("AIRPORTDATA");eP.sR("AIRPORTDATA",l.cast(m.AIRPORTINFORMATION.getItems().get(C0.get()).getRelatedReference(),"XFLTOBJ03"));this.fE("DROPDOWNCHANGED",eP);eP.e();}}}r.ln=103;r.e();};cO.mthREMOVEALL=function(){var m=this.REF,r=l.mR(this,cO,"RemoveAll",105);
r.ln=105;{r.ln=107;m.AIRPORTINFORMATION.getItems().mthREMOVEALL();}r.ln=109;r.e();};function e1(sender,Ps){var r=l.eR(this,cO,"#AirportInformation.Changed",115);r.ln=115;{r.ln=117;this.mthCHANGED();}r.ln=119;r.e();};cO.getAIRPORTCODE=function(){var f=this.FLD.XFLTPRT01;return f.F2.get();};cO.setAIRPORTCODE=function(v){var f=this.FLD.XFLTPRT01;f.F2.set(v);};cO.getITEMCOUNT=function(){return this.mthGETITEMCOUNT();};cO.getAIRPORTNAME=function(){return this.mthGETAIRPORTNAME();};cO.setAIRPORTNAME=function(v)
{this.mthSETAIRPORTNAME(v);};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"XFLTFLD04"});}},{rp:["PRIM_PANL","PRIM_TBLO","PRIM_TBLO.Row","PRIM_TBLO.Column","PRIM_TBLO.Item","PRIM_MD.Dropdown","PRIM_ALPH","PRIM_FLD"],dp:["PRIM_NMBR","PRIM_ALPH","PRIM_BOLN"]});